### ISSUE TITLE
Receiving unhandled exception --- see #98

### ISSUE THREAD

**Issue by thehamzan6** [pixeline/bugs#103]
I first installed this and then as I was about to create a project named "tet" I receive this error.

`Unhandled Exception
Message:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'default_assignee' at row 1

SQL: INSERT INTO `projects` (`name`, `default_assignee`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?)

Bindings: array (
  0 => 'Tet',
  1 => '',
  2 => '2017-03-11 13:10:52',
  3 => '2017-03-11 13:10:52',
)

Location:

D:\Server\eds-www\tracker\app\laravel\database\connection.php on line 263

Stack Trace:

#0 D:\Server\eds-www\tracker\app\laravel\database\connection.php(183): Laravel\Database\Connection->execute('INSERT INTO `pr...', Array)
#1 D:\Server\eds-www\tracker\app\laravel\database\query.php(823): Laravel\Database\Connection->query('INSERT INTO `pr...', Array)
#2 [internal function]: Laravel\Database\Query->insert_get_id(Array, 'id')
#3 D:\Server\eds-www\tracker\app\laravel\database\eloquent\query.php(267): call_user_func_array(Array, Array)
#4 D:\Server\eds-www\tracker\app\laravel\database\eloquent\model.php(402): Laravel\Database\Eloquent\Query->__call('insert_get_id', Array)
#5 D:\Server\eds-www\tracker\app\laravel\database\eloquent\model.php(402): Laravel\Database\Eloquent\Query->insert_get_id(Array, 'id')
#6 D:\Server\eds-www\tracker\app\application\models\project.php(283): Laravel\Database\Eloquent\Model->save()
#7 D:\Server\eds-www\tracker\app\application\controllers\projects.php(28): Project::create_project(Array)
#8 [internal function]: Projects_Controller->post_new()
#9 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#10 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('new', Array)
#11 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#12 D:\Server\eds-www\tracker\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('projects@(:1)', Array)
#13 D:\Server\eds-www\tracker\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#14 D:\Server\eds-www\tracker\app\laravel\laravel.php(164): Laravel\Routing\Route->call()
#15 D:\Server\eds-www\tracker\index.php(20): require('D:\\Server\\eds-w...')
#16 {main}`

**Comment by thehamzan6** [comment]
I worked around this issue by manually inserting a row into projects table. However, I still receive this problem.

**Comment by Patriboom** [comment]
Sorry for that, thehamzan6.
A constant:  all problems occur with new installation.
We will have to work on the installation process to make sure it is adapted to the reel work.
For the problem you mention here, may you correct the line 23 of app/application/views/projects/new.php file ?
set the number one ( 1 ) between the "" after value to make it pass
from     value=""  to value="1"
your line 23 should then look like
<input type="hidden" name="default_assignee" value="1" id="default_assignee-id" />

Otherwise, you can download again the whole thing. 
I'll update it within few minutes.

**Comment by Patriboom** [comment]
Please follow issue 98

**Comment by thehamzan6** [comment]
I see. Thank you for your time.
