### ISSUE TITLE
 thehamzan6 sent

### ISSUE THREAD

**Issue by Patriboom** [pixeline/bugs#108]
>  thehamzan6 commented 10 hours ago

Might I as well make a minor suggestion, under project -> open issues, the time the issue was opened is missing a space between time and ago.

**Comment by Patriboom** [comment]
> Might I as well make a minor suggestion, under project -> open issues, the time the issue was opened 
> is missing a space between time and ago.

Fixed.  I could never find it because i don't use english.
Please be super-acurate in such situation, you can even send image or video to shorten my search.

**Comment by thehamzan6** [comment]
Sorry, I am new to Github. Will do that next time.
