### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#113]
Can you plaease update the Changelog and version release?
I think it is a nice thing to do after all the new fixes.

Thank you!

**Comment by Patriboom** [comment]
Good idea, but where have I to go to do that ?

**Comment by Patriboom** [comment]
For a very new release, I will have to take off all the old stuff about emailing.  This is named « Swift » and it sits in app/vendor directory.

Before doing that, I'll try my local Bugs without the /app/vendor/Swift directory.

I you want to do so, that will help me a lot for testing this big move.
Please let me know.
