### ISSUE TITLE
Markdown compatibility

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#114]
I was trying a few options when editing comments and I notice that not all Markdown commands are working... and you have to add two extra spaces at the end of each paragraph to make it to change line... it is not standard and I discovered by accident. That's annoying...

Is it possible to make it more compatible with Markdown? At least a bit more?

I found some more about Markdown here:

http://commonmark.org/help/
http://commonmark.org/help/tutorial/
http://spec.commonmark.org/dingus/
http://spec.commonmark.org/0.26/
https://guides.github.com/features/mastering-markdown/
https://learn.getgrav.org/content/markdown
https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html
https://en.support.wordpress.com/markdown-quick-reference/
https://daringfireball.net/projects/markdown/syntax
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

I know markdown is more and more common but it would be ideal to have a HELP buttom so users could just click on it and have a screen that shows all the possible makrdown commands (or at least a link that would open a new window so they could check and see how to use markdown) 

I constantly need to check again the syntax because I don't use Markdown anywhere else (only in Bugs).

Or maybe instead of fully using markdown we could have a very simplified version but that is practical and easy to understand.

This github text box is very nice and you just type the link and it understands it is a link... Nothing else - there is no need to add [....](.....)

I would prefer to not worry about knowing markdown... just simple typing or a very simple syntax (actually that's the goal of Markdown, right?):

I think it is important to have:

- bold
- italic
- block quote
- block code
- link (just typing it should be enough)
- line
- lists

Any ideas? 
Thank you!

**Comment by Patriboom** [comment]
I would prefer a basic wysiwyg like cdeditor.
I was on my way to integrate it   [http://sdk.ckeditor.com/samples/uicolor.html](http://sdk.ckeditor.com/samples/uicolor.html)

What do you think about that? 

If I do so, I'll push markdown system out.

**Comment by Patriboom** [comment]
Coming soon:  editor wyswyg   on or Bugs:   almost whichever you want, ready for ckeditor.

Cooming soon:  change label, add some, remove some with or without writing comment.  label changing will be shown in the issue's history.

**Comment by cybersholt** [comment]
Hey Pat, 

I had pretty good luck integrating this [Bootstrap Markdown Editor](https://github.com/inacho/bootstrap-markdown-editor) into bugs, if you want I can post the code.

**Comment by Patriboom** [comment]
Good job!
Yes, post it here as an answer to this very topic.

**Comment by Patriboom** [comment]
Hello Cybersholt, please, let us know your integrating code, for the sake of all bugs' users.
I'll integer Boostrap Markdown Editor into the /app/vendors/ sub-directory, but we need to know how to integrated it into Bugs system.

**Comment by cybersholt** [comment]
Hi Patrick,

I should be able to get it added in this week. Gotta love the holidays.

**Comment by Patriboom** [comment]
Hello cybersholt ... long time so far.
Did you find time to work on Markdown ?

**Comment by Patriboom** [comment]
Any news from cybersholt ?

**Comment by Hazaels** [comment]
With CKEditor it is fine now.
Thank you!

**Comment by Patriboom** [comment]
Thanks, Hazaels.
If users want choice ... that's why I would like to have ALSO in working state the Markdown option.

**Comment by Hazaels** [comment]
OK, it is nice to have an option but I am very happy for CKEditor - actually it surpassed my expectations... and I think it is easier for the users than markdown.
Markdown is good but requires one to learn one more thing that is kind of a bit tech saving... if you understand what I mean.
Anyway, from my part the issue is closed - but do as you prefer - seems that you became the leader of this project (thanks for taking on).

**Comment by Hazaels** [comment]
Ops... tried to use some of the CKEditor features and found a problem in configuration (maybe I missed something...)
Please look the attached image (it says more than the words).
What I did was to add colors to the text and to create a hyperlink (that was removed by CKEditor).
I had issues with CKEditor in the past - it is very good but it takes some work to configure correctly...

So seems something is misconfigured... but what?
Any help is very welcome!

![screenshot_2](https://user-images.githubusercontent.com/3906754/31106154-c5646d18-a7bf-11e7-98e9-da2db2c8f53b.jpg)

**Comment by Hazaels** [comment]
Ops... now I can't even enter in bugs...
I get the following error:
`Unhandled Exception
Message:
Error rendering view: [activity/attached-file]

Undefined offset: 0
Location:
/home3/sysbasef/public_html/bugs/app/application/views/activity/attached-file.php on line 9
Stack Trace:
#0 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined offse...', '/home3/sysbasef...', 9)
#1 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(9): Laravel\{closure}(8, 'Undefined offse...', '/home3/sysbasef...', 9, Array)
#2 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#3 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#4 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#5 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(39): Laravel\View->__toString()
#6 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#7 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#8 /home3/sysbasef/public_html/bugs/app/laravel/view.php(438): Laravel\View->render()
#9 /home3/sysbasef/public_html/bugs/app/laravel/view.php(363): Laravel\View->data()
#10 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#11 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#12 /home3/sysbasef/public_html/bugs/app/laravel/response.php(246): Laravel\View->__toString()
#13 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(177): Laravel\Response->render()
#14 /home3/sysbasef/public_html/bugs/index.php(19): require('/home3/sysbasef...')
#15 {main}
`

Please look the attached image (phpMyAdmin)
![screenshot_1](https://user-images.githubusercontent.com/3906754/31153948-492c9868-a87a-11e7-9b63-c6d44231b833.jpg)

**Comment by Hazaels** [comment]
I was trying to change a bit \app\vendor\ckeditor\config.js but couldn't test because now bugs crashes due to na error on the comments/issue system (attachments issue)....
When that is fixed we can continue with the problem in CKEditor.
