### ISSUE TITLE
Update to Laravel 4

### ISSUE THREAD

**Issue by GerritHoekstra** [pixeline/bugs#12]
Are there plans to update to Laravel 4?

**Comment by GerritHoekstra** [comment]
After roughly 2 days of working I've managed to convert the Bugs application from Laravel 3.1.4 to Laravel 4.2. You can find it in [this forked repository](https://github.com/GerritHoekstra/bugs). For the install guide see [here](https://github.com/GerritHoekstra/bugs#installing-bugs).

Changelog:
https://github.com/GerritHoekstra/bugs/blob/master/changes.md

Todo list:
https://github.com/GerritHoekstra/bugs/blob/master/TODO.MD

**Comment by pixeline** [comment]
Nice!
i'm not in love with Laravel, (much prefer Fatfree framework), so I'll keep Bugs on v3.1.4. Fits my needs enough.
