### ISSUE TITLE
Problem with "Attach File" button

### ISSUE THREAD

**Issue by davidbhlm-github** [pixeline/bugs#13]
It only works properly with Chrome. 
I can select a file but I can't upload it with IE (only the comment is uploaded). 
In Firefox, I have this error.

![screen shot 2015-03-24 at 12 24 06](https://cloud.githubusercontent.com/assets/11521627/6800851/be34e5f6-d222-11e4-96fd-97e59e576843.png)

**Comment by beingalink** [comment]
I have the same problem. Would be great if this could be fixed. :)
