### ISSUE TITLE
Cannot create a new project

### ISSUE THREAD

**Issue by PhilippeCorleone** [pixeline/bugs#131]
On every time I try to create a new project I get this error:

Unhandled Exception

Message:

Call to a member function issues() on null
Location:

/mnt/web216/d0/67/54242367/htdocs/rokateer/test/app/application/models/project.php on line 91

Google cannot help me. What do I wrong? Where is the problem? Can anybody help me?

**Comment by Patriboom** [comment]
Hello Philippe, 
which version of bugs do you use?  Have you installed it lately ? 
I can't find any problem with this specific function (project.php line 91).
I've tried to create new project on my own Bugs software and encounter no error.
I'll try again, meanwhile you give me more about
- you install date
- install procedure
- how many users and projects are set
- which way you pass throw to get this error message  (do you click on the big green plus sign, do you click on « create project », is that during the install process ????  )

**Comment by Patriboom** [comment]
Ok ... I made it.  I got the problem.   ... next: fix it.
Let me some hours.  I'll be back.

**Comment by Patriboom** [comment]
I passed throu a long long way to finally find a single useless line!!!!
Anyway, i revised the entire install process!

Now it works good.

If you want to fix it without re-install, you have to copy and paste this code into you phpMyAdmin sql command line:

INSERT INTO `tags` (`id`, `tag`, `bgcolor`, `created_at`, `updated_at`) VALUES
(1,	'status:open',		'#c43c35',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(2,	'status:closed',	'#46A546',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(3,	'type:feature',	'#62cffc',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(4,	'type:bug',		'#f89406',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(6,	'resolution:won`t fix','#812323',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(7,	'resolution:fixed',	'#048383',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(8,	'status:testing',	'#FCC307',	'2013-11-30 11:23:01',	'2016-11-30 23:11:01'),
(9,	'status:inProgress','#FF6600',	'2016-11-10 23:12:01',	'2016-11-10 23:12:01');

**Comment by PhilippeCorleone** [comment]
Very nice, it works great. Thank for you quick help.
