### ISSUE TITLE
Can not create an issue under PHP 7.1

### ISSUE THREAD

**Issue by philippe-corleone** [pixeline/bugs#133]
Now I have a new problem :). I can not create a new issue, because it cames the error:

```
Unhandled Exception

Message:
Function mcrypt_get_iv_size() is deprecated

Location:
/Applications/XAMPP/xamppfiles/htdocs/bugs/app/laravel/crypter.php on line 108

```
Solutions which I found on google says to me, that the problem is php 7.1 and I should make changes on my php, but the bugs tool lies on a webspace where I can not make changes on php. How can I solve this problem?

**Comment by Patriboom** [comment]
Thanks for your complete message.  
I'll find a way to get ready against new PHP generations.
You're the first to get the 7.1 PHP version, you're our pionner.


May you modify your   app/laravel/crypter.php on line 108 ? 
Please change   **return mcrypt_get_iv_size(static::$cipher, static::$mode);**      for    **return 0;**

Let me know if it works.

**Comment by PhilippeCorleone** [comment]
Thank you for you quick help.
I think the problem lies deeper. The next error message is:

```
Unhandled Exception

Message:
Function mcrypt_create_iv() is deprecated

Location:
/Applications/XAMPP/xamppfiles/htdocs/bugs/app/laravel/crypter.php on line 36
```

I do not know MCrypt, I don't know what shall do it.

**Comment by Patriboom** [comment]
Yes, it is way deeper, but i've tried to patch it for now.
The entier crypter.php file is deprecated.  We'll have to rebuild it on other bases.
Deeper, did you write.  Yes it is!

**Comment by PhilippeCorleone** [comment]
I use now a XAMPP with php 5.6. There it works great, but it would be great if this or that will be available in the future.

**Comment by Patriboom** [comment]
Ok, good.  
For sure, I want it in working state for PHP 7.1  but I need the delay you offer me using Xampp.  You can upgrade your PHP up to 7.0.17  It works good on mine and PHP = 7.0.17 here.

**Comment by Patriboom** [comment]
I would say:  even better to run PHP 7.0 than 5.6

**Comment by Patriboom** [comment]
May you try this  ./app/laravel/crypter.php file in your PHP 7.1 please ? 

`
<?php namespace Laravel; defined('DS') or die('No direct script access.');

class Crypter {

	/**
	 * The encryption cipher.
	 *
	 * @var string
	 */
//	public static $cipher = MCRYPT_RIJNDAEL_256;
	public static $cipher = hash('sha256', 'sA*(DH');

	/**
	 * The encryption mode.
	 *
	 * @var string
	 */
	//public static $mode = MCRYPT_MODE_CBC;
	public static $mode = OPENSSL_ZERO_PADDING,;

	/**
	 * The block size of the cipher.
	 *
	 * @var int
	 */
	public static $block = 32;

	/**
	 * Encrypt a string using Mcrypt.
	 *
	 * The string will be encrypted using the AES-256 scheme and will be base64 encoded.
	 *
	 * @param  string  $value
	 * @return string
	 */
	public static function encrypt($value)
	{
		//$iv = mcrypt_create_iv(static::iv_size(), static::randomizer());
		$iv = openssl_random_pseudo_bytes(16);;

		$value = static::pad($value);

//		$value = mcrypt_encrypt(static::$cipher, static::key(), $value, static::$mode, $iv);
		$value = openssl_encrypt($value, static::$cipher, static::key(),  static::$mode, $iv);

		return base64_encode($iv.$value);
	}

	/**
	 * Decrypt a string using Mcrypt.
	 *
	 * @param  string  $value
	 * @return string
	 */
	public static function decrypt($value)
	{
		$value = base64_decode($value);

		// To decrypt the value, we first need to extract the input vector and
		// the encrypted value. The input vector size varies across different
		// encryption ciphers and modes, so we'll get the correct size.
		$iv = substr($value, 0, static::iv_size());

		$value = substr($value, static::iv_size());

		// Once we have the input vector and the value, we can give them both
		// to Mcrypt for decryption. The value is sometimes padded with \0,
		// so we will trim all of the padding characters.
		$key = static::key();

		//$value = mcrypt_decrypt(static::$cipher, $key, $value, static::$mode, $iv);
//		$value = mcrypt_decrypt(static::$cipher, $key, $value, static::$mode, $iv);
		$value = openssl_decrypt($value, static::$cipher, $key, static::$mode, $iv);

		return static::unpad($value);
	}

	/**
	 * Get the most secure random number generator for the system.
	 *
	 * @return int
	 */
	public static function randomizer()
	{
		// There are various sources from which we can get random numbers
		// but some are more random than others. We'll choose the most
		// random source we can for this server environment.
		return mt_rand();
//		if (defined('MCRYPT_DEV_URANDOM'))
//		{
//			return MCRYPT_DEV_URANDOM;
//		}
//		elseif (defined('MCRYPT_DEV_RANDOM'))
//		{
//			return MCRYPT_DEV_RANDOM;
//		}
//		// When using the default random number generator, we'll seed
//		// the generator on each call to ensure the results are as
//		// random as we can possibly get them.
//		else
//		{
//			mt_srand();
//
//			return MCRYPT_RAND;
//		}
	}

	/**
	 * Get the input vector size for the cipher and mode.
	 *
	 * @return int
	 */
	protected static function iv_size()
	{
		//return mcrypt_get_iv_size(static::$cipher, static::$mode);
		return openssl_pkey_get_details["bits"];
	}

	/**
	 * Add PKCS7 compatible padding on the given value.
	 *
	 * @param  string  $value
	 * @return string
	 */
	protected static function pad($value)
	{
		$pad = static::$block - (Str::length($value) % static::$block);

		return $value .= str_repeat(chr($pad), $pad);
	}

	/**
	 * Remove the PKCS7 compatible padding from the given value.
	 *
	 * @param  string  $value
	 * @return string
	 */
	protected static function unpad($value)
	{
		$pad = ord($value[($length = Str::length($value)) - 1]);

		if ($pad and $pad < static::$block)
		{
			// If the correct padding is present on the string, we will remove
			// it and return the value. Otherwise, we'll throw an exception
			// as the padding appears to have been changed.
			if (preg_match('/'.chr($pad).'{'.$pad.'}$/', $value))
			{
				return substr($value, 0, $length - $pad);
			}

			// If the padding characters do not match the expected padding
			// for the value we'll bomb out with an exception since the
			// encrypted value seems to have been changed.
			else
			{
				throw new \Exception("Decryption error. Padding is invalid.");
			}
		}

		return $value;
	}

	/**
	 * Get the encryption key from the application configuration.
	 *
	 * @return string
	 */
	protected static function key()
	{
		return Config::get('application.key');
	}

}


`

**Comment by PhilippeCorleone** [comment]
Sorry, I'm pretty busy lately and wasn't able to look into it. Will do it as soon as possible!
many greetings

**Comment by Patriboom** [comment]
Did you find time for testing Bugs ?

**Comment by Patriboom** [comment]
> Sorry, I'm pretty busy lately and wasn't able to look into it. Will do it as soon as possible!
many greetings
Did you find time for Bugs lately, PhilippeCorleone ?

**Comment by Patriboom** [comment]
Did you have time lately ?

**Comment by Hazaels** [comment]
Any News about this issue?

**Comment by Patriboom** [comment]
No news for @PhilippeCorleone

**Comment by Patriboom** [comment]
As long as there is no new from @PhilippeCorleone , this issue will idle.

**Comment by chaoscommander** [comment]
I'm not sure if this is the same or a separate issue, but on my installation only Administrators are able to create issues. Managers are not. The only output on failure is "Whoops, something went wrong". I can't see relevant entries in my web server log (maybe I'm looking in the wrong place?).

**Comment by Patriboom** [comment]
chaocommander: Do you run « Bugs » under PHP 7.1 ?

**Comment by PhilippeCorleone** [comment]
Sry, I have not been here for al long time. Unfortunately the project does not exists anymore. Therefor I do not use bugs anymore. sry.

**Comment by Deuchnord** [comment]
Hi there

Just installed Bugs from the Git repo for testing purpose and found this issue. I'm running Arch Linux with PHP 7.2 (yep, 7.2 😁) and it looks like the problem got worse with this version, because I'm not able to finish the installation: right just after the database creation (after the confirmation message), the following error message appears:

> # Installation
>
> mcrypt extension not found.

I read [here](https://liorkaplan.wordpress.com/2017/09/10/php-7-2-is-coming-mcrypt-extension-isnt/) that mcrypt has been removed from PHP 7.2. Apparently, upgrading to Laravel 5.1 could solve this issue.
I'm not familiar with Laravel, but I can at least help to debug if needed - all you'll have to do is tell me what I have to do. :)

**Comment by Patriboom** [comment]
Wow, merci Jérôme.  C'est la même erreur en 7.2 qu'en 7.1.  La solution proposée m'intéresse: Laravel 5.1
Ok,  thanks, Jérôme.  That's the same issue in 7.2 than in 7.1  Let try to fix it throw Laravel 5.1


Instructions are here: https://laravel.com/docs/5.1
Content is there:  https://github.com/laravel-shift/laravel-5.1

If you can try it ... let's go:  everyone will enjoy.

**Comment by chaoscommander** [comment]
> chaocommander: Do you run « Bugs » under PHP 7.1 ?

I just checked. I don't (using PHP 7.0.27). Okay, then it's a separate issue, I shall open one.

**Comment by Patriboom** [comment]
Ouille!!!  Oye!  Ouch !
What different version of Laravel!  
Bugs has be made out of Laravel 3.2  and now, we would switch to 5.5 !!!!
Too much work for me.
I think, we will try to avoid mcrypt or to change it into something else, but  ... no, I will not try to change the entire backbone of such project.

To pass Bugs to PHP 7.1 ... .7.2  ... the only thing we need for now is to fix the mcrypt problem.
Let work together on it.

**Comment by Deuchnord** [comment]
Oh, you're right, that makes a very huge step… that will certainly not be painless…
Is mcrypt used by Laravel or by Bugs? In what purpose?

**Comment by Patriboom** [comment]
Hello all,

I've worked on this today and modified an important file 
/app/laravel/crypter.php

That's why I created a new branch named  mcrypt

which I duplicated into /app/laravel/crypterMcrypt.php

Then I created a new file from that and named the new one  /app/laravel/crypterSSL.php

So now, Bugs is supposed to run with mcrypt for those who have PHP < 7.1
and supposed to run with OpenSSL for those who have PHP > 7.0

Deuchnord, may you try it with your PHP 7.2 please, **using the mcrypt branch.**
If it works good, we'll merge it into the master.

**Comment by Deuchnord** [comment]
Okay, I’ll test that Saturday :)

**Comment by Patriboom** [comment]
For the moment, using my « Bugs » built under php7.0,  Bugs under 7.2 returns an error.
Let see if a « Whole 7.2 » does the same or not.

**Comment by Deuchnord** [comment]
Hi, there!

It looks like the first step of the installation has passed, but for any reason, my database has remained empty (there is no table).
Not, I'm stuck at the next step, but the error message is not the same in English and in French.
In English, I get the following message:

> # Installation
>
> mcrypt extension not found.

In French, I get:

> # Définir l`administrateur
> Veuillez installer toutes les extensions, tous les modules PHP requis.
> mcrypt extension not found.

Translation for the non-French speakers:

> # Define the administrator
> Please install all the required PHP extensions and modules.
> mcrypt extension not found.

**Comment by Patriboom** [comment]
Ok thanks.
I've just installed PHP 7.2.  That will help to move further.  First, I'll try a full installation on PHP 7.2
I'll be back.

**Comment by Patriboom** [comment]
Ok Jérôme, 
installation has been fixed.

On my Bugs system, I have this problem under 7.2

```
Unhandled Exception
Message:

get_class() expects parameter 1 to be object, string given

Location:

/home/patrick/MesSites/Developpement/Tickets/app/laravel/auth/drivers/eloquent.php on line 18

```
Do you have the same ?

**Comment by Deuchnord** [comment]
Sorry for the late of my answer, looks like my email has not been taken in account by GitHub.

I confirm, I have the same error.
Looks like that comes from the system that connects to the database (the
error comes from a Laravel component called “drivers”. This could
explain why my database is empty, doesn't it?

**Comment by Patriboom** [comment]
Thanks for your comment.
I've just try an install from scratch:
- database has been filled
- error message from eloquent.php but - in real - from my new file which doesn't return the proper data to the installed system. 

We need to compare  /app/laravel/crypterSSL.php
along with /app/laravel/crypterMcrypt.php 

and find out how to entirely replace mycrypt by openSSL in the /app/laravel/crypterSSL.php
This is the only file I've changed, this is the only file we're supposed to work on.
This is the only file we have to fit to the whole Bugs project.

The error message I got: 
```
get_class() expects parameter 1 to be object, null given
Location:
.../app/laravel/auth/drivers/eloquent.php on line 18
```

**Comment by Patriboom** [comment]
Hello everyone!

I've made it to work under PHP 7.2

Please test the « Work 2018 » branch before it'll be merged into the master branch

**Comment by Patriboom** [comment]
Hello everyone ... as I'm using Bugs under PHP 7.2 since more than a week without any bugs, any trouble, I've merged the Work 2018 branch into master.

Please let me know if you still encounter trouble, either you're working under PHP 7.0 (or older) or PHP 7.1 (or newer).
