### ISSUE TITLE
Clean Install Fails

### ISSUE THREAD

**Issue by cybersholt** [pixeline/bugs#146]
Hi Patrick,

Just tried a clean install on my local machine, get this error message: 

`Parse error: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ')' in C:\nginx\home\bugs.local\public_html\bugs\install\mysql-structure.php on line 30
Call Stack
#	Time	Memory	Function	Location
1	0.0007	367904	{main}( )	..\index.php:0
2	0.0049	522184	install->__construct( )	..\index.php:19`

When I look at the contents of the file here are the first 30 lines:

?php return array("#Create Activity Table
CREATE TABLE IF NOT EXISTS `activity` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `description` varchar(255) character set UTF8 default NULL,
  `activity` varchar(255) character set UTF8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
",

"#Create Permissions Table
CREATE TABLE IF NOT EXISTS `permissions` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `permission` varchar(255) character set UTF8 default NULL,
  `description` text character set UTF8,
  `auto_has` varchar(255) character set UTF8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
"#

"#Create Projects Table
CREATE TABLE IF NOT EXISTS `projects` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `name` varchar(255) character set UTF8 default NULL,
  `status` tinyint(2) default '1',
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  `default_assignee` bigint(20)  default '1',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
",

As you can see there is a stray # at the end of line 18. Looks like it originates from install/MySQL_DB_Schema.sql line 19. Simply removing the # and replacing with a , fixed the issue. I'll add this with the markdown patch or however you prefer. 

Edit: PHP Version 5.3.27, MySQL 5.1.62, nginx 1.9.9

**Comment by Patriboom** [comment]
Thanks:  I did the same analysis, 
replace #--#  for #-- on line install/MySQL_DB_Schema.sql line 19
You don't need to care about that working on your markdown patch.  I'll upload the correction wihtin few minutes on master branch.

**Comment by cybersholt** [comment]
Thanks Patrick

**Comment by Patriboom** [comment]
But I still need the integration code you made, please.
