### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by GaneshKandu** [pixeline/bugs#148]
Hi,
 
I am Trying To Install Bugs 1.5.2 but Getting Following Error During Installation
Version is Not Updated in new Version, it showing 1.5 in ```app/application/config/tinyissue.php```

I dont want Emailing so keeped smtp detail default  and got following error

```php
		/**
		 * Transport Settings
		 * Transport settings if using mail or smtp
		 * 'mail' or 'smtp' must be lower case
		 */
		'transport' => 'smtp',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => '',
			'port' => , //here
			/*
			* Encryption support, SSL/TLS, used with gmail servers
			* Default: blank
			* 'ssl' or 'tls' must be lower case
			* Here example for gmail server
			*/
			'encryption' =>  '',
			'username' =>  '',
			'password' =>  ''
		),
		'encoding' => 'UTF-8'
```

but Still Getting Error when i am using stmp detail 

*mysql-structure.php* failed to open stream ```mysql-structure.php``` ,file does not exist in install folder 

```
Warning: fopen(mysql-structure.php) [function.fopen]: failed to open stream: Permission denied in  install/config-setup.php on line 65

Warning: fwrite() expects parameter 1 to be resource, boolean given in  install/config-setup.php on line 76

Warning: fclose() expects parameter 1 to be resource, boolean given in  install/config-setup.php on line 77

Parse error: syntax error, unexpected ',' in  config.app.php on line 68

Warning: fopen(mysql-structure.php) [function.fopen]: failed to open stream: Permission denied in install/config-setup.php on line 65
```
```
Warning: fwrite() expects parameter 1 to be resource, boolean given in install/config-setup.php on line 76

Warning: fclose() expects parameter 1 to be resource, boolean given in install/config-setup.php on line 77

Warning: require(./mysql-structure.php) [function.require]: failed to open stream: No such file or directory in  install/install.php on line 9

Warning: require(./mysql-structure.php) [function.require]: failed to open stream: No such file or directory in  install/install.php on line 9

Fatal error: require() [function.require]: Failed opening required './mysql-structure.php' in  install/install.php on line 9
```

**Comment by Patriboom** [comment]
Thanks for sharing the issue.
You touched the real problem:  there's no default value for this essential information ( smtp port).
If you install again, just give smtp port a value, whatever value but a number



About the other problem:  all your error messages are from your permissions.  Bugs must be able to write on disk.  If you don't want let it write, 

- you need to use install/MySQL_DB_Shema.sql directly in your PhpMyAdmin or MariaDB ou Adminer.  That will will create your database for Bugs.
- you need to copy config.app.example.php into config.app.php file and update this new config.app.php file according to your database and local informations.

**Comment by GaneshKandu** [comment]
Hi, I Did same as you mentioned

- installed MySQL_DB_Shema.sql directly in my PhpMyAdmin
- copied config.app.example.php into config.app.php file and updated this to new config.app.p

hp 

but now i Don't Know How to Login Because users table is Empty

**Comment by Patriboom** [comment]
If you did as you wrote.  You can remove or rename the install sub-directory.
To define new user, use you PhpMyAdmin and define new user into the users table, using MD5 encryption for the password.

**Comment by GaneshKandu** [comment]
I have Edited my 2nd Comment Because That Problem is Solved but Getting Another Error 

as you mentioned in you ```About the other problem: all your error messages are from your permissions. Bugs must be able to write on disk. ``` 
I gave a Writable permission to Install directory and its worked

but Getting Another Error mentioned in Second Comment

[https://github.com/pixeline/bugs/issues/148#event-1048325233](https://github.com/pixeline/bugs/issues/148#event-1048325233)

**Comment by Patriboom** [comment]
In your PhpMyAdmin use the following command: 
INSERT INTO `users` (`id`, `role_id`, `email`, `password`, `firstname`, `lastname`, `language`, `created_at`, `updated_at`, `deleted`) VALUES
(NULL,	1,	'myemail@email.com',	'XhS.DHsB8wt1o',	'admin',	'admin',	'en',	NOW(),	NOW(),	0)

Then, your first user's email will be:  myemail@email.com
And password: admin

**Comment by GaneshKandu** [comment]
I Have Run This Command in PhpMyAdmin

```sql
INSERT INTO users (id, role_id, email, password, firstname, lastname, language, created_at, updated_at, deleted) VALUES
(NULL, 1, 'myemail@email.com', 'XhS.DHsB8wt1o', 'admin', 'admin', 'en', NOW(), NOW(), 0)
```

But After Login
I am Not Able to Create New Project Because I didn't found any option for Creating New Project i Think This Insert is for user not for Admin

**Comment by Patriboom** [comment]
Sorry for that:  using PhpMyAdmin, change the « role » value to 4  that will set your first user as Administrator.

**Comment by GaneshKandu** [comment]
Thanks I Now able to see Administration Option
Sorry once more But This Bug is Not Solved, I have mentioned above [https://github.com/pixeline/bugs/issues/148#issuecomment-295228779](https://github.com/pixeline/bugs/issues/148#issuecomment-295228779) 2

Getting This Error when Clicking on Administration

![error](https://cloud.githubusercontent.com/assets/12833130/25228962/08c2ccfe-25ec-11e7-9bf1-2cd1a5da7815.png)

Unhandled Exception
Message:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bugs152.update_history' doesn't exist

SQL: SELECT * FROM `update_history` WHERE `Description` LIKE ? ORDER BY `DteRelease` DESC

Bindings: array (
  0 => 'Version%',
)

Location:

app/laravel/database/connection.php on line 263

Stack Trace:

- app/laravel/database/connection.php(183): Laravel\Database\Connection->execute('SELECT * FROM `...', Array)
- app/laravel/database/query.php(709): Laravel\Database\Connection->query('SELECT * FROM `...', Array)
- app/laravel/view.php(386) : eval()'d code(38): Laravel\Database\Query->get()
- app/laravel/view.php(386): eval()
- app/laravel/view.php(353): Laravel\View->get()
- app/laravel/view.php(447): Laravel\View->render()
- app/laravel/view.php(372): Laravel\View->data()
- app/laravel/view.php(353): Laravel\View->get()
- app/laravel/view.php(590): Laravel\View->render()
- app/laravel/response.php(246): Laravel\View->__toString()
- app/laravel/laravel.php(177): Laravel\Response->render()
- index.php(20): require('...')
- {main}

**Comment by Patriboom** [comment]
Sorry for that:  my mistake.
This line is part of the next release I'm working on.

**Comment by Patriboom** [comment]
You can fix it if you want.
Just do this:

- Open with a super simple text editor ( write or gedit or mousepad ) the following file
./app/application/views/administration/index.php
- remove all this
<?php
$project_status = \DB::table('update_history')->where('Description', 'LIKE',  'Version%')->order_by('DteRelease','DESC')->get();
echo $project_status[0]->description;
?>
- save the modified file.

**Comment by Patriboom** [comment]
Or download the correct file from
https://github.com/pixeline/bugs/blob/master/app/application/views/administration/index.php

**Comment by Patriboom** [comment]
Does it work good, now ?

**Comment by GaneshKandu** [comment]
Unhandled Exception
Message:

Undefined variable: project_status

Location:

app\laravel\view.php(386) : eval()'d code on line 46

Stack Trace:

- app\laravel\laravel.php(42): Laravel\Error::native(8, 'Undefined varia...', 'E:\Ampps\www\bu...', 46)
- app\laravel\view.php(386) : eval()'d code(46): Laravel\{closure}(8, 'Undefined varia...', 'E:\Ampps\www\bu...', 46, Array)
- app\laravel\view.php(386): eval()
- app\laravel\view.php(353): Laravel\View->get()
- app\laravel\view.php(447): Laravel\View->render()
- app\laravel\view.php(372): Laravel\View->data()
- app\laravel\view.php(353): Laravel\View->get()
- app\laravel\view.php(590): Laravel\View->render()
- app\laravel\response.php(246): Laravel\View->__toString()
- app\laravel\laravel.php(177): Laravel\Response->render()
- index.php(20): require('E:\Ampps\www\bu...')
- {main}

**Comment by GaneshKandu** [comment]
I Just Removed this
```php
		<tr>
			<th>Tiny Issue <?php echo __('tinyissue.version'); ?></th>
			<td><?php
//					$project_status = \DB::table('update_history')->where('Description', 'LIKE', 'Version%')->order_by('DteRelease','DESC')->get();
//					echo $project_status[0]->description;
				?>
			</td>
			<td rowspan="2" style="min-width: 150px; padding-left: 100px;"><br /><?php echo __('tinyissue.let_update_it'); ?></td>
		</tr>
		<tr>
			<th><?php echo __('tinyissue.version_release_date'); ?></th>
			<td><?php echo substr($project_status[0]->dterelease, 0, 10); ?></td>
		</tr>
```
and it works

**Comment by Patriboom** [comment]
Thanks, 

I'll modify the file as you did for the current release.
The code you removed is for the next release, which I'm now working on.

If you encounter any other issue, please open a new ticket.
