### ISSUE TITLE
Problem with mail in Windows

### ISSUE THREAD

**Issue by davidbhlm-github** [pixeline/bugs#15]
If you don't configure smtp, you will receive an error in Windows.

I think that in app/application/libraries/mail.php you can change it :

>switch($default)
>		{
>			case 'sendmail':
>				$transport = Swift_SendmailTransport::newInstance($options['sendmail']['path'].' -bs');
>				break;
>			case 'smtp':
>				$transport = Swift_SmtpTransport::newInstance($options['smtp']['server'], >$options['smtp']['port'], $options['smtp']['encryption'])
>					->setUsername($options['smtp']['username'])
>					->setPassword($options['smtp']['password']);
>				break;
>			default:
>				$transport = Swift_MailTransport::newInstance();
>			break;
>		}

to this:  

>switch($default)
>		{
>			case 'sendmail':
>				$transport = Swift_SendmailTransport::newInstance($options['sendmail']['path'].' -bs');
>				break;
>			case 'smtp':
>				$transport = Swift_SmtpTransport::newInstance($options['smtp']['server'], >$options['smtp']['port'], $options['smtp']['encryption'])
>					->setUsername($options['smtp']['username'])
>					->setPassword($options['smtp']['password']);
>				break;
>			
>case 'mail':
>				$transport = Swift_MailTransport::newInstance()
>				break;
>
>default:
>				$transport = Swift_NullTransport::newInstance();
>			break;
>		}

If the user wants to set the email settings, he/she only has to change config.app.php file.

**Comment by pixeline** [comment]
Thanks, included in next  release.
