### ISSUE TITLE
Adding tag triggers server security 

### ISSUE THREAD

**Issue by dasscheman** [pixeline/bugs#160]
When I try to add a tag to an issue, i'm blocked on my server. It turns out that adding a tag is seen by my server as a 'Potential Cross Site Scripting Attack'.

This is the complete error I get: 

`[Tue May 02 08:07:06 2017] [error] [client XXX.XXX.XXX.XXX] ModSecurity:  [file "/etc/httpd/modsecurity.d/10_asl_rules.conf"] [line "1085"] [id "340149"] [rev "156"] [msg "Atomicorp.com WAF Rules: Potential Cross Site Scripting Attack"] [data "<input"] [severity "CRITICAL"] Access denied with code 403 (phase 2). Pattern match "(?:< ?i?frame ?src ?= ?(?:ogg|tls|gopher|data|php|zlib|(?:ht|f)tps?):/|(?:\\\\.add|\\\\@)import |asfunction\\\\:|background-image\\\\:|\\\\be(?:cma|xec)script\\\\b|\\\\.fromcharcode|get(?:parentfolder|specialfolder)|\\\\.innerhtml|\\\\< ?input|(?:/|<) ?(?:java|live|j|vb ..." at ARGS:avant. [hostname "XXXXXXXXXXXXX"] [uri "/project/1/issue/1/retag"] [unique_id "WQgiCn8AAAEAAbdOHQYAAAAD"]`

**Comment by Patriboom** [comment]
For the moment, the best way to avoid such error 403 message is to tell your browser to accept an exception for the site.

I'll try to have a look on other way to program that, but ... nothing sure I will success.
If anyone has idea ... please feel free to share your idea / talent.

**Comment by Patriboom** [comment]
I'm now working on that.
Within a week or so you'll find everything corrected.

**Comment by Patriboom** [comment]
Ok, now it works properly on issue history page  ( index.php/project/PrjectNumber/issue/IssueNumber )
