### ISSUE TITLE
Your advice, please

### ISSUE THREAD

**Issue by Patriboom** [pixeline/bugs#162]
I had a look back on https://github.com/pixeline/bugs/issues/30
because I had to re-install everthing on my new HDD.
Again I encountered the issue ob_start.
Then, I scanned all files and found not a single one which contains ob_flush or anything like using ob_ content.

So ... what do you think?
Can we just take the ob_.... functions out ? 
Anyone knows anything about « Why do the programmer set it there ? »  or « What for is ob_start is ? »
Is that only a « Laravel » usual component which we don't use here in « Bugs » ? 

For now, I just remarked the line 32 in app/laravel/core.php   (  //ob_start('mb_output_handler');  ) 
and everything seams to work good.

Your comments, advice, opinion, please

**Comment by Hazaels** [comment]
I don't know anything about that but I really think it may be that a programmer was "debugging" and left that by accident... could it be?

**Comment by Patriboom** [comment]
Thanks Hazaels.
That's by far the best interpretation upto now ( not among those shown here  hihihi ;)  but among all those i've imagined for myself since last May.

**Comment by Patriboom** [comment]
Hello all, 

I found out, that ob_ works everytime we open a single page.
We have to manage with.
As ob_is still in PHP 7, I think I'll keep it as is instead of looking to understand all branches involved in the ob_ usage.

**Comment by Patriboom** [comment]
Hello all,

I found out, that ob_ works everytime we open a single page.
We have to manage with.
As ob_is still in PHP 7, I think I'll keep it as is instead of looking to understand all branches involved in the ob_ usage.

It's part of four main files:
/app/laravel/view.php
/app/laravel/section.php
/app/laravel/error.php
/app/laravel/redirect.php

I have no clue about what the page app/laravel/vendor/Symfony/Component/HttpFoundation/File/MimeType/FileBinaryMimeTypeGuesser.php is for but it carries ob_ function also.

Finally, the /app/laravel/core.php as no more ob_ active task since June and works good anyway.

Those are all six files which carry an ob_ family function element.

**Comment by Hazaels** [comment]
What search tool do you use to search occurences of ob_ inside the files?

**Comment by Patriboom** [comment]
The easy one provided with Linux debian
mate-search-tool

**Comment by Hazaels** [comment]
Nice, I miss a good tool in Windows. Grep isn`t an option. I was using na open Project "[SurfFind](https://sourceforge.net/projects/surffind/)" but has some bugs...

**Comment by Hazaels** [comment]
So... is bugs working the way it is right now? 
I would not remove, add or change anything that I don't really understand or know for what was being used.

**Comment by marcelloinfoweb** [comment]
Netbeans makes any search throughout the project.

**Comment by Patriboom** [comment]
Ok ... it's voluntaring after all!
Let keep it like this.
