### ISSUE TITLE
Drag and drop in TODOs not working

### ISSUE THREAD

**Issue by negatyw86** [pixeline/bugs#163]
In version: 1.5 - release 1.3.2 can't drag and drop tasks between status

**Comment by Patriboom** [comment]
I'm very busy these days, but soon, I'll have a look on this issue.

**Comment by Patriboom** [comment]
Sure doesn't work.
Second next on the «todo » list.

**Comment by Patriboom** [comment]
Let explain you doesn't work:
1) it was built without percentage and sorted according to english-only labels
2) it is now sorted according to percentage of work done with no reference to labels nor tags.

The challenge is now to move the items from columns to columns accordingly to the users preferences about the percentage of work done.   What to do with an issue which has a history like
percentage done: 75
percentage done: 76
percentage done: 77
percentage done: 78
percentage done: 79
percentage done: 80
percentage done: 81    (which brings the issue into the third column)
and bring the issue into the second column  without loosing history sequence  nor percentages of work done along such history sequence ? 

Each column content is now defined by the user preference array 'Percent' in config.app.php file.

**Comment by Hazaels** [comment]
Maybe it will require a rethink and rework the code to do what you want it to do...

**Comment by Hazaels** [comment]
The history sequence should be sorted by DATE-TIME then you get the last percentage set - simple like that.

What do you think?

**Comment by Patriboom** [comment]
I think the same way, but ... if have dense percentages like
70
69
68
67
66
...

and no room to move any of them one step back ...  will I loose a note or have double percentage (now prohibited by table unique index)  ? 

I don't know.

**Comment by Hazaels** [comment]
What about using decimals? (only when necessary?)
70
69
68.5
68.4
68.1
68.05
68.01
68.005
67
66
...

**Comment by Patriboom** [comment]
I think, that's a good idea.

**Comment by Patriboom** [comment]
Back on track.
Soon, you'll have the update on this issue.
