### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#165]
Help me!

`Unhandled Exception

Message:

Trying to get property of non-object
Location:

D:\xampp2\htdocs\bugs\app\laravel\view.php(371) : eval()'d code on line 118
Stack Trace:

#0 D:\xampp2\htdocs\bugs\app\laravel\laravel.php(42): Laravel\Error::native(8, 'Trying to get p...', 'D:\\xampp2\\htdoc...', 118)
#1 D:\xampp2\htdocs\bugs\app\laravel\view.php(371) : eval()'d code(118): Laravel\{closure}(8, 'Trying to get p...', 'D:\\xampp2\\htdoc...', 118, Array)
#2 D:\xampp2\htdocs\bugs\app\laravel\view.php(371): eval()
#3 D:\xampp2\htdocs\bugs\app\laravel\view.php(338): Laravel\View->get()
#4 D:\xampp2\htdocs\bugs\app\laravel\view.php(425): Laravel\View->render()
#5 D:\xampp2\htdocs\bugs\app\laravel\view.php(357): Laravel\View->data()
#6 D:\xampp2\htdocs\bugs\app\laravel\view.php(338): Laravel\View->get()
#7 D:\xampp2\htdocs\bugs\app\laravel\view.php(568): Laravel\View->render()
#8 D:\xampp2\htdocs\bugs\app\laravel\response.php(246): Laravel\View->__toString()
#9 D:\xampp2\htdocs\bugs\app\laravel\laravel.php(177): Laravel\Response->render()
#10 D:\xampp2\htdocs\bugs\index.php(20): require('D:\\xampp2\\htdoc...')
#11 {main}`

**Comment by Patriboom** [comment]
Hello Marcello, 

tell me the story that brough you to such error.
Is that right after install ? 
Which page did you try to see ? 
I can not figure out what you did expect to see on your screen from th above quote.

**Comment by marcelloinfoweb** [comment]
Hello,

I updated from version 1.3 to the latest available.
I did the updates of the sql, first the 1.3_1 after the 1.3_2, until here everything well.

But when I get in the Issue, appears the message above.

In "/bugs/app/application/views/project/issue/index.php" I discovered that if I remove this code, `Project\Issue::current()->assigned_to->id`, everything works perfectly.

**Comment by Patriboom** [comment]
Ok.  Good.
I'm working on this very page  /bugs/app/application/views/project/issue/index.php
and the wrong code doesn't appear anymore (did not appear before reading your comment), so it will work properly soon.
I still have some work to do on this page, but push on on github soon.

**Comment by marcelloinfoweb** [comment]
For some reason an array is not going. How would you insert a condition to check if it is an array or not?

As the database was already being used when I did the upgrade, possibly it had some wrong inserted registry that is now in need and is not in the right format.

Which tables comes the data?

**Comment by marcelloinfoweb** [comment]
My temporary solution:

In "/bugs/app/application/views/project/issue/index.php".

`<?php
if (Project\Issue::current()->assigned == null) {
   $assignedTo = '0';
 } else {
   $assignedTo = Project\Issue::current()->assigned->id;
}
?>`
