### ISSUE TITLE
Undefined index: SERVER_ADDR

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#166]
Unhandled Exception

Message:
Undefined index: SERVER_ADDR

Location:
\bugs\app\application\controllers\project\issue.php on line 239

When I submit the assignment change in issue. And the page does not update, nor does it change immediately, having to manually refresh the page.

Bugs version: 1.5 - release 1.3.2

**Comment by Patriboom** [comment]
This doesn't make any sens.  For sure we'll find something else around, because http://php.net/reserved.variables.server  is not a new function neither over-aged on.

Let change $_SERVER['SERVER_ADDR']
by $_SERVER['SERVER_NAME']
in \bugs\app\application\controllers\project\issue.php on line 239

**Comment by marcelloinfoweb** [comment]
Now it worked.
