### ISSUE TITLE
Cannot declare class phpmailerException

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#167]
When updating an issue.

**Message**:
Cannot declare class phpmailerException, because the name is already in use
Location:

\bugs\app\application\libraries\PHPmailer\class.phpmailer.php on line 4039

Checking...

**Comment by Patriboom** [comment]
Same name can not be given to both function and class.
Just change first letter to uppercase.
I'll have a look on this soon.
Thanks marcello

**Comment by Patriboom** [comment]
Please check your version.
My \bugs\app\application\libraries\PHPmailer\class.phpmailer.php has 4040 lines.
`class phpmailerException extends Exception` declaration is on line 4028.
I could not find any other declaration of such class anywhere else, nor any kind of re-calling definition.
You may need to replace your \bugs\app\application\libraries\PHPmailer\class.phpmailer.php by the one you'll find here.
Let me know, please

**Comment by marcelloinfoweb** [comment]
I updated the library PHPMailer and even then it didn't work.

Problem with PHP7.0, I had to use the PHP5.6 and returned to work.

**Comment by Patriboom** [comment]
I'm very surprised.
On my system ( PHP 7.0.14 / mysql under Linux ) I have  no PHPmailer library, but only the regular sendmail.  It works pretty good.

Please, let me know the error message and mailer behavior while using Bugs.

**Comment by marcelloinfoweb** [comment]
After I updated the library and moved on to php 5.6 does not show the message.

**Comment by Patriboom** [comment]
Please try changing  app/application/libraries/mail.php line 12
require  path('app') .  'libraries/PHPmailer/class.phpmailer.php';

by

require_once  path('app') .  'libraries/PHPmailer/class.phpmailer.php';

require_once instead of require

**Comment by Patriboom** [comment]
Just in case ... have you set properly you values in /config.app.php file ? 

Mail section needs to be provided with proper informations
```

	'mail' => array(
		'from' => array(
			'name' => 'Your name',
			'email' => 'address@youprovider.com',
		),
		/**
		 * Transport Settings
		 * Transport settings if using mail or smtp
		 * 'mail' or 'smtp' must be lower case
		 */
		'transport' => 'smtp',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => 'smtp.server.com',
			'port' => 465,
			/*
			* Encryption support, SSL/TLS, used with gmail servers
			* Default: blank
			* 'ssl' or 'tls' must be lower case
			* Here example for gmail server
			*/
			'encryption' => 'ssl',
			'username' => 'address@provider.com',
			'password' => 'Password'
		),
		'encoding' => 'UTF-8'
	),

```

**Comment by Patriboom** [comment]
Corrected file it there:  https://github.com/pixeline/bugs/blob/master/app/application/libraries/mail.php

**Comment by Hazaels** [comment]
Hi Patriboom,

So what should we do? Bugs is working fine for me right now.
Should I use the above code anyway?
Thank you!

**Comment by Patriboom** [comment]
The link is the exact same as the code above.
I put it there only to make it easier for those who are scared from code.

**Comment by Patriboom** [comment]
> So what should we do? Bugs is working fine for me right now.
Do you run it under PHP 7.0, 7.1, 5.x ?

**Comment by Hazaels** [comment]
I run it under PHP 5.5.36

But I have the following options to run PHP on my shared hosting:
7.0.7
5.6.24
5.5.36
5.4.45
5.3.29

**Comment by Patriboom** [comment]
I'm running PHP 7.0.13 and PHPmailer works goods.

**Comment by marcelloinfoweb** [comment]
Rosolved!
