### ISSUE TITLE
after install /login url return 404

### ISSUE THREAD

**Issue by ozexpert** [pixeline/bugs#17]
I just installed and seems the db is created fine, but was returning 404 for /login

Do i need to change any file permissions?

**Comment by melanholly** [comment]
you have problem with the .htaccess file look [here](http://askubuntu.com/questions/423514/how-to-enable-mod-rewrite-for-virtual-host). You can disable this feature i suppose by editing config.app.php and changing **'mod_rewrite' => true,** to **mod_rewrite' => false,**

**Comment by fnadde42** [comment]
Maybe your project is installed in a subdirectory to root? I installed it and got this problem due to the installation not being in root -> #4

**Comment by pixeline** [comment]
Fixed in forthcoming 1.5
