### ISSUE TITLE
Input::get

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#170]
I updated the files and it shows this error

Unhandled Exception
**Message**:
syntax error, unexpected ';'

**Location**:
/app/application/controllers/project/issue.php on line 278

_In theses lines_:
![error_bugs](https://user-images.githubusercontent.com/2093128/31079958-be1fad0e-a75d-11e7-857d-b73e3745df55.png)

PHP: 5.6
IDE: Netbeans

_The solutions is to changer to_:
$Modif = Input::get('Modif');
$Quel = Input::get('Quel');

**Comment by Patriboom** [comment]
That is because code is built for PHP 7
If I remember, you set back your application to PHP 5
You can correct ici this way:

```
if (isset(Input::get('Modif')) { $Modif = Input::get('Modif'); } else { $Modif = false; }
if (isset(Input::get('Quel')) { $Quel = Input::get('Quel'); } else { $Quel = "xyzxyz"; }

```

**Comment by marcelloinfoweb** [comment]
Unhandled Exception
**Message**:
Can't use function return value in write context

**Location**:
/app/application/controllers/project/issue.php on line 278

**Comment by Patriboom** [comment]
Sorry for that, but programming goes foward ... i'm only working for / with PHP 7

**Comment by marcelloinfoweb** [comment]
I understand perfectly, but imagine the following: The user will have to adapt the server to the Bugs system, and this is frustrating, and will probably make anyone choose another system. Do not get me wrong, please.

**Comment by Patriboom** [comment]
Files are modified.

**Comment by Hazaels** [comment]
Marcilloinfoweb, please check it again and confirm if it Works so the issue can be closed.
Thank you

**Comment by marcelloinfoweb** [comment]
Not work, still with the some error.

**Comment by marcelloinfoweb** [comment]
Not work, still with the some error.

**Comment by marcelloinfoweb** [comment]
I updated the php server to version 5.6 and it showed me this message:

Unhandled Exception
**Message**:
Cannot use isset() on the result of a function call (you can use "null !== func()" instead)

**Location**:
/var/www/bugs_/app/application/controllers/project/issue.php on line 287


Now this working, I did the following change:

$m = Input::get('Modif');
$q = Input::get('Quel');

if (isset($m)) { $Modif = Input::get('Modif'); } else { $Modif = false; }
 if (isset($q)) { $Quel = Input::get('Quel'); } else { $Quel = "xyzxyz"; }

**Comment by Patriboom** [comment]
The yesterday update fixed that.
