### ISSUE TITLE
Installing Bugs

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#178]
I found that the instructions to install Bugs are not clear...
What does that mean?

**set www-data ( CHOWN -R www-data:www-data ) as owner of the Bugs's main directory and sub-directories**

**Comment by Patriboom** [comment]
That's a Linux instruction to make sure that program is able to edit and write files.

**Comment by Patriboom** [comment]
I've just installed a new version of Bugs on my own computer:
Two observations:

1. Make sure your browser / PHP engine  has permission to create files and directories
2. Make sure your database user has permission to create a new database

Over that: not a single problem installing Bugs again on my computer.  For the test, I download (ZIP) form this very website ( https://github.com/pixeline/bugs/) and installed.  Nothing else.

**Comment by Hazaels** [comment]
I confirm the information.
The instalation is working fine.
