### ISSUE TITLE
Is "Your TODOs" functional?

### ISSUE THREAD

**Issue by beingalink** [pixeline/bugs#18]
There's the menu item Your TODOs but I don't see any way to interact with the empty lists there. Did I miss something?

**Comment by fnadde42** [comment]
If you go to the "Your Issues" tab and view the list of your issues, there is a green plus icon on the right of every issue. If you hover over it, it says "Add to your todos". Click it and it will appear on your todos :)

This could be more obvious by writing this instruction on the Todo-page.

**Comment by beingalink** [comment]
Thanks for the info! :)
