### ISSUE TITLE
Upload Function Not Working At All

### ISSUE THREAD

**Issue by swartjie** [pixeline/bugs#183]
Hi Guys,

Not sure if this is the correct place to post. hopefully you can help me.
I installed bugs to help us track development but we cannot upload any attachments. The upload button does nothing. It does not even do anything when we click on it. Double clicking just highlights the text "Upload"

Can you please help me find a fix for it?

**Comment by Patriboom** [comment]
Do you recieve any error message ?

**Comment by Patriboom** [comment]
Please follow the 161 issue discussion.
[https://github.com/pixeline/bugs/issues/161]https://github.com/pixeline/bugs/issues/161

**Comment by Patriboom** [comment]
Download works pretty well on my developpment sys.
I'll try to figure out what is with yours.
