### ISSUE TITLE
The requested URL /bugs-master/login was not found on this server.

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#184]
Dear, Alexandre Plennevaux and the rest of the contributors to this project
am experiencing the subject error above. Attached is the snippet of the result when i run the the project on localhost on my local PC. I will appreciate any help in solving the problem. Database creation is well executed.
![capture](https://user-images.githubusercontent.com/25264938/33515004-f9d3f194-d76d-11e7-94c4-c701cdce33d8.JPG)

**Comment by Patriboom** [comment]
Please check you bookmark, 
the proper address is :   http://(your path)/index.php/login

The capture you show doesn't present the **index.php** part

**Comment by wycky** [comment]
Thanks Patriboom , tried didnt work, i changed the localhost engine from wamp to xampp. its perfectly working without necessarily entering the path..http://(your path)/index.php/login.
