### ISSUE TITLE
PHP Mailing

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#185]
Now with PHP Mailing, anyone with idea on configuration??..checked inbox after creating an issue and assigned it to a user but can find a notification in the email. Thanks in advance.

**Comment by wycky** [comment]
solved the problem by checking on my email transport settings. working perfect

**Comment by Patriboom** [comment]
Thanks Wycky for your comeback and answer to your own problem.  I could not answer because I had a surgery and from that only one arm to type.  Second arm is back on track. I'll be back on programming also.

**Comment by wycky** [comment]
Hallo Patrick, am sorry to learn of your illness..wish you quick recovery and am glad you are back with the help of your one arm in programming. Also i noticed one error on the project, during attachment of a file on an issue,its not saved in the database and also the receipient assigned the issue cannot be able to download or view the attachment, guess some php attachment insertion code is missing. Will appreciate if you find time and check on it. Once again Patrick wish you quick recovery

**Comment by Patriboom** [comment]
Ok, i reopened your issue and changed the title.

I'm not sure if it's relevant to make it on work.  
In Bug's system, the email has mission to notice user that something is going on in the project.  Is it relevant to send also the whole content - even the attached file ?  Not quite sure. While the said file is there on system, why to send an other copy to any user ? 

I can have a look on that, but I'll do with no strong conviction of valuable function.

If anyone wants to work on that: just go for it.  We'll include your work into the project. and help you to make it at work for the next major update.
