### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#186]
thinking of implementing reports generations on bugs project and be able to print in hard copies i.e. pending issues reports, issues in progress reports, transferred issues reports, unhanded issues etc. ideas are welcomed, once am done will update you guys.

**Comment by Patriboom** [comment]
Hello Wycky, 

I'm not quite sure to understand what do you want.
What i've red here seams to be the same as the dashboard : with closed issues, open ones and so on.
Do you want to print that or take it out into a pdf document ?

**Comment by wycky** [comment]
Hello Patrick, okay i simply mean all the issues assigned to someone can be generated in a report format and be printed in a hardcopy format or be emailed. check this sample project out with reporting tools http://jdorn.github.io/php-reports/#GettingStarted to get my concept

**Comment by Patriboom** [comment]
Ah ok.
More than a plugin, we could manage to inter-connect the two systems to make the « php-reports » able to build reports from Bugs.

**Comment by wycky** [comment]
Awesome that's the point Pato

**Comment by Patriboom** [comment]
Ouf!  Lot of work!
There's so many component my computer doesn't have yet only to make the « reports » system work.
I'll try first to solve issues, then - if anyone else doesn't already do that all's benefits - I'll have a look on that.

**Comment by wycky** [comment]
Hello Team, this is my progress on reporting, however not complete, need ideas and some contributions so that we can wind up this ticket. attached are files for reporting, just a small sub-project which Patrick
 can help us include in the main Bugs project

[Bugs-Reporting.zip](https://github.com/pixeline/bugs/files/1590681/Bugs-Reporting.zip)

**Comment by Patriboom** [comment]
Where to copy the Bugs-Reporting directory ?

**Comment by wycky** [comment]
i have the right update find it here. Copy the files to the local directories of your localserver(xampp or wamp). it uses the existing bugs database

[archive.zip](https://github.com/pixeline/bugs/files/1591193/archive.zip)

**Comment by Patriboom** [comment]
I'm looking at the archive.zip you've prepared, Wicky.  For now, i find a simple mistake: it seams that we need to repeat the configurations in every single sub-part of the work.  I suggest a centralized file where to set the whole thing. 
I'll be back

**Comment by Patriboom** [comment]
Here, i suggest some modifications:
new file named BugsRepConfig.php  which will include all configurations from the enduser
Simplier mysql request for the first report you've built
Wider column for the long content (desciption) and narrower ones for other ... merge some informations into columns;
ORDER issues by project, then by issue's opening date

I don't understand how the report production works, but with long list as mine, report table is too short and can not include the whole thing.  It doesn't show the page's footer.  We have to find a way to cut pages AND to have many pages instead of only one.
[Bugs_Reporting.zip](https://github.com/pixeline/bugs/files/1594169/Bugs_Reporting.zip)
Please use simple zip instead of zip over rar.

**Comment by wycky** [comment]
Hallo Patrick,thanks for your kind observation and proposed amendments. the best way forward le me work on the whole reporting files then will share them with you so that you can comment and make some changes on it once and give way how we can include them in the bugs-master project.i thought we can add a Reports link just afters the "Projects" Link on the header of the index file of bugs-master which can be accessed by every user type. will resume working on the same new year..wish you happy and prosperous new year 2018 in advance. as foe now i can take a look at the BigsRepConfig file you have worked on..thanks for the file

**Comment by wycky** [comment]
About this "I don't understand how the report production works" we will figure out on our way as we work on reporting, just a clean formatted reports filtered project wise and also have date pickers e.g a report from 1st of December to end of 31st of December. so that a non-tech users e.g a supervisor who does not interact most times with computer systems can be able to get this reports and help him/her to know who was assigned which task, the progress of the task and any other relevant information from Bugs-Master. That is the whole idea i initially had about Reporting.

**Comment by wycky** [comment]
check my file i worked on yesterday however i couldn't make to fetch the issue assignee..check fetch code line 8 and see how can we inner join more to fetch the user. Have also compared the output of your table its awesome, check this out too and if the table margins are okay upon print out

[report.zip](https://github.com/pixeline/bugs/files/1594377/report.zip)

**Comment by wycky** [comment]
Now i see your point of introducing table widths and merging some column infos

**Comment by Patriboom** [comment]
Thanks for reply ... I will let you work on that.

> Now i see your point of introducing table widths and merging some column infos

Have a look on the report's capture I've just taken.
![capture](https://user-images.githubusercontent.com/19801202/34455703-a18fbf90-ed52-11e7-924c-80794722ff28.png)

**Comment by Patriboom** [comment]
Here: a working query.
id = 1  will need to be replaced by
`id = '.$userYouWant.' `

so ...

`SELECT ISSU.id, ISSU.title, ISSU.body, ISSU.created_at, ISSU.closed_at, 
CONCAT(USR.firstname, ' ', USR.lastname) AS assignee,
CONCAT(CRE.firstname, ' ', CRE.lastname) AS creator, 
PROJ.name 
FROM projects_issues AS ISSU
LEFT JOIN projects AS PROJ ON PROJ.id = ISSU.project_id
LEFT JOIN users AS USR ON USR.id = ISSU.assigned_to 
LEFT JOIN users AS CRE ON CRE.id = ISSU.created_by 
WHERE ISSU.created_by = 1`

**Comment by wycky** [comment]
Thanks Patrick, really helpful. For sure am  learning and gaining a lot from your work. Am not that well in PHP but am really learning from your help. You work on the other open issues, let me also work on this until completion. i will customize all reports then will share when am done. Good times folk

**Comment by Patriboom** [comment]
This one is even better.  It gives you back how many issues are attached to a project on each line:

`SELECT ISSU.id, ISSU.title, ISSU.body, ISSU.created_at, ISSU.closed_at, 
CONCAT(USR.firstname, ' ', USR.lastname) AS assignee,
CONCAT(CRE.firstname, ' ', CRE.lastname) AS creator, 
PROJ.name,
(SELECT count(id) FROM projects_issues WHERE project_id = ISSU.project_id AND (created_by = 1 OR assigned_to = 1) GROUP BY project_id ) AS nb_proj
FROM projects_issues AS ISSU
LEFT JOIN projects AS PROJ ON PROJ.id = ISSU.project_id
LEFT JOIN users AS USR ON USR.id = ISSU.assigned_to 
LEFT JOIN users AS CRE ON CRE.id = ISSU.created_by 
WHERE ISSU.created_by = 1 OR ISSU.assigned_to = 1
ORDER BY name ASC, created_at DESC`

**Comment by wycky** [comment]
indeed even better, now you have simplified my work..it will be much easier to work on the other report types remaining having helped me with this  "SELECT....."statement. 

then i work on ( Also, in BugRepConfig.php, you'll can put the personnal config for
paper size
paper orientation (landscape or portrait)
output directory
personnal header and footer
I also suggest that the index.php page give direct access to the last (3 or 6) reports using the free space under the four top icons.)

thanks Pato

**Comment by wycky** [comment]
Hallo Patrick, Happy New Year. I Have this Date_Picker however having an error (Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\Date_Picker\filter.php on line 21). Any help will appreciate

[Date_Picker.zip](https://github.com/pixeline/bugs/files/1597008/Date_Picker.zip)

**Comment by Patriboom** [comment]
Only misses a '  after your second date

`	  SELECT ISSU.id, ISSU.title, ISSU.body, ISSU.created_at BETWEEN '".$_POST["from_date"]."' AND '".$_POST["to_date"]."', 
	  ISSU.closed_at, CONCAT(USR.firstname, ' ', USR.lastname) AS assignee, 
	  CONCAT(CRE.firstname, ' ', CRE.lastname) AS creator, PROJ.name 
	  FROM projects_issues AS ISSU 
	  LEFT JOIN projects AS PROJ ON PROJ.id = ISSU.project_id 
	  LEFT JOIN users AS USR ON USR.id = ISSU.assigned_to 
	  LEFT JOIN users AS CRE ON CRE.id = ISSU.created_by 
	  WHERE ISSU.created_by = 1 OR ISSU.assigned_to = 1 
`

If you use the BugRepConfig.php, you're not supposed to repeat the connection line 
`$connect = mysqli_connect("localhost", "root", "", "bugs");`
It's in the file and the connect variable is defined for all pages.

**Comment by wycky** [comment]
its an independent project files. have not place them in Bugs_Reporting sub_project.

**Comment by Patriboom** [comment]
Ah!
Anyway, don't forget a to changer your values ( 1 ) for variables
`ISSU.created_by = 1 OR ISSU.assigned_to = 1`
for
`ISSU.created_by = "'.$number.'" OR ISSU.assigned_to = "'.$number.'"`

**Comment by Patriboom** [comment]
Link in Bugs to quick access to Reports is done.

**Comment by wycky** [comment]
SELECT ISSU.id, ISSU.title, ISSU.body, ISSU.created_at, ISSU.closed_at, CONCAT(USR.firstname, " ", USR.lastname) AS assignee, CONCAT(CRE.firstname, " ", CRE.lastname) AS creator, PROJ.name FROM projects_issues AS ISSU LEFT JOIN projects AS PROJ ON PROJ.id = ISSU.project_id LEFT JOIN users AS USR ON USR.id = ISSU.assigned_to LEFT JOIN users AS CRE ON CRE.id = ISSU.created_by


from my end i decide to leave it that way since i need all the data created by every user and assigned to any user, coz i realized if i limit the number of values of the variables, i get a report for that specific user id.

**Comment by wycky** [comment]
Hope everyone is well..Patrick my progress is good, so far added date and search filters and also data export to excel and word in general.php file. can replace Bugs_Reporting files from the ones have uploaded. if you are good in jquery kindly check for me why search is not working after filtering the data using datepickers. but it works before filtering the data by dates

[RTS_Reporting.zip](https://github.com/pixeline/bugs/files/1600767/RTS_Reporting.zip)

**Comment by wycky** [comment]
Hallo  Patrick think am done with reporting..only left with data encoding have not figured that one out. its not a priority for now but i will work on it on the long run. Kindly help me with necessary files to include Bugs_Reporting files in the main project that is Bugs_System
Thanks in advance..attached are Bugs_Reporting files.

[Bugs_Reporting.zip](https://github.com/pixeline/bugs/files/1606733/Bugs_Reporting.zip)

**Comment by wycky** [comment]
worked it out how to include reporting files in the bugs project. should be closing this case now unless someone too is interested with reporting configurations

**Comment by Patriboom** [comment]
Not yet ....
I didn't do my part.

**Comment by wycky** [comment]
Alright, your part is of help to us. i just did a basic setup of files inclusion, i know you understand Bugs better than us so we can gain a lot from your input. like i tried to include header files in Bugs_Reporting but couldn't work out for me

**Comment by Patriboom** [comment]
Just wait few hours, maybe 2 days.  Bugs is ready for the link to Reports, but is missing your files (as i said before) and testing again.

**Comment by wycky** [comment]
i zipped the files check new file 3 days ago upload

**Comment by Patriboom** [comment]
Hello, 
i tested it today.  It's ok.
Please also test the Work2018 branch and let me know.
I already started some structure for translations ... coming next.
But, before 

1 test it
2 Let correct the upload system (other issue)

**Comment by wycky** [comment]
Okay thank you

**Comment by wycky** [comment]
Perfectly works well. Thanks

**Comment by Patriboom** [comment]
I'm still working on translation and will do it before to pass the branch into « master »

**Comment by wycky** [comment]
Great work bro

**Comment by Patriboom** [comment]
Lets go foward with this developpment using  https://github.com/Patriboom/BugsReports.git

**Comment by Patriboom** [comment]
> Hallo patrick need to add some few codes to new.php file in the project/issue folder to have a datepicker..that is if i want to create an issue that should take place exactly on a given day or duration of days that is date pickers with from from and to and also add two columns for the date pickers in the table projects_issues. this will meet my requirements in Bugs project. was using this reference but has not worked out yet https://www.malot.fr/bootstrap-datetimepicker/demo.php. Have also created a calender activity file that displays all issues that will happen on a given date. i just need you to help me have the right code for date picker to add just after 'Allowed Time'
and the the line of code where insertions into the database is located. the rest i will do. Already have added 'calenderstart' => 'Date From', and 'calenderend' => 'Date To' in tinyissue.php. thanks..

> Have attached the calender output can try it with your machine.
> Calender.zip
> 

Hello Wycky, have you red the whole thing from https://github.com/smalot/bootstrap-datetimepicker ?
I think, you'll find what you want there.
I'll have a look.

to develop both sides something on Bugs-Tickets, we have to work with git. This way, we both will be able to enjoy the counterpart work quickly.
Lets go foward with this developpment using https://github.com/Patriboom/BugsReports.git

**Comment by Patriboom** [comment]
Hello wicky, 
I've translated all your 4 reports.
I invite you to update your files before working on them.  Those translated reports may help your for next reports you'll build.
There is the updated version:  https://github.com/Patriboom/BugsReports.git

**Comment by wycky** [comment]
Good Day Patrick. Thanks for your effort..looks awesome

**Comment by Patriboom** [comment]
Ok, 
I'll merge those Report parts into the Bugs' master branch.
I'll check for your datepicker in Report after.

**Comment by wycky** [comment]
Alright Thanks in advance

**Comment by wycky** [comment]
I like trying before seeking help so i tried and placed the datepickers but looks weird like has no CSS/Bootstrap like the ones at https://github.com/smalot/bootstrap-datetimepicker. Anyway when you will work it out i believe the output will be attractive. Already added two columns in the projects_issues table and added some codes to store the date data. so far i can see the the dates are being stored as i wanted. only remaining with display what has happened on the page that is displaying the dates on the page as issue title,body,assigned to, tags and allowed time are displayed.

![capture](https://user-images.githubusercontent.com/25264938/35099227-36ebd92e-fc68-11e7-996a-9ee8d1dd4713.PNG)

**Comment by Patriboom** [comment]
Please wycky , push your files into the Work2108 branch so we can share your code and go further with you.

- Install a git manager program
- create a local repository
- create a branch, 
- synchronize it whit github.com/pixeline/bugs  site.

**Comment by Patriboom** [comment]
Can we close this discussion ?

**Comment by wycky** [comment]
Sure

**Comment by Patriboom** [comment]
Hello Wicky, 

I kicked out the Report system from BUGS, but managed a link between both of those applications.  Anyone who wants to use your report system will need to install it from the git deposit mentioned below.

I would like you to come to this address  https://github.com/Patriboom/BugsReports/ to permit me to open you doors as responsible of the deposit.


> Hello wicky,
> I've translated all your 4 reports.
> I invite you to update your files before working on them. Those translated reports may help your for next reports you'll build.
> There is the updated version: https://github.com/Patriboom/BugsReports.git

**Comment by Patriboom** [comment]
Ok, I've done other way.

**Comment by Patriboom** [comment]
Wycky
I've integrated the reports into the main program of BUGS.
You can check and comment if you install the release 1.6 revision 2b as it is now in « master » branch.

**Comment by Patriboom** [comment]
![Bugs_17_1a](https://user-images.githubusercontent.com/19801202/60734547-4cedd100-9f1e-11e9-887f-a56d47edb69f.png)
