### ISSUE TITLE
Email Notification Subject

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#187]
Hallo Patrick hope you getting well..am loading a new ticket to seek some help in email notification on the subject of the email, which line of code can we edit to change the subject of the email message for every new issue loaded which i see in the database has unique ID. so that we fetch and display the unique id on the subject of every email notification rather having a repeated bold subject with the same message as the one generated by line one of new_assigned_issue.php. if we can be able to change like sample attached below on tickets loaded here,  the email notification will look better. Not yet given up still trying modifications but is has not worked out. thanks

![a](https://user-images.githubusercontent.com/25264938/34164728-5a00c076-e4eb-11e7-9bfa-44afb299b725.JPG)

**Comment by Patriboom** [comment]
That's an other good idea.
I'll work on that soon.

**Comment by Patriboom** [comment]
Ok, i'm looking that.  And many notices are properly built.

Like:

- issue reassignment which builds subject as  (line 238)
`$subject  = sprintf(__('email.reassignment'),$Issue_title,$project_nm);`

- issue comment which builds subject as (line 107)
`$subject = sprintf(__('email.new_comment'), $issue->title, $project->name);`

- assign a new ticket: ( lines, 243, 317, 376, 591, 608)


Those are lines which process the « always same message and subject »

We can imagine having an array with some different messages for the content.
The system sends now the issue title and project name as email subject.  What can you expect more or so different ? 

You can modify content editing the app/application/language/YOURLANGUAGE/tinyissue.php file, especially the following lines:

- 76 ( 'issue_assigned_to_you' variable ) 

- 83 ('issues_assigned_to_you' variable )

**Comment by wycky** [comment]
Okay thanks Patrick let me try to play around with the lines of codes to see if the output will come of what i am anticipating. if it works out the better like sample below from another project was working on but does not use arrays to fetch the data
![ticket](https://user-images.githubusercontent.com/25264938/34194039-cfa9d804-e567-11e7-8551-683c4ebfe1c8.JPG)

**Comment by wycky** [comment]
I arrived at the solution guyz
changed code to this  lines, 243, 317, 376, 591, 608 with $subject = sprintf('Ticket#'). '' .sprintf($issue->id);
by first declaring an array 'id' => 'Id', in tinyissue.php to enable fetching the id

my output:
![c](https://user-images.githubusercontent.com/25264938/34198898-f532348a-e57c-11e7-8a80-36b73ae2dd76.JPG)
