### ISSUE TITLE
Going back...

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#188]
I came to the conclusion that the bugs in bugs are so many that it would be better to go back to the original version when the main developer left the project.
What do you think about reverting all changes and just leaving it as it was before?
At least it worked...

**Comment by Patriboom** [comment]
It's all up to you.

What the bugs are they all ? 

- email doesn't send HTML, but send very nicely plain text:  this worked somehow before
-drag&drop in 1 page ( dashboard)
- download without flash : this didn't work before

For sure I will not go back.  If you want to do so, archives are here: https://github.com/pixeline/bugs/releases  

I'll go further and get ready for PHP 7.1
I'm just running out of time and helpers are not many (in fact: 0 )

**Comment by Hazaels** [comment]
For sure I want the original version. Which one is the original? 1.30? 1.31?
Since the original developer left the project nothing seems to work as expected anymore.
The fixes are more like patches over patches and the code became unstable and none can trust it anymore. It is almost better to start all over again from scratch.
I had to change to [FlySpray](http://www.flyspray.org/) and I do not regret because it is way more stable and nice than Bugs although I liked the simplicity of Bugs - unfortunatelly it was all lost since it doesn't work!
I invite anyone interested to vist FlySpray and give it a try.

**Comment by Hazaels** [comment]
Why did you close the issue? I didn't want it to be closed.
Is this a one man Project?
If this is the case I am out of here...

**Comment by marcelloinfoweb** [comment]
[Migrate to this](https://github.com/satrun77/tinyissue), it is a fork of the Original, this functional and has prospect of continuation
