### ISSUE TITLE
Closed issue 188

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#189]
I want to express that I do not agree with the policy of this Project.
Patrick closed the Issue #188 without even asking for it.
I want to communicate to everyone that I am out of this Project because I don't belive it will work.
I also invite anyone interested to visit the [FlySpray Project](http://www.flyspray.org/) because it may be a possible answer to your requirements...

**Comment by marcelloinfoweb** [comment]
[Migrate to this](https://github.com/satrun77/tinyissue), it is a fork of the Original, this functional and has prospect of continuation

**Comment by Patriboom** [comment]
Issue 188 has been closed because it's not and issue, but a comment.
