### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#191]
Patrick do you have a solution for this? it occurs when a comment is being raised when i go back on the page the comment is posted
![error](https://user-images.githubusercontent.com/25264938/34299042-dc9e74cc-e731-11e7-9477-cd6c714c4181.png)

**Comment by Patriboom** [comment]
We can check if the class is alreay defined or, when we create if first, call it with  require_once instead of require

**Comment by wycky** [comment]
Yes i have SMTP in my config file. Can the error be caused by timeout?

**Comment by Patriboom** [comment]
Please try this: 
change   app/application/librairies/mail.php line 19

from 
`require  path('app') .  'libraries/PHPmailer/class.smtp.php';`

to
`require_once  path('app') .  'libraries/PHPmailer/class.smtp.php';`

**Comment by wycky** [comment]
okay thanks bro, i will change that and check the results after christmas..for now in christmas mood hehe...wish you a Merry Christmas with your family

**Comment by wycky** [comment]
Hallo Patrick, error,solved, also modified line 41, so far so good. Thanks Geek. we can close now this ticket
