### ISSUE TITLE
Issue Reassignment

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#198]
Hey Pato, are you okay? trying to find a line of code where i can add/edit some line of codes so that a system administrator on the drop down list of issue reassignment to, he/she can be able to see all system users during issue reassignment in case the administrator wants to reassign the issue to any user belonging to any project. to avoid adding every user to every project. thanks in advance.

**Comment by wycky** [comment]
Hallo patrick need to add some few codes to new.php file in the project/issue folder to have a datepicker..that is if i want to create an issue that should take place exactly on  a given day or duration of days that is date pickers with from from and to and also add two columns for the date pickers in the table projects_issues. this will meet my requirements in Bugs project. was using this reference but has not worked out yet https://www.malot.fr/bootstrap-datetimepicker/demo.php. Have also created a calender activity file that displays all issues that will happen on a given date. i just need you to help me have the right code for date picker to add just after(<tr>
				<th><?php echo __('tinyissue.duration'); ?></th>
				<td>
					<input type="number" name="duration" style="width: 60px;" value="<?php echo $config_app['duration']; ?>" min="1" max="400" />&nbsp;<?php echo __('tinyissue.days'); ?>
				</td>
			</tr>)
 and the the line of code where insertions into the database is located. the rest i will do.  Already have added 'calenderstart' => 'Date From', and 'calenderend' => 'Date To' in tinyissue.php. thanks..

Have attached the calender output can try it with your machine.
[Calender.zip](https://github.com/pixeline/bugs/files/1628213/Calender.zip)

**Comment by Patriboom** [comment]
Hello Wycky, have you red the whole thing from https://github.com/smalot/bootstrap-datetimepicker  ?
I think, you'll find what you want there.
I'll have a look.

**Comment by Patriboom** [comment]
Hello Wycky, 

to develop both sides something on Bugs-Tickets, we have to work with git. This way, we both will be able to enjoy the counterpart work quickly.

**Comment by wycky** [comment]
Thanks for that approach, which file specifically in Bugs Project contains the reference for all the styles so that i can include these ones for datepicker:
 <link href="./bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="../css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="./jquery/jquery-1.8.3.min.js" charset="UTF-8"></script>
<script type="text/javascript" src="./bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script type="text/javascript" src="../js/locales/bootstrap-datetimepicker.fr.js" charset="UTF-8"></script>
<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 1
    });
	</script>

**Comment by wycky** [comment]
Am still stuck on issue reassignment,any help please as earlier requested you?

**Comment by Patriboom** [comment]
I don't understand your request.
What do you want the code for ?    Is it for the  Report project ? 
This issue's title is  « Issue Reassignment ».  So, is it for issue reassignment function in Bugs project ? 
First you asked for a javascript code, help to insert it into your code.
Second you as for css code ton insert into something else.
I'm all mixed up.

**Comment by wycky** [comment]
its okay, will leave at where i tried to change the lines of Bugs code. thanks
