### ISSUE TITLE
Not possible to add/remove/change tags on an issue?

### ISSUE THREAD

**Issue by sebastiancarlsson** [pixeline/bugs#2]
Hi, just wondering is this is a feature that has not been implemented yet? I can chose tags when I create an issue but I can't figure out how to change or add tags. Don't know if this is a bug, not implemented yet or if it's just me being stupid :wink:

**Comment by pixeline** [comment]
Addressed in forthcoming 1.5: a grey edit icon stands nex to the issue title.
