### ISSUE TITLE
Implement 24 hour clock

### ISSUE THREAD

**Issue by fnadde42** [pixeline/bugs#20]
It is most irritating for a user of a 24 hour clock to have to think every time when reading a 12 hour clock.

**Comment by pixeline** [comment]
true that. Same here :)

Alexandre Plennevaux
........................................................................



........................................................................
web | wide | world  - http://pixeline.be
........................................................................
Latest releases:
http://thatsthespir.it
http://bjab.org
http://karoo.me
https://brujobs.irisnet.be

**Comment by pixeline** [comment]
Implemented in forthcoming version.
