### ISSUE TITLE
[ TUTORIAL ] Editor change - step by step

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#205]
I was having problem with the add editor in the other textarea on the same page, I decided to switch to another, I chose [Trumbowyg](https://alex-d.github.io/Trumbowyg/), for being simple and light to application.

Before, download the  [Trumbowyg](https://alex-d.github.io/Trumbowyg/) and place the files in the following directory:

`/bugs/app/vendor/`

Rename it to "Trumbowyg"

### For the exchange I did the following:

In the `/bugs/config.app.php` file:
Changed `editor` for:
```php
'editor' => array(
	'BasePage' => '/app/vendor/Trumbowyg/trumbowyg.min.js',
),
```

### Edit the following files:
`/bugs/app/application/views/project/issue/activity/comment.php` line 48
`/bugs/app/application/views/project/issue/index.php` line 326
`/bugs/app/application/views/project/issue/new.php` line 187
`/bugs/app/application/views/project/issue/edit.php` line 69

### In the files above have the same code, remove or comment everything by the code below:

Code:
```php
$wysiwyg = Config::get('application.editor');
if (trim($wysiwyg['BasePage']) != '') {
    if ($wysiwyg['BasePage'] == '/app/vendor/Trumbowyg/trumbowyg.min.js') { ?>
        setTimeout(function() {
            $('textarea').trumbowyg({
                btns: [
                    ['viewHTML'],
                    ['undo', 'redo'], // Only supported in Blink browsers
                    ['formatting'],
                    ['strong', 'em', 'del'],
                    ['foreColor', 'backColor'],
                    ['superscript', 'subscript'],
                    ['link'],
                    ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                    ['unorderedList', 'orderedList'],
                    ['horizontalRule'],
                    ['removeformat'],
                    ['fullscreen']
                ],
                removeformatPasted: true,
                resetCss: true,
            });
        }, 1000);
    <?php } ?>
<?php } ?>
```

And in `/bugs/app/application/views/layouts/blocks/header.php`: line 33
Code:
```php
$wysiwyg = Config::get('application.editor');
if (trim($wysiwyg['BasePage']) != '') {
    if (substr($wysiwyg['BasePage'], -2) == 'js') { 
        echo '<link href="//servidor/bugs/app/vendor/Trumbowyg/ui/trumbowyg.min.css" media="all" type="text/css" rel="stylesheet"/>'; 
        echo '<link href="//servidor/bugs/app/vendor/Trumbowyg/plugins/colors/ui/trumbowyg.colors.css" media="all" type="text/css" rel="stylesheet"/>';
        echo '<script src="'.URL::base().$wysiwyg['BasePage'].'"></script>'; 
        echo '<script src="//servidor/bugs/app/vendor/Trumbowyg/plugins/colors/trumbowyg.colors.min.js"></script>';
    }
}
```

### And test, it should look like the image below:

![editorbugs](https://user-images.githubusercontent.com/2093128/35274992-5b255a48-0025-11e8-9122-63ba89f863e8.png)

**Comment by Patriboom** [comment]
Nice!
Do you think, we can offer both editors to the coming users ? 
I mean: the changes you've done in the php code ... can they exist in parallel with the other editor's codes  ?

**Comment by Patriboom** [comment]
Do you think i would be better to all users to switch to the editor you're talking about here ?
And ... we would change definitively to that one instead of the actual one ?

**Comment by marcelloinfoweb** [comment]
Yes, you can have both editors, no problem, which is why I chose this one because it is compatible with the generated html.
I prefer to change the whole system, for my case is enough text editing options.
Each case is a case, what has worked for me may not work for other people.

**Comment by Patriboom** [comment]
Ok, so I think it could be good to include both editor in the Bugs's system ... the user will chose.

**Comment by wycky** [comment]
Mercello i love the editor,le me try to follow the steps and see if it can work for me too
Great work

**Comment by wycky** [comment]
What are we downloading and placing here Quoted text "Before download and place the files in the following directory:
/bugs/app/vendor/"?

**Comment by marcelloinfoweb** [comment]
@wycky I added, I put the download link. Sorry for the delay to answer, I'm from Brazil.

**Comment by wycky** [comment]
Its Well. so is it the plugins we downloading or the whole Trumbowyg-master project..and have noted in the  projects some of your referenced files above are not located anywhere in the subfolders .e.g. Trumbowyg/trumbowyg.min.js, Trumbowyg/plugins/colors/trumbowyg.colors.min.js, Trumbowyg/plugins/colors/ui/trumbowyg.colors.css to mention a few. can manage to share with us your Trumbowyg folder please?

**Comment by marcelloinfoweb** [comment]
Sorry @wycky , I do not understan.

**Comment by wycky** [comment]
Okay sorry le me not bother you more.. let me figure it out on my own. and Colors on the editor your did not manage?

**Comment by marcelloinfoweb** [comment]
I'm sorry again, be more explicit, really do not understand, it may be due the google translator, if you can send a print or be clearer, it will help a lot. Thank you!!!

**Comment by Patriboom** [comment]
Hello guys, i'm working to make the wycky's suggestion able to work on any computer.

## First change:  in config.app.php file
	/**  wysiwyg editor
	  *  Default : 'BasePage'=>'/app/vendor/ckeditor/ckeditor.js',
	  *  No one  : 'BasePage'=>'',
	  *  If you want to use no wysiwyg editor please set this to empty.
	  *  Do not mark this as comment
	  *  Fill out with the entire path, begining with app/
	  *  Editor base page type permitted:  .js   .php
	  ////This (below) for ckeditor
			'directory' = > 'vendor/ckeditor',  
			'BasePage' => '/app/vendor/ckeditor/ckeditor.js',
			'name' => 'ckeditor',
	  ////This (below) for Trumbowyg editor
		'directory' = > 'vendor/Trumbowyg/',  
		'BasePage' => '/app/vendor/Trumbowyg/trumbowyg.min.js',
		'name' => 'trumbowyg',
	*/
	'editor' => array( 
		'directory' => 'vendor/Trumbowyg',
		'BasePage' => '/app/vendor/Trumbowyg/trumbowyg.min.js',
		'name' => 'trumbowyg',
	),


## Second, the app/application/views/layouts/blocks/header.php file
adding the line which begins by if(file_exists...)

		<?php $wysiwyg = Config::get('application.editor');
			if (trim($wysiwyg['BasePage']) != '') {
				if (file_exists($wysiwyg['directory'].'/Bugs_code/header.php')) { include_once $wysiwyg['directory'].'/Bugs_code/header.php'; }
				if (substr($wysiwyg['BasePage'], -2) == 'js') { echo '<script src="'.URL::base().$wysiwyg['BasePage'].'"></script>'; }
				if (substr($wysiwyg['BasePage'], -3) == 'php') { include $wysiwyg['BasePage']; }
			}
			$RepInstalled = false;
			if (file_exists("vendor/Reports/config.php")) { 
				$RepInstalled = true; 
				$Configurations = file("vendor/Reports/config.php"); 
				$ReportsConfig = explode(",",$Configurations[0]);
				foreach($ReportsConfig as $ind => $val ) { $ReportsConfig[$ind] = substr($val, 1, strlen($val)-2); }
			}
		?>

Doesn't work yet ... I'll have to work on other files, wycky said he has to change.

**Comment by Patriboom** [comment]
About other four files 
- /bugs/app/application/views/project/issue/activity/comment.php
- /bugs/app/application/views/project/issue/index.php
- /bugs/app/application/views/project/issue/new.php
- /bugs/app/application/views/project/issue/edit.php

 I did:

		<?php 
		} else if ($wysiwyg['name'] == 'trumbowyg') { ?>
			setTimeout(function() {
				$('textarea').trumbowyg({
					btns: [
						['viewHTML'],
						['undo', 'redo'], // Only supported in Blink browsers
						['formatting'],
						['strong', 'em', 'del'],
						['foreColor', 'backColor'],
						['superscript', 'subscript'],
						['link'],
						['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
						['unorderedList', 'orderedList'],
						['horizontalRule'],
						['removeformat'],
						['fullscreen']
					],
					removeformatPasted: true,
					resetCss: true,
				});
			}, 1000);

**Comment by Patriboom** [comment]
For now, it doesn't work, giving me a javascript error:

$('textarea').trumbowyg({ is not a function.

I'll dig a bit on that issue.

**Comment by Patriboom** [comment]
I did find any solution for  $('textarea')  ...   is it Jquery ? 

Anyway, to make lighter and more simple, I isolated the toolbar definition of ckeditor and trumbowyg out of all the four file.  ... like this:

<?php
	$wysiwyg = Config::get('application.editor');
	if (trim($wysiwyg['directory'	]) != '') {
		if (file_exists($wysiwyg['directory']."/Bugs_code/showeditor.js")) {
			include_once $wysiwyg['directory']."/Bugs_code/showeditor.js"; 
		} 
	} 
?>

So, for trumbowyg, we have a new file in
/app/vendor/Trumbowyg/Bugs_code/showeditor.js

**Comment by Patriboom** [comment]
At this point, with - still - the $wysiwyg['directory'] error, 
it's in Work2018 branch.

**Comment by wycky** [comment]
I tried to manually delete the issues from the projects_issues table then there was this error  next time i loaded the bugs link on the browser it failed. 
![capture](https://user-images.githubusercontent.com/25264938/35437128-296fd6b6-02a2-11e8-9695-f81c4b1e9b79.PNG)
 Later i realized for the project to load well, will have to manually delete all the data referenced in the other tables e.g. projects_issues_comments and users_activity.. so you see its a long process and this might result to deleting unwanted info, compared to when we have a click button with a right code behind it. not yet checked before if the same issue was raised by someone else

**Comment by wycky** [comment]
I will try to implement one and have a test on it, failure will brainstorm together, thanks all

**Comment by marcelloinfoweb** [comment]
Sorry for the delay, I do not have the project at home, just at work. I took some time to edit and improve the tutorial. I hope it helps.

Any questions, do not hesitate to ask.

**Comment by Patriboom** [comment]
Wycky ... you mix topics.  This one is about  Trumbowyg editor.
Please open an other issue discussion with the other topic .. yes it's achevable.

**Comment by wycky** [comment]
sorry, noted

**Comment by wycky** [comment]
Hey Guys hope everyone is doing great,

Current Bugs Editor this is my output when formatting the text. Patrick how can we disable those formatting during display of what was submitted?

![capture](https://user-images.githubusercontent.com/25264938/35763822-c9b67188-08c5-11e8-8f19-b7951d6a188d.PNG)

**Comment by Patriboom** [comment]
Sorry guys,  I did not pass yet the obstacle: 
At this point, with - still - the **$wysiwyg['directory'] error**,

I'm pretty sure you are using Jquery to achieve your install.
I don't have Jquery installed on my computer and hope to pass through this blocage first.
Then, I'll check deeper the trumbowyg

**Comment by Patriboom** [comment]
wycky ... the problem you show there is an interpretation problem.  It sounds like the text editor is unable to decode what it did encode itself.  

As I wrote before, i need to debug mine first and - for that - to find a solution for those who don't have Jquery installed.  Then, I'll be able to look at the problem you showed here.

Marcello ... any clue ?

**Comment by marcelloinfoweb** [comment]
First, why not have jquery? and second, what are you trying to do?

**Comment by Patriboom** [comment]
No jQuery yet, because there is no jQuery anywhere else in the project.   .... so no jQuery to keep it simple, near to what it was at the origin so people can upgrade easily.

Second:  what am I trying to do:  integrate your suggestion for the  Trumbowyg  into the global project, so anyone can enjoy an other text editor.

If you think, we can add jQuery to the whole project ... ok
It will push the work into and easier integration step, but maybe it will turn it harder to update the Bugs project for those who run it since long time.

Writing it all, I'm starting to think that it could be better with jQuery ... the difficult part would be to intergrate that into the migration program from 1.5 to 1.6

Waiting for your opinion

**Comment by marcelloinfoweb** [comment]
But the Bug project already has Jquery, the editor I use has used what already exists.

**Comment by Patriboom** [comment]
Good news ... it will be easier.
I'll try to find my jQuery config, because on my system it doesn't work. Doing that, I'll set the path for those who will encounter the same problem.

**Comment by Patriboom** [comment]
Does it work, now  ?
On mine it is perfect.

**Comment by Patriboom** [comment]
No one answered.
Conclusion = it's now ok.
Consequence: close this issue.
