### ISSUE TITLE
Uploads work but don't get attached

### ISSUE THREAD

**Issue by bcostea** [pixeline/bugs#219]
Uploads act strange, like when I want to attach an image to an issue it gets uploaded but not posted and then it gets attached to the next issue I create. 
Is there currently any plan for this? I'd help if i knew what's the direction you'd like to take, not to spend double effort.

**Comment by Patriboom** [comment]
Issue 202 is about that also.
It's my next homework ..
https://github.com/pixeline/bugs/issues/219
We need to fix it.
Last Bugs update is from yesterday.  Maybe,  you can check your version.  From there, we'll work together.

**Comment by Patriboom** [comment]
Next comment in https://github.com/pixeline/bugs/issues/219

**Comment by Patriboom** [comment]
As topic 202 brings the whole information, the present topic will be closed within few days.
