### ISSUE TITLE
Some hints on how to upgrade an existing installation

### ISSUE THREAD

**Issue by TheLink** [pixeline/bugs#22]
Since I'm not really good at php, I'd like to ask you to add a few lines of information to the github readme on how to upgrade an existing installation of bugs. Thanks for providing this great piece of software!

**Comment by pixeline** [comment]
For this 1.5 upgrade:
- backup config.app.php and your uploads folder.
- simply replace the codebase with the new version (via an ftp client such as Filezilla).
- make sure your uploads folder and config.app.php are still there
- pour yourself a glass of a good single malt whisky.
You're done!

(last step is optional, but highly recommended.)

**Comment by TheLink** [comment]
Additionally I had to do some changes to make it work after the update:

Add following line in the .htaccess:
RewriteBase /

If you want to use the date formatter in config.app.php:
	'my_bugs_app'=>array(
		'name'=> 'Bugs',
		'date_format'=>'F jS \a\t g:i A',
	),

**Comment by pixeline** [comment]
Ah, true, I forgot about the config update. thanks!

**Comment by Patriboom** [comment]
To use new features:
    - percentage of work done
    - max duration for an issue

You'll need to update your BUGS

Again, same procedure as up there. That means:
backup config.app.php and your uploads folder.
simply replace the codebase with the new version (via an ftp client such as Filezilla).
make sure your uploads folder and config.app.php are still there
Add this line to your config.app.php
```
'my_bugs_app'=>array(
'name'=> 'Bugs',
'date_format'=>'F jS \a\t g:i A',
),
```
- Add following line in the .htaccess:
`RewriteBase /
`

Additionnaly, you'll need to update your database.
- Open your phpMyAdmin (or equivalent)
- Give phpMyAdmin to read the file  /install/update_v1-5_6.sql
