### ISSUE TITLE
Sort of issues

### ISSUE THREAD

**Issue by marcelloinfoweb** [pixeline/bugs#220]
When I'm in any project and I click on the open issues tab and then select in the select an order and click the button to search, the result brings the issues open and closed.

**My suggestion is**: Add an order by Issues ID (it does not already have) and ONLY fetch those from the selected, open or closed tab.

**Comment by Patriboom** [comment]
Hello Marccello 
thanks for your idea.
For now, I succeeded in sorting by id on my development server.

I'll try to take the closed issues out of the opened ones list.

**Comment by Patriboom** [comment]
Ok, it works.

**Comment by marcelloinfoweb** [comment]
I will test as soon as I return to work on 05/23.

In advance, thank you!
