### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nabiljerbi** [pixeline/bugs#222]
When i try to install it , i have this : https://imgur.com/a/rPSozOL

I try localhost/index.php
thx

**Comment by Patriboom** [comment]
I looks like your PHP is not activated.

**Comment by Patriboom** [comment]
Tu peux installer EasyPHP http://www.easyphp.org/download.php 
ou Xampp https://www.apachefriends.org/fr/index.html
ou un autre outil du genre.
