### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#223]
Hi Pato, long time..hope everyone is good here..how can we make bugs become responsive like when using  on mobile phone its not that responsive like when using the system on  a computer

**Comment by Patriboom** [comment]
I have no idea.
¿ Any suggestion?
I don't have phone, so ... if can describe better what you're looking for ... we'll see.

**Comment by Patriboom** [comment]
That's will be next project ...
for version 1.6 release 2

**Comment by Patriboom** [comment]
That is a big work, big project.
Help will be be more than welcome.

**Comment by Patriboom** [comment]
The responsive version of BUGS is on its way.

May I ask for testers, please.

As tester:  note very well where you did click before to reach an unpleasant display + attach a screenshot of the so called unpleasant display.

The responsive version is available under the **Responsive** branch

**Comment by Patriboom** [comment]
Released last week and now distributed as is by Softaculous.
If you find any bug, please open a new ticket..
