### ISSUE TITLE
Times Out

### ISSUE THREAD

**Issue by ciwguru** [pixeline/bugs#224]
I am getting all types of time out issues, some periods run 30 minutes after signing in and others, the system is open for 1 day before timing out. Is there a place where this is set to make sure it is timing out the same. It is frustrating to be working on an issue and it requires the login only to have all of the typed response gone and have to start over. I realize there is no way to save the information that is only typed in but not saved but it is really annoying to keep having to login after working on it for a short time while other days, I was able to work on it all day and not be required to login. Any suggestions on what file controls the time alloted for timing out would be helpful and maybe I can increase the value.

**Comment by ciwguru** [comment]
I was using the program in chrome browser.

**Comment by Patriboom** [comment]
Is there anyone around who has the same trouble ? 
Mine is open 24 / 7 and never asks for login.
ciwguru : does your browser accept cookies ? 
May you try turn on the cookies for you « Bugs » website ?

**Comment by Patriboom** [comment]
Three months later: no news.
Does it mean it's now OK ?

**Comment by Patriboom** [comment]
I think I found the problem:  email sending.
This has been updated today.
May you check again.

**Comment by Patriboom** [comment]
Please follow the topic (https://github.com/pixeline/bugs/issues/226) it is supposed to be fixed by an hard work on reassigning ticket and sending mail
Make sure you review the config.app.php which has many changes.
