### ISSUE TITLE
Reassign

### ISSUE THREAD

**Issue by wycky** [pixeline/bugs#226]
After the last update you did, reassignement of an issue executes successifully but there is this error on dispaly what happened. check attached. where is the problem?
![capture](https://user-images.githubusercontent.com/25264938/46080206-f8087780-c1a1-11e8-8be8-9be325e667b1.PNG)

**Comment by Patriboom** [comment]
This likes a debuging code left behind.
I'll check and come back.

**Comment by Patriboom** [comment]
I did some corrections.
Please give me the entire path you'd followed to have some message if it's not correct.
What I mean:
- I've listed all projects
- Then click on one of them
- then click on one issue
- then click on the pencil (issue's modification) ...
- then  this
-then that 
- ....
- ...

**Comment by wycky** [comment]
No its not, still figuring out which line of code generates that exception.

**Comment by Patriboom** [comment]
I found a first bug: on reassign -> system tries to send mail, but finds no tool to do so.

**Comment by Patriboom** [comment]
Tested locally : it's now good.

Bellow, the comment I let on the last commit

> Back to a centralized function for mailing.
This time, it works good with 'mail' as value in your config.app.php
I set this value as default. No time - for now - to work on stmp, pop3 or google methods.

Anyways, mail value permits to send both plain text and html
Please refer to file config.app.example.php also uptaded here for default values

**Comment by Patriboom** [comment]
Please test it.
Let me know.

**Comment by wycky** [comment]
Hi Patrick, tested the update. it does not send the mail and unless you refresh the link you cannot see the reassignment tag on the page

**Comment by Patriboom** [comment]
Do you think it could be better to offer the capability of « not sending email » ? 
Let me know more about your config ( config.app.php file but also about your PHP system ... EasyPHP, Windows, Linux, mac ... ) 

Thanks.

**Comment by Patriboom** [comment]
Please check the latest version.
I hope it works good.  It does for me.

**Comment by wycky** [comment]
Hi Patrick,

should be closing this. everything is working good
