### ISSUE TITLE
Firefox, Reassign ticket open new page blank

### ISSUE THREAD

**Issue by sragneau** [pixeline/bugs#239]
Dear support,

When we try to reassign a ticket,the navigator opens a new blank page.
This issue doesn't appear with Chrome. 

In the html code when we delete "taget: _blank" code the functionality works well. This part of code seems to be added by the navigator itself. So we haven't found a way to change it.
Do you have any idea to solve it ?

Thanks for your helping.

Best Regards

**Comment by Patriboom** [comment]
Hello 
may you try this : 

`					<?php if(Project\Issue::current()->assigned): ?>
						
						<span id="span_currentlyAssigned_name">
						<?php echo Project\Issue::current()->assigned->firstname; ?>
						<?php echo Project\Issue::current()->assigned->lastname; ?>
						</span>
						
					<?php else: ?>

 							<span id="span_currentlyAssigned_name">
							<?php echo __('tinyissue.no_one'); ?>
							</span>
						
					<?php endif; ?>
`

From line 101 to 112 of
app/applications/views/project/issue/index.php 

?

You'll loose the dropdown-list 's arrow but we'll figure out later how to place it back.

**Comment by Patriboom** [comment]
Hope the new update will fullfill your expectations.
Please update the app/applications/views/project/issue/index.php  file

**Comment by sragneau** [comment]
Hi
We updated the file, but we still get the problem.
You can see with the gif where we found the target:_blank value.

![peek 28-12-2018 10-04](https://user-images.githubusercontent.com/17569666/50510027-5a666200-0a88-11e9-9798-656f7b4c028d.gif)

Merci pour l'aide.

**Comment by Patriboom** [comment]
Autre piste:

le fichier app/assets/js/project.js
contient déjà des instructions qui élíminent ces ajouts, mais dans le cas de javascript: (avec un espace).  Il n'y a pas d'espace forcé dans la commande de lien.
Peux-tu procéder à un test ? 

Le test est le suivant:  modifier le-dit fichier dans ses premières lignes.
Il faudrait que celles-ci se lisent comme suit:

```
$(function() {

	/* Make external links target to _blank */

	var links = document.links;
	$(document.links).filter(function() {
		var Ceci = this.href;
    	if (Ceci.substr(0, 14) == 'javascript:%20' || Ceci.substr(0, 11) == 'javascript:') { return false; }
    	return this.hostname != window.location.hostname;
	}).attr('target', '_blank');
```

Si ça ne fonctionne pas, nous pourrons y aller d'une solution de traitement de tous les liens externes comme le suggère  https://exceptionshub.com/add-relnofollow-and-target_blank-for-external-links-permanently.html

**Comment by Patriboom** [comment]
J'ai apporté la modification de manière permanente.
Tu peux donc simplement télécharger la mise à jour et m'en donner tes commentaires.
Si tout fonctionne bien, veuille fermer le billet.

**Comment by sragneau** [comment]
Bonjour Patriboom,
On vient d'appliquer ta correction et c'est ok pour nous.
Merci et bonne année.
