### ISSUE TITLE
Configurable notifications

### ISSUE THREAD

**Issue by beingalink** [pixeline/bugs#24]
It would be nice if not only the person who the bug is assigned to would get notifications but also the bug reporter and/or people commenting on a bug.

**Comment by beingalink** [comment]
I modified `bugs-master/app/application/models/project/issue/comment.php` so that the creator of the issue also gets a notification if someone other than him/her added a comment:

In line 70 insert:
```
                /* Notify the person who created the issue, unless that person is the one making the comment */
                if($issue->created_by && $issue->created_by != \Auth::user()->id)
                {
                        $project = \Project::current();

                        //$subject = 'Issue "' . $issue->title . '" in "' . $project->name . '" project has a new comment';
                        $subject = sprintf(__('email.new_comment'),$issue->title,$project->name);
                        $text = \View::make('email.commented_issue', array(
                                'actor' => \Auth::user()->firstname . ' ' . \Auth::user()->lastname,
                                'project' => $project,
                                'issue' => $issue,
                                'comment' => $comment->comment
                        ));

                        \Mail::send_email($text, $issue->user->email, $subject);
                }
```
This is more or less copied and modified code from the codeblock directly above line 70. Since I know nothing about php and only very few about git, I don't offer this as a pull request. You can decide if this makes sense to you and possibly integrate it in a better way.

**Comment by pixeline** [comment]
Thank you, added.
