### ISSUE TITLE
The requested URL /en/*** was not found on this server.

### ISSUE THREAD

**Issue by v1k4** [pixeline/bugs#249]
Cloned the master and installation went fine.

Index.php loads as it should, but when trying to browse anywhere else it will end up in not finding the data.

e.g.

Not Found
The requested URL /en/administration was not found on this server.

**Comment by Patriboom** [comment]
Pretty strange this « /en/ »   !!!
I'll be back..
Thanks for this notice.

**Comment by Patriboom** [comment]
That's pretty strange. 
After the install process, the main page seams to not be called.  That's the main page who is supposed to call the proper redirection.  I guess, I you do nothing but close the app and re-open it, it will work fine.
Anyway.  I've created a .htaccess for the /en/ sub-directory which is called from the browser after the install completed.
Let me know more if you encounter other problems.

**Comment by v1k4** [comment]
Did a fresh cloneof the git master.
Links on the main page are still pointing to /en/ and Not found.
Administrator.php is found in /en/ but it just opens the main page.

Not sure maybe I'm missing something in my setup?
Running pretty much out-of-the-box apache2 and php7 on ubuntu server.

**Comment by Patriboom** [comment]
Thanks for that.

We must find where is the  « /en/ » from and take it out of the link building system.
I'll be back ...
If anyone has idea or - better - solution please do not hesitate.

**Comment by Patriboom** [comment]
Finally, I've found the a piece of the problem and hope that I did not create a new issue.
I've changed
this
  $root = rtrim($root, '/').'/'.$default;  (line 115)
by that
   $root = rtrim($root, '/');  (line 116)

in app/laravel/url.php

It works good on mine, on every link.
May you let know more about what you experience with it, please.

**Comment by Patriboom** [comment]
A month later, no-one commented ... in conclude : bug fixed.
