### ISSUE TITLE
Unhandled Exception for /drivers/eloquent.php on line 21 in firefox

### ISSUE THREAD

**Issue by ciwguru** [pixeline/bugs#255]
I am getting an NULL error on PHP 7.2 in Firefox...

LINE 21 is:

else if (get_class($token) == Config::get('auth.model'))

------------------------------------------------------------

This is the error I am getting in Firefox. Can you tell me what needs to be fixed.

Thanks

Unhandled Exception
Message:

get_class() expects parameter 1 to be object, null given

Location:

/home/esportsfraud/public_html/fraud/app/laravel/auth/drivers/eloquent.php on line 21

Stack Trace:

#0 /home/esportsfraud/public_html/fraud/app/laravel/laravel.php(42): Laravel\Error::native(2, 'get_class() exp...', '/home/esportsfr...', 21)
#1 [internal function]: Laravel\{closure}(2, 'get_class() exp...', '/home/esportsfr...', 21, Array)
#2 /home/esportsfraud/public_html/fraud/app/laravel/auth/drivers/eloquent.php(21): get_class(NULL)
#3 /home/esportsfraud/public_html/fraud/app/laravel/auth/drivers/driver.php(79): Laravel\Auth\Drivers\Eloquent->retrieve(NULL)
#4 /home/esportsfraud/public_html/fraud/app/laravel/auth/drivers/driver.php(65): Laravel\Auth\Drivers\Driver->user()
#5 /home/esportsfraud/public_html/fraud/app/laravel/auth/drivers/driver.php(55): Laravel\Auth\Drivers\Driver->check()
#6 [internal function]: Laravel\Auth\Drivers\Driver->guest()
#7 /home/esportsfraud/public_html/fraud/app/laravel/auth.php(90): call_user_func_array(Array, Array)
#8 /home/esportsfraud/public_html/fraud/app/application/routes.php(119): Laravel\Auth::__callStatic('guest', Array)
#9 [internal function]: Laravel\Bundle::{closure}()
#10 /home/esportsfraud/public_html/fraud/app/laravel/routing/filter.php(119): call_user_func_array(Object(Closure), Array)
#11 /home/esportsfraud/public_html/fraud/app/laravel/routing/controller.php(279): Laravel\Routing\Filter::run(Array, Array, true)
#12 /home/esportsfraud/public_html/fraud/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#13 /home/esportsfraud/public_html/fraud/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('home@index', Array)
#14 /home/esportsfraud/public_html/fraud/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#15 /home/esportsfraud/public_html/fraud/app/laravel/laravel.php(167): Laravel\Routing\Route->call()
#16 /home/esportsfraud/public_html/fraud/index.php(15): require('/home/esportsfr...')
#17 {main}

**Comment by Patriboom** [comment]
Is that a new installation?
When did it occur first time ?

**Comment by ciwguru** [comment]
No, I originally installed the version from softaculous which has not been updated since 2015 and then upgraded PHP to 7.2 on the server from 5.x.x and got a bunch of errors and then upgraded all of the newer Laravel files from github about 3 weeks ago and now I get this exception. I am having no issues with Safari and Chrome

**Comment by ciwguru** [comment]
So it worked fine until I upgraded the PHP and then the files from github.

**Comment by Patriboom** [comment]
Good!
I started to seach the bug without any chance!
Easy why: there was not a bug.

**Comment by Patriboom** [comment]
Yes, changing PHP version, you needed to update the « Bugs » program also.
May we close the issue  ?

**Comment by Patriboom** [comment]
I wonder how we can suggest new version to softaculous.
Any idea ?

**Comment by Patriboom** [comment]
Oups, 
I understood it was good now.
If it works good under Safari and Chrome but not under Firefox, we can suppose that Firefox has something wrong in its cache.  
I suggest you to do  Ctrl-F5 to force and update on page over the cache.
You can also clean the firefox's history ( cookies, cache, etc).

**Comment by ciwguru** [comment]
Got it. Thanks we can close it now. If you use the Softaculous install on the newer versions of PHP, bugs will through a bunch of exceptions so everyone using it has to update any of the laravel files that have been updated in the past two years to make it work now. Thanks.

**Comment by ciwguru** [comment]
Thanks
