### ISSUE TITLE
Https over nginx reverse proxy

### ISSUE THREAD

**Issue by beingalink** [pixeline/bugs#26]
I'm trying to run bugs behind a nginx reverse proxy which works fine for http but over https browsers block content because it get's requested via http. These are mostly assets and favicons. Is it possible to tell bugs/laravel in a config file to load everything over https? Thanks for your answer in advance.

**Comment by oliverpool** [comment]
Reading Laravel source code, it should be automatic: https://github.com/pixeline/bugs/blob/master/app/laravel/url.php#L108

The `$https` parameter is never defined in the app: the call to `Request::secure()` should return `true` for you. Is it the case ?
(you can quickly test by adding `dd(Request::secure());` somewhere nearby and watching the source produced)

**Comment by beingalink** [comment]
Yes, you're right. It works like that when I run bugs directly on the server. I only had this problem when I run bugs in a docker container and nginx as a reverse proxy in front of it. Other php based software like owncloud work fine in this scenario so maybe it has sth to do with bugs using an old version of laravel. Anyway, I simply let bugs run directly on the server now and everything is fine. Thanks for your answer though, I appreciate it. :)

**Comment by pixeline** [comment]
You  could also remove the protocol from the assets url
src="//url/path/file. Ico"

**Comment by oliverpool** [comment]
It's probably because the connexion between your server and docker is (internally) not secured.

Maybe if you specify the https url in [the config](https://github.com/pixeline/bugs/blob/master/app/application/config/application.php#L31) it might work!
