### ISSUE TITLE
latest downlods

### ISSUE THREAD

**Issue by GaneshKandu** [pixeline/bugs#27]
Hi , what is download link of latest bugs
v1.3.1 i found on [https://github.com/pixeline/bugs](https://github.com/pixeline/bugs)
and found v1.5 from app\application\config\tinyissue.php file
i am confuse about version

what is link where i can find exact latest version and releases date

**Comment by Canopee** [comment]
Bonjour,

actuellement en congés, je prendrai connaissance de votre message à mon retour le lundi 4 janvier 2016.

Je vous souhaite de bonnes fêtes de fin d'année.

Cordialement,

Alexis Esteves

**Comment by GaneshKandu** [comment]
Joyeux Noël et bonne année

**Comment by pixeline** [comment]
latest is 1.5 You'll get automatically the latest version if you use the "download" button on http://pixeline.github.io/bugs/ or the "download zip" on the github repository homepage.

**Comment by GaneshKandu** [comment]
Merci
