### ISSUE TITLE
homepage returns 404

### ISSUE THREAD

**Issue by slavkoja** [pixeline/bugs#272]
Linked homepage http://pixeline.github.io/bugs/ redirects to http://pixeline.tk/bugs/ with result in 404 code

**Comment by Patriboom** [comment]
You're right.
I have no control on this.  I'll ask the owner to change the address for
http://bugs.rcmission.net/
which is on my server.

**Comment by Patriboom** [comment]
I asked to pixeline 7 days ago, but still no answer came back.
