### ISSUE TITLE
Right now bugs will not run on a PHP7 installation

### ISSUE THREAD

**Issue by jschuck** [pixeline/bugs#28]
Just a heads up.

I tried to use bugs on a PHP 7 installation and was greeted with a "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /srv/http/bugs/install/install.php:16PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /srv/http/bugs/install/install.php:16" in the error log.

A check on php.net told me what i feared. the mysql_connect function was marked deprecated in 5.5 and removed in 7.0.

Until you make bugs 7.0 ready you might want to explicitly state that in its requirements.

Edit: I need to clarify this, it seems that it's only the connection check in the install/install.php that needs updating to something like mysqli that fixed the installation for me. Since i'm not a php programmer i used this tool: https://github.com/philip/MySQLConverterTool which did the trick for me.

Everything else workes fine after the installation went through.

**Comment by pixeline** [comment]
Thanks, install.php patched.
