### ISSUE TITLE
Bugs - Xampp Install

### ISSUE THREAD

**Issue by Leehman** [pixeline/bugs#29]
[snap 2016-04-03 at 14 57 46](https://cloud.githubusercontent.com/assets/4561068/14234262/9e3d0e2e-f9ac-11e5-80eb-d6755db706b1.png)
I tried installing this to Xampp server on Mac and got this error: 

Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Can you help with this or where do I look to resolve this.

**Comment by Patriboom** [comment]
Did you check directory's permissions before to try install it?
Bugs needs to have all server's permissions  ( it works as www-data ) .
