### ISSUE TITLE
Warning: ob_start(): function 'mb_output_handler'

### ISSUE THREAD

**Issue by austinvernsonger** [pixeline/bugs#30]
Please see the following screenshot.

![](https://i.imgur.com/qD1Q5rH.png)

**Warning**: ob_start(): function 'mb_output_handler' not found or invalid function name in /home/username/public_html/develop/app/laravel/core.php on line 32
## Unhandled Exception

**Message**:

`ob_start(): failed to create buffer`

**Location**:

`/home/username/public_html/develop/app/laravel/core.php on line 32`

**Comment by Patriboom** [comment]
@austinvernsonger , did this issue happend again ? 
If yes, please give us more details about circumstances.

**Comment by Patriboom** [comment]
I got this error when I re-installed my apache2 server.
That is all about rights given to server on the sub-directories.
You must permit Bugs to read .htaccess and modify itself some rights on sub-directories.

**Comment by Patriboom** [comment]
Hello back austinvernonsonger, 
you may also test to set as remark the line 36 of app/laravel/core.php like this: 

`//ob_start('mb_output_handler');
`
