### ISSUE TITLE
Ability to delete issues if required

### ISSUE THREAD

**Issue by syedrosdi** [pixeline/bugs#31]
Ability to delete issues if required

**Comment by Patriboom** [comment]
Better you just close it.
In your project's history, you'll see that you had a tought about that previously and remain yourself why you did abort the project.  At least, that's my way to work with such tools.

**Comment by Hazaels** [comment]
I think it is better to leave the issue there as Patriboom said it will be used as a "memorial" to know what happened in the past.
Just leave as it is.
