### ISSUE TITLE
Problem with check git repository

### ISSUE THREAD

**Issue by jAKErCZ** [pixeline/bugs#314]
Hi, I install bugs system and go to setting and a message popped up
`We are unable to reach the git site for bugs.
Therefore, we can not compare your version with the last available version.
Please visit the git deposit.`

And xampp to no problem and linux has a problem.

Thx for help.

**Comment by Patriboom** [comment]
Thanks for your information.  I hope you're the only one who encountered that upto now.  I'll have a look on that during the coming week.

Do you use proxy ?   FireWall ?  Anything like that which could block the access from your BUGS to the internet ?

**Comment by jAKErCZ** [comment]
> Thanks for your information. I hope you're the only one who encountered that upto now. I'll have a look on that during the coming week.
> 
> Do you use proxy ? FireWall ? Anything like that which could block the access from your BUGS to the internet ?

No use proxy,FireWall. I say me xampp to windows no problem. I upload to linux and problem.

**Comment by Patriboom** [comment]
I did not understand this way.  Nice to received better information.

I'm very surprised because everything is built under Linux.  It should work better this way than under XAMPP.  Strange!
It will be easier to have a look, then ...
... I'll try to turn mine into dysfunctionnal state to find out the solution.

**Comment by Patriboom** [comment]
The message you quoted is generated when BUGS is used offline.
Are you sure your connection to internet was ON ? 

From here, it does not seam to be a bug, nor from BUGS system, but from your browser connection check.
