### ISSUE TITLE
Memory Exhausted

### ISSUE THREAD

**Issue by ciwguru** [pixeline/bugs#315]
I am getting a memory exhausted error after I upgraded from version 1.5 to 1.8. with the updated Bugs version and Laravel. Can you tell me what the problem might be and how I might go about fixing it without increasing the php.ini allowed memory size. This does not happen on 1.5 at all and the same information is contained in both databases.

Thanks,

Sean

Unhandled Exception
Message:
Allowed memory size of 33554432 bytes exhausted (tried to allocate 1646592 bytes)
Location:
/home/public_html/standards2/app/laravel/view.php on line 387

**Comment by Patriboom** [comment]
You may have touched the key of your problem:  "The same information in both databases".
From 1.5 to 1.8, many changes occured in the database.  Did you upgrade database also ? 

You may obtain better results passing through all middle major versions.

**Comment by ciwguru** [comment]
I actually installed a new version instead of upgrading. But imported the MySQL tables into 1.8 by using the 1.8 dumps as a guide to make sure they were identical except for my data. Sorry I was not clear on it. Everything is working fine except when I click the issues link at the top of the window for my issues and then it runs that error. Also I have a ton of issues. 

I accounted for the minor differences in the MySQL dumps between 1.5 to 1.8 But cannot find what might be causing the errors.

So should I upgrade 1.5 to 1.x to 1.8 or try figure out if the database is incorrect somewhere. I did upgrade the information on the database.

From what you are saying is that I should upgrade each version first

Thanks

Sean Thompson, CISM, CISSP
208-559-7135

**Comment by Patriboom** [comment]
Hello Sean, 
thanks for details.  The use of the table "users_activity" has changed a between versions 1.5 and 1.8 even if the structure is the same.

Anyway, I'll try to replicate your problem on my developpment environment.  Please correct my understanding: 
not-working : 
you click on "Issues" on top part of the windows -> it runs for every like in loop

working:
you click on any project's name ( left margin ) -> it shows list of issues attached to this project
you click on any issue's title ( center part ) -> it shows the actual issue and let you work on it.
you click on any other tab ( top windows) like "dashboard" or "My tasks" or "Projects" and it works good.
