### ISSUE TITLE
Bad time displaying between admin and a read user

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#324]
Hello,

For an admin when I open a ticket I have this screen.

![ok](https://user-images.githubusercontent.com/79452305/109796170-1ea32600-7c18-11eb-8b53-b25877f3d3c1.png)

And for a read user the ticket is displayed like this !

![bad](https://user-images.githubusercontent.com/79452305/109796332-501bf180-7c18-11eb-9b01-a7ed2ba31209.png)

Is it a normal ?

Regards

**Comment by Patriboom** [comment]
No, it's not normal.
I think the read user should have none of the progress bars.

**Comment by Albatros78** [comment]
OK
