### ISSUE TITLE
Sort by Tags does not works

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#325]
Hello,

the sort by Tag does not works

Here if I want to do a sort on one tag like below

![search](https://user-images.githubusercontent.com/79452305/109802007-890b9480-7c1f-11eb-87ee-c48d1b84b83e.png)

The result is :

![bad](https://user-images.githubusercontent.com/79452305/109802059-9aed3780-7c1f-11eb-94a4-920ad140f6ab.png)

Regards

**Comment by Patriboom** [comment]
Ok, I'll have an eye on this.
That may need some days, because my personnal computer just crashed.  I'll need first to rebuild the whole machine before to be able to work on projects like BUGS.  
Thanks for clear screenshot and details.

**Comment by Albatros78** [comment]
OK it works fine.

**Comment by Albatros78** [comment]
Hello Patrick.

J'ai parlé trop vite.

Cette option pour tout ne fonctionne pas dans la recherche

![bug](https://user-images.githubusercontent.com/79452305/110925725-d4125f80-8323-11eb-88ff-bec6072c5fd4.png)

**Comment by Patriboom** [comment]
Ce ne sera pas corrigé.  Quelqu'un qui chercherait tous les billets en imposant un filtre de type "tous les billets" devrait plutôt ne pas utiliser de filtre.  Je vais néanmoins voir s'il m'est possible de supprimer ce billet "étoilé" de la liste.

**Comment by Patriboom** [comment]
Firnalement, j'ai apporté deux corrections qui visent à éliminer les étiquettes se terminant par « :*»
