### ISSUE TITLE
Remove comment does not works

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#326]
Hello,

Into admin mode if I try to remove a comment by clicking on the red cross, the message "comment deleted"  is OK, but the comment is always displayed.
No solution to remove it from the GUI

Same issue on 2 tickets !

Regards

**Comment by Patriboom** [comment]
May I see a screenshot, please ?

**Comment by Albatros78** [comment]
OK 
here the 3 pictures in the order...

- Displaying the comment

![1](https://user-images.githubusercontent.com/79452305/110307833-a8c80180-7fff-11eb-8a8c-f2444d4e534d.png)


- Remove it

![2](https://user-images.githubusercontent.com/79452305/110307858-b3829680-7fff-11eb-99ab-0486b01187d0.png)



- Displaying is always on


![3](https://user-images.githubusercontent.com/79452305/110307869-b8474a80-7fff-11eb-8707-2d3b554ac95c.png)

**Comment by Patriboom** [comment]
Is the user has write to delete ?  What is this user's level ? 
If not, we'll need to remove the red X

**Comment by Patriboom** [comment]
Remove comment is now back usable.

Merci de votre perspicacité, Albatros, et de votre aide.

J'en ai profité pour contrôler d'autres accès plus ou moins douteux accordés aux usagers de niveau 1 ( lecteurs ) comme "rouvrir un billet".

**Comment by Albatros78** [comment]
Hello Patrick,
J'ai téléchargé le package zip et copié tout le contenu sur mon installation n-1.

Voila ce que j'obtiens.... !!!!!!

![bug](https://user-images.githubusercontent.com/79452305/110773398-0016dd80-825d-11eb-8337-e0d4d07c8e3a.png)

**Comment by Patriboom** [comment]
Je n'arrive pas à reproduire l'erreur.

Quand cela se produit-il ? 
Quelles seraient les étapes à suivre pour que j'obtienne cette erreur, cet affichage ? 

Merci.

**Comment by Albatros78** [comment]
Directement en essaynt l'URL pour accéder à la page d'accueil !!!!
Même pas de page login ..... directement l'erreur

**Comment by Albatros78** [comment]
Pas d'erreur avec une base vide !!!!! et cela fonctionne 

Veux tu ma base avec les enregistrements pour comprendre ?

**Comment by Patriboom** [comment]
Merci Albatros, tel qu'annoncé au billet  https://github.com/pixeline/bugs/issues/337  les corrections apportées aujourd'hui devraient régler à la fois le présent billet et l'autre.

Ça m'a donné l'idée d'ajouter un bouton  "Publier le commenter et fermer".  Mais ça ira plus tard.

**Comment by Albatros78** [comment]
Hello Patrick.
Avec le dernier code j'ai toujours cette erreur 'Unhandled Exception' indiquée ci dessus avec ma base déjà renseignée.

Avec une base vide j'arrive à me connecter... 
Mais en créant un nouveau ticket j'ai cette erreur.... 
Erreur dans l'envoi de l'email qui n'arrive pas, mais le ticket est ouvert


Unhandled Exception
Message:
mail(): Bad Message Return Path
Location:
E:\xampp\htdocs\bugtracker2\app\application\controllers\project\issue.php on line 66
Stack Trace:


Lorsque je veux affecter un utilisateur au projet par cet écran.

![bug](https://user-images.githubusercontent.com/79452305/110922950-a24bc980-8320-11eb-9e49-04ab84a55210.png)

En cliquant dans le champ cela part directement sur la création d'un nouveau ticket !

**Comment by Patriboom** [comment]
Puis-je vous demander de vérifier le champ  "status" dans la table  "projects_issues".
Aucune ligne ne devrait avoir un champ "status" vide, aucun champ "status" ne devrait être plus grand que 5.

**Comment by Albatros78** [comment]
Le champ status dans ma base existante est à 0,3, 4

**Comment by Albatros78** [comment]
Ma base existante ici:

[afs_bugtracker_2021-03-09-14-28-00.zip](https://github.com/pixeline/bugs/files/6130120/afs_bugtracker_2021-03-09-14-28-00.zip)

**Comment by Patriboom** [comment]
Merci de votre patience.
J'ai fait le tour et j'ai réparé

- le propblème d'affichage ci-haut représenté

J'ai confirmé le bon fonctionnement de:

- changement d'attribution de billet 
- recherche par étiquette   ----->   attention ici, il faut inscrire un beau de mot, puis choisir parmi les options offertes.

J'ai aussi fait disparaître la liste de participants à un projet des yeux d'un "lecteur seul".

Aucune erreur dans votre base.

**Comment by Albatros78** [comment]
Super... tout fonctionne bien mieux sauf l'envoi d'email à la création d'un ticket dans le nouveau post que j'ai crée.

Mais là cela est vraiment bien.

Merci

**Comment by Albatros78** [comment]
Oups.
Lorsque je veux ajouter un utilisateur au projet, cela ouvre la fenêtre nouveau ticket (comme indiqué ci dessus )

**Comment by Patriboom** [comment]
Donc aucune amélioration ici.  J'y vois.

**Comment by Patriboom** [comment]
Nous ferons un nouveau billet à ce sujet.  Ce sera moins mêlant, car le titre ne parle pas de cela du tout.
