### ISSUE TITLE
Possibility to read any ticket from any project for a simple read user !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#328]
Hello,

All projects are displayed like this into the browser with the project ID into the URL

http://localhost/bugs/project/1/issues?tag_id=1

If I am a simple read user, I can put this URL or this one into my browser,  and I have an access to the project, even if this one has not been affected to the user.

http://localhost/bugs/project/3

http://localhost/bugs/project/4

Like all project ID are sequential it's easy to understand... !!!
So I suggest to generate the project ID with a random number like

http://localhost/bugs/project/51654841
http://localhost/bugs/project/44786

Hope this helps

**Comment by Patriboom** [comment]
Non, nous établirons plutôt une sécurité aux projets / billets afin que seuls le participants autorisés accèdent à ce qu'ils sont autorisés à voir.

**Comment by Patriboom** [comment]
Ok, little thing have been done about this.
Pretty efficient.

Albatros, si tu veux bien tester.  Merci.

**Comment by Albatros78** [comment]
Branches ?. Non je ne comprends pas.
Ok pour tester, ou puis je télécharger le nouveau code ?

**Comment by Albatros78** [comment]
J'ai crée un nouveau projet/ticket avec ma base actuelle... et affecté ce nouveau projet à un nouvel utilisateur en lecture simple.

Ce nouvel utilisateur peut bien sûr accéder au projet associé, mais **lire les autre projets** comme indiqué dans mon email d'origine, soit:

http://localhost/bugs/project/3
ou
http://localhost/bugs/project/4

**Comment by Patriboom** [comment]
Merci Albatros.  D'autres changements ont été apportés ce soir.
De quel coin êtes-vous ? 
Je pourrais peut-être vous montrer comment utiliser les branches git ou ... si vous avez le goût, voici deux références 
https://www.hostinger.fr/tutoriels/tuto-git
https://www.pierre-giraud.com/git-github-apprendre-cours/

**Comment by Albatros78** [comment]
Hello Patrick,

Ha oui, c'est la gestion des versions pour le dev !!! Ok

Je suis basé en France près de Aix-en Provence (Marseille) dans le sud est

Je viens de tester et impossible de lire un projet ou ticket si je ne suis pas affecté à ce projet.. ca marche !
Super .
Merci

**Comment by Patriboom** [comment]
Merci Albatros.
