### ISSUE TITLE
Raw error message when no user is associated with a new project

### ISSUE THREAD

**Issue by hydroid7** [pixeline/bugs#33]
I get a raw PHP error message when I try to create a project, but no user is selected.

```
Unhandled Exception
Message:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'default_assignee' at row 1

SQL: INSERT INTO `projects` (`name`, `default_assignee`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?)

Bindings: array (
  0 => 'Test',
  1 => '',
  2 => '2016-09-16 11:59:47',
  3 => '2016-09-16 11:59:47',
)

Location:

/opt/lampp/htdocs/bugs/app/laravel/database/connection.php on line 263

Stack Trace:
...
```

**Comment by Patriboom** [comment]
To avoid that, i determinate a « default user » assigned to any new ticket.
Sorry for that, I don't know how to do a "pull request" so it's available on https://github.com/Patriboom/bugs

**Comment by Patriboom** [comment]
If you don't want to update your code and database, just update your database using phpmyadmin.  
Open the bugs database.
Show the project_issues table
Update the « created_by » field giving it a default value = 1
MySQL line :  «  ALTER TABLE `projects_issues`
CHANGE `created_by` `created_by` bigint(20) NULL DEFAULT '1' AFTER `id`; »
