### ISSUE TITLE
Hex characters into subscription email received

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#331]
Hello

Lorsqu'un nouvel utilisateur reçoit l'email de création de compte, la fin du mail se termine par une chaîne de caractères inutiles au message !

You may log in with email info@demo.com and password x4dTXE.

**--7474be0f956f7a71b73d66c9d5e77dcan** 

Est-il possible de ne pas inclure cette chaîne de caractères dans l'email ?

**Comment by Patriboom** [comment]
Est-ce que tout le message était en anglais ? 
Ce devrait être traduit, comme le reste du site.

**Comment by Patriboom** [comment]
Correction apportée.
Je ne suis cependant pas en mesure de vérifié ni même de tester.
Ce charabia est ce qui est appelé "boundary" dans le langage d'un message destiné à être lu au format HTML.

**Comment by Albatros78** [comment]
La chaîne de caractère est toujours présente à la fin du mail de confirmation de création du compte

You may log in with email test2@afsoftware.fr and password NaOBvN.

--affdd49750746ad4330ce5653ff85d7en
