### ISSUE TITLE
New issue: Impossible to add a New Issue into admin mode

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#337]
Hello Patrick,

Avec le package du 10-03 je ne peux plus ajouter de nouveaux tickets.

![new](https://user-images.githubusercontent.com/79452305/110774878-90095700-825e-11eb-9a14-33513adf41b1.png)

En cliquant sur le bouton j'ai l'erreur suivante:

Unhandled Exception
Message:
syntax error, unexpected end of file
Location:
E:\xampp\htdocs\bugtracker2\app\laravel\view.php(353) : eval()'d code on line 236
Stack Trace:
#0 E:\xampp\htdocs\bugtracker2\app\laravel\view.php(324): Laravel\View->get()
#1 E:\xampp\htdocs\bugtracker2\app\laravel\view.php(406): Laravel\View->render()
#2 E:\xampp\htdocs\bugtracker2\app\laravel\view.php(341): Laravel\View->data()
#3 E:\xampp\htdocs\bugtracker2\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker2\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker2\app\laravel\response.php(240): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker2\app\laravel\laravel.php(173): Laravel\Response->render()
#7 E:\xampp\htdocs\bugtracker2\index.php(19): require('E:\\xampp\\htdocs...')
#8 {main}

**Comment by Patriboom** [comment]
Réparé.

**Comment by Albatros78** [comment]
Téléchargé et installé.
Même erreur que le ticket #326

**Comment by Albatros78** [comment]
Avec une base vide cela fonctionne comme pour le ticket #326 !

**Comment by Patriboom** [comment]
Merci encore Albatros.

J'ai apporté plusieurs corrections qui devraient régler les problèmes d'ajout (https://github.com/pixeline/bugs/issues/337 )  et de retrait de commentaire 
( https://github.com/pixeline/bugs/issues/326 ) .

**Comment by Patriboom** [comment]
Will keep only one ticket for both troubles.  They are linked in code.
