### ISSUE TITLE
To hide the 'Assigned Users' menu for a simple user

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#341]
Hello Patrick,

Une dernière chose semble t'il.
Il faudrait cacher ce menu pour un simple utilisateur en mode lecture. Il n'a pas besoin d'avoir la liste des utilisateurs qui sont sur le ticket . non ?

![bug](https://user-images.githubusercontent.com/79452305/110924748-b42e6c00-8322-11eb-867f-dacd57230a39.png)

Merci

**Comment by Patriboom** [comment]
À chaque fois que l'usager «lecteur» affichera un billet, il verra bien les participants du projet.  Alors ... ôter ces mêmes noms d'entrée n'est pas essentiel.
Laissez-moi du temps de réflexion à ce sujet.

**Comment by Albatros78** [comment]
Je pense que oui.

Si l'utilisateur en mode lecteur simple est un client ou partenaire par exemple, il n'est pas nécessaire de voir les autres noms de clients qui peuvent aussi avoir un accès de leur côté !

**Comment by Patriboom** [comment]
Fait, tel que demandé.
