### ISSUE TITLE
Email not sent during new issue adding

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#343]
Hello Patrick.

Encore cette erreur lorsque l'administrateur ajoute un nouveau ticket

Unhandled Exception
Message:
mail(): Bad Message Return Path
Location:
E:\xampp\htdocs\bugtracker2\app\application\controllers\project\issue.php on line 68

Le mail n'est pas envoyé. Le ticket est crée.
L'envoi des emails fonctionne dans mon environnement et cela fonctionne aussi avec la version 1.8.3f

**Comment by Patriboom** [comment]
J'ai apporté une correction dont je ne suis vraiment pas sûr.
J'attends votre retour d'expérience.

**Comment by Albatros78** [comment]
Sorry, cela génére la même erreur... :-(

**Comment by Albatros78** [comment]
Pour aider :

J'ai copié le fichier app/application/controllers/project/issue.php de la version 1.3.8f dans mon répertoire de test et le mail est bien envoyé à la création d'un ticket.
C'est donc bien dans le fichier issue.php actuel qu'il y a un problème.

**Comment by Patriboom** [comment]
Ce semble être la nouvelle distinction qui bloque:  si le billet a été fermé en même temps que le commentaire fut soumis, le message courriel est adpaté.
En attendant de fignoler cela, je remets ici la commande fonctionnelle.

**Comment by Albatros78** [comment]
Grrrrrr....

encore la même erreur...  :-(


Unhandled Exception
Message:
mail(): Bad Message Return Path
Location:
E:\xampp\htdocs\bugtracker2\app\application\controllers\project\issue.php on line 67

**Comment by Patriboom** [comment]
Merci de votre patience, Albatros.
Vous pouvez voir que le changement apporté à la page est dans les toutes premières lignes du code.  Je ne vois pas en quoi ça change l'envoi de courriel.  Mais, enfin, si c'est ce que ça prend.
L'envoi de courriel n'est pas activé sur mon environnement de test  ( j'y verrai ... !!!), c'est pourquoi j'ai de la difficulté ici.

Qu'en est-il des autres billets que vous avez ouverts ?
J'aimerais que vous les fermiez, s'ils sont résolus.

**Comment by Patriboom** [comment]
Je remis mon expédition de courriels sur les rails.
Lors de la création d'un nouveau billet, je reçois bien le courriel attendu.
Donc testé et fonctionnel de mon côté.

**Comment by Albatros78** [comment]
J'ai modifié le fichier en mettant:

mail($WhoAddr, $subject,$text,**$header**);

et le mail est envoyé !

Un problème de configuration de mon php.ini ?
Ne serait il pas judicieux de configurer une variable $header dans le fichier d'origine ?

Merci pour l'aide.
