### ISSUE TITLE
Add text contrast in the timeline bar

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#345]
Hello,

Il faudrait mettre le texte en noir lorsque la barre devient jaune.
Là on ne voit pas la valeur !

![1](https://user-images.githubusercontent.com/79452305/111029605-dd6ffa80-83fd-11eb-9cb1-c2d0dc9e023b.png)

**Comment by Albatros78** [comment]
Et pourquoi la barre devient jaune ?
quel critère ?

**Comment by Patriboom** [comment]
La correction est faite en environnement de développement.
Lors du prochain pull_request - merge, vous verrez.

Vert, jaune, rouge : les couleurs habituelles pour dire  "Tout va bien", "oups, le délai approche", "le délai est dépassé"
Les pourcentages de références sont modifiables dans le fichier config-app.php où vous trouverez la section suivante: 
`	/**  Percentage
	 *Percentage of issue done
	 *Make sure your array count 5 items, the fifth must be 100
	 *In order:  (done, open, inProgress, Testing, SysNeed)
	 *Default: (100,0,10,80,100)
	*/
	'Percent' => array (100,0,10,80,100),
`

**Comment by Albatros78** [comment]
Merci pour l'explication. 
Je n'avais pas vu !

**Comment by Patriboom** [comment]
Le correctif est apporté.

**Comment by Patriboom** [comment]
![image](https://user-images.githubusercontent.com/19801202/111069885-90dffa00-84a5-11eb-8947-09d5d98c994b.png)

**Comment by Albatros78** [comment]
Super. Cela fonctionne

Merci

**Comment by Albatros78** [comment]
Oups...
Pas complétement

sur ce ticket l'affichage n'est pas bon !!

![1](https://user-images.githubusercontent.com/79452305/111071599-352e6480-84d7-11eb-9b40-f4cff4c103fa.png)

**Comment by Albatros78** [comment]
Il faut réouvrir ce post... !!!

**Comment by Patriboom** [comment]
Corrigé.

**Comment by Albatros78** [comment]
Non. m^me problème  sur un post !

le visuel précédent affiche bien la jauge en jaune et le texte en blanc !!

Si OK pour toi, alors on ferme le ticket pour le moment et on verra par la suite.

**Comment by Patriboom** [comment]
Veuillez copier-coller l'adresse (URL) de la page faisant défaut.  
La partie intéressante est après le nom de domaine, 
Par exmple: 
http://127.0.0.1/blabla/Tickets/project/5/issue/453

la partie intéressante est:    Tickets/project/5/issue/453

**Comment by Albatros78** [comment]
Hello Patrick.
cela fonctionne... Peut être un problème entre le calcul des jours passés !

merci
