### ISSUE TITLE
Email received twice after comment added by a simple user

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#354]
Hello Patrick,

Lorsque qu'un simple utilisateur ajoute un commentaire à un ticket, l'administrateur reçoit 2 fois le même email !

![email](https://user-images.githubusercontent.com/79452305/111067110-d6f78680-84c2-11eb-843b-5864a276490f.png)

Merci

**Comment by Patriboom** [comment]
Est-ce qu'il n'y aurait pas un courriel à l'administrateur du projet et un autre émis au responsable du billet ?

**Comment by Albatros78** [comment]
Très bonne remarque... !!!
Ici l'administrateur et le responsable du ticket.

Merci
