### ISSUE TITLE
Todo list displays not all 

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#355]
Hello Patrick,

L'affichage de la Todo List n'est pas complet. 
Normal ?

![todo](https://user-images.githubusercontent.com/79452305/111067269-ce538000-84c3-11eb-8693-d7b4be6576bf.png)

**Comment by Patriboom** [comment]
Le panneau de droite affiche le nombre total de billets (20).
La liste "todo" affiche les billets affectés à l'utilisateur en cours (13).
Pouvons conclure que 7 billets sont attribués à quelqu'un d'autre.
Oui, c'est normal.

**Comment by Albatros78** [comment]
Non . ici l'utilisateur à 18 tickets sur un projet + 1 ticket sur les 2 autres projets
et la Todo List n'affiche que 13 

![bug](https://user-images.githubusercontent.com/79452305/111070687-1332e300-84d3-11eb-89c6-5e7ad39b8e15.png)

**Comment by Albatros78** [comment]
Je ne trouve pas comment ré-ouvrir le post !

**Comment by Albatros78** [comment]
Ok on ferme ce post  et on reviendra plus tard sur ce problème..
Je vais repartir sur une base neuve et on verra le comportement.

En tout cas Merci pour tout !
