### ISSUE TITLE
syntax error by clicking on Your issues menu

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#356]
Hello Patrick

En administrateur ou utilisateur en cliquant sur le menu **Your issues** j'ai cette erreur.

Unhandled Exception
Message:
syntax error, unexpected 'echo' (T_ECHO)
Location:
E:\xampp\htdocs\bugtracker2\app\laravel\view.php(353) : eval()'d code on line 5
Stack Trace:

**Comment by Patriboom** [comment]
Merci Albatros pour votre vigilence.

**Comment by Albatros78** [comment]
Super. Cela fonctionne à nouveau

Merci
