### ISSUE TITLE
No black bullet for a ticket closed !!

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#359]
Hello Patrick

here the displaying for a close ticket.

![1](https://user-images.githubusercontent.com/79452305/111071710-bdad0500-84d7-11eb-9f28-7bfff29bc218.png)

**Comment by Albatros78** [comment]
Ce ticket était déjà fermé depuis quelques temps... Je ne viens pas de le faire.

**Comment by Patriboom** [comment]
Je n'avais pas jugé pertinent de le faire paraître puisqu'ils seraient tous identiques, il ne serviraient d'aucune façon à distinguer les billets les uns des autres.

**Comment by Albatros78** [comment]
Oui mais dans la todo list il y a le point Noir.

![1](https://user-images.githubusercontent.com/79452305/111077269-48016300-84f0-11eb-9032-2c0fa0ed4d76.png)

Je pense que le remettre dans la liste est pertinent pour être homogène et voir visuellement que le ticket est fermé en voyant le point noir

**Comment by Patriboom** [comment]
C'est un choix d'édition.  Je le ferai.
La comparaison avec la Todo ne s'applique pas vraiment à mon argument, car dans la "todo", les billets fermés sont exposés aux billets ouverts.  Ils ont donc besoin de se distinguer.  Par contre, lorsque ne sont affichés que les billets fermés, ils n'est pas utile de distinguer leur leur état.
J'avais hésité à afficher ou non le point noir.  Vous me donnez la réponse.  Je le ferai afficher.

**Comment by Albatros78** [comment]
Merci !

**Comment by Patriboom** [comment]
Veuillez fermer vos billet lorsque satisfait.

**Comment by Albatros78** [comment]
Oui Ok cela fonctionne.
merci !
