### ISSUE TITLE
Ticket closed does nto displayed !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#360]
Hello Patrick

I have just close another ticket, but not displayed now !!!

![1](https://user-images.githubusercontent.com/79452305/111071804-1aa8bb00-84d8-11eb-936e-f46fd2925ef0.png)

**Comment by Patriboom** [comment]
Vous était-il attribué?

**Comment by Albatros78** [comment]
Très bonne remarque.!!! 
C'est OK
