### ISSUE TITLE
404 error after new installation

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#366]
Hello,

After a new installation to my provider (PHP 7.4) I got a 404 error when I try to go to the index page.

I have added the URL in the config.app.php file

return array(
	/**  URL
	 * You can define your URL or leave blank to let us figure it out
	 * 	- Sometimes in non-apache setups you need to define your url
	 */
	**'url' => 'https://www.mydomain.comr/afs_bugtracker',**

But The error persists
Any help should be welcome

**Comment by Patriboom** [comment]
I'm very sorry to read that.

Please give us some more informations to help us helping you.

1)  Did you copy the original code  from your development computer or from here ? 

2)  Did you pass through the install process  ?
a) did the website setup page work good  ?
b) did the database setup page work good ? 
c) did you define the master user password ? 
d) did any message show up during or after the install ? 
e) You may need to define a database with user and password on you provider server ahead of try to install BUGS

3) Please try with slash at the end of your address  https://www.mydomain.comr/afs_bugtracker/

4) checked your website config, especially the .htaccess file to make sure the index.php is the prime file red

5) you may need to create a index.htm file if your server is looking for such prime file.
a) if so: I'll push a sample index.htm file here in the project to make it easy for you and ... maybe others.

**Comment by Patriboom** [comment]
Je dois me rendre au travail.  J'y jetterai un oeil supplémentaire ce soir.

**Comment by Albatros78** [comment]
Hello Patrick,

1 - J'ai copié mon installation qui est en localhost chez le provider en changeant les paramètres de la base : 404
2 - J'ai supprimé les précédents fichiers et j'ai recopié tout le contenu du dernier fichier ZIP téléchargé sur Github. Je suis donc arriver sur la page d'installation. L'installation s'est déroulée sans problème et le fichier config.app.php est généré correctement. Ensuite : 404
3 - J'ai mis un slash à la fin de l'URL: 404
4 - Voici le contenu de mon fichier .htaccess... qui se trouve dans le répertoire d'installation.... Je suis nul sur ce sujet !

<IfModule mod_rewrite.c>
	RewriteEngine On

	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^(.*)$ index.php?/$1 [L,QSA]
</IfModule>


5 - J'a mis un fichier index.html ou index.htm : 404


Rien ne fonctionne !

Je peux te donner un accès en FTP si besoin mais via un email privé dans ce cas.

Merci

**Comment by Albatros78** [comment]
By a Chrome Inspect I have,

![image](https://user-images.githubusercontent.com/79452305/112668590-fc8b7500-8e5e-11eb-86cd-1726d84d845b.png)

the path iss trange no ?  . It should be https://www.afsoftware.fr/afs_bugtracker !

**Comment by Albatros78** [comment]
La racine de mon site web se présente comme ici via le FTP

![image](https://user-images.githubusercontent.com/79452305/112669312-db775400-8e5f-11eb-9e74-15426e6d4aae.png)

Mon site web et son contenu se trouvent  dans le répertoire afsoftware.fr qui représente mon site web.

en me connectant via FTPp, la racine est comme ci dessous

Mon site web afsoftware.fr est donc dans le répertoire et non pas à ce niveau racine (Et je ne peux pas changer cela: configuré par le provider)

![image](https://user-images.githubusercontent.com/79452305/112669650-42950880-8e60-11eb-9a7b-b59599315809.png)

C'est la redirection qui semble donc ne pas bien fonctionner, je pense.

**Comment by Patriboom** [comment]
Bonjour monsieur Axel, 

c'est décidément la référence à la racine de votre site qui fait défaut.  Je viens de télécharger le projet en ZIP ( comme vous ) et l'installer.  Tout s'est bien déroulé et l'accès est complet.

Veuillez vérifier votre fichier config aux lignes 37 et suivantes.
Elle devraient ressembler à ceci:  
`	'database' => array(
		'driver' => 'mysql',
		'host'  => 'localhost',
		'database' => 'NomDataBase',
		'username' => 'UsagerDataBase',
		'password' => 'MotpasseDataBase',
	),
`

C'est à la ligne 39 que je soupçonne pouvoir trouver dans votre fichier une référence au nom de serveur complet alors qu'il faudrait trouver l'expression  "localhost"


Ou encore, à la ligne  8 du même fichier

`	'url' => '',
`

Que vous devriez laisser vide ( comme citée ci-haut ).

**Comment by Albatros78** [comment]
Je crois que le problème vient du fichier .htaccces et le rewrite... Mais je n'y connais rien !

Mon fichier est bien configuré avec les paramètres de la base.
et la ligne 8 vide ou pas, rien ne change

**Comment by Patriboom** [comment]
Selon `https://gist.github.com/RaVbaker/2254618` votre .htaccess est bon.
Pour ma part, je n'ai rien de configuré spécifiquement dans le .htacess de ce site, mais ma configuration de serveur fait le travail.
Il vaut mieux garder cela ainsi.  Peut-être pourriez-vous simplifier la ligne du index.php comme on le montre dans le premier exemple du site cité.

Est-ce que votre sous-domaine aide.afsoftware.fr fonctionne bien ? 
Si oui, je vous suggère de copier ses configurations dans votre cPanel et de reproduire ces dernières dans afs_bugtracker

Ce que vous amenez ici ne relève pas de BUGS, mais de la configuration de votre site.
Ci-haut, je vous ai donné la façon de me joindre personnellement par courriel.

**Comment by Albatros78** [comment]
J'ai envoyé un message via le site cartefoi.net
Tous les sous domaines fonctionnent !

Dans ma configuration af_bugtracker n'est pas un sous domaine, mais un sous répertoire de www.afsoftware.fr

**Comment by Patriboom** [comment]
Je n'ai pas reçu votre message.  J'ai pourtant testé le système de courriel et il est fonctionnel.

**Comment by Patriboom** [comment]
J'ai momentanément déverrouillé mon courriel sur le présent site. Vous devriez être en mesure de me joindre par ici ( github ).

**Comment by Albatros78** [comment]
Je viens d'envoyer un message via ***@***.***

 

pas recu ?

 

 

De : Patriboom ***@***.*** 
Envoyé : samedi 27 mars 2021 14:53
À : pixeline/bugs
Cc : Albatros78; Author
Objet : Re: [pixeline/bugs] 404 error after new installation (#366)

 

J'ai momentanément déverrouillé mon courriel sur le présent site. Vous devriez être en mesure de me joindre par ici ( github ).

**Comment by Patriboom** [comment]
Problème de configuration du serveur.  C'est l'hébergeur qui doit corriger.

Hosting server problem.  Hostint provider will fix it.

**Comment by Albatros78** [comment]
Hello Patrick,

My provider has fixed issue.
It's works fine now !

Thanks for your help
