### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by julianatienza** [pixeline/bugs#37]
Hi All.

@Patriboom  I've sent you an email but i will attach my translations here too.

Thanks to everybody for efforts!!!

Spanish Translations:
[es.zip](https://github.com/pixeline/bugs/files/614647/es.zip)

**Comment by Patriboom** [comment]
It is also there:

https://github.com/Patriboom/bugs/tree/master/app/application/language

**Comment by Patriboom** [comment]
@Julianatienza   you'll have some little word to translate again into spanish.

**Comment by julianatienza** [comment]
No problems.where are the new resources?

**Comment by Patriboom** [comment]
As usual:  /app/application/language ...  file  tinyissue.php

**Comment by julianatienza** [comment]
Attached (i hope i wasn't missing something).

Thanks for your work!
[es.zip](https://github.com/pixeline/bugs/files/619969/es.zip)

**Comment by Patriboom** [comment]
Done

**Comment by julianatienza** [comment]
Hi Patriboom. I've achieved to configure eclipse IDE and i've seen errors in file (i had pasted one console command of ls near to a translation).

This is the updated one... excuse me so much

[es.zip](https://github.com/pixeline/bugs/files/621465/es.zip)

**Comment by Patriboom** [comment]
What was the error?  A  missing comma, I guess.

Watch it, @julianatienza :  your tinyissue.php file has 167, mine 169. There are two more lines at the very end.

**Comment by Patriboom** [comment]
I fixed the missing comma.
Thanks @julianatienza

**Comment by Patriboom** [comment]
Sorry @julianatienza   I red again my message (What the error ? ) ... and i feel now it was some rough.
I didn't expect nor wanted to write it rough, but only functionnal, only « PHP code » analytic.

**Comment by julianatienza** [comment]
Hi Patrick. I'm not sure about your question on functionnal or anaylitic... 

take a look at this term:

'todo_status_2' => 'En progreso',ls -l

the "ls -l" command was pasted by me wrongly... in last version i've deleted that part of the translation.

Thanks

**Comment by julianatienza** [comment]
Hi again.
Seeing the User administration page, there are untranslated terms. That's because this is inserted in database during install... no way to make possible a translation with current code. 

Anyway... is a minor issue. 

Thanks again for your work Patrick

**Comment by Patriboom** [comment]
In french all is in french (Adminstrator page   --     http://127.0.0.1/MesSites/Tickets/administration   )

@julianatienza , may you send a screen shot please?

**Comment by julianatienza** [comment]
Screenshot is attached. Everything is in spanish except summary about roles

Thanks
![screnshot lost in translation](https://cloud.githubusercontent.com/assets/15226700/20843938/c909331e-b8bd-11e6-8566-abd27dc33264.png)

**Comment by Patriboom** [comment]
Those words are in your database, table « roles »

¿ Do you think the project should have tools to change that ?

**Comment by Patriboom** [comment]
@julianatienza : i've modified the file es/tinyissue.php according to views/admin/index.php and views/projects/index.php needs.
Those two pages now use the same expressions for
0 active project
1 active project
more than 1 active projects.

Don't worry about that, it's done .... but make sure you'll use the modified one next time.
Changes occured around lines 24 and 32 of  es/tinyissue.php

**Comment by Patriboom** [comment]
I placed a new set of tinyissue.php files in /app/app/language
Each language has now its file sorted by alaphabetic order.
Hope it will make it easier to you when we'll come time to find changes, additions and differences.

**Comment by Patriboom** [comment]
@julianatienza for you :1234:  ... you'll be able to customize your roles and roles' descriptions.
Use the new "developer" edition.

**Comment by Patriboom** [comment]
Don't use the "Edit" button.  It doesn't.
I'll work on Error 404 translations an update the issue meanwhile.

**Comment by Patriboom** [comment]
It's done  even the « Error 404 » page may be translated.
We can do the « Error 500 » page also but ... who will see that ?   
I think it's enough for now.
