### ISSUE TITLE
Email address not configured like into config.app.php

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#370]
Hello Patrick

J'ai configuré cela dans mon fichier config.app.php pour l'envoi des emails via mon provider

	'mail' => array(
		'from' => array(
			'name' => 'AFS BugTracker',
			'email' => 'no_reply@afsoftware.fr',
		),

Et lorsque je reçois un email, l'émetteur est avec ce format

"[AFS BugTracker]"@mail20.lwspanel.com

En localhost cela fonctionne bien comme je veux et je reçois les emails avec ce format pour l'émetteur

[AFS BugTracker]  <no_reply@afsoftware.fr>

Merci de ton aide

**Comment by Albatros78** [comment]
Je dois voir avec le provider pour ce problème ?

**Comment by Patriboom** [comment]
Bonjour Albatros, 

Si l'émission du courriel est bonne - que vous recevez le courriel - ce n'est pas le problème du fournisseur.
Ce que je comprends: le courriel part du serveur et se rends à destination.  Cependant l'adresse affichée n'a pas le format standard. Ce risque d'être en programmation dans BUGS.  Ce qui est étonnant, ce qu'en dévloppement et en production le résultat soit différent.  Ça pointe vers le fournisseur.  Laissez-moi regarder un peu du côté de BUGS ce soir ou demain.  Je vous reviendrai avec plus d'informations et des tests réalisés.

J'aimerais que vous me confirmiez que le courriel est émis par BUGS et reçu ( donc que le serveur a bien fait son travail ) .

**Comment by Patriboom** [comment]
Pouvez-vous me donner la suite de la configuration mail de votre config.app.php
Certains détails m'intéressent, à savoir: 

- transport  :   mail ou smtp   ?
- plainHTML  : multipart/mixed ou text/plain ? 
- sendmail  : path  ?

**Comment by Albatros78** [comment]
Je confirme de bien recevoir l'email. Cela fonctionne bien via Mail

Oui c'est bien l'adresse email de l'émetteur qui n'est pas comme je le souhaite (lorsque cela est envoyé via le provider)


ma configuration est la suivante:

	/**  Mail
	 * Mail Settings
	 * - Put in the name and email you would like email from Tiny Issue to come from
	 * - This is usually only for setting up new accounts
	 *
	 * Default Mail Transport
	 *	|
	 *	| Possible Values
	 *	| 	mail (PHP Mail Function) --- default
	 *	| 	PHP (php language mail function)
	 *	| 	sendmail (Sendmail - almost the same as 'mail' option but with authentications details)
	 *	| 	gmail (using Google's gmail system)
	 *	| 	pop3 (Define Custom POP3)
	 *	| 	smtp (Define Custom SMTP)
	 *
	 */
	'mail' => array(
		'from' => array(
			'name' => 'AFS BugTracker',
			'email' => 'no_reply@afsoftware.fr',
		),
		/**
		 * Transport Settings
		 * Transport settings if using mail or smtp
		 * 'mail' or 'smtp' must be lower case
		 */
		'transport' => 'mail',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => '',
			'port' => 25,
			/*
			* Encryption support, SSL/TLS, used with gmail servers
			* Default: blank
			* 'ssl' or 'tls' must be lower case
			* Here example for gmail server
			*/
			'encryption' =>  '',
			'username' =>  '',
			'password' =>  ''
		),

		/* Characters encoding  
		* Possible values or endless, but most usual are 'UTF-8' (Europe) or 'iso-8859-1' (North-America)
		* Default value : 'UTF-8'  
		*/
		'encoding' => 'UTF-8',

**Comment by Patriboom** [comment]
Rien ne m'indique que ça vienne de BUGS.
Vous pouvez cependant essayer la configuration suviante, question de déjouer le robot de votre fournisseur: 
`
'mail' => array(
	'from' => array(
		'name' => '',
		'email' => '"AFS BugTracker" <no_reply@afsoftware.fr>',
	),
`

Attention, les guillemets  (") sont importants avant et après le nom d'usager.

**Comment by Albatros78** [comment]
Hello Patrick

Cela fonctionne mais en mettant de simples guillemets.

'[AFS BugTracker] <no_reply@afsoftware.fr>'

Merci pour l'aide
