### ISSUE TITLE
Dead instance

### ISSUE THREAD

**Issue by aolko** [pixeline/bugs#371]
Hosted instance linked in this repository is dead. Please provide a new link.

Also please fix the screenshot.

**Comment by Patriboom** [comment]
Hello aolko, 

please give more details.  I don't know what you're talking about. 
Where are those dead links ?  Those screenshots ?

**Comment by aolko** [comment]
> Hello aolko,
> 
> please give more details. I don't know what you're talking about.
> Where are those dead links ? Those screenshots ?

in the most obvious place - main page of the repositroy, that is `README.md` and url.

**Comment by Patriboom** [comment]
Ok, aolko.  Thanks for that.
About this link : 

![BUGS_lien](https://user-images.githubusercontent.com/19801202/113414196-69849a80-938a-11eb-9774-db16a2094c08.png)

I have no access to change it.
This is a project I became in charge of.  But, still, there some details I can not change.

About the others links, I could find only the screenshots URL as dead.  I'll work on that soon.

**Comment by Patriboom** [comment]
I inclueded screenshots into the readme file.
Easier for everyone.
