### ISSUE TITLE
Error during update via administration menu

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#376]
Hello Patrick

En essayant la mise à jour via le menu d'administration.
En cliquant sur Update 

Unhandled Exception

Message:
array_merge(): Expected parameter 2 to be an array, bool given

Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 28
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(2, 'array_merge(): ...', 'E:\\xampp\\htdocs...', 28)
#1 [internal function]: Laravel\{closure}(2, 'array_merge(): ...', 'E:\\xampp\\htdocs...', 28, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(28): array_merge(Array, true)
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#10 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#11 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#12 {main}

**Comment by Patriboom** [comment]
Aïe!

Tu utilises probablement BUGS en anglais.
Une mise à jour dans les prochaines minutes réglera ça.
C'est le fichier ./app/application/views/administration/update.php qu'il faudra remplacer par celui inclus dans la prochaine version.

OU

remplacer la ligne 26 du fichier mentionné ci-haut par ceci:  
`	if (file_exists("../app/application/language/".Auth::user()->language."/update.php") && != 'en') { 
`

**Comment by Albatros78** [comment]
Je viens de recommencer (en anglais) . Même erreur
Je suis passé en francais et l'erreur et la suivante

Unhandled Exception
Message:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'afs_bugtracker.update_history' doesn't exist

SQL: INSERT INTO `update_history` (`Description`, `DteRelease`, `DteInstall`) VALUES (?, ?, ?)

Bindings: array (
  0 => '1.83g',
  1 => '2021-03-02',
  2 => '2021-04-14 11:16:59',
)
Location:
E:\xampp\htdocs\bugtracker\app\laravel\database\connection.php on line 263

**Comment by Albatros78** [comment]
Pour info je n'ai pas ce fichier dans mon installation.

./app/application/views/administration/update.php

**Comment by Patriboom** [comment]
C'est plutôt  ./application/views/administration/update/index.php que j'aurais dû écrire.

**Comment by Patriboom** [comment]
Corrigé et testé : fonctionnel.

**Comment by Albatros78** [comment]
Hello 

Dans le fichier  ./application/views/administration/update/index.php  j'ai donc modifié la ligne 26 avec:
if (file_exists("../app/application/language/".Auth::user()->language."/update.php") && Auth::user()->language != 'en') {

Lorsque je tente l'update via le menu administration (interface en anglais) j'ai l'erreur suivante:

Unhandled Exception
Message:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'afs_bugtracker.update_history' doesn't exist

SQL: INSERT INTO `update_history` (`Description`, `DteRelease`, `DteInstall`) VALUES (?, ?, ?)

Bindings: array (
  0 => '1.83g',
  1 => '2021-03-02',
  2 => '2021-04-15 11:18:32',
)




Pour avancer, ne serait t'il pas plus simple que je télécharge le zip complet et que je le décompresse sur mon installation actuelle. C'est ce que j'ai fait pour tous les autres tickets . Je n'étais jamais passé par le menu administration !!!

Merci

**Comment by Albatros78** [comment]
Mais en fait en décompressant le fichier sur mon installation actuelle, cela ne fonctionnera pas car las base est pas mise à jour dans ce cas ?

Le mieux est donc de sauvegarder ma base et de relancer une installation et de restaures mes données. 
c'est ok comme cela ?

**Comment by Patriboom** [comment]
Bonjour Albatros, 
 merci pour ton aide et ta patience.

  Faisons comme tu dis, décompressant le zip.  Inutile de sauvegarder la BDD, mais c'est toujours prudent de le faire.  Tu verras la différence lors de la prochaine mise à jour.  Les consignes données dans "Administration / mise à jour "  sont précisément de décompresser le ZIP.  Tu pourras donc procéder ainsi.  Lors du lancerment d'une nouvelle version, tu pourras alors mettre la base de données (BDD) à jour, car le fichier pour cela est inclus dans la nouvelle version et le sera dans la prochaine aussi.

J'en dis trop inutilement.

Fais comme tu dis: décompression du zip sur l'installation actuelle et ça ira bien.

**Comment by Patriboom** [comment]
May we close this ticket ?

**Comment by Albatros78** [comment]
Oui mais problème pas résolu !!!
faut il fermer ?

**Comment by Patriboom** [comment]
Je ferme le billet, car je prépare une refonte du système de mise à jour qui inclura un mode _tout-automatique_.
