### ISSUE TITLE
Progression graphic

### ISSUE THREAD

**Issue by Patriboom** [pixeline/bugs#38]
@Julianatienza ask for progression graphic, or time work or milestone linked to issue.

May you give more details about what you want, please?

What I understood:
    Let say we give 100 days to solve and issue
    A  graphic bar will increase of 1 every which has passed since the intial posting date.
    Let say, this graphic bar will be green for first 60 days, yellow for days 61-85 and red for days 85 to `100.

   If possible, the maximal duration ( up here fixed to 100 days) should be customable by the system administrator.

example:

This issue's duration: =====   (5 days)
This issue's duration: =================================  (days)
This issue's duration: =========================================================== (60 days)

That is how I understand  your wish.

**Comment by julianatienza** [comment]
@Patriboom  Perfect! I think it will be a good improvement. But it would be even more useful if this kind of visual marks (green, yellow, red) made against milestones and duration of issue will be visible in "Open Issues" View. 

In this case managers will be able to rearrange their list of issues by criticity and take actions in each case.

Thanks so much

**Comment by Patriboom** [comment]
@Julianatienza , your wish is fullfilled, you have max duration color bar.

**Comment by julianatienza** [comment]
Bravo! I will check it asap

**Comment by Patriboom** [comment]
This is the general issue window  which presents the progression bar (percentage) AND duration bar in a thin version.
![progbarres](https://cloud.githubusercontent.com/assets/19801202/20710208/4a0a322e-b607-11e6-9713-fd462e13d65a.png)

**Comment by Patriboom** [comment]
Screenshot of the issue windows, with wide colored bars for percentage done AND time scheduled.
![progbarres_ticket](https://cloud.githubusercontent.com/assets/19801202/20730134/e4432058-b652-11e6-9bfc-7d92fd3297f2.png)
