### ISSUE TITLE
No following icon for any project - Just a number

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#384]
OK j'ai décompressé le fichier ZIP sur mon instalaltion et jai mis à jour ma base avec le fichier update_v1-8_4b.sql pour créer les tables manquantes.

En ouvrant le projet pour un utilisateur j'ai cela.

![image](https://user-images.githubusercontent.com/79452305/114870215-2c8fbd80-9df8-11eb-9848-7cfbede20891.png)

et en cliquant sur un post j'ai cela

![image](https://user-images.githubusercontent.com/79452305/114870318-50eb9a00-9df8-11eb-83a5-ee0da72c04f7.png)

Voila pour commencer !

**Comment by Patriboom** [comment]
J'apprécie grandement ta patience, Albatros.  Merci.

**Comment by Patriboom** [comment]
La dernière mise à jour que je viens de pousser vers ici porte les images manquantes.

**Comment by Albatros78** [comment]
Ok la bulle est là!

A quoi correspond le nombre à côté ?

![image](https://user-images.githubusercontent.com/79452305/115010328-8ef6c580-9ead-11eb-9551-37ff67db2fef.png)


L'affichage ici n'est pas optimisé...

![image](https://user-images.githubusercontent.com/79452305/115010415-b057b180-9ead-11eb-833f-b5785edc60bf.png)


lorsque je clique . j'ai ce popup. je pense que c'est pour toi dans le dev

![image](https://user-images.githubusercontent.com/79452305/115010647-f0b72f80-9ead-11eb-8c8e-bf5e9bb89f98.png)

lorsque je mets un nouveau commentaire et/ou re-tag le mail ne part pas... mais l'action est bien enregistrée dans la base

Unhandled Exception
Message:
mail(): Bad Message Return Path
Location:
E:\xampp\htdocs\bugtracker\app\application\controllers\project\issue.php on line 115

et ensuite en cliquant sur dashboard ...

Unhandled Exception
Message:
Trying to access array offset on value of type null
Location:
E:\xampp\htdocs\bugtracker\app\application\models\user.php on line 173

**Comment by Patriboom** [comment]
Merci, merci!

Le nombre à côté de la bulle est là depuis le début du projet; la bulle aussi d'ailleurs.  Le nombre indique combien de commentaires compte la discussion.

**Comment by Albatros78** [comment]
Ha OK... 

Je ne savais pas.. donc ...justement 
est il possible d'ajouter sur le nombre par un mouse hover un tooltip avec un petit message 'nombre de commentaires'
et aussi même chose sur la bulle pour indiquer 'suivre ce ticket', 'ne plus suivre ce ticket'.
C'est pas grand chose mais utile.

**Comment by Albatros78** [comment]
Il y a toujours le problème des emails avec le suivi !

**Comment by Patriboom** [comment]
Concernant le souci de courriel, 
voici ce que j'ai trouvé:   problème de configuration du serveur de sortie  ( [https://stackoverflow.com/questions/51404390/warning-bad-message-return-path-php#51408308](https://stackoverflow.com/questions/51404390/warning-bad-message-return-path-php#51408308) -en anglais.  Il s'agit donc de la configuration que vous avez inscrite dans ./bugs/config.app.php  aux lignes 94 à 119.

Concernant  `Unhandled Exception
Message:
Trying to access array offset on value of type null
Location:
E:\xampp\htdocs\bugtracker\app\application\models\user.php on line 173`
C'est le fait d'une base vide.
Je viens d'apporter un correctif dans mon code.  Il sera disponible prochainement.
En attendant, vous pouvez ajouter la ligne suivante au fichier, entre les actuelles lignes 167 et 168
`if ($tag_diff === NULL) { $tag_diff['added_tags'] = array(); $tag_diff['removed_tags'] = array(); }`
si besoin.

**Comment by Patriboom** [comment]
Nous poursuivrons cette discussion dans le billet

**Comment by Albatros78** [comment]
Patrick

Mon fichier de config.app.php est celui que j'avais précédemment... il fonctionnait...

Voici les lignes 90 à 125

 * Default Mail Transport
	 *	|
	 *	| Possible Values
	 *	| 	mail (PHP Mail Function) --- default
	 *	| 	PHP (php language mail function)
	 *	| 	sendmail (Sendmail - almost the same as 'mail' option but with authentications details)
	 *	| 	gmail (using Google's gmail system)
	 *	| 	pop3 (Define Custom POP3)
	 *	| 	smtp (Define Custom SMTP)
	 *
	 */
	 /*
	'mail' => array(
		'from' => array(
			'name' => 'AFS BugTracker',
			'email' => 'no_reply@afsoftware.fr',
		),
		
	*/	
     'mail' => array( 
	   'from' => array( 
	    'name' => '',
		'email' => '"AFS BugTracker" <no_reply@afsoftware.fr>',
		),		
		
		/**
		 * Transport Settings
		 * Transport settings if using mail or smtp
		 * 'mail' or 'smtp' must be lower case
		 */
		'transport' => 'mail',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => '',
			'port' => 25,
			/*

Actuellement je teste en localhost et mon serveur de réception mail est l'outil Fake SMTP qui fonctionne sur le port 25 par défaut

**Comment by Albatros78** [comment]
Ne faut il pas cloturer ce ticket et ouvrir un autre pour les problèmes d'envoi d'emails.

La on va se perdre !!!

**Comment by Albatros78** [comment]
Ici l'alignement n'est pas top !

![image](https://user-images.githubusercontent.com/79452305/115150761-1b4de780-a06a-11eb-9d1d-42b1ccc85454.png)

Sur 3 lignes serait mieux !

**Comment by Albatros78** [comment]
And also

translation issue

![image](https://user-images.githubusercontent.com/79452305/115237427-d8008100-a11c-11eb-8c25-3424e6efdb8d.png)
