### ISSUE TITLE
Pictures near project name not displayed after click

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#387]
Hello

Je ne sais pas à quoi servent ces images... et lorsque l'on clique voilà ce que j'ai !

![image](https://user-images.githubusercontent.com/79452305/115031979-143ba380-9ec9-11eb-98ad-4829000ce8e5.png)

Merci

**Comment by Patriboom** [comment]
Ces images sont pour "suivre le projet".  Étrange que la version verte n'apparaisse pas.

**Comment by Patriboom** [comment]
Veuillez faire Ctrl-F5 pour recharger la page en forçant la mise à jour des images  et m'en donner le résultat. 
Les images devraient s'afficher.
Vous pouvez vérifier aussi la présence des fichiers
- icon-comments_0.png
- icon-comments_1.png

Dans ./bugs/app/assets/images/layout/

Puisque la version "verte" de la bulle s'affiche bien  ( selon https://github.com/pixeline/bugs/issues/384 ) 
et que la version grise s'affiche bien ( selon votre capture d'écran ), la version verte devrait elle aussi s'afficher ici.

Conformément à votre demande dans (  voir billet 384 ), une belle surgissante sera affichée lorsque vous passerez votre curseur au-dessus de l'image, la mise à jour des fichiers concernés réglera deux soucis d'un coup.

Merci de votre patience et votre aide.

**Comment by Albatros78** [comment]
Oui les images sont bien là !

Avec CTRL+F5 cela fonctionne, mais à chaque fois que je clique sur la bulle verte ou grise je n'affiche plus la bulle. Je dois refaire CTRL+F5 pour qu'elle change de couleur.
J'ai fermé mon onglet dans le navigateur pour en rouvrir un nouveau.. pensant un problème de cache. Même résultat

**Comment by Patriboom** [comment]
Ok.  J'irai donc avec des adresses absolues plutôt que relatives.  Ça fonctionnera à tous coups.

**Comment by Albatros78** [comment]
v1.84b

les images s'affichent correctement à chaque clic
Super... Merci

SI je comprends bien cela veut dire que si la bulle est verte je suis TOUS les tickets du projet... et si elle est grise je ne les suis plus... c'est bien cela qu'il faut comprendre ?

**Comment by Patriboom** [comment]
La compréhension n'est pas tout à fait juste.

Suivre un projet fait en sorte qu'un courriel est émis lorsque
- Un nouveau billet est créé, mais les commentaires de ce billet ne sont pas systématiquement suivis.
- Un projet est modifié ( son titre ou son état ouvert/fermé ) 

Ne seront donc suivis que les billets pour lesquels vous aurez choisi d'être avisé.
L'activation du suivi de projet ne vous avisera qu'au moment de la création d'un billet, mais ne suivra pas les détails du-dit billet.
Cette option a été choisie afin de limiter le nombre de courriels émis et reçus par un gestionnaire de plusieurs projets.

J'espère que c'est plus clair.

**Comment by Patriboom** [comment]
Concernant les images du bandeau gauche, elles font encore defaut dans certaines circonstances.  J'y verai.

**Comment by Albatros78** [comment]
OK... Avant de vérifier...

Je crois que nous travaillons sur trop de problèmes en simultané et c'est difficile de suivre aussi pour moi.
Je propose de traiter un ticket jusqu'au bout, avant de passer à un autre.

On travaille sur celui ci #387 uniquement pour tout corriger avant de tester autre chose

OK ?

**Comment by Patriboom** [comment]
Les images, c'est plutôt secondaire.

Je veux en finir avec les courriels.

**Comment by Albatros78** [comment]
OK. J'attend que tu me dises quand je dois faire quelque chose !

**Comment by Patriboom** [comment]
Le billet https://github.com/pixeline/bugs/issues/392 comporte l'info nécessaire.  Une mise à jour du fichier 
./app/application/controllers/project/issue.php

**Comment by Patriboom** [comment]
Voir commentaire dans https://github.com/pixeline/bugs/issues/353 

Je vous laisse du temps pour tester.
Merci de m'aider ainsi.

Je crois que ce message sur les images pourra être fermé.
Tout ce qui a trait aux courriels émis sera pris en charge dans le billet 353.

**Comment by Albatros78** [comment]
OK. Go to 353
