### ISSUE TITLE
Action message just on the top... Could nice to have also to the bottom (option or not)

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#389]
Lorsque nous effectuons une mise à jour d'un ticket, ou ajout d'un nouveau ticket, l'action est affichée en haut de l'écran

Comme ici:

![image](https://user-images.githubusercontent.com/79452305/115115299-fc7d2180-9f93-11eb-9662-076fc0a1e7da.png)

Il serait bien de pouvoir avoir le même message en bas de page, avec un choix optionnel (case à cocher) ou pas...!!!

Mais lorsqu'il y a plusieurs ticket et que noue mettons à jour le dernier, la page est descendue et donc le message de modification n'est pas visible... Il faut **rapidement remonter** en haut de la page pour voir le message.

**Comment by Patriboom** [comment]
Quel serait le contenu, l'objet de la case à cocher ?   À quoi ça servirait ?  Quelle option offerte ?

**Comment by Albatros78** [comment]
Au milieu de l'écran, mais il faut que l'utilisateur clique pour le faire disparaître... Car si c'est un message d'erreur il faut aussi avoir le temps de le lire.

Je pense que l'idée est bonne... Il est toujours utile de savoir se ce que l'on a fait est ok ou pas .
non ?

**Comment by Patriboom** [comment]
J'en ai réduit la largeur.
Le ruban sera dorénavant une rectangle surgissant au milieu de l'écran et disparaissant automatiquement après le même délai qu'il le faisait avant que je n'y touche.
L'oppacité de la bulle est passée de 95% à 85%, c'est donc dire qu'elle nous permet d'entrevoir ce qu'il y a derrière.
Le caractère blanc est passé au jaune BUGS.
Les coins ont été arrondis.

On peut, comme avant, le faire disparaîte en cliquant dessus.
Ce sera accessible lors de la prochaine mise à jour.

**Comment by Albatros78** [comment]
It's works fine with 1.84c

merci !!! Super

**Comment by Albatros78** [comment]
Lorsque le ticket a beaucoup de commentaires (plus d'une page) et que l'on ajoute un nouveau commentaire, le popup au milieu de l'écran est en haut de la page et plus au milieu.
Si le message pouvait rester au milieu dans tous les cas cela sera mieux !
merci
