### ISSUE TITLE
Follower does not received email on new admin comment

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#392]
Hello

Si j'ajoute un commentaire le follower qui suit le ticket ne recoit pas l'email. Le commentaire est ajouté !

Erreur:

essage:
mail(): Bad Message Return Path
Location:
E:\xampp\htdocs\bugtracker\app\application\controllers\project\issue.php on line 119

La ligne 119 dans mon issue.php est:

		mail($follower->email, __('tinyissue.following_email_comment_tit'), __('tinyissue.following_email_comment')." « ".$follower->title." ».");

**Comment by Patriboom** [comment]
Elle se lit maintenant ainsi: 
`send_mail(__('tinyissue.following_email_comment')." « ".$follower->title." ».", $follower->email, __('tinyissue.following_email_comment_tit'));`

Notez l'exclusion des adresses suivantes: 
- auteur du commentaire
- usager actuellement en ligne ( ~ auteur du commentaire )

**Comment by Patriboom** [comment]
Vous pouvez mettre à jour le fichier et tester de nouveau.
Comme dit ailleurs, c'est maintenant conforme au modèle laravel, en utilisant la fonction send_mail qui vérifie les options choisies dans la configuration plutôt que d'imposer le mode de transport _mail_.

D'autres commandes `mail` se cachent encore peut-être dans le nouveau code.

**Comment by Patriboom** [comment]
Voir commentaire dans https://github.com/pixeline/bugs/issues/353 

Je vous laisse du temps pour tester.
Merci de m'aider ainsi.

**Comment by Albatros78** [comment]
J'ai téléchargé le dernier ZIP et copier sur mon installation.

J'ouvre un nouveau ticket en mode admin (il y a aussi un follower sur le projet)

et j'ai:

Unhandled Exception
Message:
Call to undefined function send_mail()
Location:
E:\xampp\htdocs\bugtracker\app\application\controllers\project\issue.php on line 67
Stack Trace:

Mais avec sendmail il y a peut être des choses à changer dans config.app.php et aussi le php.ini de mon serveur sous xampp !

Là j'avoue ne pas savoir trop quoi faire ! je manque de connaissance !
merci de ton aide.

**Comment by Patriboom** [comment]
Désolé Albatros78 pour cela, 

Moi aussi j'ai eu ce problème et j'ai fait encore une mise à jour.
Aïe!
Je prends un pause et vous demandand de télécharger encore et tester encore, car la vraie dernière version de .app\application\controllers\project\issue.php   date de quelques minutes seulement et fonctionne bien en développement.
Ce n'est pas encore la forme définitive, mais ça permettra de relaxer un peu.

**Comment by Patriboom** [comment]
Please go to https://github.com/pixeline/bugs/issues/353  for next development.

**Comment by Patriboom** [comment]
Ici aussi, les mdifications annoncées dans le billet https://github.com/pixeline/bugs/issues/353 sont applicables.  Le retour du courriel est testé et vérifé, mais il n'y a pas encore de traitement des $headers.
