### ISSUE TITLE
Assets and redirects break if Bugs is placed in subfolder of document root

### ISSUE THREAD

**Issue by johannesalbert** [pixeline/bugs#4]
If Bugs is installed in a subfolder/basedir of a host's document root (eg. <http://www.example.com/applications/bugs>), then:

1. some **assets** (Bugs icon, favicon) disappear and
2. many of the server-side **redirects** (eg. after login, issue creation etc.) stop working (404).

1) is easily fixed by use of `URL::to_asset()` in login.php and header.php.
2) requires a thorough look at how the redirect urls are built... Example: login.php currently uses  Symfony's `Request::getRequestUri()` instead of the more application-aware (and probably correct) `URI::current()`.

**Comment by kboss** [comment]
Since this Issue is open for some time now: is there any Workaround or Patch available to be able to use subdirs for a install?

**Comment by fnadde42** [comment]
@johannesalbert Do you have a quick fix for this issue? This has to be fixed...

**Comment by pixeline** [comment]
Fixed in forthcoming 1.5
