### ISSUE TITLE
Message on action always on the top of the page

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#410]
Je l'ai indiqué dans l'autre ticket, mais lorsque le ticket possède plusieurs commentaires (~40), et lorsque tu ajoutes un commentaire en bas de page le message de mise à jour ne s'affiche pas devant l'utilisateur sur la page en cour mais tout en haut de la page.
Il faut donc remonter en haut pour voir le message

![image](https://user-images.githubusercontent.com/79452305/115531606-4405f500-a295-11eb-9a49-239bee9b6ef1.png)

Il faudrait que le message reste sur la page affichée en cours pour le visualiser.

Merci

**Comment by Patriboom** [comment]
Ceci viendra en fin de train.
Il y a présentement trois chantiers ouverts, ce détail d'affichage devra attendre.

**Comment by Patriboom** [comment]
J'ai mis quelques minutes là-dessus.  
Ce me semble bon ( fichiers disponibles ).

**Comment by Albatros78** [comment]
Je vais regarder de plus près... j'ai pas fait vraiment attention, trop focalisé sur les autres problèmes importants

**Comment by Patriboom** [comment]
C'est ici le petit "+"

Si vous pouvez bien confirmé le fonctionnement adéquat - selon votre désir et fermer le billet.
De mon côté, tout fonctionne bien.

**Comment by Albatros78** [comment]
Oui pendant mes tests, j'avais l'impression de voir le message de l'action à chaque fois au milieu  de page
Effectivement il est toujours visible quelques soit l'endroit ou l'on se trouve.

Là c'est super friendly l'utilisation et le visuel

Merci pour ce bon job !
