### ISSUE TITLE
Tag list has disappeared with search option

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#412]
Hello Patrick

Dans la version 1.83g il y avait la possibilité de lister tous les tags dans les options de recherche.
cela a disparu depuis ! erreur durant le dev ?

![image](https://user-images.githubusercontent.com/79452305/115762777-19ef2880-a3a4-11eb-8004-7ba10cb7a914.png)

**Comment by Albatros78** [comment]
D'ailleurs durant la création d'un ticket il serait bien d'avoir la liste déroulante de tous les tags à côté du champ

![image](https://user-images.githubusercontent.com/79452305/115763039-60dd1e00-a3a4-11eb-88c9-9667cf845c2d.png)

**Comment by Patriboom** [comment]
Oui, c'est disparu avant - même.
C'est seulement un projet qui n'a pas abouti. La liste ne servrait à rien d'autre qu'à voir les étiquettes disponibles.

**Comment by Albatros78** [comment]
Ben je trouve que c'est plutôt bien de voir la liste. non ?
Sinon il faut chercher lettre par lettre !

**Comment by Patriboom** [comment]
Oui, c'est pourquoi j'avais commencé cela.  Mais ce n'était que visible, pas fonctionnel.  Ça reviendra après la conclusion des autres chantiers.

**Comment by Patriboom** [comment]
La fonction existait déjà, il suffisait de la faire sortir:  il suffisait de taper le pourcentage (%) pour obtenir la liste complète.

La fonction est améliorée:  les caractères suivants sont considérés comme _universels_ et provoquent l'affichage de la liste complète (si et seulement si un de ces caractères est seul élément de recherche):  

- % 
- *

**Comment by Albatros78** [comment]
Bonjour.
Bien dormi ?

Heu... je dois télécharger le dernier code pour cela ?

**Comment by Patriboom** [comment]
Pas nécessaire de télécharger le dernier code si vous acceptez la limite d'usage au seul caractère % (pourcentage).  Le téléchargement vous permettra aussi bien d'utiliser * que %

**Comment by Albatros78** [comment]
Ok non.

% fonctionne pour un nouveau ticket, la recherche et l'édition d'un ticket
Ton autre caractère dans ton message ci dessus, je ne sais pas ce que c'est ? une petit bulle ?
Génial en tout cas


![image](https://user-images.githubusercontent.com/79452305/132097243-f2d6d845-a98f-4774-8da4-a16366d772cd.png)

peut être peux tu ajouter * et ? comme autres caractères

et peut être ajouter devant le champ tag (nouveau ticket, recherche et edition d'un ticket) une petite phrase pour aider l'utilisateur:

"to display tags list type ? or % or * "

**Comment by Albatros78** [comment]
tu peux pas trier par ordre alpha la liste qui s'affiche !

**Comment by Albatros78** [comment]
Ok pour * et % et le petit memo Joker blabla

le tri de la liste ? doable ?

**Comment by Patriboom** [comment]
C'est une idée.
Je vais voir

**Comment by Patriboom** [comment]
C'est fait.  Les étiquettes sont triées par ordre alphabétique.
Je passe ce billet à "résolu"
