### ISSUE TITLE
Error email sending during user creation

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#423]
v1.84i

J'ai essaye de créer un nouvel utilisateur simple et j'ai l'erreur suivante sur l'envoi de l'email à l'utilisateur fraichement crée.

Message:
include_once(app/application/controllers/ajax/SendMail.php): failed to open stream: No such file or directory
Location:
E:\xampp\htdocs\bugtracker\app\application\libraries\mail.php on line 12

Mais l'utilisateur est crée !

**Comment by Patriboom** [comment]
J'ai mis un patch en attendant de bâtir une solution meilleure et plus universelle.

**Comment by Albatros78** [comment]
v1.84l

Ok c'est bon !
