### ISSUE TITLE
Tag editor to add, edit, remove tags (text, color...)

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#429]
Hello Patrick,

j'ai moi même ajouter des tags manuellement dans la base et j'ai modifié la base pour avoir une couleur de texte en fonction de la couleur de fond.

![image](https://user-images.githubusercontent.com/79452305/115997229-b7d03680-a5e2-11eb-8db2-fdc58638d3a0.png)

Ensuite j'avais modifié la ligne suivante dans app/application/views/project/index/issues.php en ligne 70

<?php echo '<label class="label" style=" color:'. $tag->textcolor.'; background:'. $tag->bgcolor.';"'  .  '>' . $tag->tag . '</label>'; ?>

et ainsi la couleur du texte des tags est plus lisible comme ici.

![image](https://user-images.githubusercontent.com/79452305/115997312-f665f100-a5e2-11eb-8103-d8c12c298ded.png)

Sauf le taga 'testing' comme tu peux le voir car texte illisble.

Si cela était possible de mettre à jour le code pour afficher la couleur du texte (si la base est modifiée évidemment). Et si on pouvait éditer les tags par l'interface cela serait cool aussi.
Pas urgent non plus.

Attention de penser à changer aussi la lisibilité des tags ici.

![image](https://user-images.githubusercontent.com/79452305/115997434-61172c80-a5e3-11eb-917b-414ac6bf160b.png)

et aussi dans l'édition d'un ticket.

![image](https://user-images.githubusercontent.com/79452305/115997463-7724ed00-a5e3-11eb-82d0-7e29b1298222.png)

Voila c'est une idée mais pratique je crois.

Merci

**Comment by Patriboom** [comment]
Tout est là, dans la page d'administration:
![image](https://user-images.githubusercontent.com/19801202/116001343-09b49480-a5c2-11eb-922d-3d687bb3d6d8.png)

**Comment by Patriboom** [comment]
Ah, et puis -tiens! - en prime vous voyez l'interface sur laquelle je planche actuellement et qui vous permettra de personnaliser tous les textes automatiquement transmis.

**Comment by Albatros78** [comment]
Nice !!!!!
Awesome et beau travail !

**Comment by Patriboom** [comment]
Je ne comprends pas le commentaire qu'Albatros78 a laissé dans un autre fil de discussion.
Pouvez-vous préciser ?

**Comment by Patriboom** [comment]
Après avoir cliqué sur « Étiquettes » ( en français )  ou « Tags » (en anglais), vous devriez voir la page suivante: 
![image](https://user-images.githubusercontent.com/19801202/120055259-d15e0700-c002-11eb-9b19-8c92ca25bc8d.png)

Vous pourrez alors ajouter une étiquette
ou modifier une étiquette existante en cliquant sur ladite.
Vous arriverez alors à la page suivante: 
![image](https://user-images.githubusercontent.com/19801202/120055279-fbafc480-c002-11eb-8396-83a8fc555a1e.png)

Où vous pourrez alors définir ou modifier le mot affiché, choisir la couleur associée.

Non, il n'est pas et ne sera jamais possible de supprimer une étiquette.

**Comment by Albatros78** [comment]
5S installé.

je ne sais pas ou trouver l'option pour éditer les tags !

**Comment by Albatros78** [comment]
Comme indiqué dans mon message initial. Il est important je crois de pouvoir aussi choisir aussi la couleur du texte pour certains constrates de couleur
Il faut donc ajouter une colonne text_color dans la table !

On voit pas dans l'exemple que le texte en blanc est peu lisible.

![image](https://user-images.githubusercontent.com/79452305/120182039-23bf4380-c20e-11eb-8dc4-7609f3779804.png)

**Comment by Patriboom** [comment]
Avez-vous trouvé le chemin d'édition des étiquettes ? 

- Page Administration
- Partie centrale : «  Étiquettes / Tags »  
- Cliquez sur le mot  «  Étiquettes »  ou « Tags »  

Chacune des expression  ( Utilisateurs, Rôles, Projets, Étiquettes, Billets, Version ) mène à une interface de gestion.

**Comment by Patriboom** [comment]
Quant à la couleur du texte, pour le moment, elle est automatiquement calculée en fonction de la couleur de fond.  Il y a un point de bascule à partir duquel le texte passe du blanc ou noir.  Le vert pointé par votre flèche est près de ce point de bascule.

**Comment by Albatros78** [comment]
En 1.85s.

aucun menu !

![image](https://user-images.githubusercontent.com/79452305/120203892-7f96c600-c228-11eb-8998-e0f66afd830b.png)

**Comment by Albatros78** [comment]
Ha oui c'est le mot Tags qu'il faut cliquer !!!

**Comment by Albatros78** [comment]
Le calcul pour la couleur du texte ne fonctionne pas.

![image](https://user-images.githubusercontent.com/79452305/120204266-e7e5a780-c228-11eb-9ae9-e897745b6b30.png)

LA couleur de fond est:

![image](https://user-images.githubusercontent.com/79452305/120204346-fe8bfe80-c228-11eb-985c-f90c1ee19772.png)

**Comment by Patriboom** [comment]
C'est un bonne demande.  J'ajouterai un sélecteur de couleur pour la police.

**Comment by Albatros78** [comment]
Oui je crois que c'est plus simple car c'est l'utilisateur qui fait son propre mix !

**Comment by Patriboom** [comment]
Déjà, vous pouvez modifier votre base de données en lui faisant avaler la commande suivante: 
''ALTER TABLE tags ADD COLUMN ftcolor VARCHAR(50) DEFAULT '#FFFFFF' AFTER bgcolor;''
en vue de la prochaine mise à jour.

**Comment by Patriboom** [comment]
La mise au point complète de cette simplement fonctionnalité demandera quelque temps.  J'y travaillerai plus tard ce jour ou cette semaine.
Je vous aviserai lorsque prêt.

**Comment by Albatros78** [comment]
OK. 
Il ne faudra pas oublier de repréparer le package avec les modifications qui ont été apportées dans la base depuis nos échanges. Dans le répertoire install il existe plusieurs fichiers update_xxx.sql a ne pas oublier dans es modifications.
Cela sera nécessaire pour une réinstallation complète from scratch

**Comment by Patriboom** [comment]
Oui, merci de m'y faire penser.  C'est déjà fait.

**Comment by Patriboom** [comment]
La version 1.8, révision 5t inclut les modifications demandées et est disponible dès maintenant ( conditionnellement à ce que vous ayez effectué la modification sus-mentionnée dans votre BdD ) .

**Comment by Albatros78** [comment]
Nickel. Good job
Merci

**Comment by Albatros78** [comment]
Une chose étrange

mes tags sont les suivants:

**Comment by Patriboom** [comment]
Oui, étrange!  Je regarde.

**Comment by Patriboom** [comment]
Le numéro de version n'est en rien changé, mais le code est modifié.
Vous pouvez mettre à jour et voir que les étiquettes suivent dorénavant les consignes de couleur attribuées en Admin.

**Comment by Albatros78** [comment]
et ajouté

![image](https://user-images.githubusercontent.com/79452305/120341497-36fa0e00-c2f7-11eb-92dc-7a9631d2ba7a.png)

**Comment by Patriboom** [comment]
La version actuelle - 1.8 rev.5u  est destinée à corriger ce détail.

**Comment by Albatros78** [comment]
Hello Patrick !

v1.85u installée 
Après le login

Dashboard An overview of all the activity involving your active projects.
Database Installator
Unhandled Exception
Message:
syntax error, unexpected '.'
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 29
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#10 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#11 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#12 {main}

**Comment by Patriboom** [comment]
Aïe!!!  Désolé.  J'y vois derechef.

**Comment by Patriboom** [comment]
Je n'arrive pas à reproduire l'erreur.  Il faut chercher d'avantage.  Je vous reviens.

**Comment by Patriboom** [comment]
Je suis resté incapable de reproduire le bug décrit.  Néanmoins, j'ai apporté quelques modifications mineures.  Si vous voulez bien essayer de nouveau.  Version 1.8 rev.5u-bis

**Comment by Albatros78** [comment]
Ok, mais même erreur

Dashboard An overview of all the activity involving your active projects.
Database Installator
Unhandled Exception
Message:
syntax error, unexpected '.'
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 29
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#10 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#11 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#12 {main}

**Comment by Albatros78** [comment]
tu veux le contenu de ma base SQL ?

**Comment by Patriboom** [comment]
Pouvez-vous cliquer sur la ligne d'erreur 11  "index.php(19):require('E:\)"  afin d'avoir le message complet ? 

S'il y a une erreur là, c'est le début du début. C'est normal que rien ne fonctionne après.

Et vous me dites que "déconnexion / reconnexion" fonctionne !
Normalement, une erreur dans ce qui est annoncé en ligne 11 ne devrait même pas conduire à la page de connexion.

**Comment by Albatros78** [comment]
Moi la ligne 11 s'affiche comme cela... pas de lien !!!!!

#11 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')

l'erreur se produit après avoir indiquer mes identifiants dans la page de login qui s'affiche bien et en validant pour me connecter.

**Comment by Albatros78** [comment]
le #11 dans mon navigateur n'est pas un lien mais juste du texte

**Comment by Patriboom** [comment]
J'ai ramené un fichier modifié aujourd'hui à son état antérieur.

**Comment by Patriboom** [comment]
Version à jour:  1.8 rév 5u-ter

**Comment by Albatros78** [comment]
1.85u ter installée.

Dashboard An overview of all the activity involving your active projects.
Database Installator
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
Undefined index: ftcolor
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 11
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(11): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

j'ai réinstallé la v1.85t2 et cela fonctionne .... donc cela vient de la version actuelle

**Comment by Patriboom** [comment]
Ok, merci.
Je révise.

**Comment by Patriboom** [comment]
Merci pour votre patience.  J'ai ramené les fichiers modifiés ce jour à leur état antérieur.
Si vous voulez bien confirmer le bon fonctionnement avant que  je ne reprenne les modifications.

**Comment by Albatros78** [comment]
Je viens d'installer le dernier download...
et

Database Installator
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
**Undefined index: ftcolor**
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 11
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(11): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

mais ftcolor existe dans  ma base

![ftcolor1](https://user-images.githubusercontent.com/79452305/126368584-d80b0a71-6783-41e3-96f2-8080d3a35a2b.png)

**Comment by Patriboom** [comment]
Je reviendrai à la révision r et reprendrai tout le travail prochainement.

**Comment by Patriboom** [comment]
Retour à des bases sûres.  Tout fonctionne bien sur mon ordinateur de test.
Afin de vous assurer que toutes les mises à jour nécessaires à la poursuite du développement, je vous encourage à prendre tout le fichier  https://github.com/pixeline/bugs/archive/refs/tags/1.8_5r.zip et le déployer.

**Comment by Patriboom** [comment]
Les corrections souhaitées ci-haut seront implantées à partir de cette base (https://github.com/pixeline/bugs/archive/refs/tags/1.8_5r.zip) fonctionnelle.

**Comment by Albatros78** [comment]
version 1.85r

Dashboard An overview of all the activity involving your active projects.
Database Installator
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
Undefined index: ftcolor
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 11
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(11): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 11, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

Si je réinstalle la v1.85t2 suite à ces erreurs, tout fonctionne ...

Donc la base n'est pas en cause car je n'y touche pas.

Bon si cela devient trop compliqué on arrête dans ce cas ! Je ne voudrais que tu perdes tu temps.. Moi je ne fais que les tests !

**Comment by Patriboom** [comment]
Ce que j'observe ici, c'est la disparition de l'historique des étiquettes dans l'affichage du billet.
Les ajouts et retraits d'étiquettes devraient être insérés entre les interventions des usagers, selon l'ordre chronologique.
Il semble ici que ce soit l'enregistrement des événements (ajout / retrait d'étiquette) qui soit en défaut.
Je suis actuellement à travailler cela.

Parlez-moi plutôt des couleurs et des pages d'erreur que vous rencontriez.

**Comment by Albatros78** [comment]
Je crois avoir dit hier que le problème des erreurs Undefined Index 8 en ouvrant les issues est réglé. Plus d'erreur

Et il reste ce problème d'affichage 


![image](https://user-images.githubusercontent.com/79452305/132015601-b0c6fe9a-0f80-4fa6-8140-ad6af2bb1e9b.png)

**Comment by Albatros78** [comment]
Hop Hop
si je clique sur dashboard !!!!

![image](https://user-images.githubusercontent.com/79452305/132015878-c8571dc7-c946-4b03-9a09-6a75428ad781.png)

**Comment by Albatros78** [comment]
Ha c'est peut être à cause de ftcolor

**Comment by Patriboom** [comment]
Merci, j'y vois.  Je vous reviendrai sous peu.

**Comment by Patriboom** [comment]
Veuillez essayer de nouveau votre tableau de bord.  J'espère avoir trouvé la solution à son problème ftcolor.

**Comment by Albatros78** [comment]
Je viens de télécharger le dernier code... !!!
Boum après le login

Dashboard An overview of all the activity involving your active projects.
Database Installator
Comment
"Holé" by Admin Admin on issue Add documentation and finalization of cutomization of v1.1 Bonjour après 2021-09-02 18:24
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
Undefined index: ftcolor
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 12
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(12): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

**Comment by Patriboom** [comment]
C'est encore l'indice 8 qui bloque.
Il se trouve dans 71 fichiers!!!!!  Ça peut prendre quelques minutes.

**Comment by Patriboom** [comment]
Merci de votre patience.  Je reste incapable de reproduire les erreurs que vous me montrez.
J'ai apporté quelques corrections.  Dites-moi si ça règle le problème.
Merci.

**Comment by Albatros78** [comment]
Après Login ou en passant par bugtracker/administration et click sur Dashboard 

Dashboard An overview of all the activity involving your active projects.
Database Installator
Comment
"Holé" by Admin Admin on issue Add documentation and finalization of cutomization of v1.1 Bonjour après 2021-09-02 18:24
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
Undefined index: ftcolor
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 12
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(12): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(39): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

Désolé !

**Comment by Patriboom** [comment]
Donc toujours la même chose.
Je cherche ailleurs.
De votre côté, est-ce que les autres pages fonctionnent bien ? 
Si je comprends, il n'y a que le dashboard qui présente encore des soucis avec ftcolor.

**Comment by Albatros78** [comment]
Il y a issues aussi

![image](https://user-images.githubusercontent.com/79452305/132026656-73dd89a2-5c07-4db6-b720-ad7675065105.png)

**Comment by Patriboom** [comment]
Ah oui!  Là, j'ai le même souci!
Enfin je pourrai déboguer à partir en voyant ce que vous voyez.

**Comment by Patriboom** [comment]
Là, je crois que nous y sommes.  Autant dans le dashboard que dans issues.

Il s'agissait d'une typo, un guillemet qui se trouvait à l'intérieur d'un autre plutôt qu'à l'extérieur.

Mon dashboard n'ayant jamais été affecté par cela, je ne suis en mesure que de confirmer la correction de "issues".

**Comment by Albatros78** [comment]
new code  à télécharger ?

**Comment by Patriboom** [comment]
Oui, c'est disponible.

**Comment by Albatros78** [comment]
OK pour Issues

![image](https://user-images.githubusercontent.com/79452305/132046898-d28a2967-90e8-466a-8045-8263498cea5f.png)


Not OK pour dashboard

Dashboard An overview of all the activity involving your active projects.
Database Installator
Comment
"Holé" by Admin Admin on issue Add documentation and finalization of cutomization of v1.1 Bonjour après 2021-09-02 18:24
tag update
2021-05-30 20:14
tag update
2021-05-30 20:14
Unhandled Exception
Message:
Undefined index: ftcolor
Location:
E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code on line 12
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12)
#1 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(12): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 12, Array)
#2 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353) : eval()'d code(34): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

**Comment by Patriboom** [comment]
Oyoyoille!

Ça ne finira jamais cette chose!
Je reprends.

**Comment by Albatros78** [comment]
Pour debugger tu peux pas mettre dans le code des messages popup ( ou autre)  comme debug 1, debug 2, debug x pour voir quels sont les messages affichés avant l'erreur...
Ainsi tu te rapproches de l'erreur dans le code en passant des bloc de codes qui sont OK.

**Comment by Patriboom** [comment]
Non, je viens de mettre la main sur quelque chose de mieux.
J'y serai sous peu.

**Comment by Patriboom** [comment]
Fichiers chargés, vous ne devriez plus avoir d'erreur.
Cependant, les couleurs utilisées sont celles par défaut et non celles choisies dans la gestion de Étiquettes.
J'y travaillerai demain.

Confirmez-moi en attendant que votre dashboard s'affiche désormais sans erreur.

**Comment by Albatros78** [comment]
Yessssssssssssssss
plus d'erreur.

Great job !

**Comment by Albatros78** [comment]
On continuera demain ...... 
Sinon je testerai demain vant ton reveil :-) si tu continue quelques corrections.

**Comment by Patriboom** [comment]
Ok merci.
Bon sommeil.

**Comment by Albatros78** [comment]
Je pense ne pas avoir de problèmes de couleur pour les tags !

**Comment by Patriboom** [comment]
Ça restera anisi.
C'est pourquoi le billet est fermé.
