### ISSUE TITLE
Any user, manager, developer can change their firstname & lastname

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#430]
Hello,

Un utilisateur peut changer lui même son nom et prénom. !!!!
![image](https://user-images.githubusercontent.com/79452305/116008769-81acaa00-a616-11eb-90f9-b920c8772827.png)

je pense que seul l'administrateur doit pouvoir modifier les noms et prénoms des utilisateurs:

User
Developers
Managers

Je pense qu'il faut bloquer ces champs pour la modification si pas Admin.

Sinon cela peut vite devenir ingérable pour l'administrateur qui ne retrouvera pas les noms qu'il aura mis lui même. 

Qu'en penses tu ?

**Comment by Patriboom** [comment]
J'en pense que si l'usager n'est pas assez sérieux pour afficher sa vraie identité, le gestionnaire devrait sérieusement penser à se défaire de cet énergumène qui ne sera pas fiable dans les travaux qui lui seront confiés.

**Comment by Albatros78** [comment]
C'est pas faux non plus !
