### ISSUE TITLE
impossible to reopen a ticket. Error !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#435]
Hello,

v1.84r

Erreur si je tente de réouvrir un ticket fermé (en Admin). Et le ticket reste fermé

Undefined index: tinyssiue
Location:
E:\xampp\htdocs\bugtracker\app\application\controllers\ajax\SendMail.php on line 45

**Comment by Patriboom** [comment]
Merci de votre patience.  
Cette faille en a révéler d'autres qui ont aussi été corrigées.

**Comment by Albatros78** [comment]
OK ca fonctionne !
