### ISSUE TITLE
Just to be more friendly: need a space between 2 words

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#492]

**Comment by Albatros78** [comment]
Ici il manque un espace

![image](https://user-images.githubusercontent.com/79452305/132017375-8b595642-b5fe-4d0b-9974-4e5c64032ad7.png)

**Comment by Patriboom** [comment]
Corrigé dans le code.  
Ce sera visible prochainement.

**Comment by Albatros78** [comment]
Il en reste :-)

![image](https://user-images.githubusercontent.com/79452305/132020815-03aa35e2-d68f-49dc-a037-ad1c41e73406.png)

**Comment by Patriboom** [comment]
Created_by, assigned_to et Updated_by corrigés.

**Comment by Albatros78** [comment]
oui OK
