### ISSUE TITLE
When I modify a post title the subject into email  has not a god displaying

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#497]
En modifiant le titre d'un ticket le mail est recu mais le sujet est pas top.

![image](https://user-images.githubusercontent.com/79452305/132027302-5e053c17-52df-4c3b-a78f-d6a00100f4cd.png)

**Comment by Patriboom** [comment]
Il semble que les fichiers uploads/blabla.html et uploads/blabla_tit.html soient identiques.
J'y verrai après la question du dashboard / mes billets.

**Comment by Patriboom** [comment]
En attendant, pouvez-vous rééditer votre message et son titre ? 
Le code semble bon.  Peut-être est-ce la trace de versions antérieures qui mêlaient corps et titre.
Les messages que j'ai reçus hier étaient bien intitulés.
Merci.

**Comment by Albatros78** [comment]
Même sujet.

![image](https://user-images.githubusercontent.com/79452305/132032310-e23e7292-d0ee-416b-bf0d-a7cb5ea042d9.png)

**Comment by Albatros78** [comment]
Ce n'est que pour le changement du titre..tous les autres messages ont un sujet correct

**Comment by Albatros78** [comment]
Ici orage... Si je réponds pas rapidement, peut être coupure électrique ... ca arrive....

**Comment by Albatros78** [comment]
Si ma box Internet ne "crame" pas comme la dernière fois !!!

**Comment by Patriboom** [comment]
Bonne chance avec vos machines exposées à l'orage!!!!

Voilà, les corrections sont apportées  ( j'ai inversé l'ordre de travail annoncé ).  Je retournerai aux dashboard et liste de billets perso après le dîner.

**Comment by Albatros78** [comment]
J'ai éteint un Mac... :-)... reste moi sur mon PC win7

**Comment by Albatros78** [comment]
Voila ce que je reçois en changeant le titre du post

![image](https://user-images.githubusercontent.com/79452305/132034416-c5fe3ff7-273c-450e-86f9-1d863f68a897.png)

**Comment by Albatros78** [comment]
et aussi ici un truc étrange

![image](https://user-images.githubusercontent.com/79452305/132035218-de7ad952-0f40-40c8-82be-520644ac4bf6.png)

**Comment by Patriboom** [comment]
Pouvez-vous aller dans l'Administration et éditer vos messages?  Je crains que les titres des messages aient été contaminés par des versions antérieures.  Les éditant, nous nous assurerons que nous travaillons sur de bonnes bases.

Vous pouvez aussi les éditer directement dans le répertoire  uploads/
Le contenu du texte est dans le fichier blabla.html
Le titre du message est dans le fichier blabla_tit.html

**Comment by Patriboom** [comment]
Aussi, avez-vous installé la dernière version de BUGS ? 
Les résultats que vous me montrez ci-haut ressemblent étrangement à ce que vous affichiez antérieurement, comme si aucune modification n'avait été apportée au code.

**Comment by Albatros78** [comment]
J'ai installé la dernière version.
J'ai édité tous les messages en ajoutant un caractère pour être certain du changement
Je recois bien le message modifié en ajoutant un commentaire.

Mais en modifiant le titre du post je reçois toujours cela.

![image](https://user-images.githubusercontent.com/79452305/132038173-d2a86eb8-0675-41ed-91fb-8b46ccce068c.png)

Mais dans la partie Administration j'ai remarqué que je n'ai pas dans la liste déroulante de message pour le changement du titre.... 

![image](https://user-images.githubusercontent.com/79452305/132038327-0c8084dc-b86a-4a4e-ac7b-d5442b629389.png)


C'est pas la source du problème ?

**Comment by Patriboom** [comment]
Le titre de chaque message est défini dans la case supérieure.
![capture_BUGSadmin](https://user-images.githubusercontent.com/19801202/132040008-beacb3d4-6daa-4c83-bf01-9456403ff7ca.jpg)

**Comment by Albatros78** [comment]
Oui mais il n'y a pas d'option pour le changement du titre dans la liste déroulante !

**Comment by Patriboom** [comment]
Euh ....!

tu changes le titre à cet endroit et tu fais "Mettre à jour"

La liste déroulante présente les contextes d'émission, ces valeurs ne sont utilisées nulle part ailleurs.

**Comment by Albatros78** [comment]
Je ne comprend pas 

Le titre est associé à un choix de la liste déroulante non ?

![image](https://user-images.githubusercontent.com/79452305/132043529-7dc91837-6cdf-49d1-bd3c-9497d88db05b.png)

Je n'ai rien dans la liste pour un changement de titre !

**Comment by Patriboom** [comment]
La liste déroulate permet de choisir le "thème"
Le "thème" choisi, le titre est mis à jour, le texte (contenu du courriel) est mis à jour aussi dans la fenêtre de travail.
Lorsque vous cliquez sur le bouton "update", ces valeurs sont gravées sur le disque dur.

Si vous changez le thème, à la faveur de "New comment"

- Vous verrez le contenu du titre changé
- Vous verrez le contenu du message changé

Vous apportez alors vos modifications dans le titre et dans le contenu, puis vous cliquez sur "update" et toutes ces informations, ces formulations sont enregistrées sur le disque.  Lorsque vous soumettrez un nouveau commentaire, les abonnés recevront une message intitulé "A new comment has been added" dans leur boîte courriel.  Le contenu du message qu'ils liront sera celui que vous lisez dans l'éditeur de texte que vous voyez dans ma capture d'écran (où on lit  «Voici la touche loisir ...» )

**Comment by Patriboom** [comment]
Passez une à une toutes les options de la liste déroulante et vous verrez les titres et contenus par défaut.

**Comment by Albatros78** [comment]
Patrick j'ai bien compris..!

Mais je n'ai aucune rubrique de message lorsque je modifie le **TITRE** d'un post

![image](https://user-images.githubusercontent.com/79452305/132045509-a6a343dd-b7f2-43ba-ab63-ba1f7331a599.png)

**Comment by Albatros78** [comment]
si j'ai trouvé je crois 
c'est Issue modified dans la liste déroulante

**Comment by Patriboom** [comment]
Ce devrait être "issue Modified"

**Comment by Albatros78** [comment]
Oui c'est OK

**Comment by Albatros78** [comment]
Non pas complétement

Encore cela qui est étrange pour toujours le changement du titre d'un post

![image](https://user-images.githubusercontent.com/79452305/132046419-652c881c-30f6-479b-966d-43a4f52a0125.png)

**Comment by Albatros78** [comment]
le message xxx123456 devrait être au dessus, ce qui était l'ancien titre avant le changement en xxx1234567

**Comment by Patriboom** [comment]
Le message original inclut la phrase « Le titre précédent était .... » avant l'affichage du vieux nom.
Dans ce que vous montrez ci-haut, cette phrase a été supprimée, le code envoie néanmoins l'ancien nom.

**Comment by Patriboom** [comment]
Il faut simplement corriger la phrase de façon à présenter l'ancien nom du billet.

**Comment by Albatros78** [comment]
Mais cette phrase 

![image](https://user-images.githubusercontent.com/79452305/132047371-d8adb855-77cb-4c26-ae43-ebc3139bfdf1.png)

n'est pas dans mon texte

![image](https://user-images.githubusercontent.com/79452305/132047415-d61e0b1d-5765-4fae-ad98-8f206f46427f.png)

**Comment by Patriboom** [comment]
Il faut que vous ajoutiez une telle phrase afin de rendre intelligible la présence de l'information.  Cette information sera affichée avec ou sans phrase.  Mieux vaut alors composer un petit bout pour que le récepteur comprenne.

**Comment by Patriboom** [comment]
Par exemple:
« To help you remind the subject, the previous title as »

**Comment by Albatros78** [comment]
Oui tu as raison c'est super comme cela.

![image](https://user-images.githubusercontent.com/79452305/132051181-4ba1e633-a822-4cc6-851e-09c35b372efb.png)

Juste dans le sujet il faudrait l'ancien titre !

**Comment by Patriboom** [comment]
Ça demande du travail pour ne gérer qu'une petite exception; je passe mon tour.
Cependant, l'ancien titre sera mis en italique dans le message et ne sera plus précédé d'un retour de chariot.

**Comment by Albatros78** [comment]
L'ancien titre n'est pas en italique avec la version de ce matin !

**Comment by Patriboom** [comment]
Il le sera lors du prochain téléchargement.

**Comment by Albatros78** [comment]
OK le message est bien en italique

![image](https://user-images.githubusercontent.com/79452305/132100980-960ec666-bdf0-4e43-9bc8-d34506c1c856.png)

Mais le lien n'existe plus !

![image](https://user-images.githubusercontent.com/79452305/132100993-2973dbc0-24aa-424e-bb4e-ba989dab9ec0.png)



Même chose pour le lien sur un nouveau commentaire

![image](https://user-images.githubusercontent.com/79452305/132101035-9205f156-111f-4b80-8332-e0eb494e1bd9.png)


Lien vide 

![image](https://user-images.githubusercontent.com/79452305/132101047-afdccc48-e795-436d-b11c-a4ded248d6af.png)

**Comment by Patriboom** [comment]
J'y suis peut-être allé un peu fort sur la dose .. un code révisé est disponible.

**Comment by Albatros78** [comment]
Toujours aucun lien dans les emails dans les 3 messages cités ci dessus.
