### ISSUE TITLE
Testing message with double header, footer

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#499]
Ici le message recu en cliquant sur le bouton test de l'envoi du message

![image](https://user-images.githubusercontent.com/79452305/132034945-9f212e02-1511-498a-bb2e-038bc1e2dfaa.png)

Surement suite à la correction des autres messages qui n'avaient pas le Hello et Bye

**Comment by Patriboom** [comment]
Il doit y avoir une en-tête prédéfinie (et commune à tous les messages) dans la section « Mise en forme de vos courriels »
Cette salutation s'applique à TOUS les messages.

Si vous répétez de telles lignes dans chacun de vos messages, et bien .... c'est doublé!

Il faut garder en tête que la section « Mise en forme ... » s'applique à TOUS les  courriels émis
La section « Contenu des courriels automatiques » pour sa part ne doit contenir que le spécifique.

![capture_BUGSadmin2](https://user-images.githubusercontent.com/19801202/132050358-f7869e0b-8a7f-4f79-8698-a8c44a09d52a.jpg)

**Comment by Albatros78** [comment]
C'est bien ma configuration !!! . Ce problème est survenu après la correction ou justement l'entête et la fin n'était pas ajouté dans les messages. 
Et avant ce problème le message de test fonctionnait bien.
Après correction et ajout de l'entête et du bas dans les emails, le message de test a des doublons.

**Comment by Patriboom** [comment]
Ok, je corrige le doublon du message de test, mais .... il faut aller vous coucher ... hihi ;)

**Comment by Albatros78** [comment]
OK , plus de doublon sur le message de test. et les autres messages sont bien formattés aussi.
Good job !
