### ISSUE TITLE
URL link inside email source not good !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#502]
Il faut regarder dans la génération des emails, mais le lien dans la source est souvent pas bon

Ici par exemple
![image](https://user-images.githubusercontent.com/79452305/132045018-15933f79-9fd2-4a87-8aa8-0c50e16536d5.png)

Dans la source de l'email j'ai 

<p><p>1 - A ticket you are following has received a new comment. This ticket is titled « <a href="**http://localhost/bugtracker/project/1/issue**">First Beta version of Form Manager1234</a> »</p>

c'est faux ...

tu peux regarder dans les autres messages envoyés, car cela n'est uniquement dans un type de message

**Comment by Patriboom** [comment]
Je ne sais pas ce qui est faux, ce qui est vrai dans votre exemple.
Vous pointez vers « First Beta version of Form Manager 1234 »
Quelle devrait être cette valeur ? 

Quel est son lien ? 
Quel devrait être le lien ?

**Comment by Albatros78** [comment]
Erreur de ma part. fatigue .... 
On ferme le ticket.

**Comment by Albatros78** [comment]
Non je n'avais pas la berlu !!!

j'ai ajouté un fichier à un ticket et j'ai l'email avec le lien

![image](https://user-images.githubusercontent.com/79452305/132098469-0463f67e-f91a-467a-80cd-387d175f5b1e.png)

Dans le source de mon email j'ai

Content-Type: text/html; charset="UTF-8"

<p><p>Hello<strong>&nbsp;</strong><strong>Manager</strong>,</p>
</p>
<p><p>1 - File has been attached to the ticket « <a href="**http://localhost/bugtracker/project/5/issue/31/upload?Nom=FRX.gif&ext=gif&fileName=FRX.gif&icone=/bugtracker/project/5/issue/31uploads**">rfzref</a> »</p>

<p>&nbsp;</p>
</p>
<p><p>Best Regards<br />
BugTracker Team<br />

et donc le lien ne fonctionne pas car il n'est pas bon...

![image](https://user-images.githubusercontent.com/79452305/132098487-40753e2f-defd-4fc1-a9b8-b6cc11a664c6.png)


Donc il faut revoir cela dans les messages... certains ne doivent pas fonctionner.

**Comment by Patriboom** [comment]
Merci du retour.
Est-ce que l'adresse suivante fonctionnerait:
http://localhost/bugtracker/project/5/issue/31/  car c'est l'adresse qui conviendrait ici.  Tout ce qui dépasse de cela est superflu, je pourrais gérer cela.

**Comment by Albatros78** [comment]
Oui c'est bien cela qu'il faut mettre dans l'email

**Comment by Albatros78** [comment]
A la **création d'un nouveau ticket ** le lien dans le source de l'email est:

http://localhost/bugtracker/project/5/issue

Il manque le N° du post crée dans ce lien, soit

http://localhost/bugtracker/project/5/issue/52

**Comment by Patriboom** [comment]
N'est-ce pas dans votre message le problème ? 
Il faudrait que vous mettiez la balise {issue} plutôt que la balise {project}
Dites-moi si je me trompe.

> A la **création d'un nouveau ticket ** le lien dans le source de l'email est:
> 
> http://localhost/bugtracker/project/5/issue
> 
> Il manque le N° du post crée dans ce lien, soit
> 
> http://localhost/bugtracker/project/5/issue/52
> 
> Meme problème avec l'**ajout d'un commentaire** sur un ticket existant. Il manque le numéro du ticket dans l'URL
> 
> Meme problème avec l'**création d'un ticket** . Il manque le numéro du ticket dans l'URL

**Comment by Albatros78** [comment]
Je ne reçois plus d'email !!! instable... J'ai rebooté mon PC... 
plus d'emails... le test fonctionne ... étrange

**Comment by Albatros78** [comment]
Pour un nouveau commentaire j'ai cela...
![image](https://user-images.githubusercontent.com/79452305/132099713-0f68e5da-79e7-41c0-8eec-b7f51130401c.png)

Pour justement indiquer directement le lien du ticket... Si on met {projet} on ira vers le projet et pas le ticket lui même

**Comment by Patriboom** [comment]
Merci du retour rapide.

Pensez-vous que l'instabilité des courriels était liée au gestionnaire de tickets ou est-ce un hasard ? 

Je mettrai en ligne une dernière mise à jour dans quelques minutes.  Ce sera tout pour aujourd'hui.
Je reviendrai sur cette question des liens lundi ou durant la semaine prochaine.

**Comment by Albatros78** [comment]
On oublie l'instabilité... je crois que cela vient de mes configs utilsiateurs et suivis des tickets, projets.

**Comment by Patriboom** [comment]
Plus de détails dans https://github.com/pixeline/bugs/issues/526  .. .nous ne garderons donc que le billet https://github.com/pixeline/bugs/issues/526
