### ISSUE TITLE
Error when opening project from project menu

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#504]
Ici j'ai 2 projets qui provoquent une erreur à l'ouverture par le menu projet

![image](https://user-images.githubusercontent.com/79452305/132050747-a8228760-de90-4611-be6a-d690a71f0d01.png)

Erreur

Unhandled Exception
Message:
Trying to access array offset on value of type null
Location:
E:\xampp\htdocs\bugtracker\app\application\models\project.php on line 193
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Trying to acces...', 'E:\\xampp\\htdocs...', 193)
#1 E:\xampp\htdocs\bugtracker\app\application\models\project.php(193): Laravel\{closure}(8, 'Trying to acces...', 'E:\\xampp\\htdocs...', 193, Array)
#2 E:\xampp\htdocs\bugtracker\app\application\controllers\project.php(25): Project->activity(10)
#3 [internal function]: Project_Controller->get_index('4')
#4 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#5 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('index', Array)
#6 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#7 E:\xampp\htdocs\bugtracker\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project@index', Array)
#8 E:\xampp\htdocs\bugtracker\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#9 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#10 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#11 {main}

**Comment by Patriboom** [comment]
Avez-vous les mêmes erreurs lorsque vous tentez d'accéder aux-dits en cliquant sur le menu de gauche ?

**Comment by Albatros78** [comment]
Non aucune erreur avec le menu à gauche. Juste avec le menu 'Projects'

**Comment by Patriboom** [comment]
Merci, je jeterai un oeil là-dessus demain.

**Comment by Albatros78** [comment]
Non plus d'erreur !
Mais comme je ne peux pas créer un second projet, je vais attendre pour tester lorsque plusieurs projets seront OK

On laisse ouvert le ticket pour mémo

**Comment by Patriboom** [comment]
Est-ce que le billet https://github.com/pixeline/bugs/issues/525 a résolu ce même problème ?

**Comment by Patriboom** [comment]
Pour  ma part, avec votre BD, il  n'y pas de souci de ce côté.

**Comment by Albatros78** [comment]
OK.... Plus d'erreur avec la version qui règle aussi le #525
