### ISSUE TITLE
Popup displayed when I add a tag into a ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#506]
Lorsque j'ajoute un tag à un ticket j'ai le popup suivant:

![image](https://user-images.githubusercontent.com/79452305/132068061-1e11e9d0-1a43-43b8-b034-59e2fc554d7b.png)

**Comment by Patriboom** [comment]
Oups, ça c'est du code de débogage qui est resté à la traîne.
J'enlève

**Comment by Patriboom** [comment]
Il appert que les étiquettes n'étaitent plus affichées au gré de leur ajout dans la liste des événement d'un billet. C'est l'envoi de courriel qui bloquait cela.
Tandis que je réactive l'affichage des étiquettes, je dois temporairement désactiver l'émission de courriel lors de cet événement.

Vous deviez en avoir plusieurs!!!!  
hihihi
Merci de votre patience.

**Comment by Albatros78** [comment]
Ok c'est bon maintenant il n'y a plus de popup
Mais je ne recois plus de messages sur ajout /suppression de tags dans un post !!!

**Comment by Patriboom** [comment]
Je sais, pour la perte des courriels lors d'ajout/suppression d'étiquette.  C'est à cela que je m'affairais hier, mais ça ne fonctionne pas encore.

**Comment by Albatros78** [comment]
Avec la v1.85z que j'ai téléchargé le mail est reçu pour l'ajout d'un fichier fonctionne !
