### ISSUE TITLE
Find a way to display all tags available to add/edit a ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#509]
Lorsque l'on veut ajouter un tag à la création ou à l'édition d'un ticket existant il faut trouver un moyen de faire apparaître la liste de tous les tags disponibles

Par exemple ici

![image](https://user-images.githubusercontent.com/79452305/132086022-0927f85b-45c4-4898-9dbe-e368b5ed3160.png)

Nous devons tapez une à une les lettre de l'alphabet pour avoir une liste restrictive des tags comportant cette lettre (nous n'avons pas toute la liste dans ce cas) . Mais il n'y a pas moyen d'avoir la liste complète . Peut être en mettant * ou ? dans le champ et la liste s'affiche pour choisir ! Pourquoi pas ?
Ce n'est pas simple et convivial à utiliser en tapant lettre par lettre pour trouver les tags.

De plus: imagine que l'administrateur ajoute 2 ou 5 tags.... Comment un autre utilisateur peut le voir/savoir rapidement....???

Je propose soit une liste déroulante ou alors un peu ce qui se fait en ce moment, afficher tous les boutons pour choisir... comme ci dessous; mais cela risque de polluer l'affichage de l'interface.

![image](https://user-images.githubusercontent.com/79452305/132086110-11907567-5b44-4596-9e39-d4cc813aa9fb.png)

et en cliquant sur le bouton il se met dans le champ comme maintenant.

Je pense que cette feature est importante ! comme pour le #412

**Comment by Patriboom** [comment]
L'idée de l'étoile est bonne, j'y penserai.
Ce sujet est abordé dans un autre billet:  https://github.com/pixeline/bugs/issues/412
Nous continuerons avec ce billet qui porte l'étiquette « On hold »

**Comment by Patriboom** [comment]
L'étiquette « On hold » de https://github.com/pixeline/bugs/issues/412 a été retirée.
La solution est toute simple:  taper « * » ou « % »  et la liste complète apparaîtra.
