### ISSUE TITLE
SMTP Error when a new ticket is created

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#516]
En créant un nouveau ticket, le mail est bien envoyé aux utilisateurs qui suivent le projet.
Mais je reçois cette erreur !!!

Unhandled Exception
Message:
mail(): SMTP server response: 503 Error: need RCPT command
Location:
E:\xampp\htdocs\bugtracker\app\application\controllers\ajax\SendMail.php on line 114
Stack Trace:
#0 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(40): Laravel\Error::native(2, 'mail(): SMTP se...', 'E:\\xampp\\htdocs...', 114)
#1 [internal function]: Laravel\{closure}(2, 'mail(): SMTP se...', 'E:\\xampp\\htdocs...', 114, Array)
#2 E:\xampp\htdocs\bugtracker\app\application\controllers\ajax\SendMail.php(114): mail('', 'A new ticket ha...', '1 - A new ticke...', 'From: "AFS BugT...')
#3 E:\xampp\htdocs\bugtracker\app\application\controllers\project\issue.php(473): include_once('E:\\xampp\\htdocs...')
#4 E:\xampp\htdocs\bugtracker\app\application\controllers\project\issue.php(46): Project_Issue_Controller->Courriel('Project', true, 1, 61, 1, Array, Array)
#5 [internal function]: Project_Issue_Controller->post_new('1')
#6 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#7 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('new', Array)
#8 E:\xampp\htdocs\bugtracker\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#9 E:\xampp\htdocs\bugtracker\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#10 E:\xampp\htdocs\bugtracker\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#11 E:\xampp\htdocs\bugtracker\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#12 E:\xampp\htdocs\bugtracker\index.php(19): require('E:\\xampp\\htdocs...')
#13 {main}

En faisant un retour arrière on revient dans l'interface, ticket crée

**Comment by Patriboom** [comment]
Ce peut être lié au billet https://github.com/pixeline/bugs/issues/497  , mais j'ai des doutes.  Il est ici question de configuration SMTP, peut-être est-ce plutôt lié à vos lenteurs décrites dans un autre billet.

**Comment by Albatros78** [comment]
Pas certains, car tous les autres emails sont OK.
On va patienter un peu sur ce sujet... a regarder doucement.

**Comment by Albatros78** [comment]
Même erreur avec la dernière version !

**Comment by Albatros78** [comment]
Mais je n'ai pas cette erreur sur un autre projet.... je cherche ....

**Comment by Albatros78** [comment]
Etrange..... Je me demande si il ne faut pas que je reparte à zero base vide.... Peu têtre trop de choses se sont mélanagées dans les configurations depuis tous nos tests.

Si je vide la base complètement, en résinstallant le dernier package  il va récréer la base   ?

**Comment by Albatros78** [comment]
Bon ca marche pas... car ton zip n'est pas complet je pense.... 
Il faut que tu me crée un package complet pour une installation from scratch (table tag, activity, follower ...Etc)
tout bien propre quoi pour repartir de zéro.

**Comment by Patriboom** [comment]
Il faut simplement renommer ou effacer le fichier  config.app.php

**Comment by Albatros78** [comment]
Non pas juste cela ....

J'ai du recopie config-setup.php dans install
et Installation terminée.

Mais après le login en allant dans la page administration, erreur car la table tags n'existe pas !

Unhandled Exception
Message:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'afs_bugtracker.tags' doesn't exist

SQL: SELECT COUNT(*) AS `aggregate` FROM `tags`

Bindings: array (
)
Location:
E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php on line 263
Stack Trace:
#0 E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php(183): Laravel\Database\Connection->execute('SELECT COUNT(*)...', Array)
#1 E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php(166): Laravel\Database\Connection->query('SELECT COUNT(*)...', Array)
#2 E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php(144): Laravel\Database\Connection->first('SELECT COUNT(*)...', Array)
#3 E:\xampp\htdocs\bugtracker2\app\laravel\database\query.php(741): Laravel\Database\Connection->only('SELECT COUNT(*)...', Array)
#4 E:\xampp\htdocs\bugtracker2\app\laravel\database\query.php(934): Laravel\Database\Query->aggregate('COUNT', Array)
#5 [internal function]: Laravel\Database\Query->__call('count', Array)
#6 E:\xampp\htdocs\bugtracker2\app\laravel\database\eloquent\query.php(267): call_user_func_array(Array, Array)
#7 [internal function]: Laravel\Database\Eloquent\Query->__call('count', Array)
#8 E:\xampp\htdocs\bugtracker2\app\laravel\database\eloquent\model.php(789): call_user_func_array(Array, Array)
#9 [internal function]: Laravel\Database\Eloquent\Model->__call('count', Array)
#10 E:\xampp\htdocs\bugtracker2\app\laravel\database\eloquent\model.php(804): call_user_func_array(Array, Array)
#11 E:\xampp\htdocs\bugtracker2\app\application\controllers\administration.php(27): Laravel\Database\Eloquent\Model::__callStatic('count', Array)
#12 [internal function]: Administration_Controller->get_index()
#13 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#14 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('index', Array)
#15 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#16 E:\xampp\htdocs\bugtracker2\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('administration@...', Array)
#17 E:\xampp\htdocs\bugtracker2\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#18 E:\xampp\htdocs\bugtracker2\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#19 E:\xampp\htdocs\bugtracker2\index.php(19): require('E:\\xampp\\htdocs...')
#20 {main}

**Comment by Albatros78** [comment]
et aussi table update_history, following.... manquantes dans la base

Voila ce qui est crée durant l'installation:

![image](https://user-images.githubusercontent.com/79452305/132110090-d20dd1e8-3b60-425b-b493-12d3225f94b8.png)


Bon un bon zip prêt serait mieux que de faire manuellement.

**Comment by Patriboom** [comment]
Pourtant oui, les tables citées existent dans le fichier de création de la structure ( bugs/install/MySQL_DB_Schema.sql )
aux lignes 157, 215 et 226
Le contenu par défaut de la table 'tags' et défini aux lignes 299 et suivantes.  Les tables 'following' et 'update_history' sont vides par défaut.
Il faut vraiment prendre la dernière version de chacun des fichiers.

Vous pouvez tirer les parties de texte qui vous concernent depuis le fichier ci-haut mentionné vers un fichier texte de votre choix.


`
#--#Create tags table
CREATE TABLE `tags` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tag` varchar(255) NOT NULL,
  `bgcolor` varchar(50) DEFAULT '#330033',
  `ftcolor` varchar(50) DEFAULT '#FFFFFF',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tag` (`tag`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE 'utf8_general_ci';
#--

#--Create the update history system table
CREATE TABLE `update_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Footprint` varchar(25) DEFAULT NULL,
  `Description` varchar(100) DEFAULT NULL,
  `DteRelease` datetime DEFAULT NULL,
  `DteInstall` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
#--

#--Create following table - this permits to user to receive email on ticket's activity
CREATE TABLE `following` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `project_id` int(11) NOT NULL,
  `issue_id` int(11) NOT NULL,
  `project` tinyint(2) NOT NULL DEFAULT 0,
  `attached` tinyint(2) NOT NULL DEFAULT 1,
  `tags` tinyint(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
#--

#--#Create default tags
INSERT INTO `tags` (`id`, `tag`, `bgcolor`, `created_at`, `updated_at`) VALUES
(1,	'status:open',		'#c43c35',		'#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(2,	'status:closed',	'#46A546',		'#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(3,	'type:feature',	'#62cffc',		'#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(4,	'type:bug',			'#f89406',		'#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(6,	'resolution:won`t fix','#812323','#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(7,	'resolution:fixed',	'#048383',	'#FFFFFF',	'2013-11-30 11:23:01',	'2013-11-30 11:23:01'),
(8,	'status:testing',	'#FCC307',		'#FFFFFF',	'2013-11-30 11:23:01',	'2016-11-30 23:11:01'),
(9,	'status:inProgress','#FF6600',	'#FFFFFF',	'2016-11-10 23:12:01',	'2016-11-10 23:12:01')
#--
`

**Comment by Albatros78** [comment]
Bon c'est pas tip top de faire à la main...
OK j'ai crée les 3 tables.

Ma table tags est donc:

![image](https://user-images.githubusercontent.com/79452305/132120542-7a0e8ee3-e2bc-4bf3-82f4-a4c6e8d85572.png)



Mais impossible de remplir la table tags. J'ai modifié l'insert en ajoutant ftcolor qui n'existe pas dans le fichier bugs/install/MySQL_DB_Schema.sql

Cela est donc:

INSERT INTO tags (id, tag, bgcolor, ftcolor, created_at, updated_at) VALUES
(1, 'status:open', '#c43c35', '#FFFFFF','#000000', '2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(2, 'status:closed', '#46A546', '#FFFFFF','#000000', '2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(3, 'type:feature', '#62cffc', '#FFFFFF', '#000000','2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(4, 'type:bug', '#f89406', '#FFFFFF', '#000000','2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(6, 'resolution:won`t fix','#812323','#FFFFFF', '#000000','2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(7, 'resolution:fixed', '#48383', '#FFFFFF', '#000000','2013-11-30 11:23:01', '2013-11-30 11:23:01'),
(8, 'status:testing', '#FCC307', '#FFFFFF', '#000000','2013-11-30 11:23:01', '2016-11-30 23:11:01'),
(9, 'status:inProgress','#FF6600', '#FFFFFF', '#000000','2016-11-10 23:12:01', '2016-11-10 23:12:01');

Mais j'ai l'erreur suivante comme si il manquait un champ !!!

![image](https://user-images.githubusercontent.com/79452305/132120527-e788cb40-8b53-440e-b274-51e4adf27b05.png)


J'ai pas trouvé pourquoi !

**Comment by Albatros78** [comment]
OK j'ai fait à la main... Grrrrrr

**Comment by Albatros78** [comment]
Ok 4 utilisateurs ajoutés, je crée un projet.

Boum

nhandled Exception
Message:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_assignee' in 'field list'

SQL: INSERT INTO `projects` (`name`, `default_assignee`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?)

Bindings: array (
  0 => 'Projet 1',
  1 => '1',
  2 => '2021-09-05 10:38:02',
  3 => '2021-09-05 10:38:02',
)
Location:
E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php on line 263
Stack Trace:
#0 E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php(183): Laravel\Database\Connection->execute('INSERT INTO `pr...', Array)
#1 E:\xampp\htdocs\bugtracker2\app\laravel\database\query.php(818): Laravel\Database\Connection->query('INSERT INTO `pr...', Array)
#2 [internal function]: Laravel\Database\Query->insert_get_id(Array, 'id')
#3 E:\xampp\htdocs\bugtracker2\app\laravel\database\eloquent\query.php(267): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\bugtracker2\app\laravel\database\eloquent\model.php(402): Laravel\Database\Eloquent\Query->__call('insert_get_id', Array)
#5 E:\xampp\htdocs\bugtracker2\app\application\models\project.php(283): Laravel\Database\Eloquent\Model->save()
#6 E:\xampp\htdocs\bugtracker2\app\application\controllers\projects.php(66): Project::create_project(Array)
#7 [internal function]: Projects_Controller->post_new()
#8 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('new', Array)
#10 E:\xampp\htdocs\bugtracker2\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#11 E:\xampp\htdocs\bugtracker2\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('projects@new', Array)
#12 E:\xampp\htdocs\bugtracker2\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#13 E:\xampp\htdocs\bugtracker2\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#14 E:\xampp\htdocs\bugtracker2\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

Je crois qu'il faut revoir la création de la base avec un fichier .SQL OK

Merci

**Comment by Patriboom** [comment]
J'ai trouvé quatre erreurs grâce à ton test.  Merci.
Des mises à jour seront disponibles plus tard.

**Comment by Patriboom** [comment]
Je n'ai pas compris ce qui n'était pas correct dans le code.  Mais en copiant/collant des segments fonctionnels, les erreurs ont été corrigées.  Les tables tags, update_history et following seront dorénavant bien créées et garnies.
Le zip d'installation est disponible et fonctionnel.

**Comment by Albatros78** [comment]
Je viens de télécharger et réinstaller....
Via le menu administration

Unhandled Exception
Message:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'afs_bugtracker.tags' doesn't exist

SQL: SELECT COUNT(*) AS `aggregate` FROM `tags`

Bindings: array (
)
Location:
E:\xampp\htdocs\bugtracker2\app\laravel\database\connection.php on line 263

et pourtant elle est bien dans le fichier .sql

![image](https://user-images.githubusercontent.com/79452305/132141636-aaf6cc87-c827-49ce-836a-84242c07cceb.png)

Toujours la même chose
![image](https://user-images.githubusercontent.com/79452305/132141646-9673f642-9719-4bff-b60c-0d4a3e4148a6.png)

**Comment by Albatros78** [comment]
Bon j'ai réinstallé dans un nouveau répertoire vide...
Tout semble OK.

![image](https://user-images.githubusercontent.com/79452305/132141729-26dd6807-40f1-46fe-9339-982ba6bde6b0.png)


Sauf que la tables tags est vide ! Pas grave je fais la faire à la main pour continuer

**Comment by Patriboom** [comment]
Concernant le billet disant que la table tags était vide:  vous avez raison.  Encore merci.

C'est corrigé et testé.

**Comment by Patriboom** [comment]
La suite dans le billet https://github.com/pixeline/bugs/issues/520

Veuillez fermer ce billet lorsqu'opportun; merci.

**Comment by Albatros78** [comment]
PK je ferme... En plus plusieurs sujets dans le même ticket. On s'y perd...
Je vais réouvrir de nouveaux tickets pour être plus clair et limpide.
