### ISSUE TITLE
No email on new / suppressed tags

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#520]
Reinstallation complète from scratch

Ici un point sur le problème de la réception des emails avec la dernière version 06/09/2021 00:014

**Ajout / Suppression de tags**  ==> AUCUN email

**Comment by Patriboom** [comment]
Oui, nous en avons parlé dans un autre ticket.
Je fermerai l'autre ticket et ne garderai que celui-ci, car je crois que c'était le dernier élément de l'autre ticket.
Je ne sais pas encore pour quelle raison, il a fallu choisir entre l'affichage instantané de l'ajout/retrait de l'étiquette et l'envoi de courriel.  
Je verrai prochainement à faire en sorte que les deux fonctionnent, de même que l'affichage de l'historique des ajouts/retraits d'étiquettes.

**Comment by Patriboom** [comment]
Voilà, la fonction d'envoi de courriels est rétablie.
Le code est disponible.

**Comment by Albatros78** [comment]
L'email est recu pour l'ajout et la suppression du tag
Mais le contenu du lien URL est pas bon.
