### ISSUE TITLE
Pourcentage of work not the same into admin and other role

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#522]
J'ai crée un nouveau ticket

Le pourcentage de travail est de 1%

![image](https://user-images.githubusercontent.com/79452305/132143319-483b179b-ffff-4fea-9785-9e44af778837.png)

En regardant ce même ticket avec un autre utilisateur (manager ou developer) le pourcentage est de 10%. 
Je crois que ce pourcentage ne bouge pas !

![image](https://user-images.githubusercontent.com/79452305/132143345-862016ca-2909-465b-a91b-4cce9fe202d3.png)

**Comment by Patriboom** [comment]
La règle originale devait faire en sorte que le pourcentage monte à 10% au moment de la première intervention (premier commentaire), montrant par là que le tickets a déjà connun une forme de _prise en main_

J'y reviendrai après travail sur les bogues révélés aujourd'hui.

**Comment by Patriboom** [comment]
À chaque fois qu'un commentaire est ajouté à un billet, ça ajoute 1% du travail total.
On peut aussi changer le poucentage du travail accompli en agissant sur la valeur affichée au bas de la page d'un billet lorsqu'on a les droits suffisants.
![image](https://user-images.githubusercontent.com/19801202/136995453-8abc1e72-aab2-48dd-8c63-4f9d36c68f6e.png)


Il semble y avoir une erreur ici, car l'usager affiché dans l'exemple a les droits suffisants et devrait avoir accès à cette modification.  J'y retourcherai.  Néanmoins, j'espère que ça répond à votre question.

En complément, c'est le pourcentage du travail accompli qui fait varier la barre colorée en tête d'un billet
![image](https://user-images.githubusercontent.com/19801202/136995758-2189f7ce-4b8f-4ea3-9c05-39563be2117c.png)


Vous aurez prochainement un retour sur la correction à faire (en programmation) au bas d'un billet, correction qui vous redonnera le loisir de modifier le pourcentage du travail accompli.

**Comment by Patriboom** [comment]
Aucune modification à faire.
Il faut, cependant, rencontrer deux conditions pour que la modification du pourcentage accompli soit disponible

1. Avoir le statut d'auteur, de modificateur ou d'administrateur
2. Être en charge du billet  ( « Attribué à ....»  vous ) 

Exemple: 
![image](https://user-images.githubusercontent.com/19801202/136996743-c3ac5e2e-deeb-4770-9d55-465acd73d01d.png)
