### ISSUE TITLE
Priority color not registered

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#523]
Ici par defaut il y a une erreur car 2 priorités ont la même couleur

![image](https://user-images.githubusercontent.com/79452305/132143762-0c375651-fba4-4eac-b119-47980e3ba7d6.png)

En cliquant sur Update la couleur semble changer
![image](https://user-images.githubusercontent.com/79452305/132143783-22667164-5b74-4574-a7a7-1bad5f4455cd.png)

Mais en rafraichissant la page la couleur n'est pas enregistrée ou relue ! et donc les tickets ont tous le même point de couleur

![image](https://user-images.githubusercontent.com/79452305/132143803-39aafec6-8350-41d2-b9ef-1a99ce44269f.png)

**Comment by Patriboom** [comment]
Ce détails attendra, vous avez révélé des erreurs plus importantes.

**Comment by Patriboom** [comment]
Correction apportée, fichiers disponibles.

**Comment by Patriboom** [comment]
Non pas encore correct.

**Comment by Patriboom** [comment]
Cette fois oui.

**Comment by Patriboom** [comment]
Après ces corrections, je prendrai congé du projet quelques semaines.
J'en ferai d'ailleurs une nouvelle édition ( release 1.8 rev. 5aa ) pour le public.

Merci encore de votre aide - albatros78

**Comment by Albatros78** [comment]
Oui cela fonctionne bien.
Affaire réglée...

Si tu peux régler juste le ticket #543 avant absence cela serait cool. !

Je vais pouvoir ainsi commencer à le mettre en route pour moi... Les problèmes restants ne sont pas bloquant à l'utilisation. On verra à ton retour pour essayer de clôturer tout cela... Nous étions partis pour quelques modifications et cela dure depuis quelques mois !!!


Merci encore en tout cas pour ton support & aide.
