### ISSUE TITLE
Error when I create a 2nd project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#525]
Ce matin en voulant crée un second projet, erreur !!!!!

![image](https://user-images.githubusercontent.com/79452305/132181730-b748c28f-16b4-4da4-b7c3-7efdd8687db9.png)

Le projet semble crée tout de même !

**Comment by Albatros78** [comment]
Je dois m'absenter dans 30 mn....
Voici ma base pour tester  !!!!

[afs_bugtracker Projet 1 - 2.zip](https://github.com/pixeline/bugs/files/7116850/afs_bugtracker.Projet.1.-.2.zip)

Login :
axel@afsoftware.fr
password

Mais erreur en créant un projet 2

**Comment by Patriboom** [comment]
Merci encore.
Votre base de données m'a permis d'identifier les problèmes.

C'est réglé: vous pouvez ajouter un projet, en supprimer un.

**Comment by Albatros78** [comment]
Je viens de télécharger la version.
La création de x projets semble être OK désormais

Merci pour le travail !
