### ISSUE TITLE
Resume: All URL's info into emails received

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#526]
Ici je reprend le détail des emails recus et du contenu pour rester clair.

**Projet renommé**
_____________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132212647-2aa14442-108a-4f01-bf41-12e0962f8215.png)

Il faudrait ici mettre aussi l'ancien nom du projet en italique

Le lien vers le projet n'est pas bon.
![image](https://user-images.githubusercontent.com/79452305/132182705-a681bad3-e416-468a-b0ac-f43382fe6167.png)

**Nouveau ticket**
_____________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132183037-c311af19-fdd5-46bc-8404-65019e6e9aaa.png)

Le lien vers le projet n'est pas bon.
![image](https://user-images.githubusercontent.com/79452305/132183096-db71559d-09c1-4705-ad84-a0d3aa4480fc.png)

**Ticket renommé**

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132183687-872ff466-74da-4f86-809f-60857f26c9f6.png)

Le lien vers le projet n'est pas bon.
![image](https://user-images.githubusercontent.com/79452305/132183743-8d7b6e8c-3859-44e8-a111-5eb3a18083fe.png)

**Ticket commenté**
______________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132183928-4cbd1fe8-e42d-46e5-9e55-6855f98ffd1e.png)

Le lien vers le projet n'est pas bon.
![image](https://user-images.githubusercontent.com/79452305/132183985-4337c495-17b2-4115-8a64-a816a1836d9b.png)

**Fichier attaché**
___________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132184209-3ca4e143-fa14-4f35-964e-6895a5cccd5a.png)

Le lien est **OK** !

**Fermeture du ticket**
________________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132184639-5ed24320-4e34-4892-a1e4-17eeb97fe94d.png)

Le lien est **OK** !

**Réouverture du ticket**
___________________________

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132184927-5c7fd796-e030-4ab6-9c05-ad50d1fd7b15.png)

Le lien est **OK** !

Bon courage !

**Comment by Albatros78** [comment]
Ajout / suppression de tags

L'email est:
![image](https://user-images.githubusercontent.com/79452305/132235103-0db5e577-b0c3-4601-950b-67823b24fbbf.png)

Le lien n'est pas bon pour les 2 cas:
![image](https://user-images.githubusercontent.com/79452305/132235202-6acc1ddc-261f-425e-a9d8-47c22757f11b.png)

**Comment by Patriboom** [comment]
Le présent billet étant mieux détaillé que https://github.com/pixeline/bugs/issues/502, nous fermerons https://github.com/pixeline/bugs/issues/502 et ne garderons que celui-ci.

**Comment by Patriboom** [comment]
Ce me semble bon, maintenant.

**Comment by Albatros78** [comment]
Je ne mets ici que les emails et URL erronés et pas ceux qui sont maintenant OK


Projet renommé
------------------
Le lien n'est pas bon:
![image](https://user-images.githubusercontent.com/79452305/132319919-2d90e53e-8ad4-4104-9842-c3a2611a60f8.png)



Ticket renommé
------------------
Le lien est celui ci dans l'email
![image](https://user-images.githubusercontent.com/79452305/132320572-64a6771c-76f8-4469-ab41-620eda44e1d4.png)

Mais celui ci serait mieux non sans le mode edit ?:
http://localhost/bugtracker3/project/1/issue/2


Fichier attaché
----------------
Le lien est celui ci dans l'email
![image](https://user-images.githubusercontent.com/79452305/132321077-697cee0d-1387-4173-9c99-16e9faaacec9.png)


On peut faire plus court je crois :-)
http://localhost/bugtracker3/project/1/issue/2




Fermeture du ticket
---------------------

![image](https://user-images.githubusercontent.com/79452305/132321832-0c5724c5-277b-4105-99ce-023b9ef9e518.png)

Je n'ai pas de messages personnalisable pour ce message !!!
![image](https://user-images.githubusercontent.com/79452305/132321921-9e74b63a-2e8e-4295-b8a7-f43ca9e28961.png)

La phrase du bas n'est pas complète

Le lien est OK



Réouverture du ticket
-----------------------

![image](https://user-images.githubusercontent.com/79452305/132322261-5c5039bb-b2d5-4af4-b19e-7d06f89eb887.png)

Je n'ai pas de messages personnalisable pour ce message !!!
![image](https://user-images.githubusercontent.com/79452305/132321921-9e74b63a-2e8e-4295-b8a7-f43ca9e28961.png)

La phrase du bas n'est pas complète

Le lien est
![image](https://user-images.githubusercontent.com/79452305/132322369-a701401e-4b05-4cea-9377-42d7fc1db276.png)

peut être que celui ci est suffisant
http://localhost/bugtracker3/project/1/issue/2


Voila pour le moment ceux qu'ils restent à corriger

**Comment by Patriboom** [comment]
Une toute nouvelle méthode a été installée.

Pouvez-vous éditer votre fichier  config.app.php et donner l'information complète au champ 'url'
Dans les prochaines versions de l'installation, cette information sera requise.

La ligne doit ressembler à (pour un serveur local)

`
'url' => 'http://127.0.0.1/MesSites/Developpement/TicketsTest/',
`

**Comment by Albatros78** [comment]
OK je fonce télécharger...

en localhost aussi cela marche ?

moi j'ai mis:
http://localhost/bugtracker3

**Comment by Albatros78** [comment]
Plus de lien !!!

![image](https://user-images.githubusercontent.com/79452305/132347958-25279268-00f5-4b73-9302-26f3982f2df6.png)

![image](https://user-images.githubusercontent.com/79452305/132348000-6f40943b-d8e3-4082-b004-7975f9359fbf.png)

**Comment by Patriboom** [comment]
> OK je fonce télécharger...
> 
> en localhost aussi cela marche ?
> 
> moi j'ai mis:
> http://localhost/bugtracker3

Il faut terminer avec un trait oblique  /

**Comment by Patriboom** [comment]
Ouais ... toute une reconstruction!!!!

Les liens sont là et sont bons.

**Comment by Albatros78** [comment]
Allez on y va...

Projet renommé
------------------
Le nom de l'ancien serait bien non ?
![image](https://user-images.githubusercontent.com/79452305/132353113-4b79f254-58c9-4fc0-bdb9-bbddc562d499.png)

Lien pas bon
![image](https://user-images.githubusercontent.com/79452305/132353147-82a0c2f4-ccf6-48eb-86d2-1e8c345ac071.png)


Fermeture ticket 
------------------
Phrase non terminée
![image](https://user-images.githubusercontent.com/79452305/132353865-26d73f44-da25-4ef2-b1d6-3d62f912374d.png)


Réouverture ticket
--------------------
Phrase non terminée
![image](https://user-images.githubusercontent.com/79452305/132354098-86dca8a5-7d18-42f2-b900-d0fbde01b320.png)

Le contenu pour la fermeture et l'ouverture est celui du message texte suivant

![image](https://user-images.githubusercontent.com/79452305/132354242-e0471e44-e796-447c-b66b-2b62ca8512a4.png)

Mais le sujet change à la volée... Il faut que j'adapte le contenu du message alors ?

**Comment by Patriboom** [comment]
Et c'est bien ainsi (ci-bas) qu'est ton fichier config.app.php  ? 

`
<?php
return array(
	/**  URL
	 * You can define your URL or leave blank to let us figure it out
	 * 	- Sometimes in non-apache setups you need to define your url
	 */
	'url' => 'http://localhost/bugtracker3/',
[...]

`

Que c'est étrange!

**Comment by Albatros78** [comment]
Copy
![image](https://user-images.githubusercontent.com/79452305/132356912-1a9e24eb-01ff-40c3-a006-a3c9c26b8bc7.png)

**Comment by Albatros78** [comment]
Il n'y a que le projet renommé qui n'a pas de lien... Les autres sont OK sur les liens...
Mais pas dans le texte des messages recu comme ci dessus

Donc cela marche on dirait

**Comment by Patriboom** [comment]
Fichiers disponibles. 
J'ai ajouté la mention de l'ancien du projet tel que demandé.
Le lien vers le projet renommé devrait fonctionner.

**Comment by Albatros78** [comment]
OK pour projet renommé et le nom de l'ancien projet... 

Reste les autres infos dans le mail  juste au dessus pour: 

- Fermeture ticket
- Réouverture ticket
- Ticket déplacé

**Comment by Patriboom** [comment]
Liens (ticket et projet) pas bons, effichage erroné: tout ceci relève de la même erreur.   C'est la référence vers le nouveau projet qui doit être ici et non la référence à l'ancien.

J'y verrai demain.

**Comment by Patriboom** [comment]
Correction faite.
Les fichiers sont disponibles.


Voici le message configuré dans admin (billet déplacé): 


**Le billet « {issue} » a été affecté au projet « {project} ».

Son projet originel est:**



Voici le message reçu: 


**_Le billet « Nombreux changement d'étiquettes » a été affecté au projet « Billets ».

Son projet originel est:Plongee.ca_**

**Comment by Albatros78** [comment]
Le ticket semble bien changer de projet...mais

Aucun email recu !

De plus l'ajout/suppression de tags et je ne reçois plus de mail comme avant.... c'est casser ! :-(

**Comment by Patriboom** [comment]
Une erreur de cete fameuse mauvaise journée d'hier!!!
;)

Corrgée, fichiers disponibles.

**Lorsque je déplace le ticket du projet 1 vers le projet 2 ... pas d'email**
Seuls les abonnés d'un des deux projets sont avisés.

**Lorsque je déplace le ticket du projet 2 vers le projet 1 ... Email OK**
Seuls les abonnés d'un des deux projets sont avisés.

**Pour l'instant, ça restera ainsi.**

**Comment by Albatros78** [comment]
Et voila . correctif OK cette fois ci.
merci

Et l'email pour les tags est revenu :-)


Je crois que tous est en ordre pour les emails et les URL's...
On ferme ce ticket, qui était bien chargé !
