### ISSUE TITLE
Archiving Project and email received like renamed project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#527]
Lorsque j'archive un projet je reçois cet email !!!!

![image](https://user-images.githubusercontent.com/79452305/132194134-8f5aac23-0b04-488a-a096-e7b00b509e01.png)

Qui est l'email lorsque l'on renomme un projet.
Peut être faut il ajouter une section dans la liste des emails pour ajouter "archived project" et configurer un email spécifique.

![image](https://user-images.githubusercontent.com/79452305/132194315-728d91c8-36b9-4bb5-91f5-e33efc4c6388.png)

**Comment by Patriboom** [comment]
Les seules options de courriel pour les projets sont listées ci-haut dans votre message:

1. Projet supprimé
2. Projet modifié

L'archivage d'un projet est un changement au projet lui-même.
Il faut donc modifier votre message de manière à ce qu'il reflète mieux les différents changements aux projets:

- changement de nom
- changement de responsable par défaut
- archivage
- réactivation

Peut-être que les messages seront mieux distingués, séparés dans un avenir incertain.  Pour l'instant, il y a plusieurs autres choses à faire et celles-ci passeront avant la messagerie séparée de différentes modification à un projet.

**Comment by Patriboom** [comment]
Le présent billet a valeur de réponse au billet https://github.com/pixeline/bugs/issues/530
Le présent billet permettra le suivi du billet https://github.com/pixeline/bugs/issues/530 puisque ce sont deux items d'un même sujet.

**Comment by Albatros78** [comment]
OK c'est bon.. 
Merci pour l'explication
