### ISSUE TITLE
Strange message after changing assigned user on a ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#529]
Après avoir changé de 'Assigned user' sur un ticket en visualisant le ticket j'ai les messages de changements affichés comme ci dessous:

![image](https://user-images.githubusercontent.com/79452305/132196735-4ffaa033-de98-4424-9e5b-064f4d399267.png)

Mais j'ai aussi ceux là !

![image](https://user-images.githubusercontent.com/79452305/132196703-a383f080-8a7a-45ce-ba4d-7249e583c864.png)

**Comment by Patriboom** [comment]
Ce semble bon, maintenant.

**Comment by Albatros78** [comment]
Là maintenant j'ai plus aucun message de changement ! 
Affichage en clair ou mauvais affichage comme avant dans les images

Il n'y a plus d'affichage du tout ? ou problème ?

**Comment by Patriboom** [comment]
C'est vraisemblablement parce qu'une page est restée dans la mémoire cache.  
Pour contourner cela: 
Shift + clic (sur rafraîchir la page)

**Comment by Albatros78** [comment]
Ha c'est OK le message en clair est là et plus les autres !

![image](https://user-images.githubusercontent.com/79452305/132238096-84652f97-6e4f-430a-bd4c-992a1d1f108e.png)


Cela avance bien ... Super !
