### ISSUE TITLE
Changing Assigned user  and email received like renamed project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#530]
En changeant d'utilisateur assigné au projet on reçoit un email comme si le projet était renommé

![image](https://user-images.githubusercontent.com/79452305/132202065-e2558dd4-a23d-459e-80b4-8836c2d601f8.png)

Il semble que la section 'Assigned' dans la gestion des emails ne soit pas prise en compte

![image](https://user-images.githubusercontent.com/79452305/132202477-b10ad4f0-2834-4a6e-9880-a0b6909a12b5.png)

**Comment by Patriboom** [comment]
Dans la gestion des emails, la section 'Assigned' ne s'applique qu'au changement de responsable d'un billet précis; non à un changement de responsable par défaut.

Le message avisant d'un changement du projet est donc correct.  La personne désignée par défaut  fait partie de la définition du projet.  Si la personne désignée par défaut est changée, c'est tout le projet qui est changé. C'est un peu comme le directeur d'un département (dans une entreprise); c'est tout le départerment qui sera affecté dans ses méthodes et relations de travail.

**Comment by Patriboom** [comment]
Ceci est en lien avec https://github.com/pixeline/bugs/issues/527
Nous ne garderons que le billet  https://github.com/pixeline/bugs/issues/527
