### ISSUE TITLE
Error during project deleting

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#536]
J'ai téléchargé la version qui corrige la création  du second projet.

J'ai crée 2 autres projets.
En faisant un delete d'un projet j'ai l'erreur

Unhandled Exception
Message:
Undefined property: stdClass::$title
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php on line 176
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 176)
#1 E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php(176): Laravel\{closure}(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 176, Array)
#2 [internal function]: Project_Controller->post_edit('3')
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#6 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project@edit', Array)
#7 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#9 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#10 {main}

En revenant en arrière le projet ne semble pas supprimé !

**Comment by Patriboom** [comment]
Ce message est bien complet et me permets de repérer l'erreur.
Une version corrigée sera disponible dans quelques minutes.

**Comment by Patriboom** [comment]
Vous devriez y trouver aussi un petit ( + ) que vous aimerez. 
C'est là.

**Comment by Albatros78** [comment]
Je crois que j'aime pas encore :-)
Télécharger et installer

En cliquant sur un projet

Unhandled Exception
Message:
syntax error, unexpected ';', expecting ')'
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php on line 175
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(203): Laravel\Routing\Controller::load('application', 'project')
#1 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(145): Laravel\Routing\Controller::resolve('application', 'project')
#2 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project@index', Array)
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#4 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#5 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#6 {main}

**Comment by Patriboom** [comment]
Aïe, quelle erreur (horreur) bête!!!!
Désolé, ma faute, entièrement mienne.

Testé et corrigé.  Code disponible dans quelques minutes.

**Comment by Albatros78** [comment]
Faut prendre des vitamines ... !!! Lol

**Comment by Albatros78** [comment]
J'ai téléchargé la dernière version (celle qui doit corriger le dépalcement des tickets)
et je supprime un projet.
Boum

Unhandled Exception
Message:
Call to undefined function Courriel()
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php on line 176
Stack Trace:
#0 [internal function]: Project_Controller->post_edit('3')
#1 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#2 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project@edit', Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#6 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#7 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#8 {main}

**Comment by Patriboom** [comment]
Décidément!!!

Pas une bonne journée pour moi, hein!

Merci encore de votre patience.

La correction est là.

**Comment by Albatros78** [comment]
Really Bad day... ca arrive !


Unhandled Exception
Message:
Array to string conversion
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\ajax\SendMail.php on line 19
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Array to string...', 'E:\\xampp\\htdocs...', 19)
#1 E:\xampp\htdocs\bugtracker3\app\application\controllers\ajax\SendMail.php(19): Laravel\{closure}(8, 'Array to string...', 'E:\\xampp\\htdocs...', 19, Array)
#2 E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php(198): include_once('E:\\xampp\\htdocs...')
#3 E:\xampp\htdocs\bugtracker3\app\application\controllers\project.php(176): Project_Controller->Courriel('Project', true, 4, 0, Array, Array, Array)
#4 [internal function]: Project_Controller->post_edit('4')
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#6 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#7 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#8 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project@edit', Array)
#9 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#10 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#11 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#12 {main}

**Comment by Patriboom** [comment]
Corrigé, testé, fonctionnel.
Fin de ma (mauvaise) journée de travail sur ce projet.

Merci de votre patience.

**Comment by Albatros78** [comment]
Projet supprimé avec succès sans erreur
Je ne vois pas le petit "+" que je dois aimer !!!

**Comment by Patriboom** [comment]
Concernant le petit "+"   .... l'affichage de l'action récemment posée se fait désormais au centre de l'écran.
Essayez-le avec nouveau commentaire à un billet déjà bien garni en commentaires. Vous verrez .. l'affichage ne se fera plus en tête de liste (hors écran).

Fermons le présent billet, le petit détail a son propre billet au numéro https://github.com/pixeline/bugs/issues/410

**Comment by Albatros78** [comment]
Ha oui .... cool...

**Comment by Patriboom** [comment]
Ne pouvons-nous pas fermer le présent billet ?
