### ISSUE TITLE
Strange message during ticket moving

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#540]
En déplaçant un ticket d'un projet vers un autre, voila les messages !

![image](https://user-images.githubusercontent.com/79452305/132356521-cc4485e5-5e85-45dd-9e0b-22fb9696aba7.png)

**Comment by Patriboom** [comment]
C'est corrigé.

Ce sera tout pour moi aujourd'hui.

Merci de votre aide.

**Comment by Albatros78** [comment]
Fichiers dispos ?

**Comment by Patriboom** [comment]
Oui, fichiers disponibles.

**Comment by Albatros78** [comment]
Téléchargé, installé, Badaboum en déplaçant un ticket dans  un autre projet..
Essayé sur 2 projets différents

Unhandled Exception
Message:
Undefined variable: NumResp
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php on line 106
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 106)
#1 E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php(106): Laravel\{closure}(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 106, Array)
#2 [internal function]: Project_Issue_Controller->get_edit('1', '3')
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#6 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project.issue@e...', Array)
#7 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#9 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#10 {main}

**Comment by Patriboom** [comment]
Signe que je doive prendre un peu de répit.
Ma faute.  Désolé.
Ce devrait être bon, là.

**Comment by Albatros78** [comment]
Presque 

Unhandled Exception
Message:
Undefined variable: nomRes
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php on line 111
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 111)
#1 E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php(111): Laravel\{closure}(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 111, Array)
#2 [internal function]: Project_Issue_Controller->get_edit('1', '4')
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#6 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project.issue@e...', Array)
#7 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#9 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#10 {main}

**Comment by Patriboom** [comment]
Fichier corrigé.

**Comment by Albatros78** [comment]
Bad day !
:-)

Unhandled Exception
Message:
Undefined offset: 4
Location:
E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php on line 111
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 111)
#1 E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php(111): Laravel\{closure}(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 111, Array)
#2 [internal function]: Project_Issue_Controller->get_edit('1', '4')
#3 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#6 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project.issue@e...', Array)
#7 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#9 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#10 {main}

**Comment by Patriboom** [comment]
Aïe, quelle patience!  Merci.

C'est là. testé avec votre BD sur mon système de développement.

**Comment by Albatros78** [comment]
OK c'est bon...Plsu d'erreur et messages OK

Good Job Patrick ! :-)
