### ISSUE TITLE
Not possible to modify a comment: pencil is grayed

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#543]
Impossible de modifier un commentaire. Le crayon est grisé et inactif en mode admin, manager ...

![image](https://user-images.githubusercontent.com/79452305/132365971-48fd9054-7479-4984-9968-806f43645664.png)

**Comment by Patriboom** [comment]
Veuillez procéder à l'ajout suivant dans votre base de données: 
`INSERT INTO `activity` (`id`, `description`, `activity`) VALUES (9,	'Deleted a comment','DeleteComent' );`

Ça servira prochainement.

**Comment by Albatros78** [comment]
Pas possible y'a déjà du monde en ID 9

INSERT INTO activity (id, description, activity) VALUES (9, 'Deleted a comment','DeleteComent' );

Je fais l'insertion en ID 11 alors ?

**Comment by Patriboom** [comment]
Attention, il y a une faute de frappe, Comment prend deux m.

J'ai corrigé mon commentaire et le vôtre.

oui, en ID = 11

**Comment by Patriboom** [comment]
Attendez, ce n'est pas au point encore.

**Comment by Patriboom** [comment]
Voici la commande qui fonctionnera.
Mes excuses.

`INSERT INTO `activity` (`id`, `description`, `activity`) VALUES (11,	'Deleted a comment','delete_comment' );`

Je suis allé trop vite.

**Comment by Albatros78** [comment]
Done.

**Comment by Patriboom** [comment]
Une autre mise à jour de base: 
`INSERT INTO `activity` (`id`, `description`, `activity`) VALUES (12, 'Edited a comment','edit_comment' );`

**Comment by Patriboom** [comment]
Le crayon est de nouveau fonctionnel.
De plus, 

- L'édition du commentaire laisse des traces dans "users_activity"
- La suppression d'un commentaire laisse de telles traces aussi
- Les commentaires supprimées restent désormais accessibles ( bulle rouge à droite de la mension "commentaire supprimé" ) 

Bref, plusieurs changements qui devraient vous plaire.

**Comment by Albatros78** [comment]
Installé.

Je peux cliquer sur le crayon. :-)
D'ailleurs il est toujours grisé. Ne serait il pas mieux si il était en bleu (ou autre) par exemple car en grisé on peut penser 'non actif'

Bon je peux ouvrir un commentaire et l'éditer... Mais rien ne se passe en cliquant sur Save... j'attends... rien.
je ferme et reviens sur le ticket... Modification pas prise en compte.

**Comment by Albatros78** [comment]
Si tu peux arriver à régler cela avant ton absence.
Merci

**Comment by Albatros78** [comment]
Bon J'arrive à modifier les commentaires et les sauvegarder.
Le bug et que cela est impossible lorsque je fais un retour chariot et ajout de commentaire... Là aucune action avec Save

Lorsque je clique sur le crayon, le curseur est placé à la fin du premier du texte. Si j'ajoute le texte à la fin, le commentaire se sauvegarde.
Si j'ai un commentaire sur plusieurs lignes, et place le curseur à la fin du texte. Aucun enregistrement possible... Le saut de ligne provoque un **bug** sur l'enregistrement.

Aucune bulle rouge !!!!  Ni même un verre de vin (rouge) :-)

Mais j'ai ceci et c'est cool !

![image](https://user-images.githubusercontent.com/79452305/133235891-65692fca-e38e-4606-810a-c2ec016f764d.png)

**Comment by Patriboom** [comment]
Je n'observe de problème que l'enregistrement de texte long.

Quant à la fenêtre HTML pour faire paraître le texte supprimé ... j'y ai pensé, mais je me suis dis « Bof, c'est du texte supprimé après tout.  Si on l'a supprimé, c'est qu'il n'était pas important. »

**Comment by Albatros78** [comment]
Ha zut alors...

Oui tu as raison sur la fenêtre pour les textes longs... Mais en cliquant et qu'il ne se passe rien c'est ennuyeux... Il faudrait au moins afficher 100 ou 300 caractères... un minimum et en mettant 3 points ... à la fin pour comprendre qu'il y avait une suite.

**Comment by Albatros78** [comment]
Bon moi j'ai toujours les problèmes:

- Commentaire effacé, toujours visible
- Edition d'un commentaire et saut de ligne ne fonctionne pas.

Voila ma base
[afsof357059_16yselj (4) base AFS OK .zip](https://github.com/pixeline/bugs/files/7162045/afsof357059_16yselj.4.base.AFS.OK.zip)

Login: axel@afsoftware.fr/password

**Comment by Patriboom** [comment]
Quant aux icônes, peut-être faut-il les charger manuellement, car leur répertoire est exclus des mises à jour git  (fichier .gitignore)
Voici leurs adresses: 
https://github.com/pixeline/bugs/blob/master/app/assets/images/layout/icon-comments_2.png
https://github.com/pixeline/bugs/blob/master/app/assets/images/layout/icon-edit_1.png

**Comment by Albatros78** [comment]
Je les mets ou ?

**Comment by Patriboom** [comment]
Commentaire effacé toujours visible: corrigé, c'est un oubli de programmeur, le code avait été mis en "remarque".  Fonction active lors de la prochaine mise à jour.  ( non disponible encore; je travaille aux soucis d'édition )

**Comment by Albatros78** [comment]
Ha ce développeur... je vais en changer :-)

**Comment by Patriboom** [comment]
Le crayon est grisé lorsque actif et coloré lorsqu'on passe la souris au-dessus.  Autrement:  il n'est pas là du tout.

**Comment by Albatros78** [comment]
Oui j'ai vu...moi c'est le grisé qui me dérange pour un élément actif...Généralement cela signifie que l'objet n'est pas actif justement.

**Comment by Patriboom** [comment]
Oui, mais le principe de système de billet n'est pas l'édition d'un commentaire, mais l'ajout de commentaires au gré de l'évolution.  Je ne voulais pas attirer l'attention vers une fonction secondaire (édition) dans un contexte où l'usager devrait être orienté vers l'ajout d'information.

**Comment by Albatros78** [comment]
OK je comprends... c'est bien clair et tu as raison.
Restons en là sur la couleur du crayon !

**Comment by Patriboom** [comment]
Voilà, les modifications du jour sont disponibles:

- Édition de commentaire long
- Suppression d'un commentaire
- Liste des langues ne devrait plus afficher le fichier all.php

**Comment by Albatros78** [comment]
Installé
Suppression d'un commentaire est OK. Il ne s'affiche plus

Mais en cliquant sur Dashboard par la suite (erreur en bas)

Dashboard An overview of all the activity involving your active projects.
AFS Public Techbase
Comment
"What is the frequency of updates ?" by Manager1 Manager1 on issue All infos to download our AFS public Technical Database
2021-09-13 11:33
tag update
EnhancementNot a bug but configtags added in All infos to download our AFS public Technical Database by Axel FALCK 
2021-09-13 11:32
Created
All infos to download our AFS public Technical Database was created by  Axel FALCK 2021-09-13 11:32 
AFS Public Techbase
BugTracker
Comment
"OK. Configuration is known and doucmented on how to  " by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-09-13 11:00
tag update
Not a bug but configtag added in Configure email sending into HTML and not plain text by Axel FALCK 
2021-09-13 11:00
tag update
Fixedtag removed in Configure email sending into HTML and not plain text by Axel FALCK 
2021-09-13 11:00
tag update
If OK -> close ittag added in Configure email sending into HTML and not plain text by Axel FALCK 
2021-09-13 10:49
tag update
Wait for commentstag added in Configure email sending into HTML and not plain text by Axel FALCK 
2021-09-13 10:49
BugTracker
Database Installator
Comment
"v1.1 is compiled and ready !" by Axel FALCK on issue Add documentation and finalization of cutomization of v1.1
2021-09-13 10:53
Closed
Add documentation and finalization of cutomization of v1.1 was closed by Axel FALCK 2021-09-13 10:53
tag update
Opentag removed in Add documentation and finalization of cutomization of v1.1 by Axel FALCK 
2021-09-13 10:52
tag update
Fixedtag added in Add documentation and finalization of cutomization of v1.1 by Axel FALCK 
2021-09-13 10:52
tag update
Work in Progresstag removed in Add documentation and finalization of cutomization of v1.1 by Axel FALCK 
2021-09-13 10:52
Database Installator
Form Manager
Comment
"Ok. Done" by Axel FALCK on issue First Beta version of Form Manager
2021-09-13 11:01
Closed
First Beta version of Form Manager was closed by Axel FALCK 2021-09-13 11:01
tag update
¿ fixed ?tag removed in First Beta version of Form Manager by Axel FALCK 
2021-09-13 11:01
tag update
Opentag removed in First Beta version of Form Manager by Axel FALCK 
2021-09-13 11:01
tag update
On holdtag removed in First Beta version of Form Manager by Axel FALCK 
2021-09-13 11:01
Form Manager
Key Generator
tag update
EnhancementWork in Progresstags added in v2021.1 - Corriger la variable de la récupération de la version by Axel FALCK 
2021-09-10 12:24
Created
v2021.1 - Corriger la variable de la récupération de la version was created by  Axel FALCK 2021-09-10 12:24 
tag update
EnhancementWork in Progresstags added in v2021.1 - Mettre les champs vides en mode utilisateur by Axel FALCK 
2021-09-10 12:22
Created
v2021.1 - Mettre les champs vides en mode utilisateur was created by  Axel FALCK 2021-09-10 12:22 
Key Generator
Temporary GenURL
Comment Deleted
by Axel FALCK on issue Add checking of URI posted into the link and website URI
2021-09-14 16:11
Comment Deleted
by Axel FALCK on issue Add checking of URI posted into the link and website URI
2021-09-14 16:11
Comment Deleted
by Axel FALCK on issue Add checking of URI posted into the link and website URI
2021-09-14 14:50
Unhandled Exception
Message:
Trying to get property 'id' of non-object
Location:
E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code on line 1
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1)
#1 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(1): Laravel\{closure}(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1, Array)
#2 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(34): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker3\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

**Comment by Albatros78** [comment]
J'avais mis 2 commentaires long
Le premier affichait en bleu comme ci dessous le commentaire effacé 'plus de bulle rouge !)
![image](https://user-images.githubusercontent.com/79452305/133275095-378b66d6-a793-4b4f-a931-07bb83a3cf7d.png)

J'ai effacé le second commentaire long et sans changer de page j'ai cela:

![image](https://user-images.githubusercontent.com/79452305/133275199-3d30e6f6-a245-473f-bba2-d7e9a042ae43.png)

En quittant la page et en revenant même affichage !!!!

**Comment by Albatros78** [comment]
J'ai réinstallé ma base et refait le test avec texte long et suppression. idem

![image](https://user-images.githubusercontent.com/79452305/133275756-041c2109-5fef-4ccf-af22-7f94c2e183b0.png)

**Comment by Patriboom** [comment]
Bulle rouge corrigée.
Devrait désormais ouvrir une nouvelle fenêtre avec le contenu affiché.  Ceci devrait régler aussi l'affichage erroné (bleu) illustré ci-haut.

Quant à

> J'avais mis 2 commentaires long
> Le premier affichait en bleu comme ci dessous le commentaire effacé 'plus de bulle rouge !)

Les bulles rouges ne sont présentes - en principe - qu'en lien avec des commentaires supprimés (longs ou courts), mais pas dans l'édition.

Voyez si la mise à jour corrige un seul ou les deux soucis mentionnés et illustrés ci-haut.

Quant au dashbord qui affiche un message d'erreur, les informations données ci-haut ne me permettent pas de comprendre, car les retours du serveur sont tronquées.  Si vous voulez bien me passer copie de votre base, ce pourrait me permettre de reproduire le problème.

**Comment by Albatros78** [comment]
Alors reprenons avec cette mise à jour

Commentaire update ==> OK
Commentaire update avec sauts de ligne ==> OK
Suppression commentaire long ou court ==> OK
Affichage commentaire supprimé dans fenêtre web ==> OK

Reste le problème en cliquant sur le dashboard

Unhandled Exception
Message:
Trying to get property 'id' of non-object
Location:
E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code on line 1
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1)
#1 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(1): Laravel\{closure}(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1, Array)
#2 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(34): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker3\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}


Voilà ma base avant erreur qui est bien liée aux suppressions (je n'ai rien fait d'autres)

[afsof357059_16yselj (4) base AFS OK .zip](https://github.com/pixeline/bugs/files/7163265/afsof357059_16yselj.4.base.AFS.OK.zip)

axel@afsoftware.fr/password

**Comment by Albatros78** [comment]
Petite question pour ma culture HTML 
Quelle commande tu utilises  pour une ouvrir une fenêtre indépendante du navigateur pour afficher le message supprimé.

<a href="" target="**quoi ???**">

car _blank ouvre un nouvel onglet et pas une fenêtre !

Merci

**Comment by Patriboom** [comment]
> Petite question pour ma culture HTML
> Quelle commande tu utilises pour une ouvrir une fenêtre indépendante du navigateur pour afficher le message supprimé.

Voilà le point, ce n'est pas HTML, c'est javascript.

commande window.open  détaillée dans https://www.w3schools.com/jsref/met_win_open.asp
D'ailleurs, w3school est un très bon site.

**Comment by Patriboom** [comment]
Avec vos données (votre base), avec la denière mise à jour  ( ver 1.8 5ab )  : aucun erreur au dashboard.
Oserais-je vous demander de forcer une mise à jour de la page  Shift-clic (bouton refresh du fureteur) ?

**Comment by Albatros78** [comment]
Même chose sur un petit commentaire. Pas lié à la taille du commentaire semble t'il ?

Message:
Trying to get property 'id' of non-object
Location:
E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code on line 1
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1)
#1 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(1): Laravel\{closure}(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 1, Array)
#2 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353) : eval()'d code(34): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtracker3\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtracker3\app\laravel\response.php(240): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(173): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#15 {main}

Grrrrrrr

**Comment by Albatros78** [comment]
Je suis sous Google Chrome...
Même erreur sous Firefox....

**Comment by Albatros78** [comment]
J'utilise souvent ws3school car c'est effectivement super bien fait et pratique

Mais je ne vois pas le paramètre pour ouvrir une fenêtre seule en dehors du navigateur !
Fatigué peut être !

**Comment by Albatros78** [comment]
C'est bon j'ai trouvé .
Merci du tuyau

**Comment by Patriboom** [comment]
Je reprends les tests avec votre BD et le code récent.
Listez-moi les étapes que vous suivez pour arriver à l'affichage de cet écran d'erreur svp.

**Comment by Patriboom** [comment]
Voilà, j'ai réussi à trouver, en supprimant un commentaire. 
Je vous reviendrai.

**Comment by Patriboom** [comment]
Voilà, un fichier corrigé; j'espère que ce sera le seul qui aura besoin de ce médicament.
Quoi qu'il en soit, je ferai le tour de cette série de fichiers afin de m'assurer que ce la ne se produise plus.

Pouvez-vous aussi confirmer que all.php n'apparaît plus dans la liste des choix de langue (autre billet) ?   et fermer le billet correspondant.

**Comment by Albatros78** [comment]
Installé.
Plus de crash avec dashboard :-) :-)

all.php toujours là !

je ferme ce billet
