### ISSUE TITLE
Into Dashboard tags does not repected your tag list and color

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#555]
En affichant le dashboard tous les tags sont de la même couleur.

![image](https://user-images.githubusercontent.com/79452305/132841252-3b13dcb4-7310-4738-a809-33a1f586cfcd.png)

Il serait bien si ils affichaient la couleur configurée dans la table tag

**Comment by Patriboom** [comment]
C'était déjà dans mes cartons.
Voilà que c'est fait, testé et fonctionnel.

**Comment by Albatros78** [comment]
Le carton est mal emballé !!!!
:-) :-)

J'ajute un tag ici !

![image](https://user-images.githubusercontent.com/79452305/132869970-3924e5cf-c7f2-4ff8-ba9c-d08d4579ea04.png)

et il apparaît dans un autre projet ?????

![image](https://user-images.githubusercontent.com/79452305/132870118-90dba7c5-cb71-48ae-8e01-fad5097c358d.png)

**Comment by Patriboom** [comment]
Est-ce que l'image du bas vient du Panneau de contrôle (dashboard) ? 
Si oui, pouvez-vous saisir un espace plus grand, une zone qui permette de voir à la fois le projet 4 et le projet 11 ? 
Si non, qu'elle l'origine de cette capture ? 

Merci.

**Comment by Albatros78** [comment]
Oui cela provient du Dashboard
Page trop grande, mais voilà le projet 11

![image](https://user-images.githubusercontent.com/79452305/132897206-33e0073c-e9d9-4861-b702-a91c9e0baa73.png)

**Comment by Patriboom** [comment]
Est-ce un billet qui a changé de projet au cours du temps ?

**Comment by Albatros78** [comment]
Oui... lorsque j'ai fait mes tests de déplacement de ticket.

**Comment by Albatros78** [comment]
Je viens de créer un nouveau ticket et ensuite je lui ajoute des tags.... (rien d'autres)
AUCUN affichage dans le dashboard

**Comment by Patriboom** [comment]
Ce qui m'étonne le plus, c'est que vous eussiez de ces mentions avant la mise à jour.

Pouvez-vous me retourner le résultat de la commande suivante (appliquée dans votre PHPmyadmin) : 

`SELECT * FROM users_activity ORDER BY id DESC LIMIT 0,25;`

Merci.

**Comment by Albatros78** [comment]
![image](https://user-images.githubusercontent.com/79452305/132980089-dc015915-ff4e-4584-a130-7c73ee16186d.png)

**Comment by Patriboom** [comment]
Bonjour, 

la dernière mise à jour (disponible) ne règlera pas le souci lié aux étiquettes d'un billet déplacé, mais reglera l'affichage de l'historique des étiquettes dans l'affichage des détails d'un billet et dans l'affichage de dashboard et de l'historique récent d'un projet.

- http://localhost/BUGS/
- http://localhost/BUGS/project/1
- http://localhost/BUGS/project/1/issue/1


Nous verrons ensuite s'il est possible d'agir sur les étiquettes de billet ou de project déplacé.  (  ¡ SI il est possible !  )

**Comment by Albatros78** [comment]
Téléchargé et installé.

Aucune action dans l'activité ! RIEN, NADA

Dans les détails du billet, mais oui mais pas le dashboard ou l'activité d'un projet.

ici ma base si besoin.
[afs_bugtracker (11).zip](https://github.com/pixeline/bugs/files/7149920/afs_bugtracker.11.zip)

**Comment by Patriboom** [comment]
Les donnnées transmises me sont utiles.
Les étiquettes restent ajoutées ou retirées restent liées au projet antérieur ( avant déplacement d'un billet ).  Je dois travailler et faire en sorte de corriger cette erreur.

**Comment by Patriboom** [comment]
Oups!  J'analysais un vieux code.
Je prends, à l'instant, le code d'ici - celui que je suppose être celui vous utilisez - et reprends mes tests.

**Comment by Patriboom** [comment]
J'ai trouvé le problème.  Je m'attarde à le corriger.

**Comment by Patriboom** [comment]
Merci de votre patience.  Le problème est corrigé.  Il s'agissait de valeur fixe laissée en place plutôt qu'une variable; c'est du code de développement qui traînait derrière.

La mise à jour est disponible, testée et fonctionnelle.

**Comment by Albatros78** [comment]
Hello,

Super job... là cela fonctionne bien. sur les projets et incidents.
Je n'ai pas testé le changement de projet pour un ticket car tu as dit que cela sera fait après si possible... Mais là c'est déjà super bien !
merci

**Comment by Patriboom** [comment]
Merci du retour.

Je crois que vous pouvez tester le changement de projet.  Ça devrait passer.

**Comment by Albatros78** [comment]
Excellent. Le ticket est changé de projet sans problème et les tags suivent le ticket dans le nouveau projet.
et l'activité indique bien le changement de projet.

![image](https://user-images.githubusercontent.com/79452305/133003512-6e26fbe6-2efb-4f20-951a-cd778d49f980.png)

Un petit espace à ajouter ici pour un tag removed
![image](https://user-images.githubusercontent.com/79452305/133003592-61e0913c-45b7-40e9-a4eb-02b7ef90b5b8.png)

A nouveau good job !

**Comment by Patriboom** [comment]
C'est fait.
Fermons ce billet.
