### ISSUE TITLE
Testing Message an steange word

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#560]
Le message de test comporte un mot au début ! qui n'est pas dans le message

![image](https://user-images.githubusercontent.com/79452305/133072158-3878d5cd-f3ac-4471-878e-cde9801dabe9.png)

**Comment by Patriboom** [comment]
J'y verrai bientôt.

**Comment by Patriboom** [comment]
Traitement de ce bug en commun avec https://github.com/pixeline/bugs/issues/560

**Comment by Patriboom** [comment]
Oups!  J'ai fermé celui que je devais garder!!!

**Comment by Patriboom** [comment]
Les messages et blocages révélés aujourd'hui sont corrigés et disponibles.
Il se peut, cependant, que ça ne fonctionne pas encore parfaitement bien, car je suis occupé à corriger d'autres choses qui peuvent utiliser des fichiers communs aux deux chantiers.  
Veuillez patienter en cas de souci, l'autre chantier risque de demander plus de temps.

**Comment by Albatros78** [comment]
Testé aussi 
Affaire réglée. Le message de test est OK maintenant
