### ISSUE TITLE
Message non approprié sur mise à jour du contenu des emails

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#561]
En mettant à jour le contenu des emails, le message n'est pas bon

![image](https://user-images.githubusercontent.com/79452305/133072626-1a475df9-e0af-4dd4-a29b-daa0851d2438.png)

**Comment by Albatros78** [comment]
Ha si...cela reprend le contenu du message ...Les 2 traits verticaux devant le message sont inutiles !

**Comment by Patriboom** [comment]
Ce n'est pas prévu que ce message reprenne le contenu nouvellement édité.
C'est une erreur à corriger.

**Comment by Patriboom** [comment]
Traitement de ce bug en commun avec https://github.com/pixeline/bugs/issues/560

**Comment by Albatros78** [comment]
Testé.
Affaire réglée (presque) mais ca marche bien et le message est OK

Juste un truc sur mon écran (grande largeur) le message n'est pas centré 

![image](https://user-images.githubusercontent.com/79452305/133096656-c73282ec-20ca-41b5-919a-9edbfd16bea9.png)
