### ISSUE TITLE
Mise a jour des paramètres serveur email reste rouge

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#562]
En cliquant sur Update cela reste rouge...
Il me semble que cela revenait vert après la mise à jour.

![image](https://user-images.githubusercontent.com/79452305/133073153-f3f9fc5b-53ab-4e55-bfa0-8342d791aea3.png)

**Comment by Patriboom** [comment]
Ok, merci de l'observation.  Il y eut - oui - un changement à ce niveau.  Ce devait être le message "pop-up" qui remplace.  J'y verrai.

**Comment by Patriboom** [comment]
Traitement de ce bug en commun avec https://github.com/pixeline/bugs/issues/560

**Comment by Albatros78** [comment]
OK testé juste maintenant. 
Affaire réglée. De plus cela va super vite par rapport à avant. Tant mieux.
Bravo pour le message "Nous avons terminé "!
