### ISSUE TITLE
Error into language list for a user

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#569]
En changeant la langue d'un utilisateur la liste comprend une erreur

![image](https://user-images.githubusercontent.com/79452305/133256170-0242f188-b923-42ee-a7a4-5ccc7f87d116.png)

**Comment by Patriboom** [comment]
C'est bien clair sur votre image.  J'y verrai.

**Comment by Patriboom** [comment]
Étrange, le mien ne fait pas ça

![image](https://user-images.githubusercontent.com/19801202/133257439-3e070f71-cd23-460f-9651-719f0d210083.png)

**Comment by Patriboom** [comment]
Le code était bon.  Je l'ai amélioré un peu, en espérant avoir trouvé ce qui fait problème sur un serveur roulant sous Windows.

Sera disponible après correction des questions éditoriales  (texte long).

**Comment by Albatros78** [comment]
Une différence entre un apache Windows/PHP et linux ?

pourquoi ma liste est pas noire et barre orange  chez moi :-( ?
CSS somewhere ?

**Comment by Patriboom** [comment]
Noire et barre orange:  c'est la configuration du fureteur: valeur par défaut du OS.  Dans l'OS:  thème sombre.  Comme ici dans github: thème sombre....

![image](https://user-images.githubusercontent.com/19801202/133260254-403271bd-82ef-4642-804c-9bdf35858d63.png)

**Comment by Albatros78** [comment]
Ha OK ... You win one beer :-)

**Comment by Patriboom** [comment]
Fermons le billet avant de nous enivrer dedans.

**Comment by Albatros78** [comment]
Mets le Hold On pour revenir plus tard sur le sujet !

**Comment by Patriboom** [comment]
Vous pouvez introduire brièvement ce qui vous intéresse à ce sujet.

**Comment by Albatros78** [comment]
Supprimer de l'affichage de la liste  le all.php

**Comment by Patriboom** [comment]
Faut voir la nouvelle version, car c'est fait.

**Comment by Albatros78** [comment]
Celle corrige les suppressions de commentaires ne corrige pas ce problème

**Comment by Patriboom** [comment]
Si vous voulez bien vérifier cette version, le problème devrait être résolu.

**Comment by Albatros78** [comment]
v1.8.5ab
Non corrigé !

**Comment by Patriboom** [comment]
Je ne regardais pas du tout au bon endroit.
J'en ai profité pour corriger les autres endroits où le choix de langue est possible.

Bref, voilà.  C'est corrigé.
Veuillez confirmer et fermer le billet.

Merci de votre patience et votre vigilance.

**Comment by Albatros78** [comment]
HA ben voilà !
Avec un peu de bonen volonté ... :-)
Affaire réglée !

Merci

Allez bonnes vacances ou bon break... 
A bientôt
