### ISSUE TITLE
Tag by default when I open a new ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#600]
A l'ouverture d'un nouveau ticket j'ai cela à chaque fois comme tag....

![image](https://user-images.githubusercontent.com/79452305/136997928-3f104207-7e62-4f57-9065-8c99e90cbe4c.png)

Si on ne met rien dans les tags et que le tag Open se mettra seul à la confirmation (déjà le cas), c'est pas mieux ?

**Comment by Patriboom** [comment]
Possiblement que vous avez changé les étiquettes dans la table « tags »
Il faut absolument que le tag à id = 1 soit celui « Ouvert »
Il faut absolument que le tag à id = 2 soit celui « Fermé »

Vous ne pouvez pas changer les étiquettes 1 à 9 autrement que pour les traduire ou éditer les champs tag, bgcolor, ftcolor et, pour cela, mieux vaut utiliser  l'outil prévu.

Le tag "Open" est la valeur par défaut qui devrait se trouver dans la case que vous affichez ci-haut.  Il ne sera pas ajouté si la case des étiquettes est vide, considérant que vous pouvez vouloir qu'elle soit vide.
