### ISSUE TITLE
Useful thing but not a bug

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#618]
Hello,

Au tout début j'avais modifié le code pour afficher cela, car besoin d'avoir 2 autres options dans la sidebar.

![image](https://user-images.githubusercontent.com/79452305/137875822-abb24a8a-636c-429b-ac02-c4f0e5a91224.png)

Et j'avais modifie le code dans 
Dans app/application/views/layouts/blocks/default_sidebar.php à la ligne 46
avec 

![image](https://user-images.githubusercontent.com/79452305/137876728-5acc964d-c148-478d-ab70-1333a8ed5b08.png)

Ici le second lien n'est pas affiché dans l'image.
Mais si tu pouvais en fait, permettre à l'utilisateur de pouvoir ajouter 2 menus/liens comme cela en configurant cela dans config.app.php alors cela serait super.
Ainsi l'utilisateur peut ajouter 2 options qui lui sont utiles. Ici tu vois j'ai aussi ajouté un lien pour une aide rapide pour les utilisateurs.
Ainsi après une mise à jour pas besoin de remodifier le code car cela est configurable par des paramètres.

J'espère que c'est clair. Il faudrait partir sur l'idée d'avoir entre 1 et 3 options... je epnse que c'est suffisant.

Pas urgent, mais petit plus utile.

**Comment by Albatros78** [comment]
Ha oui j'ai aussi ajouté cela car c'est à la mode aujourd'hui d'être informé d'une connexion dans une application.
Que l'administrateur recoive un email à la connexion d'un utilisateur.

![image](https://user-images.githubusercontent.com/79452305/137877071-ef2ffc1f-db56-4951-8441-5977a0c6dacc.png)

c'était là !
![image](https://user-images.githubusercontent.com/79452305/137877389-0f89e460-1b6d-450e-a928-884844078a9a.png)

**Comment by Patriboom** [comment]
Pouvez-vous m'envoyer vos fichiers

- dump.php
- afs_bugtracker_help.pdf
?

Quand à l'avertissement sur connexion d'usager, j'en ferai un option dans le compte admin, car - pour ma part - ça m'emmerde d'avoir 50 messages par jour pour me dire que 8 personnes se sont connectées chacune 6 fois.

Merci pour les captures d'écran; ça aide.
Auriez-vous la gentillesse de m'envoyer cela en format texte ( dans un fichier zip comprenant les différentes sources où se trouvent ces modification) ? 

En ce qui a trait au menu d'aide.  Je favorise la création d'un wiki en ligne.  Les usagers pourrons ajouter et mettre à jour.

Au plaisir.

**Comment by Patriboom** [comment]
Le wiki est intégré à BUGS ( plusieurs liens accessibles dans le panneau de gauche )

Parmi vos suggestions, il ne reste que l'avis à l'administrateur.

**Comment by Patriboom** [comment]
Aussi, le problème de sauvegarde de la BDD.
Veuillez m'envoyer votre code ( en texte ) du fichier **dump.php**

Je soupçonne ici un écart de commandes entre Windows et  Linux.

**Comment by Albatros78** [comment]
Pour le Wiki pourquoi pas. Mais il faut l'associer à Bugs pour éviter une URL vers ton provider . Non ?
Bon je n'ai pas regardé le Wiki

Pour le fichier dump, je ne l'utilise plus car effectivement il ne fonctionne pas sur Windows. Voici le mien... qui doit ressembler à tons code.

[dump.zip](https://github.com/pixeline/bugs/files/7387598/dump.zip)


Mais peut être que l**'on peut laisser en recommandation** (dans la menu administration) que la sauvegarde ne fonctionne que sur Linux (90% des hébergements)
Et moi je testerais lorsque j'exporterai chez mon provider... sur Linux
Quand nous aurons fini !!! 
Bientôt j'espère ....

**Comment by Patriboom** [comment]
Concernant mysqldump ... pouvez-vous essayer ceci:  [https://john-dugan.com/dump-and-restore-mysql-databases-in-windows/](https://john-dugan.com/dump-and-restore-mysql-databases-in-windows/) (étape 2 = éveiller mysql sous Windows ); 

je pourrez mettre cela dans les consignes.

Aussi, afin de faciliter le suivi et vous permettre de proposer du code, vous pourriez installer [GIT pour Windows](https://git-scm.com/downloads), vous aimerez.

**Comment by Patriboom** [comment]
Là, j'y suis.
J'ai trouvé - finalement - l'erreur qui était à la source du problème chez vous.
Je ne comprends pas pourquoi votre serveur de site ne réagit pas comme un Linux normalement constitué. Il semble qu'on ne lui ait pas installé la commande  mysqldump.  Néanmoins, vous pourrez faire fonctionner la Sauvegarde en mode « Windows » comme je l'ai fait grâce à votre accès FTP.

Voyez, deux fichiers ont été créés dans votre répertoire temp.  Ils l'ont été par la page php élaborée à cette fin.

**Comment by Albatros78** [comment]
Y'a intérêt !!! 
:-) :-)

**Comment by Patriboom** [comment]
La révision 7p génère autant de commandes  _INSERT INTO_ qu'il a d'éléments à insérer.  Ça génère un peu plus de trafic, mais ça élimine complètement les soucis rencontrés ci-haut.  Cette procédure a soustrait près d'une dizaine de lignes de code et générera un processus SQL plus facile à déboguer.

C'est disponible.

**Comment by Albatros78** [comment]
Hello Patrick

version 7p installée.
Sauvegarde database OK
restore database OK

![image](https://user-images.githubusercontent.com/79452305/139657149-00689933-bb24-406b-8693-7c36b2fee15a.png)


Super.

merci
