### ISSUE TITLE
Other thing useful but not a bug

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#619]
Serait cool si on pouvez personnaliser le message d'inscription d'un utilisateur  directement via le menu Administration pour éviter d'aller dans le fichier .php  dans app\application\language\en\email.php  qui sera écrasé à la mise à jour suivante .

Et si on pouvait récupérer le nom de l'application dans config.app.php 
	'my_bugs_app'=>array(
		'name'=> 'AFS BugTracker',

Pour le mettre dans ce message à la place de BUGS codé en dur !

Nice to have :-)

**Comment by Albatros78** [comment]
Oui...

**Comment by Patriboom** [comment]
Une première version est en ligne.

**Comment by Patriboom** [comment]
Je crois que vous aimerez la toute dernière version.

Voici le résultat obtenu:  #637 

Les contenus "courriel" et "statique" sont maintenant intégrés et gérés par les remplacements (comme {first}, {last} et cie)

Courriel:  {email}
Contenu statique: {static}

À ce sujet, j'ai mis quelques notes dans le  [wiki](https://bugs.rcmission.net/pmwiki.php?n=Admin.EditEmails)
