### ISSUE TITLE
Percentage of project done

### ISSUE THREAD

**Issue by samoy2002** [pixeline/bugs#666]
I am wondering if it would be possible to have a percentage of project completed in the following area.

![image](https://user-images.githubusercontent.com/80289477/139453492-deeb2118-5e9d-4a46-9853-b52d8a520605.png)

Just to the right of the project name, it would be nice to have a percentage showing what part of the project is completed.  
![2021-10-29 09_34_54-Bugs](https://user-images.githubusercontent.com/80289477/139454029-bfb9682a-27ab-4441-9a6f-c7bdb22154a4.jpg)

**Comment by Albatros78** [comment]
Hello Patrick

Don't forget the little message on mouse hover on the number .
Just for user reminding.

**Comment by Patriboom** [comment]
All together with https://github.com/pixeline/bugs/issues/667, you should find the fix you asked for and patch for the issue #667

**Comment by Albatros78** [comment]
7p installed and

Starnge all tickets are closed for ALL projects (same issue with 7o) !!

![image](https://user-images.githubusercontent.com/79452305/139658105-68663465-79f6-49ad-9fc3-354aefe821a5.png)

When I click on one closed project or todo list menu I have this error...


here with Todo menu
![image](https://user-images.githubusercontent.com/79452305/139658229-c38cda56-162b-4303-a4c0-eac54cab9bdc.png)


And here with Closed ticket
![image](https://user-images.githubusercontent.com/79452305/139658307-dd8909a3-db8e-4ebd-b76a-3f994ff23f36.png)

**Comment by Patriboom** [comment]
> Hello Patrick
> 
> Don't forget the little message on mouse hover on the number . Just for user reminding.

Oui, j'ai oublié.  De quoi s'agit-il  ?

**Comment by Patriboom** [comment]
The bug you - Albatros78 - mentionned is not from this patch but from your backup restoration: a table is missing.
Please change all ";" for "&" in all fields  "preferences" from users table.  This command will do the trick:
> UPDATE users SET preferences = replace(preferences, ";", "&"); 
> UPDATE users SET preferences = replace(preferences, "!", "&"); 

--- you have it in the file ./install/update_v1-8_7p.sql

You can send me you archive file (.zip or .sql), I can edit it for you.

**Comment by Albatros78** [comment]
Dans 1.87p il n'y a que cela dans le fichier ./install/update_v1-8_7p.sql

UPDATE users SET preferences = replace(preferences, "!", "&"); 

Bon j'ai exécuté les 2 lignes:
UPDATE users SET preferences = replace(preferences, ";", "&");
UPDATE users SET preferences = replace(preferences, "!", "&");

Plus le 2 erreurs.

**Comment by Albatros78** [comment]
Tous les tickets sont TOUS fermés sur TOUS les projets !

**Comment by Albatros78** [comment]
Non j'ai parlé trop vite. Toujours l'erreur

![image](https://user-images.githubusercontent.com/79452305/139718703-d9ceba23-4e6b-4ae0-91fa-18e47d76b6f8.png)

Voici la base.

[Uploading database_20211101190128.zip…]()

**Comment by Albatros78** [comment]
Pour le mouse hover difficile de distinguer entre les 2 chiffres (0/4) ... pour un message différents

![image](https://user-images.githubusercontent.com/79452305/139718954-7e69d0f6-d7e7-45cc-9718-337174a529fd.png)

et mettre un message nombre de tickets ouverts/fermés et pas que Open tickets

Pourquoi pas mettre le chiffre des tickets ouverts en vert et ceux fermés en noir par exemple (ou au choix dans la configuration)

**Comment by Patriboom** [comment]
Ok pour le mouseover, j'y verrai.

Votre BDD a été contaminée par l'expérience Sauvegarde / Réstauration.  Il faut modifier les contenus des données pour qu'elles soient digestes à la restauration.

**Comment by Albatros78** [comment]
Tu peux remettre la base au propre ?
c'est étrange car je n'avais jamais restauré avec des sauvegardes... Elles ne marchaient pas...
Peut être que cela traîne depuis longtemps

**Comment by Albatros78** [comment]
et c'est pour cela (Base contaminée) que tous les tickets sont fermés ?

**Comment by Patriboom** [comment]
Puisque des tables ont été perdues, le système BUGS n'arrivera pas à restaurer par lui-même.  ll faudrait m'envoyer votre BDD afin que je la répare manuellement.

**Comment by Patriboom** [comment]
The pre-release 7q is avaible here: 

https://github.com/pixeline/bugs/releases/tag/v1.8_7q

It includes : 

- The big green button « Create new project » is back into the left panel
- New report (pdf) gives back the data for billing: time planned, work time, billed time, payed time
- In left panel, the list of projects shows how many issues are open, how many are closed. On hover this information a label shows up repeating the same but larger
- Well working backup & restore system ( but does not yet automatically applies the structure modifications on BDD )

**Comment by Albatros78** [comment]
Ci joint la base sauvegardée avec v1.87p
[database_20211101232914.zip](https://github.com/pixeline/bugs/files/7456488/database_20211101232914.zip)

**Comment by Patriboom** [comment]
J'ai envoyé votre base de données par courriel privé, c'est plus sécuritaire.
Et ...oui ... c'est à cause de la corruption que tous les billets affichent "fermés".
La correction envoyée devrait corriger cela.

**Comment by Albatros78** [comment]
Merci... J'ai installé la table..

Mais tous les tickets sont toujours TOUS fermés !!!
Mais curieusement aussi certains sont affiché ouverts dans la todo list

![image](https://user-images.githubusercontent.com/79452305/139818495-82163b2b-a2c2-4594-8c35-a97a6092349d.png)

Et si je restaurais (dans mon bugs de dev)  le contenu de mon bugs en production (perso) qui lui semble plus stable  ? qu'en pense tu ?
je retrouverais mes billets ouverts et fermés qui sont bien là dans ma partie production.

**Comment by Patriboom** [comment]
Je crois que c'est une bonne idée de restaurer la BDD de prod, car celle de dev a subi tellement de tests qu'elle est trouée de partout.

**Comment by Patriboom** [comment]
Tous les fureteur ne fonctionnent pas de la même manière quand vient le temps d'ajouter l'ascenseur.  Certains en feront une bande étroite qui élargira sous la souris et couvrir du texte, d'autres comme-ci haut prennent toute la largeur et réaménagent le texte.

Bref, non, je ne me mettrai pas les pieds dans la gestion de l'ascenseur.  Il revient à l'usager de nommer ses projets et de les gérer.
