### ISSUE TITLE
Upgrading problems

### ISSUE THREAD

**Issue by samoy2002** [pixeline/bugs#667]
I am struggling to update my version of bugs.   Here is what the administration page says.

![image](https://user-images.githubusercontent.com/80289477/139455036-80ad8568-f1c4-46ce-b56a-d44f9b2eaa7f.png)

When I try to replace all files with the newest version, I get an error when I login stating there are columns missing in the database.   What is the solution to this?

**Comment by samoy2002** [comment]
Ok, I did that but am still getting the error referenced above on the administration page.

**Comment by Patriboom** [comment]
You have access to new version via the branch "Travail"  ... I borrowed internet access for few minutes.

Monday or tuesday will come full working version.

**Comment by Patriboom** [comment]
Opportunity given to access to internet ... You'll find the patches in the branch _**branch**_
It is not a stable release yet, but it should fix your problem & show the closed issues ( https://github.com/pixeline/bugs/issues/666 )

**Comment by Patriboom** [comment]
Patches are available.
Let close this issue and keep only the #666  open if the issue is fixed.
