### ISSUE TITLE
Impossible to create a new project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#670]
With the new display of the project list on the left, the big '+' to add project has disappeared

![image](https://user-images.githubusercontent.com/79452305/139713039-eac4c6e9-ad57-4b11-9913-e0bb9c8fb439.png)

So not possible to create a new project !

Workaround is to go to the bottom of the projects menu to create a new project

![image](https://user-images.githubusercontent.com/79452305/139712993-5d6e0dca-0a5e-4c91-96cb-63e8b69db8dc.png)

**Comment by Patriboom** [comment]
Veuillez lire le billet #669 où il est mentionné que vos problèmes sont issus du dernier exercice de sauvegarde / récupération.  Une erreur s'est glissée dans la sauvegarde.  Les tables, selon l'ordre alphabétique, qui suivent la table « users » n'ont pas été créées ou sont déficientes.

**Comment by Albatros78** [comment]
J'ai fait l'update avec les 2 commandes SQL du #666 mais toujours pas possible de créer un nouveau projet comme avec le gros '+' avant ! (haut droite)

**Comment by Patriboom** [comment]
> With the new display of the project list on the left, the big '+' to add project has disappeared

Yes, this disapears.  I wanted it clean. The button was too big for nothing.

Did you really appreciate it as handy ? 
I fact, when you have your projects set ... no one does use it daily.

**Comment by Albatros78** [comment]
Yes but to go to the bottom of project page to have the option to create a project is not very useful and quick !!! No intuitive ...

Why not add a '+ ' near the title 
![image](https://user-images.githubusercontent.com/79452305/139730965-b729d7f1-2f22-49b5-bce9-c1e2ce118bf6.png)

**Comment by Patriboom** [comment]
Ok.  I'll do it like  
![image](https://user-images.githubusercontent.com/19801202/139732523-edc212a8-8ab7-4180-b838-31423abd22c5.png)

**Comment by Patriboom** [comment]
La révisionn 7q ramène le bouton vert.

Voici les améliorations de la révision 7q

Le gros bouton vert ( + ) créer un nouveau projet est de retour dans le panneau de gauche ( mais seulement lorsqu'il n'y a aucun projet en cours d'affichage)

Un nouveau format de rapport a été créé afin de rendre compte des heures soumissionnées, faites, facturées et payées.  Ça fait partie des nouvelles fonctions de calcul du temps de travail.

La souris au-dessus du nombre de billets ( dans le panneau de gauche ) affiche désormais de manière distincte le nombre de billets ouverts et le nombre de billets fermés du projet où se trouve la souris.

**Comment by Albatros78** [comment]
v7Q installé.
Ouf le signe '+' pour ajouter un projet rapidement...
Attention au responsive, pas au top !!!

![image](https://user-images.githubusercontent.com/79452305/139750849-466e47db-11ce-4398-970d-cea2eac089bc.png)


Faute de texte à corriger! 
![image](https://user-images.githubusercontent.com/79452305/139750888-a04c2973-ffd4-4b38-b30f-8f34ac513e0b.png)


Et TOUS mes billets fermés !!! à cause de la base contaminée ?

![image](https://user-images.githubusercontent.com/79452305/139750929-bdbfdca0-76e0-4e2f-8842-b0094f0aecd4.png)

**Comment by Patriboom** [comment]
Merci pour le commentaire.  Les textes français et anglais "Nouveau projet" ont été raccourci afin d'améliorer la mise en page.
Ce sera disponible prochainement.
