### ISSUE TITLE
Could be useful to assign projects by one click for an user

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#675]
Hello Patrick

Un truc pratique serait de pouvoir assigner x projets de façon très rapide pour un utilisateur.
Actuellement, il faut passer dans chaque projet et assigner l'utilisateur. L'option est là, laissons là, mais ne serait il pas possible d'avoir une liste de tous les projets disponibles dans le profil de l'utilisateur comme ici:

![image](https://user-images.githubusercontent.com/79452305/140385023-14294650-db52-4de3-8881-3e121c667a32.png)

Et de pouvoir visualiser par une case à cocher en face de chaque projet, ceux qui sont assignés et de pouvoir en assigner /d"-assigner rapidement.
C'est beaucoup plus visuel si tu as plusieurs projets....et plus rapide.

je en sais pas ce que représente le travail à faire... 

C'est une idée ...mais pratique aussi.

**Comment by Patriboom** [comment]
C'est une idée.
Gardons-la en banque pour l'instant, il y a d'autres chats à fouetter.

**Comment by Patriboom** [comment]
La révision 8t montre à quoi pourrait ressembler la bébite.
J'attends vos commentaires.

**Comment by Patriboom** [comment]
Ce sera un long travail, car je me rends compte que BUGS n'a jamais bien géré les droits.  De fait, BUGS ne travaille qu'avec le rôle défini dans la fiche de l'usager.  BUGS dorénavant (à la fin de cette séquence de travaux) travaillera à partir de droits définis dans chaque projet.  Ainsi, un usager pourra être admin dans un projet et observateur dans l'autre.  Mais il faut travailler dans les entrailles de la bête.
Vous verrez des éléments apparaître au gré des travaux, mais la prochaine publication d'un révision incluant tout cela demandera quelques semaines.

This is a big work. I'll need some weeks to achieve that because it needs to works on the BUGS fundamentals.

**Comment by Albatros78** [comment]
j'espère que ce chantier ne va pas avoir des effets de bord sur tout ce que a été réglé depuis des semaines...
J'ai un peu peur de cela !!! Mais je ne sais pas comment est structuré BUGS....
Je ne pensais pas que cela imposait une refonte de la gestion des droits sans tout casser.

J'aurai peut être dû ne rien proposer ...Lol

**Comment by Patriboom** [comment]
C'est en cours de travail.
C'était une faille importante de BUGS et nous ne venons que de la mettre en lumière.
Ce sera utile pour la suite des choses.  Alors aussi bien s'y mettre dès maintenant, puisque c'est là que nous constatons la faille.

Il y a donc deux chantiers en marche: 
- celui-ci ( gestion des droits selon le rôle assumé dans chaque projet)
- temps de travail, un petite section à terminer

Vous voyez que n'apparaît pas ici l'objet de l'autre billet, celui sur la configuration du courriel.  Ce que vous révélez là relève de l'usager.

**Comment by Patriboom** [comment]
Le chantier du temps de travail investi est fermé.  Le travail y est complet.

Nous passerons à la complétion du présent chantier, la gestion des droits selon ce qui est établi dans la table
projects_users.  Voici l'état des lieux: 
- À la création d'un nouveau projet:  l'administrateur est invité à attribuer des rôles à chaque participant qu'il ajoute au projet
- À la modification d'un projet existant: l'administrateur peut ajouter ou retirer des participants, mais aussi changer le rôle de chaque participant déjà présent.  Le rôle d'aucun participant ne peut dépasser celui de l'administrateur.

Il faut maintenant passer toutes les pages d'affichage en revue afin de conformer les boutons, les options, les fonctions disponibles à chacun en fonction de son « rôle » dans le projet. Actuellement, ces adaptations contextuelles sont faites en fonction du « rôle » de l'usager sur l'ensemble du système.

Dorénavant, donc, un administrateur - dans le système - pourrait se trouver simple "observateur" dans tel ou tel projet et ainsi être empâché de commenter dans ces projets seulement.  Ce même administrateur pourrait être « Gestionnaire » dans d'autres projets et « Administrateur » dans d'autres encore.  Il ne sera donc plus « Administrateur » mur-à-mur comme c'est le cas actuellement.  De la même façon, un « Observateur » pourrat être promu « Commentateur », « Gestionnaire » voire « Administrateur » dans un ou l'autre des projets.  Ses fonctions, boutons et possibilités seront adaptées conformément à son « rôle » dans le projet qu'il fait afficher.

L'affiche montré ci-haut n'est pour l'instant que de l'affichage.  Avant d'en faire un outil de modification et de gestion, il faut s'assurer que toutes les codes d'affichage tiendront compte de ces nouvelles fonctions accordées à l'un ou l'autre usager.

**Comment by Patriboom** [comment]
Voilà, j'ai mis en place ce qui avait été initialement demandé.
Reste à faire en sorte que ces choix soient pris en considération tout au long des affichage et autres modes d'utilisastion pertinents.

J'attends vos commentaires, pendant que je continuerai la vérification en arrière-plan des consisérations ci-haut.

**Comment by Albatros78** [comment]
OK.
Actuellement le niveau des rôles est le suivant:

- Administrateur
- Manager
- Developer
- User

Et maintenant tu parles de
- Administrateur
- Gestionnaire
- Observateur 
- Commentateur

STP, Il faudrait faire un tableau type XLS pour bien comprendre le niveau et rôle de chacun

Par ailleurs il doit donc y avoir un Super Administrateur qui lui configure tout cela.

Après tes remarques sur ces points, je vais regarder pour mieux me rendre compte.

**Comment by Patriboom** [comment]
Il ne faut pas vous soucier de la nomenclature, car celle-ci peut être modifiée par celu-ci qui installe le système.
En français, les termes que j'utilise sont: 
- Admin
- Gestionnaire
- Développeur
- Observateur

Peut-être que des outils viendront et permettront de changer ces termes.  Pour l'instant, il faut le faire dans la BDD.

**Comment by Albatros78** [comment]
OK...
Juste installé la v1.87w et pas encore testée.
Premières remarques sur la fenêtre 

![image](https://user-images.githubusercontent.com/79452305/141654089-60b9e829-3775-481d-901e-4c25640ef825.png)

- Correction sur le titre.
- Au lieu de NULL je pense qu'il serait mieux de mettre Not Used ...
- Elargir un peu la fenêtre. les titres de projets longs prennent 2 lignes et donc vont augmenter la hauteur. 
- Ascenseur... à définir la haut maximum de la fenêtre ou à configurer  !

Autant faire les modifications au fil de l'eau...

Faut que je teste un peu.

**Comment by Albatros78** [comment]
Ici
![image](https://user-images.githubusercontent.com/79452305/141654257-0c71d95b-f2e2-4351-a0eb-fe72b6a8e00f.png)

L'administrateur dans le cadre bleu est l'administrateur général et avec la flèche rouge il est administrateur sur le projet indiqué. 
C'est bien cela qu'il faut comprendre ?

**Comment by Patriboom** [comment]
`L'administrateur dans le cadre bleu est l'administrateur général et avec la flèche rouge il est administrateur sur le projet indiqué.
C'est bien cela qu'il faut comprendre ?`

Bien compris

Le titre est bon :   les points de suspensions seront automatiquement remplacés par le prénom et le nom du candidat lorsque vous les aurez définis.

L'expression « NULL »  est bonne.  Elle répond très bien à la question « Quel est le rôle de cet usager dans le projet xyz ? »  Son rôle est « NULL » et non pas « Not in use »

Ok, pour l'ascenseur.  Quant à la largeur ... euh .... j'sais pas.  Il faut y aller avec l'esthétique d'ensemble de la page.

**Comment by Patriboom** [comment]
J'ai améliorer l'apparence de la page de gestion des rôles.
En couleurs, c'est plus beau.  C'est moins évident qu'il s'agisse d'une page d'édition, cependant, mais c'est plus facile et agréable à lire.

![image](https://user-images.githubusercontent.com/19801202/141654527-3df4189d-6e0f-417b-a4b5-ef163119bf5d.png)

Prochaine révision.

**Comment by Patriboom** [comment]
Please follow tests on #684

**Comment by Patriboom** [comment]
![image](https://user-images.githubusercontent.com/19801202/141662461-910451e8-4ab3-494a-b23e-171b23830568.png)

The #684 is closed, so we're back here  ( #675 )

**Comment by Patriboom** [comment]
La révision z est disponible.
Ce me semble complet avec ça.

**Comment by Albatros78** [comment]
OK. v1.87z installée

Bravo pour les couleurs dans les roles...
Les emails ne fonctionnent plus ! (SMTP alive ou pas)
Le test du message non plus (SMTP alive ou pas)
Si trop galère, mets en remarque ton ping et on laisse comem c'était...

Pour la création d'un User il y a toujours cette option.

![image](https://user-images.githubusercontent.com/79452305/141694461-250f4559-70bc-4ce3-8d7e-5945f270c66f.png)

Je n'ai pas testé mais que ce passe t'il avec ce rôle ???  par rapport aux autres sur les projets...

**Comment by Patriboom** [comment]
Le courriels et leur test sont de nouveau fonctionnels.

**Comment by Patriboom** [comment]
`Je n'ai pas testé mais que ce passe t'il avec ce rôle ??? par rapport aux autres sur les projets...`

Pour l'instant, ça ne sert qu'à faire apparaître le bouton "Créer un nouveau projet" et quelques autres bricoles.  Nous devons le conserver.

**Comment by Patriboom** [comment]
La hauteur de la liste des projets a été limitée et un ascenseur permettra de voir les projets du bas de la liste.

**Comment by Albatros78** [comment]
v18.7ae installée.
Ascenseur OK pour la liste des projets

Mais impossible d'ajouter une projet pour un nouvel utilisateur ou même de modifier dans la liste les projets pour un user... Tout est est NULL et aucun effet avec la souris


![image](https://user-images.githubusercontent.com/79452305/142760569-67ed3838-f13f-4897-8f21-a3507374d56d.png)

**Comment by Patriboom** [comment]
Les options affichées (ci-haut « Null » partout ) sont en fonction des droits de l'utilisateur.  Si l'utilisateur qui veut inscrire un membre n'a qu'un niveau 2, les options offertes sont limitées à 0, 1 et 2.

Dites-moi le chemin que vous suivez pour arriver à ce résultat.  De mon côté, tout est fonctionnel.

**Comment by Albatros78** [comment]
Je suis en administrateur !!

**Comment by Patriboom** [comment]
Il y eut des dizaines, voire centaines, de modifications en fin de semaine.  Pouvez-vous me confirmer la persistance du problème ?

**Comment by Patriboom** [comment]
For now, a pre-release including all that and also new features  is available  at :  https://github.com/pixeline/bugs/releases/tag/v1.8_7al

Dès maintenant, en pré-lancement, tous ces correctifs et d'autres, de même que quelques nouvelles fonctions sont disponibles à l'adresse https://github.com/pixeline/bugs/releases/tag/v1.8_7al

**Comment by Albatros78** [comment]
Hello Patrick
Suis hospitalisé covid  depuis 8 jours
On verra à mon retour.
Dans l'ensemble cela va bien !


Envoyé de mon iPad

**Comment by Patriboom** [comment]
Aïe!!!  C'est bien ce que je craignais.  Prenez le temps.
