### ISSUE TITLE
Fails to upload attachments

### ISSUE THREAD

**Issue by acluk** [pixeline/bugs#68]
Version 1.5 installed by Softculous on ISP - select upload works (not on Mac Safari however) gives "http error"

Success on text comments - cannot upload attachment - on three browsers.

Uploads folder has 777 permissions.
Assistance required!
Thanks

**Comment by Patriboom** [comment]
Hello acluk, 
As I know from experience, Softaculous is usualy far away late on its updates.
May you try the version you find HERE and give feed back about upload, please.

**Comment by acluk** [comment]
Sure will - (was I expecting a link on the word 'HERE'?)
I'm not overly familiar with Github - so if you could an idea of how to get the files I need to trial would be excellent :-)

**Comment by Patriboom** [comment]
Just click on « Code » tab
There, click on green button:  « Clone or download »
According to what you're familiar with:  chose to clone or to download as ZIP
[From the current git deposit ](https://github.com/pixeline/bugs/)

**Comment by acluk** [comment]
Hello.
I believe that I've done this right.
Backup up the whole folder and copied folder 'app' to overwrite...
Now get this on launch
Unhandled Exception

Message:

syntax error, unexpected '?'
<dir>/app/laravel/lang.php on line 118

Any assistance would be appreciated.
thanks

**Comment by Patriboom** [comment]
I'll correct that.  It's from program done for  PHP 7; but you seam to use PHP 5.
Give me a minute or two.

**Comment by Patriboom** [comment]
To fix it, you can download the file  ( [app/laraval/lang.php](https://github.com/pixeline/bugs/blob/developer/app/laravel/lang.php))  from  deverloper branch or correct the line yourself usign the follwin code:

		if (is_null($default)) $default =  isset($LangEN["tinyissue"][substr($this->key, strrpos($this->key, ".")+1)]) ? $LangEN["tinyissue"][substr($this->key, strrpos($this->key, ".")+1)] : $this->key;

**Comment by Patriboom** [comment]
Comment about language issue has been moved to  https://github.com/pixeline/bugs/issues/73

**Comment by Patriboom** [comment]
Is you « bugs » program ok, now @acluk ?

**Comment by acluk** [comment]
Hi - tbh I had to move on. Thanks and good luck
