### ISSUE TITLE
Column not found when I add a 'user' role to an existing user on a new project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#684]
J'édite un utilisateur qui à déjà le role de utilisateur

Je veux lui affecter un nouveau projet en mode 'user'

![image](https://user-images.githubusercontent.com/79452305/141654510-f20af76f-1f2e-45b7-a924-543e5258ede6.png)

Je valide par Update.. et message d'erreur

Unhandled Exception
Message:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tag' in 'field list'

SQL: INSERT INTO following (user_id, project_id, project, attached, tag) VALUES (12, 3, 1, 1, 1)

Bindings: array (
)
Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\database\connection.php on line 263
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\database\connection.php(183): Laravel\Database\Connection->execute('INSERT INTO fol...', Array)
#1 [internal function]: Laravel\Database\Connection->query('INSERT INTO fol...')
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\database.php(179): call_user_func_array(Array, Array)
#3 E:\xampp\htdocs\bugtrackerok\app\application\models\user.php(284): Laravel\Database::__callStatic('query', Array)
#4 E:\xampp\htdocs\bugtrackerok\app\application\controllers\administration\users.php(42): User::update_user(Array, '12')
#5 [internal function]: Administration_Users_Controller->post_edit('12')
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('edit', Array)
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('edit', Array)
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('administration....', Array)
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#11 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(158): Laravel\Routing\Route->call()
#12 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#13 {main}

Ma table Tags est la suivante:

![image](https://user-images.githubusercontent.com/79452305/141654556-90f23b68-a69f-4006-a0c9-95af1656dffd.png)

En faisant retour arrière le mode user est indiqué...(je ne sais pas si il fonctionne !!)

![image](https://user-images.githubusercontent.com/79452305/141654583-d970bb1e-39f0-49a5-a908-517817893fdf.png)

**Comment by Albatros78** [comment]
Ensuite je remets la valeur **NULL** au projet.

![image](https://user-images.githubusercontent.com/79452305/141654607-4dfc5856-ad6c-440b-8129-382fdd58d859.png)

Et je valide. La mise à jour est OK

![image](https://user-images.githubusercontent.com/79452305/141654621-96ba4faf-b44f-4eef-9d8f-ec5580093329.png)

Mais non !!!! car il est configuré en Administrateur et pas en NULL 

![image](https://user-images.githubusercontent.com/79452305/141654635-ebd643ee-39aa-4eb3-b9ea-ae171583e819.png)

**Comment by Patriboom** [comment]
`user_id, project_id, project, attached, tag`
Il manque un s à tag.

Mise à jour disponible.

**Comment by Patriboom** [comment]
`Plusieurs essais et impossible de remettre le mode NULL...`
Je crois que c'est un souci avec la mémoire-cache.
Si vous visitez un autre page et revenez à cette page de gestion, la correction devrait être visible.

**Comment by Albatros78** [comment]
Pour le mode NULL . Non ne semble pas venir du cache... Plusieurs changement de page, login/logout et toujours le mode Administrator indiqué.

Par ailleurs pour le moment les configurations ne sont pas prises en compte. 
Actuellement c'ets le role actuel de l'utilisateur qui est le plus fort.

![image](https://user-images.githubusercontent.com/79452305/141654928-b66e8b7d-c3ca-42dd-b933-c7dc17543417.png)

ici cet utilisateur reste en mode 'User' sur tous les projets.

![image](https://user-images.githubusercontent.com/79452305/141654983-1013a0f4-2ca5-4bdf-af3c-4be5b9210c61.png)

En affectant un nouveau projet en mode developer par exemple, fait que le projet devient visible pour lui mais en mode 'user' (son rôle principal)

**Comment by Patriboom** [comment]
Je comprends la confusion que vous soulevez.

Il y a deux endroits DISTINCTS où un niveau est attribué à un usager.
D'une part, il y a son niveau général.
D'autre part il y a son niveau dans un projet.

Le niveau général permettra ou non à l'usager de créer des projets, de produire des rapports.

Le niveau dans un projet lui permettra ou non d'ouvrir de nouveaux billets, de commenter ou de modifier ce projet précis.

Le niveau général est une configuration qui est appelée à disparaître.
Si vous changez le niveau d'un usager dans un projet précis, ça n'aura AUCUN effet sur son niveau général.
Si vous changez son niveau général, ça n'aura AUCUN effet sur ses niveaux particuliers dispersés dans les projets.

Ce que vous mentionnez ci-haut démontre qu'un changement particulier n'a aucun effet sur le général; qu'un changement général n'a aucun effert sur le particulier.  C'est tout à fait normal.

Dans un premier temps, j'ai ôté l'élément « Niveau général » de la fiche de l'usager.  Mais je ne peux pas encore en arriver là, puisque toutes les corrections ne sont pas apportées. De évaluations du niveau « général » restent à débusquer un peu partout dans le code afin de les remplacer par des évaluations du niveau particulier (au projet affiché).

**Comment by Patriboom** [comment]
De retour au billlet #675 pour le développement.
Le présent billet n'a permis que de déboguer une faute de frappe.

**Comment by Albatros78** [comment]
Heuuuu ...

Tu dis: "Le présent billet n'a permis que de déboguer une faute de frappe"

Non pas d'accord...
Il y a  un problème de changement de rôle qui semble ne pas fonctionner pour remettre NULL dans le champ...

Donc ce ticket n'est pas terminé !

Et j'ai du mal à suivre les tickets... Ouverts, fermés, réouverts ...etc on change, on revient.... etc....

Je suis peut être fatigué , mais je n'arrive pas à suivre.

**Comment by Patriboom** [comment]
Ok, 

je viens de comprendre le souci que vous voyez.  L'affichage de l'information ne suit pas le contenu des valeurs lues en BDD, car - oui - les modifications sont bien apportées en BDD.  Je vous reviendra avec la correction à l'affichage.


                   ____________________                                                      billet 684
________/   . . . . . . . . . . . . . . . . . . . . \_____________________          billet 675   _____________________

Quant aux suivi des billet.  Voyez celui-ci comme un apartée au premier auquel nous revenons pour continuer le travail

Quelques minutes.  C'est une correction que j'avais faite hier, mais je j'ai perdue dans un petit souci logiciel.

**Comment by Patriboom** [comment]
C'est corrigé

![image](https://user-images.githubusercontent.com/19801202/141662408-947c47f7-dfcb-45ed-8a2c-bbdbda773111.png)

Nous revenons cond au billet #675   la boucle du 684 est terminée ... peut-être y aura-t-il une autre boucle, mais l'axe principal restera le 675.
