### ISSUE TITLE
Undefined offset by clicking on project editing

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#688]
En cliquant ici 

![image](https://user-images.githubusercontent.com/79452305/141694567-bb3b0964-2c22-4cd9-8a5b-dc6dff630a85.png)

j'ai ce message d'erreur pour tous les projets.

Unhandled Exception
Message:
Undefined offset: 0
Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code on line 38
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 38)
#1 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(38): Laravel\{closure}(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 38, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(406): Laravel\View->render()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(341): Laravel\View->data()
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\response.php(237): Laravel\View->__toString()
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(174): Laravel\Response->render()
#10 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#11 {main}

**Comment by Patriboom** [comment]
Je n'arrive pas à reproduire l'erreur.
Est-ce encore la BDD de travail ?

**Comment by Albatros78** [comment]
Voila la base qui doit être stable normalement.


[database_20211114231217.zip](https://github.com/pixeline/bugs/files/7534790/database_20211114231217.zip)

**Comment by Albatros78** [comment]
En production j'ai la v1.87k et pas l'erreur...
peut être suite aux dernières modifications des rôles ? (que je n'ai pas en production)

**Comment by Albatros78** [comment]
v1.87ab installée.

Correction OK.

Mais impossible d'ajouter un utilisateur. Normal avec le changement des rôles ?
Mais c'était bien aussi de pouvoir le faire par içi, si oubli.


![image](https://user-images.githubusercontent.com/79452305/141785157-4220d251-9bc4-46a5-9064-a0532faf1f70.png)

**Comment by Patriboom** [comment]
Assurez-vous de bien recharger la page javascript  en faisant   « Shift - clic » sur recharger la page
Autrement, vous pouvez inscrire dans la barre d'adresse : 
http://..../Tickets/app/assets/js/app.js  et forcer le rafraîchissement de la page  (  F5  ou  clic sur "recharger la page" ) 

Testé et fonctionel.

**Comment by Albatros78** [comment]
Marche pas chez moi 
CTRL+ F5 pour rafraîchir le cache de Chrome 
toujours bouton vide pour ajouter un utilisateur

![image](https://user-images.githubusercontent.com/79452305/141805579-50ae3d34-8b3c-426a-b702-fc97f910cbf0.png)

Et je ne sais pas ou  mettre ton URL.
http://localhost/bugtrackerok/project/6/edit/Tickets/app/assets/js/app.js
ou cela
http://localhost/bugtrackerok/Tickets/app/assets/js/app.js

Mais bon rafraîchir le cache avec un script, on peut pas laisser cela pour l'utilisateur non plus !

**Comment by Patriboom** [comment]
Ce n'est pas un problème pour l'utilisateur, car sa mémoire cache ne sera pas occupée par de vieux fichiers.

**Comment by Albatros78** [comment]
Je reçois une insulte :-)

![image](https://user-images.githubusercontent.com/79452305/141819569-70d8877a-6e1c-4e4a-b482-efa930190603.png)

**Comment by Patriboom** [comment]
`Je reçois une insulte`
Je croyais avoir écrit  « Je vais me coucher, je regarderai cela demain. »
Mes phrases de travail son parfois étonnantes!


`Je n'ai pas de répertoire Tickets !!!! si on cherche un répertoire`

Pourquoi répertoire « Tickets » ? 

c'est .app/storage/

N'y perdez pas de temps.  Je ne pourrai pas travailler là-dessus aujourd'hui.  Je vous reviendrai lors qu'il y aura du dévloppement.

**Comment by Albatros78** [comment]
v1.87ae installée
tout semble être bien !
merci
