### ISSUE TITLE
Bad labels into reports

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#689]

**Comment by Albatros78** [comment]
Ici une petite correction.

![image](https://user-images.githubusercontent.com/79452305/141700578-97a57c58-29b1-4291-9d3d-c0839271bf8b.png)

**Comment by Patriboom** [comment]
Ok, merci.
J'y verrai.

**Comment by Patriboom** [comment]
Corrigé, merci.

Disponible dans la révision 7aa.

**Comment by Albatros78** [comment]
OK
