### ISSUE TITLE
Not possible to add a user to a project via left sidebar

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#692]
v1.87ab installée.

Impossible d'ajouter un utilisateur...
Le clique ne fonctionne pas !

![image](https://user-images.githubusercontent.com/79452305/141784727-f33c6f71-e7c0-4adf-8de2-52aa3a8224cf.png)

**Comment by Albatros78** [comment]
Houla la 

Les cliques fonctionnent mais ne sont pas visibles au moment ou on le fait...!!!!

![image](https://user-images.githubusercontent.com/79452305/141785373-12a811c9-7360-4fd2-8d45-f5efd66d400d.png)

**Comment by Patriboom** [comment]
C'est de retour: fonctionnel.

**Comment by Patriboom** [comment]
Parlant du panneau de gauche, j'ai ajouté l'option - dans la page des configurations personnelles - de faire apparaître ou non le menu déroulant des projets.  Pour ceux qui ont peu de projets, c'est plus léger ainsi.

**Comment by Albatros78** [comment]
v.187ae installée

Bravo pour le menu déroulant optionnel. Belle option !
L'ajout des utilisateurs est redevenu fonctionnelle !
