### ISSUE TITLE
Unworking functions definition for error management

### ISSUE THREAD

**Issue by Patriboom** [pixeline/bugs#694]
Ici nous suivrons la discussion sur la gestion des erreurs.
Comme dit précédemment, les personnalisations ne sont pas encore enregistrées dans le système, n'ont donc aucun effet pour l'instant.

La question de la phrase incomplète est un bon point,  J'y verrai prochainement.

**Comment by Patriboom** [comment]
Voici une version fonctionnelle.
Je n'y ai pas mis de message méchant, cette fois.  Je ne veux plus en échapper ;)

**Comment by Albatros78** [comment]
v1.87ae installée
A suivre à l'usage...
Super pour le message personnalisable et son aperçu... C'est bien plus clair  !

**Comment by Patriboom** [comment]
Je tente ici l'usage de la fonction try {} catch {} dans SendMail.
Donnez-m'en vos commentaires.
La version finale n'est pas encore là.  Afin de colmater une brèche de sécurité, tous les fichiers du répertoire ajax sont en révision et réorganisation.

**Comment by Patriboom** [comment]
La façon de faire n'était pas bonne.  J'ai corrigé.  Les erreurs seront désormais gérées en courriel.

Ce écrit, les travaux majeurs d'intégration de toutes les procédures ajax dans les procédures laravel sont faits; ne reste que SendMail à traiter.

**Comment by Patriboom** [comment]
For now, a pre-release including all that and also new features  is available  at :  https://github.com/pixeline/bugs/releases/tag/v1.8_7al

Dès maintenant, en pré-lancement, tous ces correctifs et d'autres, de même que quelques nouvelles fonctions sont disponibles à l'adresse https://github.com/pixeline/bugs/releases/tag/v1.8_7al
