### ISSUE TITLE
Error  Undefined property: stdClass::$en after installation of last code

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#718]
J'ai téléchargé le dernier code.... Je n'en connais pas la version car crash après le login

DashboardAn overview of all the activity involving your active projects.
AFS BugTracker
Comment
"Now available directly into the sources.  " by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-10-24 18:05
Unhandled Exception
Message:
Undefined property: stdClass::$en
Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code on line 14
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14)
#1 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(14): Laravel\{closure}(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(77): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtrackerok\app\laravel\response.php(237): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(174): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#15 {main}
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS

Lorsque je clique ici:
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS

Sur la page d'accueil j'ai la v1.87as

**Comment by Albatros78** [comment]
Et je trouve la page de login assez moche: couleur et texte trop gros

![image](https://user-images.githubusercontent.com/79452305/147564771-1b830caf-5cd8-42f5-80f0-c3ab6cb22399.png)

Pb de CSS ?

**Comment by Patriboom** [comment]
Étrange, étrange!

Sur mes deux navigateurs j'obtiens pourtant le résultat suivant: 
![BUGS_Login](https://user-images.githubusercontent.com/19801202/147567116-1ea047ec-6af5-4f52-af51-f2131f1c86a3.png)

Je tenterai de reproduire ce que vous me montrez ci-haut. 
Quel fureteur utilisez-vous ?

**Comment by Patriboom** [comment]
Bonjour Albatros78, 

dans le premier message (ci-haut), vous mentionnez un crash à la connexion.
Un peu plus bas, dans le même message, vous laissez entendre que la connexion a réussi.
Pouvez-vous me dire ce qui se passe lorsque vous 
- déconnectez
- videz la mémoire cache du fureteur
- tentez une reconnexion.

À la lecture des détails de votre message, j'ai cru un moment qu'il s'agissait d'un problème de langue.
Maintenant que vous avez réussi un première connexion, je crois que vous ne rencontrerez plus ce problème.  Si c'est bien le cas (le problème est résolu), la source du crash mentionné serait dans l'absorption par BUGS des nouvelles fonctionnalités .... dans la lecture des préférences personnelles.  
J'attends votre retour.
Merci de votre compréhension.

**Comment by Patriboom** [comment]
Si le problème vient d'une non-définition de canevas, la révision 18_at  corrige cela.

**Comment by Albatros78** [comment]
J'utilise Chrome
je viens de vider le cacher par CTRL + F5.
Au login j'ai cet affichage grossier.

![image](https://user-images.githubusercontent.com/79452305/147592472-8cf39650-93c9-4e08-8369-1719ea115e5b.png)

Après le login je tombe sur cette page

![image](https://user-images.githubusercontent.com/79452305/147592508-8c43b75a-6859-4eea-8870-e45ce6d36403.png)


et en cliquant sur le lient du bas:  Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS
La page s'affiche.

![image](https://user-images.githubusercontent.com/79452305/147592566-8807a290-1f30-4940-a22f-2fbb5bf26879.png)

Si je clique sur le menu Dashboard je retrouve la même erreur

DashboardAn overview of all the activity involving your active projects.
AFS BugTracker
Comment
"Now available directly into the sources.  " by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-10-24 18:05
Unhandled Exception
Message:
Undefined property: stdClass::$en
Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code on line 14
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14)
#1 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(14): Laravel\{closure}(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(77): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtrackerok\app\laravel\response.php(237): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(174): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#15 {main}
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS

**Comment by Albatros78** [comment]
v1.87at installée. Même erreurs !!

**Comment by Patriboom** [comment]
Avez-vous installé les mises à jour de la BDD
- install/update_v1-8_7p.sql
- install/update_v1-8_7r.sql
- install/update_v1-8_7s.sql
- install/update_v1-8_7u.sql
- install/update_v1-8_7ag.sql   (la petite dernière et non la moindre )  ?

Je tenterai de reproduire le problème en « défaisant » ma mise à jour install/update_v1-8_7ag.sql 
Si j'obtiens la même erreur que vous, ça me permettra de corriger.

**Comment by Patriboom** [comment]
Tel qu'annoncé ci-haut, mise à jour automatisée de la structure BDD selon les fichiers .sql logés dans le répertoire install.

**Comment by Albatros78** [comment]
Je pense que la v1.8 7au est installée !!

La page login affiche cela.

![image](https://user-images.githubusercontent.com/79452305/147683442-b5b7e622-1ff0-4173-aede-b59fefa0e084.png)

Il ne se passe rien en cliquant sur les liens. J'ai donc fait les mises à jours à la main dans ma base, mais la page login reste la même.

Ci joint ma base pour inspection des problèmes.
[afs_bugtracker.zip](https://github.com/pixeline/bugs/files/7789785/afs_bugtracker.zip)

**Comment by Patriboom** [comment]
C'est le javascript qui devait prendre en charge la tâche ici.  Je vais faire en sorte que les liens soient utilisables manuellement et vous reviendrai.  J'ai testé plusieurs fois localement et tout fonctionne bien.  Il faut adapter aux besoins de tous, merci de votre patience.

**Comment by Patriboom** [comment]
Voilà, la possibilité est offerte de mettre à jour manuellement ou automatiquement.
Si vous restiez bloqué sur la page d'accueil c'est parce que le fichier install/historique.txt n'a pas été mis à jour.
La mise à jour que je viens de rendre disponible apportera ces modifications à **historique.txt** nécessaires à la continuité.

**Comment by Albatros78** [comment]
Moi c'est juste beau, mais il ne se passe rien en cliquant !!!
:-)

![image](https://user-images.githubusercontent.com/79452305/147689384-04c65fb0-0590-4d32-97aa-d97a60b1bc48.png)

**Comment by Patriboom** [comment]
Ce qui est étrange ici, c'est que mon fureteur permît de soumettre le fourmulaire comme si rien n'était.  Il y avait un omission évidente dans le code.  C'est corrigé et testé sous deux fureteurs (firefox et chromium) :  fonctionnel.
Version 1.8 révisino 7aw en ligne.

**Comment by Albatros78** [comment]
Même chose en installant le dernier zip... aucun effet en cliquant 


regarde en haut de mon navigateur, ca tourne en rond !!!
![2021-12-30_17h35_29](https://user-images.githubusercontent.com/79452305/147770851-aca2653e-2f0d-46b4-ae8e-15d94238497b.gif)

**Comment by Patriboom** [comment]
C'est comme si vous n'aviez pas de fichier install/historique.txt; étrange.
Merci encore d'être aussi patient.  Voici une correction qui devrait faire le travail attendu.
L'image soumise par vous montre que le système automatique de mise à jour tente de fonctionner.
Je le désactiverai afin de procéder au premier test.  Faites une seule mise à jour.
Si celle-ci fonctionne bien, vous pourrez ôter les marques de commentaire de la ligne 97
Cette dernière est ainsi: 
`//			echo '<script>document.getElementById(\'form_MAJsql\').submit();</script>';`
et devra - après une tentative réussie de bouton cliqué - être ainsi : 
`			echo '<script>document.getElementById(\'form_MAJsql\').submit();</script>';`


C'est disponible.

**Comment by Albatros78** [comment]
Ok... 
Avant de commencer ,dans quel fichier je dois enlever le commentaire si cela fonctionne pour une mise à jour ?

**Comment by Patriboom** [comment]
Oups, désolé, j'ai oublié cette information importante !
Le fichier ** app/application/views/layouts/login.php**

**Comment by Patriboom** [comment]
L'autre prossibilité qui expliquerait ce souci que vous rencontrez se trouve dans les permissions accordées au serveur apache.
Il faut qu'Apache ait le droit de modifier le fichier install/historique.txt  
Pour cela, dans un explorateur de fichiers, cliquez à l'aide du  bouton de droite sur le nom du fichier, allez dans les « propriétés » et les droits. Accordez le droit d'écriture à tous.

**Comment by Albatros78** [comment]
Installée.
En cliquant sur la 1ere mise à jour, il ne se passe rien, ou enfin je ne sais pas ... Ni message et le bouton de mise à jour est toujours présent.
si j'enlève le commentaire de la ligne 97, cela tourne en rond dans mon onglet comme dans mon image précédente.
Le fichier .txt est bien en read/write.

Mais normalement ma base (envoyée précédemment) est à jour puisque je l'ai fait manuellement fichier par fichier. Pourquoi dans ce cas je n'ai pas la page de login ?
Peut être pas la peine de s'énerver et perdre du temps sur ces mises à jours qui seront intégrées dans le zip final !

**Comment by Patriboom** [comment]
J'ai tout mis en commentaire, vous ne serez donc plus importuné par la vérification des mises à jour.
J'y retravaillerai plus tard.

**Comment by Albatros78** [comment]
Je viens d'installer le dernier zip

Erreur ci dessous... Grrrrrr.

DashboardAn overview of all the activity involving your active projects.
AFS BugTracker
Comment
"Now available directly into the sources.  " by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-10-24 18:05
tag update
Fixedtag added in Configure email sending into HTML and not plain text by Axel FALCK 
2021-10-24 18:04
Comment
"OK. Configuration is known and doucmented on how to  " by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-09-13 11:00
tag update
Not a bug but configtag added in Configure email sending into HTML and not plain text by Axel FALCK 
2021-09-13 11:00

Unhandled Exception
Message:
Undefined index: en

Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code on line 29
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 29)
#1 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(29): Laravel\{closure}(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 29, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(77): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtrackerok\app\laravel\response.php(237): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(174): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#15 {main}
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS
90

**Comment by Albatros78** [comment]
Perso je préfère la page de login d'avant comme ci dessous:

![image](https://user-images.githubusercontent.com/79452305/148555487-fbd7702e-6f12-400c-a2b0-a777d973e6fa.png)


et pas 

![image](https://user-images.githubusercontent.com/79452305/148555536-999e1118-e635-48ca-ba9b-c6761466088b.png)


de plus la couleur verte du fond est pas top !
(avis perso)

**Comment by Albatros78** [comment]
Ou laisse l'administrateur choisir la couleur du fond  par une option !
Mais les polices sont trop grosses je trouve.

**Comment by Albatros78** [comment]
Oui j'utilise l'anglais.

Lorsque je clique ici sur la page d'erreur j'arrive bien dans l'interface et tout semble OK.

![image](https://user-images.githubusercontent.com/79452305/148582948-a64be6fd-6578-47c5-9721-068a98571d25.png)


Sauf lorsque je clique sur le menu dashboard je retrouve l'erreur.

**Comment by Patriboom** [comment]
Bonjour, 

   Je n'arrive toujours pas à reproduire votre problème.  Pouvez-vous tenter la correction suivante dans votre PHPmyAdmin -> commande SQL:

`DELETE FROM users_activity WHERE id=55;`

Vérifiez aussi le fichier
../app/application/languages/en/tinyissue.php
il doit y avoir onze entrées en lien avec les **_tags_** ... Voici la liste complète que vous devriez trouver aux lignes 287 à 297

`'tag_added' => 'tag added', `
`'tag_has_been_created' => 'Tag has been created!',`
`'tag_has_been_updated' => 'Tag has been updated!',`
`'tag_removed' => 'tag removed',`
`'tag_update' => 'tag update',`
`'tag' => 'Tag',`
`'tags_added' => 'tags added',`
`'tags_bgcolor' => 'Background',`
`'tags_ftcolor' => 'Font color for tag',`
`'tags_removed' => 'tags removed',`
`'tags' => 'Tags',`

**Comment by Albatros78** [comment]
Le fichier ../app/application/languages/en/tinyissue.php avec les tags est OK

Je viens de supprimer la ligne dans la base.

Toujours même erreur lorsque je clique sur 'Entrer' pour me connecter.

**Comment by Patriboom** [comment]
J'ai enfin réussi à reproduire l'erreur.  Je vous reviendrai.

**Comment by Patriboom** [comment]
Bon, c'est fait!!!!
Correction disponible.
Merci de votre patience.

**Comment by Albatros78** [comment]
Hé ben voilà Patrick.... Bravo plus d'erreur...

Juste cet affichage que je trouve ..... un peu beurkkkkk :-)

![image](https://user-images.githubusercontent.com/79452305/148755031-012d7920-d853-4e5f-9892-3a4523def89d.png)

On peut faire mieux ?
