### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by Patriboom** [pixeline/bugs#73]
Hello.
I believe that I've done this right.
Backup up the whole folder and copied folder 'app' to overwrite...
Now get this on launch
Unhandled Exception

Message:

syntax error, unexpected '?'
<dir>/app/laravel/lang.php on line 118

Any assistance would be appreciated.
thanks

**Comment by Patriboom** [comment]
That is from using PHP5 while bugs begins to turn into PHP7.
I've downgraded code into PHP5 in developer version.

To fix it, you can download the file  ( [app/laraval/lang.php](https://github.com/pixeline/bugs/blob/developer/app/laravel/lang.php))  from  deverloper branch or correct the line yourself usign the follwin code:

		if (is_null($default)) $default =  isset($LangEN["tinyissue"][substr($this->key, strrpos($this->key, ".")+1)]) ? $LangEN["tinyissue"][substr($this->key, strrpos($this->key, ".")+1)] : $this->key;

**Comment by acluk** [comment]
Hello
Appreciate the help - and here's a report of the result my end.
The lang.php was changed and overwritten via FTP - Whilst I can now log on and see the issues listed (noting new style BTW) - drilling through results in further errors - ie

Unhandled Exception

Message:

Error rendering view: [project/index/issues]

Division by zero
Location:

/PATH/app/application/views/project/index/issues.php on line 102
Stack Trace:

#0 /PATH/app/laravel/laravel.php(42): Laravel\Error::native(2, 'Division by zer...', '/home/divineedu...', 102)
#1 /PATH/app/laravel/view.php(386) : eval()'d code(102): Laravel\{closure}(2, 'Division by zer...', '/home/divineedu...', 102, Array)
#2 //PATH/app/laravel/view.php(386): eval()
#3 /PATHapp/laravel/view.php(353): Laravel\View->get()
#4 /PATH/app/laravel/view.php(447): Laravel\View->render()
#5 /PATH/app/laravel/view.php(372): Laravel\View->data()
#6 /PATH/app/laravel/view.php(353): Laravel\View->get()
#7 /PATH/app/laravel/view.php(447): Laravel\View->render()
#8 /PATH/app/laravel/view.php(372): Laravel\View->data()
#9 /PATH/app/laravel/view.php(353): Laravel\View->get()
#10/PATH/app/laravel/view.php(590): Laravel\View->render()
#11 /PATH/app/laravel/response.php(246): Laravel\View->__toString()
#12 /PATH/app/laravel/laravel.php(177): Laravel\Response->render()
#13 /PATH/index.php(15): require('/home/divineedu...')
#14 {main}

All rather troublesome I fear! Any thoughts?
Thanks

**Comment by Patriboom** [comment]
I fixed that.
Thanks for patience and help.

**Comment by cybersholt** [comment]
Hi,

I ran into the same issue on a new install of this, apache / php 5.6, mine was in the same file: 

/app/application/views/project/issue/index.php on line 32

I checked the variable and it was null so a simple fix was this added to line 32

`if (@$issue->duration === 0||@is_null($issue->duration)) { $issue->duration = 30; }`

**Comment by Patriboom** [comment]
Thanks cycersholt, 
I'll add you contribution to the file.

**Comment by cybersholt** [comment]
Hi Patriboom,

No problem there are a few more issues that were resolved with the same method, I'll swing back by when I get a chance and let you know where they are as well.  

Cheers
