### ISSUE TITLE
Welcome message not displayed

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#731]
Hello

Ici le message n'est pas affiché !!!

![image](https://user-images.githubusercontent.com/79452305/148755635-e93aacb7-990d-44c5-830d-21abc28d6402.png)

Rien de grave !

**Comment by Patriboom** [comment]
Il n'y a rien de plus à afficher.  Supprimer la virgurle suffirait.
Néanmoins, je modifierai la présentation pour lier « Bienvenue » et le nom de l'usager.

Quant à l'écran d'accueil, je n'aime pas le vert vomi non plus.  Je modifierai, mais je ne reviendrai pas à la version antérieure que je trouvais trop froide.

**Comment by Albatros78** [comment]
Mais il faut laisser le choix à l'administrateur de changer la couleur du fond de page.

**Comment by Patriboom** [comment]
Non. Cette page est affichée trop brièvement pour que ça vaille la peine d'investir du temps de programmation.

**Comment by Albatros78** [comment]
OK . pas de problème... mais pas ce vert please !!!!!

**Comment by Patriboom** [comment]
Le code est prêt, mais pas encore disponible.  Ça ira plus tard dans la journée ou demain pour la mise en disponibilité du code.

Vert vomi ... c'est fini.
