### ISSUE TITLE
Database updates not working with v1.87ax

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#732]
Hello

Dans le menu administration j'ai cela affiché .

![image](https://user-images.githubusercontent.com/79452305/148808726-0d005f5c-877d-4741-baee-57359ebfbcd3.png)

Mais rien ne se passe en cliquant sur un lien !

Il y a bien cela dans le bas du navigateur, mais pas de popup ou message !

![image](https://user-images.githubusercontent.com/79452305/148808869-e277788b-0b4a-4a01-ba1f-3e6437ce90fb.png)

**Comment by Patriboom** [comment]
Ce n'est pas prêt.
C'est la nouvelle version de mise à jour qui est en cours de construction.  Je voulais mettre l'accent sur l'erreur antérieure, j'ai laissé glisser du code incomplet.  Ne vous en inquiétez pas.

**Comment by Patriboom** [comment]
Version 1.8 correctif 2ba  disponible.
Mise à jour de la BDD automatisée en login, commandée en admin
Le suivi des mises à jour de BDD est désormais assumé par la BDD dans la table  « update_history » 
Les mises à jours structurelles seront notées là aussi, sans pour autant que des modifications au processus de mise à jour soit modifié.

Ici sont mes dernières corrections.
Le projet prendra un pause de modifications quand tout ceci sera éprouvé et approuvé.  La version « stable » sera alors publiée et laissée telle quelle au cours des prochains mois.

**Comment by Albatros78** [comment]
Hello Patrick.
Installée et voilà le résultat.

![image](https://user-images.githubusercontent.com/79452305/150774945-5fc75aef-c13d-450a-a2a3-2aad0367f100.png)

et

![image](https://user-images.githubusercontent.com/79452305/150774672-9e974216-62a2-48d0-a3f0-7334eef9613d.png)

Impossible d'aller plus loin... Ca tourne, ca tourne...

**Comment by Patriboom** [comment]
Ouille!!!!
J'ai ôté la boucle, mais j'ai gardé le système de mise à jour dans la page administration.
Voyant les mises à jour que votre système tente de faire, je vérifierai s'il y a là des codes mal tournés.
En attendant, ce sera fonctionnel chez vous avec avec mise à jour disponible ( révision 7bb )

**Comment by Albatros78** [comment]
v1.87bb installée.

Login OK et j'ai fait les mises à jour via l'administration et la table update _history est mise à jour.

Peut être qu'il n'est pas utile de chercher pour les mises à jour sur la pgae de login si cela fonctionne.
Par contre ce qui serait bien c'est de faire apparaître un message après le login si la mise à jour  de BUGS nécessite de faire des update de la base. 
Ainsi l'utilisateur sait si il y a des mises à joru à faire sans aller dans le panneau d'aministration.

Par contre le fond de la page de login est toujours beurkkkkk.

**Comment by Patriboom** [comment]
Les mises à jour nécessaires sont déjà signalées par la couleur rouge du numéro de version ( sous le logo BUGS, en haut à gauche).  S'il n'y a pas de mise à jour à faire, la version est écrite en blanc.  S'il y a des mises à jour à faire, la version est écrite en rouge.

J'ai corrigé les erreurs, car la page d'administration et la page « login » utilisent le même code.  Si ça bloquait en « login », c'est dire que seule la mention de la MAJ est disparue de la liste, mais son action n'a pas été appliquée.  En faisant paraître de nouveau la page « administration » vous retrouverez la mise à jour que le code n'a pas su interpréter (c'est ce qui faisait bloquer la page « login » )   Dans quelques minutes, vous trouverez la mise à jour qui fait les mises à jour correctement.  Si tout va bien, ce sera la fin du développement et le début d'un long congé.

Au contraire, j'aime bien cette nouvelle page de présentation:  un soleil levant qui met en évidence le logo BUGS.

**Comment by Albatros78** [comment]
Je vais tenter de récupérer ma base qui est en ligne pour quelques clients avec une version 1.87k et je vais localement la réinstaller et faire un update avec 1.87bb et voir si tout baigne....

Ensuite je te donnerais mon feedback...

**Comment by Albatros78** [comment]
Bon
J'ai la v1.87bb en localhost qui fonctionne bien.

Je récupère la base d'une v1.87k
J'installe les tables dans une nouvelle base.
Je modifie mon fichier config.app.php pour mettre cette nouvelle base dans les paramètres
Je me connecte
et après le login ... patatrac...

DashboardAn overview of all the activity involving your active projects.
AFS BugTracker
Comment
"Fixed & customizable now into the core of software. Tes..." by Axel FALCK on issue Configure email sending into HTML and not plain text
2021-11-12 15:47
Closed
Configure email sending into HTML and not plain text was closed by Axel FALCK 2021-11-12 15:47
Unhandled Exception
Message:
Undefined property: stdClass::$en
Location:
E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code on line 14
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14)
#1 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(14): Laravel\{closure}(8, 'Undefined prope...', 'E:\\xampp\\htdocs...', 14, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#3 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#4 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353) : eval()'d code(77): Laravel\View->__toString()
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(353): eval()
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(406): Laravel\View->render()
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(341): Laravel\View->data()
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(324): Laravel\View->get()
#11 E:\xampp\htdocs\bugtrackerok\app\laravel\view.php(534): Laravel\View->render()
#12 E:\xampp\htdocs\bugtrackerok\app\laravel\response.php(237): Laravel\View->__toString()
#13 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(174): Laravel\Response->render()
#14 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#15 {main}
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS

Si je clique sur le lien BUGS j'arrive dans l'interface
Mais en cliquant à nouveau sur Dashboard j'ai ce message 
En cliquant ensuite sur Administration j'ai tout cela qui s'affiche.. Normal je pense...

![image](https://user-images.githubusercontent.com/79452305/151817152-5a52cce2-7eaa-4e7e-a69e-4411678da2d3.png)

Bon je n'ai pas fait les updates car il faut peut être corriger l'erreur avant

Tu me dis quoi faire please

**Comment by Albatros78** [comment]
Je pense que l'erreur est là car la base n'est justement pas à jour... comme elle devrait être

**Comment by Patriboom** [comment]
Je reprendrai l'intégralité de votre exercice en espérant obtenir le même résultat.
Pour l'instant, si vous désirez travailler avec votre BDD, vous pouvez appliquer les mises à jour dont le numéro est semblable ou plus grand que 1.8-7k les autres étant déjà incluses dans la version installée.
Il me faudra quelques jours pour analyser tout cela et mettre en place les correctifs nécessaires.
Merci de votre retour de test.

**Comment by Albatros78** [comment]
Voila la base en question
[afsof357059_16yselj.zip](https://github.com/pixeline/bugs/files/7974647/afsof357059_16yselj.zip)

**Comment by Albatros78** [comment]
Tu me dis de faire les mises à jour supérieures à 1.87k.
Mais pourquoi y a t'il de la version 1_2, 1_3 qui apparaît dans la liste des mises à joru, si elle sont déjà incluses ? 
Petit réglage interne ?

Je dois donc faire les updates à partir de 1.87m ? c'est bien cela ?

**Comment by Patriboom** [comment]
Bonjour, 

	non, ne faites rien pour le moment. Je dois d'abord faire mon
analyse.


On Tue, 01 Feb 2022 01:12:46 -0800
Albatros78 ***@***.***> écrivites:

> Tu me dis de faire les mises à jour supérieures à 1.87k.
> Mais pourquoi y a t'il de la version 1_2, 1_3 qui apparaît dans la
> liste des mises à joru, si elle sont déjà incluses ? Petit réglage
> interne ?
> 
> Je dois donc faire les updates à partir de 1.87m ? c'est bien cela ?
> 
> 
> 










---

Soyez artisans de paix.

Patrick Allaire, ptre

**Comment by Albatros78** [comment]
Ok docteur :-)

**Comment by Albatros78** [comment]
Bon je suis en test... donc si il y a de la casse, je peux recommencer...

**Comment by Patriboom** [comment]
Comme vous voulez.  C'est très apprécié.

Je ne veux pas vous faire du temps, car - comme écrit ci-haut - je
n'aurai de disponibilité pour cela que plus tard au cours de la semaine.

On Tue, 01 Feb 2022 04:57:54 -0800
Albatros78 ***@***.***> écrivites:

> Bon je suis en test... donc si il y a de la casse, je peux
> recommencer... 
> 










---

Soyez artisans de paix.

Patrick Allaire, ptre

**Comment by Albatros78** [comment]
Ok j'ai fait les updates depuis v1.87m.
Même erreur après le login
J'ai fait tous les autres updates de la liste
Même erreur après le login

Pour info, dans les 2 cas, cela est quasi instantané...!
La table history est là

![image](https://user-images.githubusercontent.com/79452305/152018870-f650520e-53c2-4104-ae74-b47ac2ba23bf.png)


Mais lorsque je regarde le fichier install\update_v1_8_7p.sql il y a cela dans le fichier:
UPDATE users SET preferences = replace(preferences, ";", "&"); 
UPDATE users SET preferences = replace(preferences, "!", "&"); 

Mais dans la base j'ai cela ...
![image](https://user-images.githubusercontent.com/79452305/152019123-d35246b3-7deb-4b2a-b7dc-49667364dd18.png)
Les remplacements ne sont pas faits on dirait.

Je pense que aucun fichier. sql n'a été exécuté sur la base !

Je les lance à la main pour voir ?

**Comment by Albatros78** [comment]
Effectivement par le panneau d'aministration en cliquant sur les fichiers SQL cela n'a pas fait les mises à jour.
J'ai fait les mises à jours manuellement dans MyphpAdmin
Logout et login
même erreur.

**Comment by Patriboom** [comment]
C'est ici le dernier élément à mettre au point pour finaliser la version version 8.7

Ne reste que la mise à jour des structures BDD qui fonctionne bien à partir de 8.6g et jusqu'aux dernières modifications.
Les nouveaux usagers n'auront pas ces problèmes.
Le travail à faire est de s'assurer que les MAJ 1.1 à 8.6 fonctionnent elles aussi avec autant de succès pour les anciens usagers.

Je ferai les tests nécessaires avant la diffusion de la version 8.7 finale
S'il devait y avoir d'autres modifications à BUGS, ce serait en version 8.8 qui n'est pas encore dans la mire.

**Comment by Patriboom** [comment]
Il ne faut pas oublier 

![image](https://user-images.githubusercontent.com/19801202/152684053-265e2130-432b-43aa-a134-a1d36eca75c1.png)

Les changements de page de semblent pas fonctionnels hors de la colonne des billets fermés.

**Comment by Patriboom** [comment]
Samoy2002 wrote

```Good morning,```
```I downloaded all the files this morning, uploaded them to the server, and it updated to 1.8 - 7be ```
```while I believe stable versionis higher than that. I did run all the database queries to update, and```
``` yet I am still getting an error  on the admin page of "Your database needs to be updated" ```
```so I tried running all the updates again without any luck. Can you help me figure out what I am ```
```missing to go to the latest release?```

Only the so called « stable » is the stable version.  1.7 - 7be is still in master as « work in progress »
The next stable version waits for this fix to come out.

**Comment by Patriboom** [comment]
Update will be available as soon as gitHub will permit it.  For now, it looks like too slow or blocked.

**Comment by Patriboom** [comment]
Mise à jour disponible.

Patch available in «master» only, not yet in «stable» .

**Comment by Patriboom** [comment]
Waiting for you comments to launch the next « stable » release.

**Comment by Albatros78** [comment]
Hello Patrick,

Je viens de télécharger le dernier zip... 
Et je me retrouve avec la page de login comme ci dessous, bloqué . rien ne se passe.

![image](https://user-images.githubusercontent.com/79452305/153850778-b59a7436-7fd0-4447-bb23-e00a77252fc6.png)

**Comment by Patriboom** [comment]
Le dernier zip ne contient plus de fichier
update_v1-1 ....

Le premier fichier de ce genre est désormais le update_v1-5_8...


Veuillez comparer votre répertoire  install à ceci :   https://github.com/pixeline/bugs/tree/master/install
Votre répertoire install doit être conforme à ceci https://github.com/pixeline/bugs/tree/master/install  et tout ira bien.

**Comment by Patriboom** [comment]
Mais attendez, je vais coder quelque chose qui règlera tout cela pour vous et pour les autres.

**Comment by Patriboom** [comment]
Voilà, c'est fait.
Les fichiers périmés devraient être renommés  « OLD_».....
tandis que le nouveau zip fournira une copie à jour de ceux-ci sous l'appellation  « old_»...

Disponible.

**Comment by Albatros78** [comment]
Même problème avec le dernie rtéléchargement.
Mon répertoire install après instalaltion du dernier zip, est:

![image](https://user-images.githubusercontent.com/79452305/153875551-030670a1-94fe-4489-8ad3-3719c9221c6b.png)


et la page de login est:

![image](https://user-images.githubusercontent.com/79452305/153875600-4c4af8ae-3fde-419b-8a86-99c793d2d472.png)


et plus rien ne fonctionne encore.

**Comment by Patriboom** [comment]
C'est décidément un souci avec javascript.
Je verrai ce que je peux faire plus tard cette semaine.

**Comment by Patriboom** [comment]
Mise à jour ( désactivation de javascript pour cette page) disponible.

**Comment by Albatros78** [comment]
Aucun message d'erreur dans la console Inspect de Chrome.

Voila ce qui se passe.... les boutons changent de couleur sur le mouse hover... Aucun clic actif !
Ca bouge tout seul !!! :-)
BUGS version twist .... Lol

![2022-02-14_16h52_44](https://user-images.githubusercontent.com/79452305/153898481-8ff505b4-5f70-47a2-80a5-ebe955157820.gif)

**Comment by Albatros78** [comment]
Téléchargé, installé la mise à jour.
Même chose...Pas de login.

**Comment by Patriboom** [comment]
Si ça bouge tout seul, c'est parce qu'il y a tentative d'application automatique (javascript).  Il faut essayer cette nouvelle version avec un autre furteur ou effacer la mémoire cache de celui-ci.

**Comment by Patriboom** [comment]
Je comprends votre point de vue, mais des gens qui ne font que télécharger la version .ZIP sans vérifier l'état de la BDD pourraient se retrouver sans possibilité même d'ouvrir BUGS si la BDD a connu des modifications.

Avec cette vue d'avenir, il faut arriver à faire passer les mises à jour de façon fluide.

**Comment by Patriboom** [comment]
J'ai encore testé : et sur Firefox et sur Chrome ... tout est fluide, tout est bon.
Je n'arrive pas à répéter les erreurs que vous rencontrez.
Comme discuté ci-haut et antérieurement à la semaine courante, je veux mettre un terme à la présente séquence.  Je mettrai donc en veille ce développement.  S'il reste en veille longtemps qu'aucune autre modification à la BDD ne survient au cours des autres développements (encore à ce jour inconnus et imprévus ), nous n'aurons pas investi de temps pour rien.  Autrement ... il faudra y revenir et surmonter les embuches.

Dans quelques heures les modfications finales seront disponibles. 
Pouvez-vous, entre temps, confirmer le fonctionnement des deux autres billets que vous avez ouverts et les femer les trois billets  ?

**Comment by Patriboom** [comment]
La révision 7bz est en ligne et qualifiée de "finale et stable".  
Je prendrai congé pendant quelques mois de la prog BUGS.

**Comment by Albatros78** [comment]
v1.87bz installée.
Login fonctionnel.
Il reste donc le chantier des updates à la connexion.... 
Mais cela doit pouvoir attendre, car les updates BUGS sont peu fréquents sauf le travail que nous avons faits. Les demandes sont peu fréquentes


Merci encore Patrick pour tes ces efforts... L'utilisation est désormais plus intéressante qu'il y a 8 mois !!!

**Comment by Patriboom** [comment]
La toute dernière version stable est maintenant disponible et distribuée par Softculous: 
[version 1.8 - révision 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
