### ISSUE TITLE
Error during user creation with v1.87ax

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#733]
En créant un utilisateur j'ai cette erreur.

Unhandled Exception
Message:
Undefined offset: 0
Location:
E:\xampp\htdocs\bugtrackerok\app\application\libraries\mail.php on line 41
Stack Trace:
#0 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(37): Laravel\Error::native(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 41)
#1 E:\xampp\htdocs\bugtrackerok\app\application\libraries\mail.php(41): Laravel\{closure}(8, 'Undefined offse...', 'E:\\xampp\\htdocs...', 41, Array)
#2 E:\xampp\htdocs\bugtrackerok\app\application\models\user.php(361): Mail::letMailIt(Array, 1, 'en')
#3 E:\xampp\htdocs\bugtrackerok\app\application\controllers\administration\users.php(22): User::add_user(Array)
#4 [internal function]: Administration_Users_Controller->post_add()
#5 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(303): call_user_func_array(Array, Array)
#6 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(266): Laravel\Routing\Controller->response('add', Array)
#7 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\controller.php(157): Laravel\Routing\Controller->execute('add', Array)
#8 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('administration....', Array)
#9 E:\xampp\htdocs\bugtrackerok\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#10 E:\xampp\htdocs\bugtrackerok\app\laravel\laravel.php(158): Laravel\Routing\Route->call()
#11 E:\xampp\htdocs\bugtrackerok\index.php(18): require('E:\\xampp\\htdocs...')
#12 {main}
Cliquez ci-contre pour retourner à la page d`accueil de.  BUGS

L'utilisateur est crée mais aucun email recu pour la création  !

**Comment by Patriboom** [comment]
Il n'y a plus d'erreur lors de la création d'un nouvel usager.

Aussi, j'ai apporté les corrections esthétiques demandées.
La page de connexion se fait plus joyeuse et lumineuse.

**Comment by Patriboom** [comment]
Voilà, c'est réglé.  J'ai testé et tout va bien.  J'en ai profité pour ajouter l'envoi d'un courriel à l'administrateur qui vient de créer l'usager.  Ainsi, il aura confirmation de l'ajout.

**Comment by Albatros78** [comment]
Hello

v1.87ay installée
Création utilisateur OK, message recu aussi pour l'administrateur et plus d'erreur.

Travail de pro ....

Pour le fond de page, ca pète très fort pour les yeux.... 
Le graphisme c'est un métier ...Lol
Tu peux pas adoucir un peu les couleurs... en peu plus pastel !!!

**Comment by Patriboom** [comment]
Merci du retour.
Ne me reste que la mise en place des mises à jour à réaliser.  Ouf, ça achève!

**Comment by Albatros78** [comment]
OK... corrigé .
Les couleurs de la page de login restent toujours très flash je trouve.

**Comment by Patriboom** [comment]
La toute dernière version stable est maintenant disponible et distribuée par Softculous: 
[version 1.8 - révision 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)

The very late release is now available: 
[version 1.8 - release 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
