### ISSUE TITLE
Bad character during user adding into a project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#741]
Lorsque l'on veut ajouter un utilisateur qui possède des accents dans son nom l'affichage est erroné.

![image](https://user-images.githubusercontent.com/79452305/150816926-388b6ec7-c527-42d6-ac41-34c46522ee05.png)

Par contre dans le projet la liste est affichée correctement

![image](https://user-images.githubusercontent.com/79452305/150817155-66a9513b-ed3e-4781-9bb3-7426c3bec09e.png)

Une fois ajouté le nom s'affiche correctement

![image](https://user-images.githubusercontent.com/79452305/150817006-9b252ae6-cc9f-488e-a242-4696a034d7c1.png)

**Comment by Patriboom** [comment]
Tout le codage est en UTF8.  En UTF8 dans le navigateur aussi, tout est conforme.  Ce n'est qu'une minorité d'usagers qui en souffriont, la minime différence ne vaut pas les temps de travail nécessaire à la correction de ceci.

**Comment by Patriboom** [comment]
La toute dernière version stable est maintenant disponible et distribuée par Softculous: 
[version 1.8 - révision 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)

The very late release is now available: 
[version 1.8 - release 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
