### ISSUE TITLE
Impossible to add suer to a project

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#743]
en v1.87bb

impossible d'ajouter un utilisateur !
Il n'apparaît comme avant pour le choisir ...

![image](https://user-images.githubusercontent.com/79452305/152030582-1b83733a-5ce7-464a-9592-fdcfb943b262.png)

Même par ici

![image](https://user-images.githubusercontent.com/79452305/152030677-a4874dc5-3bf7-4bfe-84b6-b0f96479be3c.png)

**Comment by Patriboom** [comment]
Ceci est de retour.

**Comment by Albatros78** [comment]
Bennnnn pourquoi closed !

marche pas chez moi !

**Comment by Patriboom** [comment]
C'est du javascript il faut alors faire  Shift-Clic sur la flèche
arrondie afin de forcer la mise à jour du fichier appelé.

On Wed, 02 Feb 2022 10:12:19 -0800
Albatros78 ***@***.***> écrivites:

> Bennnnn pourquoi closed !
> 
> marche pas chez moi !
> 










---

Soyez artisans de paix.

Patrick Allaire, ptre

**Comment by Albatros78** [comment]
Tous les shifts et clic ne donnent rien....
Etrange

v1.87bb je répète... Voila ce que j'ai dans mon inspect sous chrome !!!

![image](https://user-images.githubusercontent.com/79452305/152312271-c9830354-2b01-4de1-a7c1-085eea0a5e67.png)

app.js n'est pas content !!!

**Comment by Patriboom** [comment]
C'est précisément l'erreur que j'ai corrigée.
Chrome est particulièrement capricieux.
Pour lui faire entendre raison et le forcer à prendre le fichier mis à jour il faut: 

1. Faire paraître le fichier .js dans le navigateur   http://127.0.0.1/BUGS/app/assets/js/app.js
2. Forcer sa mise à jour  ( F5  ou Shift-F5 ) 
3. Retourner au travail sur BUGS

J'observe aussi un souci d'image dans votre capture d'écran.  La prochaine révision corrigera cela.

**Comment by Albatros78** [comment]
Rien  ....  dans Chrome ou Firefox !
pas d'utilisateur affiché !

**Comment by Patriboom** [comment]
Tout fonctionne bien, je vous assure.  Regardez la démo ci-bas.

https://user-images.githubusercontent.com/19801202/152661168-7bd8de7c-77df-451c-a125-24992b1894d9.mp4

Cette démo est tournée avec Chromium, le plus capricieux de Chrome et Firefox quant à la mémoire cache.
Il faut suivre ces étapes pour vider la mémoire cache.

- [ ] Faire paraître le fichier .js dans le navigateur http://127.0.0.1/BUGS/app/assets/js/app.js
- [ ] Rendez-vous à la ligne 209 et gardez en tête son contenu  vous y devez trouver `if (n-d > 3000 ) { Modif = "AddOneTag"; }`
- [ ] Forcer sa mise à jour ( F5 ou Shift-F5 )
- [ ] Comparez la ligne 209, vous n'y trouverez plus ce que vous voyiez ci-haut, mais désormais `$.post(siteurl + 'ajax/project/proposeProjectUser', {`.  Si ce n'est pas le cas, forcer à nouveau la mise à jour ou videz la mémoire cache.
- [ ] Retourner au travail sur BUGS et ça devrait fonctionner comme dans la vidéo.

**Comment by Albatros78** [comment]
Bon moi ca ne marche toujours pas en v1.87bb.... 
Je fais toutes les manipulations indiquées et rien.... 
C'est peut être mon installation en localhost. qui merdouille..

En v1.87k (qui est celle que j'utilise en ligne) ... cela fonctionne... !!! sauf les changements de pages dans le menu Todo....
Si il faut, tant pis je travaillerais comme cela...

Mais j'en ai un peu marre.... comme toi j'imagine un peu.
Faut mettre un point final... sinon on va continuer comme cela des mois...

**Comment by Patriboom** [comment]
La version montrée dans la vidéo est la version 8.7bd  et non bb

C'est peut-être là que ça se passe.

Je considère ce dossier-ci clos, car fonctionnel en test  sous   8.7bd

Ne reste alors que la mise à jour des structures BDD qui fonctionne bien à partir de de 8.6g.
Les nouveaux usagers n'auront pas ces problèmes.
Je ferai les tests nécessaires avant la diffusion de la version 8.7 finale
S'il devait y avoir d'autres modifications à BUGS, ce serait en version 8.8 qui n'est pas encore dans la mire.

Je vous réfère donc à la discussion sur la MAJ de BDD #732  et ferme le présent billet.

**Comment by Albatros78** [comment]
Je viens de télécharger je ne sais pas quelle version mais voila ce qui ce passe...
Les updates ne fonctionnent pas et pas de login
Mais c'est peut être l'ancienne version et pas la 8.7bd !!


![image](https://user-images.githubusercontent.com/79452305/152675657-2cd88bd7-a8de-44d2-9295-0b2b4039b192.png)

**Comment by Albatros78** [comment]
Pense à vérifier si le changement de pages fonctionne aussi dans le menu Todo

![image](https://user-images.githubusercontent.com/79452305/152675807-5dbd9200-3090-48c7-a8c8-6d3c851aba41.png)

**Comment by Patriboom** [comment]
À propos de mises à jour, c'est encore le même problème qu'avant ... les mises à jour fonctionnent bien à partir de 1.7g
Là, vous me montrez des mises à jour   1.1 à 1.6   bloquées  pas étonnant.
Je vous donne donc une version débloquée pour vous permettre de retrouver vos fonctions en attendant que je travail la prise en compte des version 1.1 à 1.6

Je viens de mettre en ligne la version 1.8-7be pour vous.
Je devrai travailler là ces deux points avant que vous ne puissiez tester de nouveau.

Tous les commentaires à venir devront être soumis dans #742

**Comment by Albatros78** [comment]
v1.87be installée.

Je peux ajouter un utilisateur au projet. Super. Merci

![image](https://user-images.githubusercontent.com/79452305/152692683-72e8268e-67ed-4f89-abe6-f844467c3aae.png)

Les accents s'affichent bien aussi. tant mieux

![image](https://user-images.githubusercontent.com/79452305/152692746-4f73702c-8674-4f8e-a4fe-ae63bae84d3e.png)

Le changement de pages dans le menu Todo fonctionne à nouveau... Super. Merci

On peut stopper ici pour ces 2 points... 

Merci
