### ISSUE TITLE
Impossible to add a project to a user !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#746]
En v1.87be il est toujours impossible d'ajouter /modifier un projet à un utilisateur par le menu Users
La liste est toujours sur NULL pour un utilisateur ou même un manager !!!

![image](https://user-images.githubusercontent.com/79452305/152693112-2359eff3-a242-4278-959e-e3c0013a218e.png)

**Comment by Patriboom** [comment]
Je n'arrive toujours pas à recrée le problème.
Pouvez-vous m'indiquez le chemin par où vous arrivez à cette page, qu'attendez-vous dans les listes déroulantes ? 

Avez-vous le même souci en développement et en production ?

**Comment by Albatros78** [comment]
En production c'est la v1.87k et ces options n'existaient pas !
En test avec la v1.87be. Je clique sur le menu users et ensuite edit pour un des utilisateurs.
Et la liste apparaît avec NULL à tous les projets. Donc impossible d'ajouter un projet pour l'utilisateur en passant par là.
Cela fonctionne par la sidebar de gauche projet par projet ou en éditant un projet....

J'ai des utilisateurs affectés à suivre plusieurs projets (par la sidebar de gauche). Mais dans la liste par le menu users les projets ou ils sont affectés est à NULL aussi

Serait lié à ma base ????? la voici au cas ou

[afs_test_new.zip](https://github.com/pixeline/bugs/files/8047610/afs_test_new.zip)

**Comment by Patriboom** [comment]
Merci des clarifications.  Je comprends mieux.
J'y verrai dans les prochains jours.

**Comment by Patriboom** [comment]
Est-ce possible que ces usagers dont l'affichage des rôles dans les projets est défectueux soient des usagers qui ont été liés aux projets avant une certaine version de BUGS?

Je crois que cette fonctione était incomplète ou défectueuse jusqu'à un certain moment.
Parmi mes usagers en base de test, certains ne voyaient pas leurs rôles dans les projets (comme ce que vous montrez ci-haut), d'autres oui.  J'ai bien tenté d'ajouter, puis retirer, puis ajouter un usager à un (puis à plusieurs) projet et toujours, cette modification se refète dans la liste des rôles de l'usager.

Ce que je peux vous proposer pour l'intant, c'est une mise à jour de la BDD qui fera en sorte que tous les usagers affectés à un projet et dont le rôle est NULL soit propulsés au rang de développpeurs:  
`UPDATE projects_users SET role_id = 2 WHERE role_id=0;`

**Comment by Albatros78** [comment]
Hello Patrick.

As tu regardé avec ma base envoyée dans le post précédent pourquoi ? ou testé avec celle ci.
Tu peux changer directement le mot de passe de l'admin (axel@afsoftware.fr) dans la base par un copier/coller pour le remplacer.

Peut être une analyse de ma base permettrait de comprendre

**Comment by Patriboom** [comment]
oui, c'est vérifié avec votre BDD aussi.
Vos usagers 15, 16, 17, 18 qui présentent plusieurs associations à des projets affichent bien les rôles qui leurs sont désignés.
( 15 étant Frank, 16 Marko, 17 Dr et 18 Amelie )

**Comment by Albatros78** [comment]
Je suis resté en v1.97be et j'ai effectué ta commande:
UPDATE projects_users SET role_id = 2 WHERE role_id=0;

Désormais oui j'au peu changer les choses pour les utilisateurs comme ci dessous
![image](https://user-images.githubusercontent.com/79452305/153849780-72a4ae2c-8d90-4b8f-8dbb-24a1d354bc0d.png)

Cela semble OK désormais.
Juste une chose cela à modifier mes propres permissions (administrator) pour tous les projets ou je suis marqué comme developper et non plus administrator

![image](https://user-images.githubusercontent.com/79452305/153849954-1c12d341-325e-4c27-b3f0-d585e99c32cc.png)

Une petite requête SQL peut être pour corriger ? ou bug ?


En production v1.87k l'information est OK

![image](https://user-images.githubusercontent.com/79452305/153850156-f77c9f34-aa62-4c10-b3a3-2f539561c3d4.png)

**Comment by Patriboom** [comment]
Pour votre usager principal, puisqu'il est passé dans la moulinette de ceux qui avaient un rôle de 0, voici la commande:
`UPDATE projects_users SET role_id = 4 WHERE user_id=1;`
