### ISSUE TITLE
Todo List displays value +1

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#747]
j'avais déjà remarqué. Dans la liste des Todos la liste affiche un de plus que la configuration 

![image](https://user-images.githubusercontent.com/79452305/152693367-d27ce713-509f-430b-b680-46f3bc10f0f3.png)

et il affiche 6 tickets au lieu de 5.

![image](https://user-images.githubusercontent.com/79452305/152693447-e24dfc3b-c6cf-4f5c-a384-86b9be99087d.png)

Même chose pour les autres colonnes.

Tu dois compter avec le 0 inclus dans le source :-)

**Comment by Patriboom** [comment]
La mise à jour sera disponible dès que gitHub le permetra.  Ce semble au ralenti, voire bloqué en ce moment.

**Comment by Patriboom** [comment]
Mise à jour disponible.

**Comment by Albatros78** [comment]
v1.87bz installée.
Correctif OK 

merci

**Comment by Patriboom** [comment]
La toute dernière version stable est maintenant disponible et distribuée par Softculous: 
[version 1.8 - révision 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)

The very late release is now available: 
[version 1.8 - release 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
