### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by samoy2002** [pixeline/bugs#748]
Good morning,
I downloaded all the files this morning, uploaded them to the server, and it updated to 1.8 - 7be while I believe stable version is higher than that.   I did run all the database queries to update, and yet I am still getting an error on the admin page of "Your database needs to be updated" so I tried running all the updates again without any luck.   Can you help me figure out what I am missing to go to the latest release?

**Comment by Patriboom** [comment]
Hello, 
thanks for your comments.

I'm actually working on this specific point.
That is the last step I'll work on before to launch the next release.
I have programming to do, but also thorough tests to success in.

Your topic and issue are the same as #732   so I close this issue and refere you to #732 for the coming progress on that topic.

**Comment by Patriboom** [comment]
A new stable version is available.

**Comment by Patriboom** [comment]
Here's the address for the very late stable version:  [https://github.com/pixeline/bugs/releases/tag/v1.8_7ca]( https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
