### ISSUE TITLE
New Issue button not displayed into user mode

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#759]
v1.87bz

le bouton New issue n'est pas disponible en mode utilisateur à l'édition d'un projet

![image](https://user-images.githubusercontent.com/79452305/154040143-169f2aa0-3bcd-4ee7-b332-f052005f66ea.png)

Il est accessible en éditant un ticket uniquement

![image](https://user-images.githubusercontent.com/79452305/154040250-4e43c3c8-327a-4b40-b338-b34ce630e0a3.png)

Il serait bien de corriger en remettant le bouton à l'édition du projet comme cela est le cas en mode administrateur.

**Comment by Patriboom** [comment]
De quel niveau d'accès parlons-nous ici quand vous écrivez « en mode utilisateur » ? 
Si c'est "observateur", le bouton ne devrait paraître en aucune circonstance.
Si non, il est vrai que sa présence est requise.

**Comment by Albatros78** [comment]
Je parle de ce mode là

![image](https://user-images.githubusercontent.com/79452305/154049462-651fbc74-13be-4901-8616-741fa9658636.png)


Alors si il ne doit pas apparaître en éditant un projet, il ne doit pas apparaître non plus en ouvrant un ticket comme dans l'image ci avant.
Mais perso je trouve que ouvrir un ticket pour un utilisateur c'est plutôt intéressant aussi....
