### ISSUE TITLE
v1.87bz Database backup on Windows does not works & Linux too

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#760]
Il ne se passe rien ici !!!  même avec un mauvais mot de passe.
Aucune message.... Bouton inactif (DB sur Windows)

![image](https://user-images.githubusercontent.com/79452305/154116459-b74c799f-8638-427c-8104-38197c31c708.png)

**Comment by Albatros78** [comment]
Et sur Linux chez mon hébergeur voila ce qu'il me dit

![image](https://user-images.githubusercontent.com/79452305/154122929-625e5821-7a5f-4110-bb7e-75e2af9c9a67.png)

**Comment by Patriboom** [comment]
Les coordonnées à utiliser, qu'on soit en développement ou en production, sont celles de l'usager BUGS et non celles de l'usager du serveur.

Sur le serveur de production, assurez-vous d'avoir accordé les droits en écriture à www-data (ou à l'usager PHP/MySQl assigné par votre fournisseur d'hébergement) dans le répertoire (BUGS)/temp/

**Comment by Albatros78** [comment]
Oui oui nous sommes bien d'accord. !!!! 
J'utilise le login et mot de passe de la connexion à BUGS.

Cela fonctionnait en 1.87k avant sur le serveur de production.
Et donc ne focntionne plus en v1.87bz sur le serveur de production (Linux) et en localhost (Windows)

La sauvegarde des emails fonctionne... Mais le contenu du zip est mal formatté... Avant il affaichait la liste des fichiers directement.

Là c'est comme cela..
![image](https://user-images.githubusercontent.com/79452305/154127930-a2684588-8cc1-4976-99fd-ec7bf1f32cf0.png)


mais en cliquant sur ..\uploads les emails sont là.

**Comment by Patriboom** [comment]
Merci du retour.  Je vérifierai le bon fonctionnement de l'archivage de BDD.

Quant au classement des fichiers dans l'archive ZIP, c'est voulu ainsi.  Le but est de remettre les fichiers là où ils sont attendus par BUGS au moment de la récupération du ZIP lors d'une nouvelle installation ou d'une ré-insstallation.  L'usager n'a pas à se soucier du répertoire où classer ses fichiers, il dézippe et tous les fichiers sont placés automatiquement au bon endroit.

**Comment by Albatros78** [comment]
ok.

**Comment by Patriboom** [comment]
Bonjour Albatros78, 

merci de votre vigilence.
La sauvegarde de la BDD est de nouveau fonctionnelle.  Le problème était dans la programmation de la sauvegarde pour Windows. Puisque les codes pour Windows et pour Linux partageaient de grandes parties, je crois que la sauvegarde pour Linux sera de retour aussi pour vous.  Chez moi, du moins, elle a toujours été fonctinnelle et l'est encore.

Au plaisir.

**Comment by Patriboom** [comment]
oui, laissons ainsi.
Chez votre hébergeur, la formule "Windows" fonctionnera très bien.
La différence entre les deux versions est celle-ci:
Windows:  procédure ligne par ligne passant au travers de la BDD  (total: une trentaine de lignes de prog)
Linux: une seule commande fournie par l'OS

Il fort possible que votre hébergeur ait bloqué votre accès aux commandes à l'OS.  C'est la pratique courante et sécuritaire.

**Comment by Albatros78** [comment]
Ha oui pour le blocage des commande OS... ca c'est certain que cela est bloqué.


Bon alors je pense que l'on peut clôturer BUGS pour un bon moment.
En tout cas merci.... Toutes ces semaines de correctifs, nouveautés & idées traitées ensemble pour enfin arriver à un produit bien supérieur à ce qu'il était.
cela reste simpleet bien utile. Efficacité rapide pour un suivi de projets, bugs, problèmes, ajouts ....

On reste en contact par email pour la suite à donner sur d'autres horizons.


Axel

**Comment by Patriboom** [comment]
La toute dernière version stable est maintenant disponible et distribuée par Softculous: 
[version 1.8 - révision 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)

The very late release is now available: 
[version 1.8 - release 7ca](https://github.com/pixeline/bugs/releases/tag/v1.8_7ca)
