### ISSUE TITLE
v1.87bza - Popup message when tag added / removed

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#776]
Hello Patrick

Curieux... cela fonctionnait bien et d'un coup j'ai ce popup en manipulant un tag

![image](https://user-images.githubusercontent.com/79452305/156465983-ae46671d-92ef-4a9c-b1c5-8a721b75189d.png)

et il reste affiché !!!!

v1.87bza ... Mise à jour automatique ?
Mon dernier post était sur une 1.87bz
https://github.com/pixeline/bugs/issues/760

?????

**Comment by Patriboom** [comment]
Mise à jour automatique n'a pas ni ne sera réactivée avant un bon moment.  Ce n'est donc pas la cause de la chose.
Quant au message #760 , je le croyais résolu.  S'il en est autrement, veuillez le rouvrir.

Je suis passablement occupé ce jours-ci, peu de temps pour la programmation de BUGS.  Il se peut donc que les délais sont plus longs qu'il en était en décembre ou janvier.

Les soucis que vous rencontrez actuellement sont presque tous liés au javascript.  Il manque peut-être une virgule à la ligne x d'un fichier de 2000 lignes et donc les lignes x+1 et suivantes sont dysfonctionnelles.  C'est la joie du javascript.

**Comment by Albatros78** [comment]
Pas urgent
merci

**Comment by Patriboom** [comment]
Je crois que j'ai trouvé la solution.  
La version disponible en pré-lancement  ([Version 1.8 révision 7ck](https://github.com/pixeline/bugs/releases/tag/v1.8_7ck) ) devrait mieux fonctionner.

**Comment by Albatros78** [comment]
J'ai installé la v1.8 7ck sur ma plateforme de tests.
Même problème, le popup ne disparaît pas....

![image](https://user-images.githubusercontent.com/79452305/158353514-d4948ecd-7fde-41c3-b034-fd471de6a8e6.png)

Mais l'ajout ou suppression du tag fonctionne quand même.
Juste un problème d'affichage
Pas urgent.

**Comment by Patriboom** [comment]
Ceci a été corrigé aujourd'hui.

**Comment by Alabtros78** [comment]
Cela semble effectivement OK.
Merci

**Comment by Patriboom** [comment]
Merci du retour. 
Je ferme le ticket.
