### ISSUE TITLE
Email reception for administrator when a new user is created !

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#777]
Lorsque je crée un nouvel utilisateur, je recois l'email suivant et l'utilisateur recois le sien !
Normal que l'administrateur le recoive aussi... c'ests lui qui vient de créer le nouvel utilisateur.

![image](https://user-images.githubusercontent.com/79452305/156882373-f8aa3552-9b02-4ed1-ba12-6471ad64ed84.png)

**Comment by Patriboom** [comment]
Est-ce qu'on laisse ainsi ou me demandez-vous d'avoir un texte spécifique envoyé à l'administrateur ? 
Peut-être voulez-vous que l'administrateur n'ait pas de message du tout.  Si c'est le cas, l'idée derrière le message envoyé à l'administrateur est de lui fournir une archive du mot de passe.  Ce mot de passe ne pourrait pas être récupéré autrement.

Je travaille actuellement à la préparation du code afin que BUGS soit totalement compatible avec PHP 8.0 et 8.1.  C'est pourquoi vous trouvrez des version _master_ en évolution constante alors que _stable_ est au beau fixe.  Cette révision du code inclut aussi une révision du processus d'installation qui comptait une - voire plusieurs - étape en trop et - selon l'OS de l'usager - des erreurs qui bloquaient l'installation dans dans certaines circonstances.  Ceci se fait dans le peu de temps que j'ai disponible ces jours-ci.  Or, cette préparation à PHP 8 est prioritaire sur les modifications demandées ici.  Il s'en suit donc que les modifications demandées ici peuvent tarder à paraître dans les publications à venir.

**Comment by Albatros78** [comment]
Je crois que les 2 messages ne comprennent pas le même mot de passe.
Donc il est inutile à l'administrateur qui peut toujours le changer dans l'interface et le redonner à l'utilisateur

Que l'administrateur recoive un message, pourquoi pas. Mais dans ce cas il faut juste dire que l'utilisateur x a été crée et que un message lui à été envoyé. Rien de plus 

Pas urgent non plus
Merci

**Comment by Albatros78** [comment]
Je viens de re-vérifier. Si le mot de passe est bien le même dans les 2 messages.

**Comment by Patriboom** [comment]
Dorénavant, le mot de passe sera remplacé à par des ***** dans le message envoyé aux administrateurs.

**Comment by Alabtros78** [comment]
Good !! :-)

Toujours en mode amélioration je vois.

**Comment by Patriboom** [comment]
Ma créativité se tourne vers d'autres projets.  Je ne fais fermer le dossier BUGS et permettre à quelques courts élans de se manifester.  Ces astérisques, par exemple, sont beaucoup plus simple à faire que de gérer un message totalement différent, je suis donc allé du côté de la facilité tout en respectant l'idée; à preuve que je me tourne vers une fermeture du dossier.
