### ISSUE TITLE
Password forgotten link into the login page

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#779]
Hello Patrick,

Un gros oubli durant nos tests précédents.
Il manque l'option du mot de passe oublié sur la page de login.

**2 solutions:**

One:
L'utilisateur va par un lien sur la page de login renseigner son adresse email inscrite pour recevoir un nouveau mot de passe par email. L'adresse email doit être vérifié pour voir si l'utilisateur est déjà bien inscrit.
Le mot de passe **EST** dans l'email c'est pas top ni secure !!!

Two:
L'utilisateur va par un lien sur la page de login renseigner son adresse email inscrite pour recevoir un lien par email pour changer son mot de passe. 
L'adresse email doit être vérifié pour voir si l'utilisateur est déjà bien inscrit.
En cliquant sur le lien dans so email l'utilisateur arrive sur une page ou il doit mettre son nouveau mot de passe.
Le mot de passe n'est **PAS** dans l'email c'est plus secure !!!

Bon courage...
J'utilise la v1.87bza et tout va bien à part les 2 petits posts sans urgence.

**Comment by Patriboom** [comment]
Ok, c'est un bon commentaire.
Comme il est impossible de revenir en arrière dans l'encodage du mot de passe.  La solution consistera à générer un autre mot de passe et l'envoyer à l'usager.

**Comment by Patriboom** [comment]
La fonction est disponible.

**Comment by Patriboom** [comment]
C'est disponible. Dites-moi ce que vous en pensez.

**Comment by Albatros78** [comment]
OK je regarderai. Je ne suis pas focus la dessus en ce moment.
Merci en tout cas pour tes correctifs.
