### ISSUE TITLE
URGENT PLS: Error after new ticket added. Impossible to open it

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#780]
Hello Patrick

J'ai cette erreur après avoir crée un ticket...
l'URL est la suivante: https://www.afsoftware.fr/afs_bugtracker/project/20/issue/78

Impossible de réouvrir le ticket qui est crée

Unhandled Exception
Message:
Error rendering view: [project/issue/activity/create-issue]

Trying to get property 'id' of non-object
Location:
/htdocs/afs_bugtracker/app/application/views/project/issue/activity/create-issue.php on line 205
Stack Trace:
#0 /htdocs/afs_bugtracker/app/laravel/laravel.php(37): Laravel\Error::native(8, 'Trying to get p...', '/htdocs/afs_bug...', 205)
#1 /htdocs/afs_bugtracker/app/laravel/view.php(353) : eval()'d code(205): Laravel\{closure}(8, 'Trying to get p...', '/htdocs/afs_bug...', 205, Array)
#2 /htdocs/afs_bugtracker/app/laravel/view.php(353): eval()
#3 /htdocs/afs_bugtracker/app/laravel/view.php(324): Laravel\View->get()
#4 /htdocs/afs_bugtracker/app/laravel/view.php(406): Laravel\View->render()
#5 /htdocs/afs_bugtracker/app/laravel/view.php(341): Laravel\View->data()
#6 /htdocs/afs_bugtracker/app/laravel/view.php(324): Laravel\View->get()
#7 /htdocs/afs_bugtracker/app/laravel/view.php(534): Laravel\View->render()
#8 /htdocs/afs_bugtracker/app/laravel/response.php(237): Laravel\View->__toString()
#9 /htdocs/afs_bugtracker/app/laravel/laravel.php(174): Laravel\Response->render()
#10 /htdocs/afs_bugtracker/index.php(18): require('/htdocs/afs_bug...')

Tu peux m'aider à rétablir la base ci jointe.

[database_20220315000956.zip](https://github.com/pixeline/bugs/files/8248993/database_20220315000956.zip)

Merci de ton aide.

**Comment by Patriboom** [comment]
Je ne comprends pas le souci; écrivez-moi en privé, vous connaissez mon courriel.

**Comment by Patriboom** [comment]
Quel est le nouveau ticket qui bloque ?   Donnez-moi un description de son contenu ou identifiez son auteur.

**Comment by Patriboom** [comment]
Y eut-il des soucis avec cette base de données avant ? 
Si non, quand les soucis ont-ils commencé ( donnez-moi des événements du genre « mise à jour », commentaire untel ou  ...)
Avec l'historique que je lis dans la BDD, je pourrais peut-être me débrouiller avec une date, mais c'est plus de travail pour moi.

**Comment by Patriboom** [comment]
Ce que je vois, c'est l'usager 2 qui a répondu au billet 25. Je ne trouve aucune autre activité par quelqu'autre usager que l'usager 1.

**Comment by Patriboom** [comment]
Essayez de lui passer la commande suivant dans phpMyAdmin / requête SQL:

`UPDATE projects_issues SET assigned_to = 1 WHERE id = 78;`

**Comment by Albatros78** [comment]
J'ai eu ce problème juste après avoir crée le ticket (en administrateur)
Très bonne analyse de ta part.
La commande SQL a réglé le problème.

Merci

**Comment by Albatros78** [comment]
J'ai crée un nouveau ticket sur ce projet (le même)

https://www.afsoftware.fr/afs_bugtracker/project/20

et j'ai la même erreur 

Unhandled Exception
Message:
Error rendering view: [project/issue/activity/create-issue]

Trying to get property 'id' of non-object
Location:
/htdocs/afs_bugtracker/app/application/views/project/issue/activity/create-issue.php on line 205
Stack Trace:
#0 /htdocs/afs_bugtracker/app/laravel/laravel.php(37): Laravel\Error::native(8, 'Trying to get p...', '/htdocs/afs_bug...', 205)
#1 /htdocs/afs_bugtracker/app/laravel/view.php(353) : eval()'d code(205): Laravel\{closure}(8, 'Trying to get p...', '/htdocs/afs_bug...', 205, Array)
#2 /htdocs/afs_bugtracker/app/laravel/view.php(353): eval()
#3 /htdocs/afs_bugtracker/app/laravel/view.php(324): Laravel\View->get()
#4 /htdocs/afs_bugtracker/app/laravel/view.php(406): Laravel\View->render()
#5 /htdocs/afs_bugtracker/app/laravel/view.php(341): Laravel\View->data()
#6 /htdocs/afs_bugtracker/app/laravel/view.php(324): Laravel\View->get()
#7 /htdocs/afs_bugtracker/app/laravel/view.php(534): Laravel\View->render()
#8 /htdocs/afs_bugtracker/app/laravel/response.php(237): Laravel\View->__toString()
#9 /htdocs/afs_bugtracker/app/laravel/laravel.php(174): Laravel\Response->render()
#10 /htdocs/afs_bugtracker/index.php(18): require('/htdocs/afs_bug...')
#11 {main}

Le ticket est tout de  même crée mais impossible d'y accéder 
et dans la base ils est crée avec un 0 à assigned_to...

![image](https://user-images.githubusercontent.com/79452305/158366942-0a37ed32-ac08-4dda-829c-66699889a2da.png)

La requête SQL est tout fonctionne.

J'ai crée un autre ticket dans un autre projet, sans erreur

Cela semble donc lié au projet .

Si tu peux vérifier dans la base, si il n'y a pas quelques chose d'anormal pour le projet identifié 20 dans l'URL  ou "WSX5 Invoice Manager" dans le titre

Merci de ton aide à nouveau, car la y'a de la casse on dirait...
C'est ma base de production. tout d'un coup alors que je disais que tour fonctionnait bien !

**Comment by Albatros78** [comment]
Oui avec la requête SQL avec le bon id ou en mettant directement la valeur à 1 avec MyPHPAdmin pour le champ **assigned_to** Cela fonctionne et ensuite je peux ajouter des commentaires sans problèmes.

**Comment by Patriboom** [comment]
Le correctif est disponible.

**Comment by Albatros78** [comment]
Installé. Semble OK désormais !
Merci pour la rapidité.
