### ISSUE TITLE
Not found by clicking on a picture into a ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#783]
Après insertion d'un image dans un ticket j'obtiens un not found

![image](https://user-images.githubusercontent.com/79452305/158576999-e05976df-b3d7-4096-8afd-ec1c5d81333d.png)

Curieusement dans le ticket il y a:

![image](https://user-images.githubusercontent.com/79452305/158577089-d12b6fab-5401-458a-998f-d4da9a5f78f1.png)

Et le lien fonctionne

et aussi ce lien

![image](https://user-images.githubusercontent.com/79452305/158577165-d281589f-a59c-4404-8fd0-981cafac59cb.png)

Et le lien ne fonctionne pas !

Pas urgent.

**Comment by Patriboom** [comment]
Ok, merci.  Les images et réfeŕences m'aideront à corriger.

**Comment by Patriboom** [comment]
L'image a-t-elle été insérée dans le message à l'aide de l'éditeur de texte ou  a-t-elle été ajoutée à l'aide du bouton « Joindre un fichier »  ?

**Comment by Alabtros78** [comment]
C'est par le bouton "Joindre un fichier" en ajoutant un commentaire.

**Comment by Patriboom** [comment]
Simple question d'être bien sûr : ....

Est-ce à la pointe de la flèche verte ou de la jaune que vous cliquez ? 

![image](https://user-images.githubusercontent.com/19801202/159133874-7f4414db-d3f2-445b-b9e7-6182622cb958.png)

Ajoutez-vous l'image avant ou après l'ajout de texte dans l'espace d'édition ? 

Ensuite, faites-vous « Soumettre » ou non ? 


J'essaie de reproduire le problème et le résultat est bel et bien celui attendu:
- mini-image dans le rectangle « Fichier ajouté par .... »
- Lien fonctionnel dans ce même rectangle
- image intégrée au message lorsque j'utilise la méthode au bout de la flèche verte
-

**Comment by Alabtros78** [comment]
Hello,
J'ai écrit mon commentaire et ajouté le fichier par la flèche jaune. 
(Je crois que dans l'éditeur nous ne pouvons pas télécharger un fichier depuis le disque local mais depuis une URL uniquement)

et ensuite j'ai validé.
Cela sur ma plateforme de production.

Je vais essayer sur la plateforme de test pour ne pas polluer la production.

**Comment by Alabtros78** [comment]
Hello Patrick,

Je viens de re-tester sur ma plateforme de test... Je ne reproduis pas le problème
Je ne vois pas comment l'image peut se mettre DANS le commentaire !!!
Si tu trouves pas, ne perd pas ton temps la dessus... On laisse le ticket en attente !

**Comment by Patriboom** [comment]
Je crois avoir résolu le souci.
Une nouvelle version sera disponible dans les prochains jours .... lorsque j'aurai corrigé autres choses.

**Comment by Patriboom** [comment]
La correction est en ligne, disponible dès maintenant.

**Comment by Albatros78** [comment]
OK je regarderai. Je ne suis pas focus la dessus en ce moment.
Merci en tout cas pour tes correctifs.
