### ISSUE TITLE
Problems uploading photos

### ISSUE THREAD

**Issue by samoy2002** [pixeline/bugs#789]
As of today, for some reason i can no longer upload photos into issues.

When I try to upload a photo, it gives me an onscreen error of:

Unable to manage with this :****

Looking at the log files, nothing is being inserted to explain why this error might be happening.   No updates were done, and I used the system a week ago without any problems at all.  I went back to that project to try and upload a photo into it, and it is also giving me the problem.    I also tried uploading from a different directory, tried adjusting the size of the image to be under 2.5 MB and still continue to get that error.

Any Ideas what might be happening?

Mark

**Comment by Patriboom** [comment]
Hello Mark, 

this tools has some limits:

- file's size
- file's type:  JPG or PNG only
- rights onto the destination directory

According to what i read you've tried, I guess on the rights to access / write into the destination directory.

How did you try to upload the file ...
- usign the « attach file » button (directly in BUGS)
- using the file's functions of the ckeditor ? 

I'll try to repeat the situation and find an answer meanwhile you'll answer my questions.
Also, I'll change the upload script to have more informations in the log file next time.

**Comment by samoy2002** [comment]
I was trying to upload the photo using the attach file button.   The same
way I have done it for hundreds of other photos.   The photos are .jpg, and
limited in size.  I have gone into the uploads directory and looked.   There
was a directory created for the file, which is set up as 755, which should
be good enough to allow the software to save the file?

 

 

Mark

**Comment by Patriboom** [comment]
Hello Mark, 

I had a quick look on that this morning.
Could not find the problem yet.  But, I've prepared some better logging
I'll may have time to investigate deeper during weekend.

```
There was a directory created for the file, which is set up as 755, which should
be good enough to allow the software to save the file?
```
Yes, that sounds pretty good.  I'll have to find out why the file hasn't been moved into this directory.
My tests  - with the same code as yours - doesn't behave like you describe, but works good.

The strangest part is:  it was working good until it stopped to do so for no reason (no update, no change in your directories or rights, proper file size, proper directory's rights)..     ..... surprising.

Coming soon: better logs.

**Comment by Patriboom** [comment]
Nice!
Thanks to let me know.

Anyway, your problem opened a new field of work:  better logs.  And this field is on its way.
May we close the issue ?

**Comment by samoy2002** [comment]
Yes, please, It is working perfectly.

 

Mark
