### ISSUE TITLE
Error on first start as "foreign" user

### ISSUE THREAD

**Issue by HUisHU-Christian** [pixeline/bugs#796]
I'm trying this from a german browser (with 'de' as locale setting) and right after installation I get:

Unhandled Exception
Message:
Undefined array key "de"
Location:
[..]\app\laravel\view.php(356) : eval()'d code on line 109

**Comment by HUisHU-Christian** [comment]
I forgot the stack trace...

Stack Trace:
#0 [...]\app\laravel\laravel.php(37): Laravel\Error::native(2, 'Undefined array...', 'C:\\Bugs...', 109)
#1[...]\app\laravel\view.php(356) : eval()'d code(109): Laravel\{closure}(2, 'Undefined array...', 'C:\\Bugs...', 109)
#2 [...]\app\laravel\view.php(356): eval()
#3 [...]\app\laravel\view.php(327): Laravel\View->get()
#4 [...]\app\laravel\view.php(537): Laravel\View->render()
#5 [...]\app\laravel\response.php(237): Laravel\View->__toString()
#6 [...]\app\laravel\laravel.php(174): Laravel\Response->render()
#7 [...]\index.php(17): require('C:\\Bugs...')
#8 {main}

**Comment by Patriboom** [comment]
Thanks for that, Christian.  The patch has been merged.

Si vous le pouvez, écrivez-moi en français ce sera plus facile.

However, I would like to know when and how the error occurred.
Was it during the install process? - step 1?  step 2 ? 
Was it after the install, creating the first project ? creating the first issue ? 
Was during the first « real » usage ? 

Anyways, you're more than welcome to review the whole  ./app/application/language/de directory - even to create it so BUGS may work properly in deutch language.

**Comment by CWBudde** [comment]
This happened after everything has been set up and upon the initial loading of the site (right before showing the login mask). Probably the missing translation for "lost password" or others alike were the reasons.

**Comment by Patriboom** [comment]
I fixed the source of the issue. A patch is coming.

**Comment by Patriboom** [comment]
Hello Christian, 
the patch is now available.
Thanks for your contribution, you've permitted to correct a bug.

**Comment by Patriboom** [comment]
Again Christian, 

if you want your BUGS entirely in german, you can copy the ./app/application/language/en/ sub-directory into ./app/application/language/en/ new one and translate there all expressions in all files.

**Comment by HUisHU-Christian** [comment]
So far, we're still evaluating several bug trackers for a possible use in our agency. We're not set for anything particular. And eventually we will extend and use our project planning tool in the end, but if we decide to use Bugs, we surely contribute with translations.
