### ISSUE TITLE
Unhanded Exception: Undefined index: duration

### ISSUE THREAD

**Issue by mjanker4247** [pixeline/bugs#91]
Hello,

I installed the master branch from github and configured everything correctly to run it. However if I create a new issue I run into an "Unhandled Exception". I'm not yet familiar with this code nor with this framework so I want to ask if anybody can share his knowledge with me and show me what is wrong.
I believe that the view doesn't include an input field for "duration", but the model expects it.
But how can I change the code accordingly?

Any help is appreciated.

Unhandled Exception

Message:

Undefined index: duration
Location:

/var/www/bugs/app/application/models/project/issue.php on line 558
Stack Trace:

#0 /var/www/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined index...', '/var/www/bugs/a...', 558)
#1 /var/www/bugs/app/application/models/project/issue.php(558): Laravel\{closure}(8, 'Undefined index...', '/var/www/bugs/a...', 558, Array)
#2 /var/www/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#3 [internal function]: Project_Issue_Controller->post_new('1')
#4 /var/www/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#5 /var/www/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#6 /var/www/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#7 /var/www/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#8 /var/www/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#9 /var/www/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#10 /var/www/bugs/index.php(20): require('/var/www/bugs/a...')
#11 {main}

**Comment by Patriboom** [comment]
Hello mjanker, 
thanks for your complete description.

Here are the correction you have to do if you don't want to re-install the whole thing.
In your browser, reach your MySQL server.
It's probably something like
http://127.0.0.1/mysql/
or
http://127.0.0.1/PhpMyAdmin/

There, you'll find a button which says "SQL"
Click on it, 
the window while refresh and present you a « kind of » terminal in what paste the following code:
`
DROP TABLE IF EXISTS `projects_issues`;
CREATE TABLE `projects_issues` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_by` bigint(20) NOT NULL DEFAULT '1',
  `closed_by` bigint(20) DEFAULT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `assigned_to` bigint(20) DEFAULT NULL,
  `project_id` bigint(20) DEFAULT NULL,
  `status` tinyint(2) DEFAULT '1',
  `weight` bigint(20) NOT NULL DEFAULT '1',
  `title` varchar(255) DEFAULT NULL,
  `body` text,
  `created_at` datetime DEFAULT NULL,
  `duration` smallint(3) NOT NULL DEFAULT '30',
  `updated_at` datetime DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

`

Your problem permits us to correct the source.
If you prefer to re-install the whole thing, the proper code will be available within few minutes from now.

**Comment by Patriboom** [comment]
The new database structrure is available.
