### ISSUE TITLE
Could not login on system (first login)

### ISSUE THREAD

**Issue by rfsales** [pixeline/bugs#96]
After some errors and correcting line

46: ) ENGINE=MyISAM DEFAULT CHARSET=utf8;",
on install/mysql-structure.php

I'm getting the following error:

Unhandled Exception
Message:

Error rendering view: [activity.dashboard]

Undefined variable: SansAccent

Location:

/home/www/bugs/app/application/views/activity/dashboard.php on line 26

Stack Trace:

#0 /home/www/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined varia...', '/home/www/...', 26)
#1 /home/www/bugs/app/laravel/view.php(386) : eval()'d code(26): Laravel\{closure}(8, 'Undefined varia...', '/home/www/...', 26, Array)
#2 /home/www/bugs/app/laravel/view.php(386): eval()
#3 /home/www/bugs/app/laravel/view.php(353): Laravel\View->get()
#4 /home/www/bugs/app/laravel/view.php(447): Laravel\View->render()
#5 /home/www/bugs/app/laravel/view.php(372): Laravel\View->data()
#6 /home/www/bugs/app/laravel/view.php(353): Laravel\View->get()
#7 /home/www/bugs/app/laravel/view.php(590): Laravel\View->render()
#8 /home/www/bugs/app/laravel/response.php(246): Laravel\View->__toString()
#9 /home/www/bugs/app/laravel/laravel.php(177): Laravel\Response->render()
#10 /home/www/bugs/index.php(20): require('/home/vectorco/...')
#11 {main}

**Comment by Patriboom** [comment]
Thanks for long quotation and details.
Correction for database has been done also.
