### ISSUE TITLE
Error on bugs/project/1/issue/new --- see #98

### ISSUE THREAD

**Issue by rfsales** [pixeline/bugs#99]
Unhandled Exception
Message:

Undefined index: duration

Location:

/home/www/bugs/app/application/models/project/issue.php on line 558

Stack Trace:

#0 /home/www/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined index...', '/home/www/...', 558)
#1 /home/www/bugs/app/application/models/project/issue.php(558): Laravel\{closure}(8, 'Undefined index...', '/home/www/...', 558, Array)
#2 /home/www/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#3 [internal function]: Project_Issue_Controller->post_new('1')
#4 /home/www/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#5 /home/www/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#6 /home/www/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#7 /home/www/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#8 /home/www/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#9 /home/www/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#10 /home/www/bugs/index.php(20): require('/home/www/...')
#11 {main}

**Comment by Patriboom** [comment]
Thanks for your patience.
It is supposed to be find, now.

**Comment by Patriboom** [comment]
Please let me know when you'll have tested this patch and it works.

**Comment by rfsales** [comment]
I got another error:

Unhandled Exception
Message:

Undefined property: Swift_Transport_StreamBuffer::$_sequence

Location:

/home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php on line 236

Stack Trace:

#0 /home/www/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', '/home/www/...', 236)
#1 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', '/home/www/...', 236, Array)
#2 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO sisani.com...')
#3 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO sisani.com...')
#4 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO sisani.com...')
#5 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO sisani.com...', Array, Array)
#6 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(267): Swift_Transport_EsmtpTransport->executeCommand('EHLO sisani.com...', Array)
#7 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 /home/www/bugs/app/application/libraries/mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 /home/www/bugs/app/application/models/project/issue.php(597): Mail::send_email(Object(Swift_Message), 'edilycesar@gmai...', 'New issue "Disp...')
#11 /home/www/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#12 [internal function]: Project_Issue_Controller->post_new('1')
#13 /home/www/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#14 /home/www/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#15 /home/www/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#16 /home/www/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#17 /home/www/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /home/www/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#19 /home/www/bugs/index.php(20): require('/home/www/...')
#20 {main}

**Comment by Patriboom** [comment]
That is part of https://github.com/pixeline/bugs/issues/98

**Comment by Hazaels** [comment]
I also have simmilar problem (happens all the time...). 
Doesn't matter what I do it happens. Creating a user, a new issue, changing etc...

Here is what I get:

```
Unhandled Exception
Message:
Undefined property: Swift_Transport_StreamBuffer::$_sequence
Location:
/home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php on line 236
Stack Trace:
#0 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', '/home3/sysbasef...', 236)
#1 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', '/home3/sysbasef...', 236, Array)
#2 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO www.sysbas...')
#3 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO www.sysbas...')
#4 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO www.sysbas...')
#5 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO www.sysbas...', Array, Array)
#6 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(268): Swift_Transport_EsmtpTransport->executeCommand('EHLO www.sysbas...', Array)
#7 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 /home3/sysbasef/public_html/bugs/app/application/libraries/mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 /home3/sysbasef/public_html/bugs/app/application/models/project/issue.php(597): Mail::send_email(Object(Laravel\View), 'yotham@douzetri...', 'New issue "Old ...')
#11 /home3/sysbasef/public_html/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#12 [internal function]: Project_Issue_Controller->post_new('1')
#13 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#14 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#15 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#16 /home3/sysbasef/public_html/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#17 /home3/sysbasef/public_html/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#19 /home3/sysbasef/public_html/bugs/index.php(20): require('/home3/sysbasef...')
#20 {main}
```

**Comment by Patriboom** [comment]
According to what I've found, this problem exists since - at least - 2013 and has never been solved.
I'll check what can I do.  Thanks for entire informations you gave here.

**Comment by Hazaels** [comment]
Since 2013??? Wow... that's not good news but I hope you will be able to fix it.
The problem is really annoying and makes the system to be unusable...

Do you think it has anything to do with the "Requirements"?

Here is what is written about it:

PHP 5.3+
MySQL 5+
PDO Extension for PHP (MySQL)
MCrypt Extension for PHP
Javascript Enabled - Bugs also uses heavy Javascript to make it easier to use

How do I check if my environment has all all those?
Would be nice to have a PHP code to test that gives the results all in one page so I could just upload to the webserver and execute that PHP code to see what it shows. 
Any clue?

Thank you for your help.

**Comment by Patriboom** [comment]
On my system (according to phpinfo() ) 
-PHP 7
-mysqlnd API Extensions 	mysqli,pdo_mysql 
-PDO drivers 	mysql enabled
-PDO Driver for MySQL	enabled
-----Client API version 	mysqlnd 5.0.12-dev - 20150407 - $Id: -----b5c5906d452ec590732a93b051f3827e02749b83 $ 
-----pdo_mysql.default_socket	/var/run/mysqld/mysqld.sock	/var/run/mysqld/mysqld.sock

defined by those ini files
- php/7.0/apache2/conf.d/10-pdo.in
- php/7.0/apache2/conf.d/20-pdo_mysql.ini


I've never seen such trouble

It was a good idea to look on versions, but I'm not sure there's anything to do with.  
It's all about - I guess - default values and values passed from function to function.

**Comment by Patriboom** [comment]
Please follow issue [98](https://github.com/pixeline/bugs/issues/98)
